### ISSUE TITLE
NPE from CompactionTask

### ISSUE THREAD

**Issue by nickeylawrence** [apache/druid#10154]
Hi,

I am encountering a NullPointerException from the CompactionTask. Can anyone please suggest a solution?

To brief on the scenario, I added a new metric with aggregator type 'doubleSum' and loaded data to Druid. Later on, the aggregator had to be changed to 'doubleMax', and more data was loaded. 

Now, the compaction task is failing with the error:

_""2020-07-08T09:49:19,241 WARN [task-runner-0-priority-0] org.apache.druid.query.aggregation.AggregatorFactory - failed to merge aggregator factories
" org.apache.druid.query.aggregation.AggregatorFactoryNotMergeableException: can't merge [max_XX : org.apache.druid.query.aggregation.DoubleMaxAggregatorFactory] and [max_XX : org.apache.druid.query.aggregation.DoubleSumAggregatorFactory] , with detailed info [DoubleMaxAggregatorFactory{fieldName='max_XX', expression='null', name='max_XX'}] and [DoubleSumAggregatorFactory{fieldName='max_XX', expression='null', name='max_XX'}]
	at org.apache.druid.query.aggregation.SimpleDoubleAggregatorFactory.getMergingFactory(SimpleDoubleAggregatorFactory.java:183) ~[druid-processing-0.18.1.jar:0.18.1]
	at org.apache.druid.query.aggregation.AggregatorFactory.mergeAggregators(AggregatorFactory.java:299) [druid-processing-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.common.task.CompactionTask.createMetricsSpec(CompactionTask.java:688) [druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.common.task.CompactionTask.createDataSchema(CompactionTask.java:667) [druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.common.task.CompactionTask.createIngestionSchema(CompactionTask.java:531) [druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.common.task.CompactionTask.runTask(CompactionTask.java:374) [druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.common.task.AbstractBatchIndexTask.run(AbstractBatchIndexTask.java:123) [druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:421) [druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:393) [druid-indexing-service-0.18.1.jar:0.18.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
"2020-07-08T09:49:19,246 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner - Exception while running task[AbstractTask{id='compact_XXX-07-08T09:49:13.044Z', groupId='compact_XXX-07-08T09:49:13.044Z', taskResource=TaskResource{availabilityGroup='compact_XXX-07-08T09:49:13.044Z', requiredCapacity=1}, dataSource='DataSource_XX', context={storeCompactionState=true, priority=25, forceTimeChunkLock=true}}]
" java.lang.NullPointerException: null
	at org.apache.druid.query.aggregation.AggregatorFactory.mergeAggregators(AggregatorFactory.java:294) ~[druid-processing-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.common.task.CompactionTask.createMetricsSpec(CompactionTask.java:688) ~[druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.common.task.CompactionTask.createDataSchema(CompactionTask.java:667) ~[druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.common.task.CompactionTask.createIngestionSchema(CompactionTask.java:531) ~[druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.common.task.CompactionTask.runTask(CompactionTask.java:374) ~[druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.common.task.AbstractBatchIndexTask.run(AbstractBatchIndexTask.java:123) ~[druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:421) [druid-indexing-service-0.18.1.jar:0.18.1]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:393) [druid-indexing-service-0.18.1.jar:0.18.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
"2020-07-08T09:49:19,250 INFO [task-runner-0-priority-0] org.apache.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "compact_XXX-07-08T09:49:13.044Z",
  "status" : "FAILED",
  "duration" : 1432,
  "errorMsg" : "java.lang.NullPointerException",
  "location" : {
    "host" : null,
    "port" : -1,
    "tlsPort" : -1
  }_

**Comment by jihoonson** [comment]
Hi @nickeylawrence, seems like `max_XX` was defined as doubleMax in some segments while it was doubleSum in other segments. Would you please check if that's the case? I think compaction cannot work in that case.

**Comment by abhishekagarwal87** [comment]
It means that compaction cannot determine what aggregator factory to use for this metric column. One segment has the metric rolled up as max and one segment has that metric rolled up as sum. How would you rollup the metric in these two segments into one? Max or sum? What you can do is provide `metricsSpec` explicitly in your compaction spec. So you tell druid how the two values should be rolled up.
