### ISSUE TITLE
startup druid data server exception  Error in custom provider, org.apache.druid.java.util.common.ISE: Number overflow

### ISSUE THREAD

**Issue by trollhe** [apache/druid#10579]
```
# startup data server
cd /opt/apache-druid-0.20.0
bin/start-cluster-data-server
```

```
 Error in custom provider, org.apache.druid.java.util.common.ISE: Number overflow
  at org.apache.druid.guice.DruidProcessingModule.getMergeBufferPool(DruidProcessingModule.java:132) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.DruidProcessingModule)
  at org.apache.druid.guice.DruidProcessingModule.getMergeBufferPool(DruidProcessingModule.java:132) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.DruidProcessingModule)
  while locating org.apache.druid.collections.BlockingPool<java.nio.ByteBuffer> annotated with @org.apache.druid.guice.annotations.Merging()
    for the 4th parameter of org.apache.druid.query.groupby.strategy.GroupByStrategyV2.<init>(GroupByStrategyV2.java:106)
  while locating org.apache.druid.query.groupby.strategy.GroupByStrategyV2
    for the 3rd parameter of org.apache.druid.query.groupby.strategy.GroupByStrategySelector.<init>(GroupByStrategySelector.java:44)
  while locating org.apache.druid.query.groupby.strategy.GroupByStrategySelector
    for the 1st parameter of org.apache.druid.query.groupby.GroupByQueryQueryToolChest.<init>(GroupByQueryQueryToolChest.java:107)
  at org.apache.druid.guice.QueryToolChestModule.configure(QueryToolChestModule.java:95) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.QueryRunnerFactoryModule)
  while locating org.apache.druid.query.groupby.GroupByQueryQueryToolChest
  while locating org.apache.druid.query.QueryToolChest annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=82, type=MAPBINDER, keyType=java.lang.Class<? extends org.apache.druid.query.Query>)
  at org.apache.druid.guice.DruidBinders.queryToolChestBinder(DruidBinders.java:48) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.QueryRunnerFactoryModule -> com.google.inject.multibindings.MapBinder$RealMapBinder)
  while locating java.util.Map<java.lang.Class<? extends org.apache.druid.query.Query>, org.apache.druid.query.QueryToolChest>
    for the 1st parameter of org.apache.druid.query.MapQueryToolChestWarehouse.<init>(MapQueryToolChestWarehouse.java:35)
  while locating org.apache.druid.query.MapQueryToolChestWarehouse
  while locating org.apache.druid.query.QueryToolChestWarehouse
    for the 1st parameter of org.apache.druid.server.QueryLifecycleFactory.<init>(QueryLifecycleFactory.java:56)
  at org.apache.druid.server.QueryLifecycleFactory.class(QueryLifecycleFactory.java:56)
  while locating org.apache.druid.server.QueryLifecycleFactory
    for the 1st parameter of org.apache.druid.server.QueryResource.<init>(QueryResource.java:122)
  at org.apache.druid.server.QueryResource.class(QueryResource.java:82)
  while locating org.apache.druid.server.QueryResource
Caused by: org.apache.druid.java.util.common.ISE: Number overflow
	at org.apache.druid.java.util.common.HumanReadableBytes.getBytesInInt(HumanReadableBytes.java:49)
	at org.apache.druid.query.DruidProcessingConfig.intermediateComputeSizeBytes(DruidProcessingConfig.java:51)
	at org.apache.druid.guice.DruidProcessingModule.verifyDirectMemory(DruidProcessingModule.java:163)
	at org.apache.druid.guice.DruidProcessingModule.getMergeBufferPool(DruidProcessingModule.java:132)
	at org.apache.druid.guice.DruidProcessingModule$$FastClassByGuice$$5c8d684e.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.multibindings.MapBinder$RealMapBinder$ValueProvider.get(MapBinder.java:821)
	at com.google.inject.multibindings.MapBinder$RealMapBinder$RealMapProvider.get(MapBinder.java:605)
	at com.google.inject.multibindings.MapBinder$RealMapBinder$RealMapProvider.get(MapBinder.java:586)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050)
	at org.apache.druid.guice.LifecycleModule$2.start(LifecycleModule.java:141)
	at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:115)
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:63)
	at org.apache.druid.cli.Main.main(Main.java:113)

5 errors
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050) ~[guice-4.1.0.jar:?]
	at org.apache.druid.guice.LifecycleModule$2.start(LifecycleModule.java:141) ~[druid-core-0.20.0.jar:0.20.0]
	at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:115) [druid-services-0.20.0.jar:0.20.0]
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:63) [druid-services-0.20.0.jar:0.20.0]
	at org.apache.druid.cli.Main.main(Main.java:113) [druid-services-0.20.0.jar:0.20.0]

```

**Comment by FrankChen021** [comment]
what's the value of `druid.processing.buffer.sizeBytes` in your configuration ?

**Comment by trollhe** [comment]
> druid.processing.buffer.sizeBytes


yes, i configing it,  resource can used: 64GB RAM, 8Cores,7.7TB HDD

### historical
jvm.
```
-server
-Xms40g
-Xmx40g
-XX:MaxDirectMemorySize=64g
-XX:+ExitOnOutOfMemoryError
-Duser.timezone=UTC
-Dfile.encoding=UTF-8
-Djava.io.tmpdir=var/tmp
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager

```

runtime.
```
druid.processing.buffer.sizeBytes=4096MiB
druid.processing.numMergeBuffers=4
druid.processing.numThreads=15
...
```

### middleManager
jvm.
```
-server
-Xms10240m
-Xmx10240m
-XX:+ExitOnOutOfMemoryError
-Duser.timezone=UTC
-Dfile.encoding=UTF-8
-Djava.io.tmpdir=var/tmp
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager

```

```
# Processing threads and buffers on Peons
druid.indexer.fork.property.druid.processing.numMergeBuffers=2
druid.indexer.fork.property.druid.processing.buffer.sizeBytes=4096MiB
druid.indexer.fork.property.druid.processing.numThreads=1

# Task launch parameters
druid.indexer.runner.javaOpts=-server -Xms4g -Xmx4g -XX:MaxDirectMemorySize=8g -Duser.timezone=UTC -Dfile.encoding=UTF-8 -XX:+ExitOnOutOfMemoryError -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
...
```

**Comment by FrankChen021** [comment]
```
druid.processing.buffer.sizeBytes=4096MiB
```

Unfortunately, current upper size of this configuration is INT.MAX. You could set a smaller value.

**Comment by FrankChen021** [comment]
Hi @gianm , 

Current implementation holds value of `druid.processing.buffer.sizeBytes` in integer which means the limit for this configuration is INT.MAX. 

And the limitation is not mentioned in the doc except the default value. Do you know what's the consideration behind the implementation ? If this is what we expect, I think the doc needs to be updated to describe this limitation.
https://github.com/apache/druid/blame/master/docs/configuration/index.md#L1201
>  |`druid.processing.buffer.sizeBytes`|This` specifies a buffer size for the storage of intermediate results. The computation engine in both the Historical and Realtime processes will use a scratch buffer of this size to do all of their intermediate computations off-heap. Larger values allow for more aggregations in a single pass over the data while smaller values can require more passes depending on the query that is being executed. Human-readable format is supported, see [here](human-readable-byte.md). |auto (max 1 GiB)|

**Comment by trollhe** [comment]
> Hi @gianm ,
> 
> Current implementation holds value of `druid.processing.buffer.sizeBytes` in integer which means the limit for this configuration is INT.MAX.
> 
> And the limitation is not mentioned in the doc except the default value. Do you know what's the consideration behind the implementation ? If this is what we expect, I think the doc needs to be updated to describe this limitation.
> https://github.com/apache/druid/blame/master/docs/configuration/index.md#L1201
> 
> > |`druid.processing.buffer.sizeBytes`|This` specifies a buffer size for the storage of intermediate results. The computation engine in both the Historical and Realtime processes will use a scratch buffer of this size to do all of their intermediate computations off-heap. Larger values allow for more aggregations in a single pass over the data while smaller values can require more passes depending on the query that is being executed. Human-readable format is supported, see [here](human-readable-byte.md). |auto (max 1 GiB)|

thank u, Verified available.
