### ISSUE TITLE
Unknown provider[postgresql] of Key[type=org.apache.druid.server.audit.AuditManagerProvider, annotation=[none]], known options[[derby]]

### ISSUE THREAD

**Issue by trollhe** [apache/druid#10576]
Hello,

   my settings postgresql to save matedata,but throw this exception:
```
1) Unknown provider[postgresql] of Key[type=org.apache.druid.metadata.MetadataStorageConnector, annotation=[none]], known options[[derby]]
  at org.apache.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:109) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.derby.DerbyMetadataStorageDruidModule)
  while locating org.apache.druid.metadata.MetadataStorageConnector
    for the 1st parameter of org.apache.druid.guice.JacksonConfigManagerModule.getConfigManager(JacksonConfigManagerModule.java:52)
  at org.apache.druid.guice.JacksonConfigManagerModule.getConfigManager(JacksonConfigManagerModule.java:52) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.JacksonConfigManagerModule)
  while locating org.apache.druid.common.config.ConfigManager
    for the 1st parameter of org.apache.druid.common.config.JacksonConfigManager.<init>(JacksonConfigManager.java:49)
  at org.apache.druid.guice.JacksonConfigManagerModule.configure(JacksonConfigManagerModule.java:41) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.JacksonConfigManagerModule)
  while locating org.apache.druid.common.config.JacksonConfigManager
    for the 1st parameter of org.apache.druid.guice.JacksonConfigProvider.configure(JacksonConfigProvider.java:65)
  at org.apache.druid.guice.JacksonConfigProvider.bind(JacksonConfigProvider.java:38) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)
```

**Comment by FrankChen021** [comment]
It seems that postgresql extension is not loaded. Have you enabled the extension by putting `postgresql-metadata-storage` in the `druid.extensions.loadList`? [See here](http://druid.apache.org/docs/latest/development/extensions-core/postgresql.html)

**Comment by trollhe** [comment]
> It seems that postgresql extension is not loaded. Have you enabled the extension by putting `postgresql-metadata-storage` in the `druid.extensions.loadList`? [See here](http://druid.apache.org/docs/latest/development/extensions-core/postgresql.html)

thanks
