### ISSUE TITLE
Stream ingest Error when set coordiantor 'druid.serverview.type=http'

### ISSUE THREAD

**Issue by zhangyue19921010** [apache/druid#10600]
Set coordiantor `druid.serverview.type=http` and Stream Ingest Task will report ERROR when stopping.

### Affected Version
0.17.1

### Description
```
2020-11-24T02:42:42,769 ERROR [main] org.apache.druid.server.initialization.jetty.JettyServerModule - Jetty lifecycle event failed [class org.eclipse.jetty.server.Server]
java.util.concurrent.TimeoutException: null
	at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:129) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:30) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandlerContainer.doShutdown(AbstractHandlerContainer.java:181) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.doStop(Server.java:439) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.druid.server.initialization.jetty.JettyServerModule$2.stop(JettyServerModule.java:443) [druid-server-0.17.1.jar:0.17.1]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.stop(Lifecycle.java:368) [druid-core-0.17.1.jar:0.17.1]
	at org.apache.druid.cli.CliPeon.run(CliPeon.java:299) [druid-services-0.17.1.jar:0.17.1]
	at org.apache.druid.cli.Main.main(Main.java:113) [druid-services-0.17.1.jar:0.17.1]
2020-11-24T02:42:42,776 WARN [main] org.apache.druid.server.initialization.jetty.JettyServerModule - Unable to stop Jetty server.
java.util.concurrent.TimeoutException: null
	at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:129) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:30) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandlerContainer.doShutdown(AbstractHandlerContainer.java:181) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.doStop(Server.java:439) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.druid.server.initialization.jetty.JettyServerModule$2.stop(JettyServerModule.java:443) [druid-server-0.17.1.jar:0.17.1]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.stop(Lifecycle.java:368) [druid-core-0.17.1.jar:0.17.1]
	at org.apache.druid.cli.CliPeon.run(CliPeon.java:299) [druid-services-0.17.1.jar:0.17.1]
	at org.apache.druid.cli.Main.main(Main.java:113) [druid-services-0.17.1.jar:0.17.1]
2020-11-24T02:42:42,777 INFO [main] org.apache.druid.java.util.common.lifecycle.Lifecycle - Stopping lifecycle [module] stage [NORMAL]
```

**Comment by himanshug** [comment]
is this causing any functional issue or just a corrupted log ?

is it possible for you to get a thread dump from peon process right before it happens?

**Comment by zhangyue19921010** [comment]
Just a corrupted log as far as I know. It happens each time Stream tasks is stopping, trying to stop lifecycle of `JettyServerModule`
Sure, I will provide more logs and infos about this error.

**Comment by mfroembgen** [comment]
@zhangyue19921010 It still happens with the newest version. Did you perhaps find a solution for this error?

**Comment by zhangyue19921010** [comment]
> @zhangyue19921010 It still happens with the newest version. Did you perhaps find a solution for this error?

Had to say, i didn't fix it. Although it seams this error caused no damage.
