### ISSUE TITLE
SysMonitor is throwing 'SigarFileNotFoundException' in official Docker images

### ISSUE THREAD

**Issue by YoavNordmann** [apache/druid#10615]
We can see many instances of `org.hyperic.sigar.SigarFileNotFoundException: No such file or directory` in the log file after adding `org.apache.druid.java.util.metrics.SysMonitor` to the list of monitors.
### Affected Version
We are using the official helm chart "incubator/druid" version "0.2.18

### Description

Please include as much detailed information about the problem as possible.
We are using the helm chart as is while adding some monitors such as the `org.apache.druid.java.util.metrics.SysMonitor`.
- Cluster size: Default
- Configurations in use: Additional Monitors
- Steps to reproduce the problem: Just run the Helm chart and run some ingestion. We specifically use 'kafka_ingestion"

Some log file excerpts:
`2020-10-18T12:16:57,518 ERROR [MonitorScheduler-0] org.apache.druid.java.util.metrics.SysMonitor - Failed to get DiskUsage[/opt/apache-druid-0.19.0/var]
org.hyperic.sigar.SigarFileNotFoundException: No such file or directory
	at org.hyperic.sigar.DiskUsage.gather(Native Method) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.DiskUsage.fetch(DiskUsage.java:30) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.Sigar.getDiskUsage(Sigar.java:680) ~[sigar-1.6.5.132.jar:?]
	at org.apache.druid.java.util.metrics.SysMonitor$DiskStats.emit(SysMonitor.java:310) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.SysMonitor.doMonitor(SysMonitor.java:107) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.AbstractMonitor.monitor(AbstractMonitor.java:47) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:124) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:119) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.concurrent.ScheduledExecutors$4.run(ScheduledExecutors.java:158) [druid-core-0.19.0.jar:0.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2020-10-18T12:17:57,517 ERROR [MonitorScheduler-0] org.apache.druid.java.util.metrics.SysMonitor - Failed to get DiskUsage[/var/druid]
org.hyperic.sigar.SigarFileNotFoundException: No such file or directory
	at org.hyperic.sigar.DiskUsage.gather(Native Method) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.DiskUsage.fetch(DiskUsage.java:30) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.Sigar.getDiskUsage(Sigar.java:680) ~[sigar-1.6.5.132.jar:?]
	at org.apache.druid.java.util.metrics.SysMonitor$DiskStats.emit(SysMonitor.java:310) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.SysMonitor.doMonitor(SysMonitor.java:107) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.AbstractMonitor.monitor(AbstractMonitor.java:47) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:124) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:119) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.concurrent.ScheduledExecutors$4.run(ScheduledExecutors.java:158) [druid-core-0.19.0.jar:0.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2020-10-18T12:17:57,518 ERROR [MonitorScheduler-0] org.apache.druid.java.util.metrics.SysMonitor - Failed to get DiskUsage[/dev/termination-log]
org.hyperic.sigar.SigarFileNotFoundException: No such file or directory
	at org.hyperic.sigar.DiskUsage.gather(Native Method) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.DiskUsage.fetch(DiskUsage.java:30) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.Sigar.getDiskUsage(Sigar.java:680) ~[sigar-1.6.5.132.jar:?]
	at org.apache.druid.java.util.metrics.SysMonitor$DiskStats.emit(SysMonitor.java:310) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.SysMonitor.doMonitor(SysMonitor.java:107) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.AbstractMonitor.monitor(AbstractMonitor.java:47) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:124) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:119) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.concurrent.ScheduledExecutors$4.run(ScheduledExecutors.java:158) [druid-core-0.19.0.jar:0.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2020-10-18T12:17:57,518 ERROR [MonitorScheduler-0] org.apache.druid.java.util.metrics.SysMonitor - Failed to get DiskUsage[/etc/resolv.conf]
org.hyperic.sigar.SigarFileNotFoundException: No such file or directory
	at org.hyperic.sigar.DiskUsage.gather(Native Method) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.DiskUsage.fetch(DiskUsage.java:30) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.Sigar.getDiskUsage(Sigar.java:680) ~[sigar-1.6.5.132.jar:?]
	at org.apache.druid.java.util.metrics.SysMonitor$DiskStats.emit(SysMonitor.java:310) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.SysMonitor.doMonitor(SysMonitor.java:107) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.AbstractMonitor.monitor(AbstractMonitor.java:47) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:124) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:119) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.concurrent.ScheduledExecutors$4.run(ScheduledExecutors.java:158) [druid-core-0.19.0.jar:0.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2020-10-18T12:17:57,518 ERROR [MonitorScheduler-0] org.apache.druid.java.util.metrics.SysMonitor - Failed to get DiskUsage[/etc/hostname]
org.hyperic.sigar.SigarFileNotFoundException: No such file or directory
	at org.hyperic.sigar.DiskUsage.gather(Native Method) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.DiskUsage.fetch(DiskUsage.java:30) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.Sigar.getDiskUsage(Sigar.java:680) ~[sigar-1.6.5.132.jar:?]
	at org.apache.druid.java.util.metrics.SysMonitor$DiskStats.emit(SysMonitor.java:310) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.SysMonitor.doMonitor(SysMonitor.java:107) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.AbstractMonitor.monitor(AbstractMonitor.java:47) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:124) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:119) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.concurrent.ScheduledExecutors$4.run(ScheduledExecutors.java:158) [druid-core-0.19.0.jar:0.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2020-10-18T12:17:57,518 ERROR [MonitorScheduler-0] org.apache.druid.java.util.metrics.SysMonitor - Failed to get DiskUsage[/etc/hosts]
org.hyperic.sigar.SigarFileNotFoundException: No such file or directory
	at org.hyperic.sigar.DiskUsage.gather(Native Method) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.DiskUsage.fetch(DiskUsage.java:30) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.Sigar.getDiskUsage(Sigar.java:680) ~[sigar-1.6.5.132.jar:?]
	at org.apache.druid.java.util.metrics.SysMonitor$DiskStats.emit(SysMonitor.java:310) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.SysMonitor.doMonitor(SysMonitor.java:107) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.AbstractMonitor.monitor(AbstractMonitor.java:47) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:124) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:119) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.concurrent.ScheduledExecutors$4.run(ScheduledExecutors.java:158) [druid-core-0.19.0.jar:0.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2020-10-18T12:17:57,518 ERROR [MonitorScheduler-0] org.apache.druid.java.util.metrics.SysMonitor - Failed to get DiskUsage[/opt/apache-druid-0.19.0/var]
org.hyperic.sigar.SigarFileNotFoundException: No such file or directory
	at org.hyperic.sigar.DiskUsage.gather(Native Method) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.DiskUsage.fetch(DiskUsage.java:30) ~[sigar-1.6.5.132.jar:?]
	at org.hyperic.sigar.Sigar.getDiskUsage(Sigar.java:680) ~[sigar-1.6.5.132.jar:?]
	at org.apache.druid.java.util.metrics.SysMonitor$DiskStats.emit(SysMonitor.java:310) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.SysMonitor.doMonitor(SysMonitor.java:107) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.AbstractMonitor.monitor(AbstractMonitor.java:47) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:124) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:119) [druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.concurrent.ScheduledExecutors$4.run(ScheduledExecutors.java:158) [druid-core-0.19.0.jar:0.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

A possible solution might be hidden in this issue: https://itectec.com/ubuntu/ubuntu-install-cgconfig-in-ubuntu-16-04/

**Comment by maytasm** [comment]
Came across this message https://the-asf.slack.com/archives/CJ8D1JTB8/p1605124961461100?thread_ts=1605121473.460400&cid=CJ8D1JTB8 when I was looking into similar error.

**Comment by ryanmorris708** [comment]
I am seeing this as well in version 0.20.1, deployed on Kubernetes using the [Druid Operator](https://druid.apache.org/docs/latest/operations/kubernetes.html). I tried changing the securityContext to use root for everything, since some of the files that the SysMonitor wants to read are owned by root, but this didn't help.

The log is always exactly the same (always DiskUsage regardless of the file), with the same stack trace:

`<date> ERROR [MonitorScheduler-0] org.apache.druid.java.util.metrics.SysMonitor - Failed to get DiskUsage[<file>]`

The affected files/directories are:

- /dev/termination-log
- /etc/hosts
- /etc/resolv.conf
- /etc/hostname
- /opt/druid/var
- /opt/druid/conf/druid/cluster/_common
- /opt/druid/conf/druid/cluster/data/broker
- /opt/druid/conf/druid/cluster/data/coordinator
- /opt/druid/conf/druid/cluster/data/historical
- /opt/druid/conf/druid/cluster/data/middleManager
- /opt/druid/conf/druid/cluster/data/router

Relevant parts of my Druid resource definition (no volumes mounted yet):

```
apiVersion: "druid.apache.org/v1alpha1"
kind: "Druid"
metadata:
  name: dev
spec:
  image: apache/druid:0.20.1
  startScript: /druid.sh
  securityContext:
    fsGroup: 0
    runAsUser: 0
    runAsGroup: 0
  services:
    - spec:
        type: LoadBalancer
  commonConfigMountPath: "/opt/druid/conf/druid/cluster/_common"
  jvm.options: |-
    -server
    -XX:+UseG1GC
    -XX:+ExitOnOutOfMemoryError
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Djava.io.tmpdir=/opt/druid/var/tmp
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
  common.runtime.properties: |

    druid.extensions.loadList=["druid-histogram", "druid-datasketches", "postgresql-metadata-storage", "druid-kafka-indexing-service", "kafka-emitter", "druid-s3-extensions"]
    druid.monitoring.monitors=["org.apache.druid.client.cache.CacheMonitor", "org.apache.druid.java.util.metrics.SysMonitor", "org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.java.util.metrics.JvmCpuMonitor", "org.apache.druid.java.util.metrics.CpuAcctDeltaMonitor", "org.apache.druid.java.util.metrics.JvmThreadsMonitor", "org.apache.druid.server.metrics.EventReceiverFirehoseMonitor"]
```

Example stack trace for /dev/termination-log:

```
2021-05-13T21:09:48,627 ERROR [MonitorScheduler-0] org.apache.druid.java.util.metrics.SysMonitor - Failed to get DiskUsage[/dev/termination-log]
org.hyperic.sigar.SigarFileNotFoundException: No such file or directory
        at org.hyperic.sigar.DiskUsage.gather(Native Method) ~[sigar-1.6.5.132.jar:?]
        at org.hyperic.sigar.DiskUsage.fetch(DiskUsage.java:30) ~[sigar-1.6.5.132.jar:?]
        at org.hyperic.sigar.Sigar.getDiskUsage(Sigar.java:680) ~[sigar-1.6.5.132.jar:?]
        at org.apache.druid.java.util.metrics.SysMonitor$DiskStats.emit(SysMonitor.java:310) [druid-core-0.20.1.jar:0.20.1]
        at org.apache.druid.java.util.metrics.SysMonitor.doMonitor(SysMonitor.java:107) [druid-core-0.20.1.jar:0.20.1]
        at org.apache.druid.java.util.metrics.AbstractMonitor.monitor(AbstractMonitor.java:47) [druid-core-0.20.1.jar:0.20.1]
        at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:124) [druid-core-0.20.1.jar:0.20.1]
        at org.apache.druid.java.util.metrics.MonitorScheduler$1.call(MonitorScheduler.java:119) [druid-core-0.20.1.jar:0.20.1]
        at org.apache.druid.java.util.common.concurrent.ScheduledExecutors$4.run(ScheduledExecutors.java:158) [druid-core-0.20.1.jar:0.20.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

**Comment by sachinsagare** [comment]
I see same issue on the druid 0.23. Is there any solution for this ?

**Comment by jasonwzm** [comment]
Also seeing this after adding `org.apache.druid.java.util.metrics.SysMonitor`. Any updates?

**Comment by mariuskimmina** [comment]
Same here, would appreciate any hints on how to fix this.

**Comment by daniel-imgarena** [comment]
same problem

version: 25.0.0

**Comment by maaz-adjoe** [comment]
Same problem 

versionL 24.0.1-1

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
Same problem with druid (25.0.0+) inside an LXC container.
Seems it tries to use device files that don't exist inside the container:
```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop5       16G  9.8G  5.2G  66% /
/dev/loop8       24G  8.8G   16G  37% /var/lib/druid

# ls /dev/loop5 /dev/loop8
ls: cannot access '/dev/loop5': No such file or directory
ls: cannot access '/dev/loop8': No such file or directory
```

**Comment by coolcut2012** [comment]
version: 0.18.1
Maybe set the container privileged mode docker run --privileged or create a custom user druid and set user permissions in the Dockerfile. Or simply the "druid.Monitoring.Monitors=" remove this SysMonitor configuration

**Comment by mingatairdna** [comment]
seeing the same thing on druid 27 and druid 29.

**Comment by JRobTS** [comment]
I just ran into this in 37.0.0

```
2026-08-31T13:08:58,595 ERROR [MonitorScheduler-0] org.apache.druid.java.util.metrics.SysMonitor - Failed to get FileSystem list
org.hyperic.sigar.SigarFileNotFoundException: No such file or directory
        at org.hyperic.sigar.Sigar.getFileSystemListNative(Native Method)
        at org.hyperic.sigar.Sigar.getFileSystemList(Sigar.java:650)
        at org.apache.druid.java.util.metrics.SysMonitor$DiskStats.emit(SysMonitor.java:290)
        at org.apache.druid.java.util.metrics.SysMonitor.doMonitor(SysMonitor.java:105)
        at org.apache.druid.java.util.metrics.AbstractMonitor.monitor(AbstractMonitor.java:54)
        at org.apache.druid.java.util.metrics.BasicMonitorScheduler.lambda$startMonitor$0(BasicMonitorScheduler.java:55)
        at org.apache.druid.java.util.common.concurrent.ScheduledExecutors$2.run(ScheduledExecutors.java:165)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by FrankChen021** [comment]
Confirmed on Druid 37.0.0 when the deprecated `SysMonitor` is enabled. It uses Sigar to query disk statistics for every local mount, including Kubernetes/Docker pseudo- and bind mounts such as `/etc/hosts` and `/dev/termination-log`, which may not have corresponding block devices inside the container. This is not a permissions issue. Removing `SysMonitor` and using `OshiSysMonitor` resolves the errors; also check inherited `druid.monitoring.monitors` configuration.

**Comment by JRobTS** [comment]
> Confirmed on Druid 37.0.0 when the deprecated `SysMonitor` is enabled. It uses Sigar to query disk statistics for every local mount, including Kubernetes/Docker pseudo- and bind mounts such as `/etc/hosts` and `/dev/termination-log`, which may not have corresponding block devices inside the container. This is not a permissions issue. Removing `SysMonitor` and using `OshiSysMonitor` resolves the errors; also check inherited `druid.monitoring.monitors` configuration.

Thank you!!!   We were upgrading an old system and I missed [this](https://druid.apache.org/docs/latest/release-info/upgrade-notes#sysmonitor-support-deprecated) deprecation notice from 27.0.0
