### ISSUE TITLE
LOST_CONTACT_WITH_STREAM issue with big load

### ISSUE THREAD

**Issue by smit-aterlo** [apache/druid#10672]
Druid Supervisor fails with `LOST_CONTACT_WITH_STREAM` after running for a while and it happens after 1 or 2 Kafka log clean-up. 

### Affected Version

0.20.0

### Description

Please include as much detailed information about the problem as possible.

- Cluster Size: 1 Master, 1 Query (Both 16 CPUs and 64GB Memory), 2 Data Nodes (Both 64 CPUs and 196GB Memory)
- A number of Topics: 5 Topics (1 big topic is with 1000 partitions)
- Ingestion Rate: 4 Topic Ingest around 100k each and 1 with around 1 million
- Supervisor Config for biggest topic:
```
{
    "type": "kafka",
    "spec": {
        "ioConfig": {
            "type": "kafka",
            "topic": "table1",
            "consumerProperties": {
                "bootstrap.servers": "10.128.0.96:9092"
            },
            "inputFormat": {
                "type": "json"
            },
            "useEarliestOffset": true,
            "appendToExisting": true
        },
        "tuningConfig": {
            "type": "kafka",
            "resetOffsetAutomatically": true
        },
        "dataSchema": {
            "dataSource": "table1",
            "granularitySpec": {
                "type": "uniform",
                "queryGranularity": "NONE",
                "segmentGranularity": "HOUR",
                "rollup": false
            },
            "timestampSpec": {
                "column": "Time",
                "format": "millis"
            },
            "dimensionsSpec": {
                "dimensions": [
                    "AddressSpace",
                    "Field1",
                    "Field2",
                    {
                        "type": "long",
                        "name": "Gauge"
                    },
                    {
                        "type": "long",
                        "name": "Gauge2"
                    },
                    "Field3",
                    "Field4",
                    "Field4",
                    "Field5",
                    "Field6",
                    "Field7",
                    "Field8"
                ]
            }
        }
    }
}
```

- Steps to Reproduce: Druid can consume all the messages until 1st or 2nd log clean up runs on the Kafka side. Once it runs Supervisor fails with `LOST_CONTACT_WITH_STREAM` and the following error:

```
{
      "timestamp": "2020-12-11T12:09:19.517Z",
      "exceptionClass": "org.apache.druid.java.util.common.ISE",
      "message": "org.apache.druid.java.util.common.ISE: Previous sequenceNumber [716362] is no longer available for partition [461] - automatically resetting sequence",
      "streamException": true
    }
```

Can someone please help me with this issue?

Thank you

**Comment by zhangyue19921010** [comment]
It seems that offset is out of range. Is there any full payload config, you can find it in Druid UI.
If you reset this supervisor, can supervisor be recovery?

**Comment by smit-aterlo** [comment]
Sometimes it starts working after full reset but once it gives `LOST_CONTACT_WITH_STREAM` error then reset does not work.

**Comment by smit-aterlo** [comment]
I am getting this error in task when this happens:

```
2020-12-11T20:25:10,929 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner - Encountered exception in run() before persisting.
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_275]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_275]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.possiblyPause(SeekableStreamIndexTaskRunner.java:1270) ~[druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.runInternal(SeekableStreamIndexTaskRunner.java:570) [druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.run(SeekableStreamIndexTaskRunner.java:267) [druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTask.run(SeekableStreamIndexTask.java:145) [druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:451) [druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:423) [druid-indexing-service-0.20.0.jar:0.20.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

```
