### ISSUE TITLE
host cannot be null Druid redis

### ISSUE THREAD

**Issue by HashSalmon** [apache/druid#10770]
Hey All,

I am trying to connect to redis cluster with druid 0.19. The broker log shows host cannot be null. It looks like druid cannot parse config name "druid.cache.cluster.nodes". 

`2021-01-16T01:06:47,894 WARN [DruidSchema-Cache-0] org.apache.druid.client.cache.RedisCache - Exception pulling items from cache
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226) ~[jedis-2.9.0.jar:?]
	at org.apache.druid.client.cache.RedisCache.getBulk(RedisCache.java:118) ~[druid-redis-cache-0.19.0.jar:0.19.0]
	at org.apache.druid.client.CachingClusteredClient$SpecificQueryRunnable.computeCachedValues(CachingClusteredClient.java:580) ~[druid-server-0.19.0.jar:0.19.0]
	at org.apache.druid.client.CachingClusteredClient$SpecificQueryRunnable.pruneSegmentsWithCachedResults(CachingClusteredClient.java:540) ~[druid-server-0.19.0.jar:0.19.0]
	at org.apache.druid.client.CachingClusteredClient$SpecificQueryRunnable.run(CachingClusteredClient.java:358) ~[druid-server-0.19.0.jar:0.19.0]
	at org.apache.druid.client.CachingClusteredClient.run(CachingClusteredClient.java:195) ~[druid-server-0.19.0.jar:0.19.0]
	at org.apache.druid.client.CachingClusteredClient.access$100(CachingClusteredClient.java:110) ~[druid-server-0.19.0.jar:0.19.0]
	at org.apache.druid.client.CachingClusteredClient$3.run(CachingClusteredClient.java:220) ~[druid-server-0.19.0.jar:0.19.0]
	at org.apache.druid.query.RetryQueryRunner$RetryingSequenceIterator.hasNext(RetryQueryRunner.java:208) ~[druid-server-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.BaseSequence.accumulate(BaseSequence.java:43) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.MergeSequence.toYielder(MergeSequence.java:62) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.query.RetryQueryRunner$1.toYielder(RetryQueryRunner.java:124) ~[druid-server-0.19.0.jar:0.19.0]
	at org.apache.druid.common.guava.CombiningSequence.toYielder(CombiningSequence.java:78) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:49) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:49) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:88) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:84) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:74) ~[druid-processing-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.WrappingSequence.toYielder(WrappingSequence.java:83) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:88) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:84) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.WrappingSequence.toYielder(WrappingSequence.java:83) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.java.util.common.guava.Yielders.each(Yielders.java:32) ~[druid-core-0.19.0.jar:0.19.0]
	at org.apache.druid.sql.calcite.schema.DruidSchema.refreshSegmentsForDataSource(DruidSchema.java:538) ~[druid-sql-0.19.0.jar:0.19.0]
	at org.apache.druid.sql.calcite.schema.DruidSchema.refreshSegments(DruidSchema.java:494) ~[druid-sql-0.19.0.jar:0.19.0]
	at org.apache.druid.sql.calcite.schema.DruidSchema.lambda$start$2(DruidSchema.java:267) ~[druid-sql-0.19.0.jar:0.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149) ~[?:1.8.0_192]
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216) ~[?:1.8.0_192]
	at redis.clients.jedis.Connection.connect(Connection.java:184) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106) ~[jedis-2.9.0.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:836) ~[commons-pool2-2.2.jar:2.2]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:434) ~[commons-pool2-2.2.jar:2.2]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361) ~[commons-pool2-2.2.jar:2.2]
	at redis.clients.util.Pool.getResource(Pool.java:49) ~[jedis-2.9.0.jar:?]
	... 32 more`

**Comment by FrankChen021** [comment]
> JedisConnectionException: Could not get a resource from the pool

This specific error usually is caused by :

1. smaller number of connections
2. limited access to redis

To solve it, 
1. you could enlarge the `druid.cache.maxTotalConnections` and `druid.cache.maxIdleConnections`
2. check the `druid.cache.password` configuration is correct or if the brokers/historical nodes are in the whitelist of redis

Hope it works
