### ISSUE TITLE
UnsupportedOperationException during BUILD_SEGMENTS for arbitrary segment granularity 

### ISSUE THREAD

**Issue by aewhite** [apache/druid#10820]
### Affected Version

0.20.

### Description

Issue an index spec with the following granularity spec

```
 "granularitySpec": {
        "type": "arbitrary",
        "queryGranularity": "TEN_MINUTE",
        "rollup": true,
        "intervals": [
              "2021-01-01T00:00:00.000Z/2021-01-01T01:00:00.000Z",
              "2021-01-01T02:00:00.000Z/2021-01-01T04:00:00.000Z"
        ]
}
```

The job will fail with 

```
2021-01-30T13:32:56,777 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.common.task.IndexTask - Encountered exception in BUILD_SEGMENTS.
java.lang.UnsupportedOperationException: null
	at org.apache.druid.segment.indexing.granularity.ArbitraryGranularitySpec.getSegmentGranularity(ArbitraryGranularitySpec.java:117) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.common.task.OverlordCoordinatingSegmentAllocator.lambda$new$0(OverlordCoordinatingSegmentAllocator.java:68) ~[druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.appenderator.ActionBasedSegmentAllocator.allocate(ActionBasedSegmentAllocator.java:58) ~[druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.common.task.OverlordCoordinatingSegmentAllocator.allocate(OverlordCoordinatingSegmentAllocator.java:117) ~[druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.segment.realtime.appenderator.BaseAppenderatorDriver.getSegment(BaseAppenderatorDriver.java:334) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.segment.realtime.appenderator.BaseAppenderatorDriver.append(BaseAppenderatorDriver.java:402) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.segment.realtime.appenderator.BatchAppenderatorDriver.add(BatchAppenderatorDriver.java:114) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.common.task.InputSourceProcessor.process(InputSourceProcessor.java:106) ~[druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.common.task.IndexTask.generateAndPublishSegments(IndexTask.java:876) ~[druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.common.task.IndexTask.runTask(IndexTask.java:492) [druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.common.task.AbstractBatchIndexTask.run(AbstractBatchIndexTask.java:140) [druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexSupervisorTask.runSequential(ParallelIndexSupervisorTask.java:919) [druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexSupervisorTask.runTask(ParallelIndexSupervisorTask.java:445) [druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.common.task.AbstractBatchIndexTask.run(AbstractBatchIndexTask.java:140) [druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:451) [druid-indexing-service-0.20.0.jar:0.20.0]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:423) [druid-indexing-service-0.20.0.jar:0.20.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by aewhite** [comment]
This seems nearly identical to a 4 year old bug that was closed due to inactivity: https://github.com/apache/druid/issues/3170
