### ISSUE TITLE
Idle timeout expired:300000/300000 ms

### ISSUE THREAD

**Issue by zhangxin12138** [apache/druid#10903]
version: druid-0.15.1

error message:
2021-02-19T05:41:57,130 WARN [qtp1898870910-192] org.eclipse.jetty.server.HttpChannel - /druid/v2/
java.lang.RuntimeException: java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 300000/300000 ms
        at org.apache.druid.server.QueryResource$1.write(QueryResource.java:245) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
        at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71) ~[jersey-core-1.19.3.jar:1.19.3]
        at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57) ~[jersey-core-1.19.3.jar:1.19.3]
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302) ~[jersey-server-1.19.3.jar:1.19.3]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510) ~[jersey-server-1.19.3.jar:1.19.3]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) ~[jersey-server-1.19.3.jar:1.19.3]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) ~[jersey-server-1.19.3.jar:1.19.3]
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) ~[jersey-servlet-1.19.3.jar:1.19.3]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) ~[jersey-servlet-1.19.3.jar:1.19.3]

**Comment by suneet-s** [comment]
@zhangxin12138 Can you provide more context around this issue? This exception usually means that the query you were running took more than 5 minutes to run. Were you expecting the query to finish faster? Can you share details about the query and the environment
