### ISSUE TITLE
Extension [/opt/apache-druid-0.20.1/dist/druid/extensions/druid-orc-extensions] specified in “druid.extensions.loadList” didn’t exist? 

### ISSUE THREAD

**Issue by ankitmani2004** [apache/druid#11062]
I am trying to deploy apache/druid:0.20.1 in Kube. I am getting error:

`Extension [/opt/apache-druid-0.20.1/dist/druid/extensions/druid-orc-extensions] specified in "druid.extensions.loadList" didn't exist!? `

                                     
I have taken off druid-orc-extensions from extensions list in my common properties but still getting the same for the next one druid-s3-extensions and so on. I somewhere on Google found that repositoryList solved the issue. I did try:

`druid.extensions.repositoryList=[ "druid-hdfs-storage", "druid-kafka-indexing-service", "druid-datasketches","druid-s3-extensions", "druid-kafka-indexing-service", "postgresql-metadata-storage", "druid-parquet-extensions", "druid-datasketches", "druid-basic-security"]`
Now, I did not get error, but its not able to connect too Postgres Metadata and giving error:

```
2021-04-01T14:14:06,926 ERROR [main] org.apache.druid.cli.CliCoordinator - Error when starting up. Failing.
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) Unknown provider[postgresql] of Key[type=org.apache.druid.metadata.MetadataStorageProvider, annotation=[none]], known options[[derby]]
 at org.apache.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:109) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.derby.DerbyMetadataStorageDruidModule)
 while locating org.apache.druid.metadata.MetadataStorageProvider
 while locating org.apache.druid.metadata.MetadataStorage
```
Please suggest. Thanks.

**Comment by FrankChen021** [comment]
From the exception message, obviously, `postgresql-metadata-storage` extension is not in `druid.extensions.loadList`.

**Comment by ankitmani2004** [comment]
postgresql-metadata-storage extension is in druid.extensions.loadList

**Comment by ankitmani2004** [comment]
What should be druid.extensions.directory given for 0.20.1 version? I have given dist/druid/extensions. 
1) When I dont give druid.extensions.directory and no druid.extensions.loadList then it loads all the core-extensions but then fails with error:

1) No implementation for org.apache.druid.query.QuerySegmentWalker was bound.
  while locating com.google.inject.Provider<org.apache.druid.query.QuerySegmentWalker>
    for the 1st parameter of org.apache.druid.query.movingaverage.MovingAverageQueryToolChest.<init>(MovingAverageQueryToolChest.java:61)
  at org.apache.druid.query.movingaverage.MovingAverageQueryModule.configure(MovingAverageQueryModule.java:48) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.movingaverage.MovingAverageQueryModule)

2) No implementation for org.apache.druid.client.TimelineServerView was bound.
  while locating org.apache.druid.client.TimelineServerView
    for the 1st parameter of org.apache.druid.query.materializedview.DataSourceOptimizer.<init>(DataSourceOptimizer.java:62)
  at org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule.configure(MaterializedViewSelectionDruidModule.java:55) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule)

3) No implementation for org.apache.druid.query.QueryToolChestWarehouse was bound.
  while locating org.apache.druid.query.QueryToolChestWarehouse
    for the 1st parameter of org.apache.druid.query.materializedview.MaterializedViewQueryQueryToolChest.<init>(MaterializedViewQueryQueryToolChest.java:48)
  at org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule.configure(MaterializedViewSelectionDruidModule.java:52) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule)

4) No implementation for org.apache.druid.server.log.RequestLogger was bound.
  while locating org.apache.druid.server.log.RequestLogger
    for the 2nd parameter of org.apache.druid.query.movingaverage.MovingAverageQueryToolChest.<init>(MovingAverageQueryToolChest.java:61)
  at org.apache.druid.query.movingaverage.MovingAverageQueryModule.configure(MovingAverageQueryModule.java:48) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.movingaverage.MovingAverageQueryModule)

5) A binding to com.google.common.base.Supplier<org.apache.druid.server.audit.SQLAuditManagerConfig> was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule)

6) A binding to com.google.common.base.Supplier<org.apache.druid.server.audit.SQLAuditManagerConfig> was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.sqlserver.SQLServerMetadataStorageModule)

7) A binding to org.apache.druid.server.audit.SQLAuditManagerConfig was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule)

8) A binding to org.apache.druid.server.audit.SQLAuditManagerConfig was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.sqlserver.SQLServerMetadataStorageModule)

2) When I give directory and loadlist it fails with error that extension not found

3) When I give Copy command in docker file -> COPY  extensions-core /opt/druid/dist/druid/extensions  and  directory and loadlist in common run time then it loads only the extensions in the list but give error:

Unknown provider[postgresql]  
OR
does not recognize S3.

Thanks.
