### ISSUE TITLE
Unable to ingest a csv into druid

### ISSUE THREAD

**Issue by abandaga** [apache/druid#11579]
ive started a druid 021.1 instance on a local linux box. 

I then am trying to load a csv into it. While doing it, im running a command: ./bin/post-index-task --file ../druiddatafileconfig.json --url http://localhost:8081

I get the following console messages:
Beginning indexing data for fly
Traceback (most recent call last):
  File "apache-druid-0.21.1/bin/post-index-task-main", line 174, in <module>
    main()
  File "apache-druid-0.21.1/bin/post-index-task-main", line 158, in main
    task_id = json.loads(post_task(args, task_contents, submit_timeout_at))["task"]
  File "apache-druid-0.21.1/bin/post-index-task-main", line 58, in post_task
    raise_friendly_error(e)
  File "apache-druid-0.21.1/bin/post-index-task-main", line 109, in raise_friendly_error
    raise Exception("HTTP Error {0}: {1}, check overlord log for more details.\n{2}".format(e.code, e.reason, text))

Exception: HTTP Error 400: Bad Request, check overlord log for more details.

{"error":"Cannot construct instance of `org.apache.druid.data.input.impl.CsvInputFormat`, problem: At least one of [Property{name='hasHeaderRow', value=null}, Property{name='findColumnsFromHeader', value=null}] must be present\n at [Source: (org.eclipse.jetty.server.HttpInputOverHTTP); line: 136, column: 7] (through reference chain: org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexSupervisorTask[\"spec\"]->org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexIngestionSpec[\"ioConfig\"]->org.apache.druid.indexing.common.task.batch.parallel.ParallelIndexIOConfig[\"inputFormat\"])"}

**Comment by bananaaggle** [comment]
Hi, can you provide your `druiddatafileconfig.json`? I think something necessary is not set.

**Comment by FrankChen021** [comment]
As we can see from the error message, there're some properties missing in the 'inputFormat'.  Please see the [doc](https://druid.apache.org/docs/latest/ingestion/data-formats.html#csv) for more information.
