### ISSUE TITLE
Overlord spins 300% and consumes all -Xmx even though Middle Managers are idle.

### ISSUE THREAD

**Issue by didip** [apache/druid#11592]
### Affected Version

0.21.1

### Description

After several days of smooth batch ingestion, Overlord now spins 300% consuming all of its memory even though 98% of middle managers are idle. The 5 middle managers that are running were unable to talk to Overlord via HTTP request.

```
druid.indexer.runner.type=httpRemote
```

Even after shutting down all middle managers, Overlord still spins 300%.

I am dumping its heap and trying to analyze it right now. We configured Overlord to have 500 threads and 24GB heap.

Overlord JVM config:
```
-server
-Xms1g
-Xmx24g
-XX:+UseG1GC
-XX:+CrashOnOutOfMemoryError
-XX:+UseStringDeduplication
-XX:-UseBiasedLocking
-XX:MaxGCPauseMillis=100
-XX:ParallelGCThreads=3
-Duser.timezone=UTC
-Dfile.encoding=UTF-8
-Djava.io.tmpdir=var/tmp
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
```

**Comment by didip** [comment]
Based on the heap dump analysis, 80% of wasted memory is caused by:

```
org.apache.druid.metadata.SQLMetadataStorageActionHandler.getCompletedTaskInfo
```

**Comment by vrrs** [comment]
I have the same issue. I increased the heap from 3gb to 16gb. I can see this on the logs 
```
2021-08-19T00:16:29,763 WARN [qtp2009492047-84] org.apache.druid.java.util.common.RetryUtils - Retrying (4 of 9) in 10,348ms.
org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 0 milliseconds ago.  The last packet sent successfully to the server was 13,316 milliseconds ago. [statement:"SELECT   id,   status_payload,   created_date,   datasource,   payload FROM   druid_tasks WHERE active = FALSE AND created_date >= :start ORDER BY created_date DESC", located:"SELECT   id,   status_payload,   created_date,   datasource,   payload FROM   druid_tasks WHERE active = FALSE AND created_date >= :start ORDER BY created_date DESC", rewritten:"SELECT   id,   status_payload,   created_date,   datasource,   payload FROM   druid_tasks WHERE active = FALSE AND created_date >= ? ORDER BY created_date DESC", arguments:{ positional:{}, named:{start:'2021-08-18T00:14:42.483Z'}, finder:[]}]
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:284) ~[jdbi-2.63.1.jar:2.63.1]
	at org.apache.druid.metadata.SQLMetadataConnector.lambda$retryWithHandle$0(SQLMetadataConnector.java:145) ~[druid-server-0.20.0-iap3.3.jar:0.20.0-iap3.3]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:87) ~[druid-core-0.20.0-iap3.3.jar:0.20.0-iap3.3]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:115) ~[druid-core-0.20.0-iap3.3.jar:0.20.0-iap3.3]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:105) ~[druid-core-0.20.0-iap3.3.jar:0.20.0-iap3.3]
	at org.apache.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:145) ~[druid-server-0.20.0-iap3.3.jar:0.20.0-iap3.3]
	at org.apache.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:155) ~[druid-server-0.20.0-iap3.3.jar:0.20.0-iap3.3]
	at org.apache.druid.metadata.SQLMetadataStorageActionHandler.getCompletedTaskInfo(SQLMetadataStorageActionHandler.java:277) ~[druid-server-0.20.0-iap3.3.jar:0.20.0-iap3.3]
```

I thought it was a db failure but i can make the same query from a docker mysql client to the same host and it works fine.

**Comment by vrrs** [comment]
I found the issue. I had a spec submitted with "None" for both segment and query granularity. It works as a poison pill. The overlord doesnt reject the spec when it is submitted. It stores the spec on the metadata store. So every time a new task is submitted, it runs on the same issue. The solution is to delete the bad spec from the metadata store.

**Comment by a2l007** [comment]
@didip I don't have the complete context for your issue, but it would be worth checking the size of `druid_tasks` metadata table for completed tasks. I suspect that this table contains a large number of completed task entries which could be why the overlord consumes more memory. If that is indeed the case, enabling `druid.indexer.logs.kill.enabled` and related properties would help.

**Comment by didip** [comment]
@a2l007 That is indeed the issue. `druid_tasks` was simply too full. After enabling the automatic task pruner feature(`druid.indexer.logs.kill.enabled `). The problem disappeared.
