### ISSUE TITLE
SQL `max()`, `min()` fail for `VARCHAR` (`string`) columns

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#11659]
### Affected Version

Version: 0.21.1

### Description

The SQL functions `min()` and `max()` are typically defined to operate over any type with an ordering. However, Druid fails when they are used with a `VARCHAR` (Druid `string`) column. Example:

```sql
SELECT
  min("start"), max("end")
FROM sys.segments
```

Results:

```text
Error: Unknown exception
java.lang.reflect.InvocationTargetException
java.lang.RuntimeException
```

But, the following does work:

```sql
SELECT
  min("size"), max("size")
FROM sys.segments
```

When run against the sample Wikipedia data, we get a more detailed error message:

```sql
SELECT min("user")
FROM "wikipedia"
```

```text
Error: Unknown exception

Error while applying rule DruidQueryRule(AGGREGATE), args [rel#1235:LogicalAggregate.NONE.[]
(input=RelSubset#1230,group={},EXPR$0=MIN($19)), rel#1244:DruidQueryRel.NONE.[](query=
{"queryType":"scan","dataSource":{"type":"table","name":"wikiticker-2015-09-12-sampled"},"intervals":
{"type":"intervals","intervals":["2021-09-03T23:04:08.000Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":
[],"resultFormat":"compactedList","batchSize":20480,"order":"none","filter":null,"columns":
["__time","added","channel","cityName","comment","countryIsoCode","countryName","deleted","delta","
isAnonymous","isMinor","isNew","isRobot","isUnpatrolled","metroCode","namespace","page","
regionIsoCode","regionName","user"],"legacy":false,"context":{"sqlOuterLimit":100,
"sqlQueryId":"531a8bef-ce4b-45a7-96f4-c153d98a0951"},"descending":false,"
granularity":{"type":"all"}},signature={__time:LONG, added:LONG, channel:STRING, 
cityName:STRING, comment:STRING, countryIsoCode:STRING, countryName:STRING, 
deleted:LONG, delta:LONG, isAnonymous:STRING, isMinor:STRING, isNew:STRING, 
isRobot:STRING, isUnpatrolled:STRING, metroCode:STRING, namespace:STRING, 
page:STRING, regionIsoCode:STRING, regionName:STRING, user:STRING})]

java.lang.RuntimeException
```

**Comment by FrankChen021** [comment]
`min`, `max` are aggregators which are supposed to be executed on metric columns. So I think this problem could be treated as a new feature. And could you explain that what's your use case that these two functions are used on string columns?

**Comment by paul-rogers** [comment]
@FrankChen021, thanks for the explanation. I guess my response is more philosophical than technical.

Druid claims to support SQL, and SQL is a standard. Supporting SQL means supporting the standard with, of course, the subtle adjustments and variations needed for each system. The standard was created as an aggregation of many use cases: the standard reviewed and supported those use cases so that each vendor doesn't have to repeat that process. And, as a user, if Druid claims to support SQL, then I should be able to use my knowledge of SQL with Druid without having to justify each SQL feature I might want to use.

Of course, Druid need not support SQL. Some tools offer a "Whatever Query Language", such as a "Druid Query Language" (DQL) which is SQL-like, but picks and chooses which features to support. It confusing for Druid to use the "SQL" term for its "DQL", if the language isn't really SQL. As I said, this is philosophical; we won't resolve it here.

In my case, segments are listed in Druid's own `segments` table using string timestamps. I want to run a single query that finds the range of (published) data for a table. This should be easy to do with standard SQL:

```sql
SELECT
    MIN("start") AS "earliestData",
    MAX("end")   AS "latestData" 
FROM sys.segments
WHERE datasource = 'whatever'
  AND is_published = 1
  AND is_overshadowed = 0
```

SQL is designed to allow such queries. Having contributed to a couple of query engines, I've seen that the `MIN` and `MAX` "aggregate" functions are not hard to implement (I won't say "easy" because nothing in a query engine is easy).

From the user perspective, it should not matter what "kind" of column I use (dimension or metric). In fact, here, it is Druid itself that chose how to represent the columns. (In the `sys` tables, does it even make sense to ask which columns are metrics and which are dimensions? How would I even know?)

Maybe the problem has to do with the special way that Druid handles the `sys` tables? Maybe they are not "really" tables? Maybe some documentation would help to say that "here is a list of Druid SQL features not supported in system tables..."

**Comment by clintropolis** [comment]
> Maybe the problem has to do with the special way that Druid handles the sys tables? Maybe they are not "really" tables? Maybe some documentation would help to say that "here is a list of Druid SQL features not supported in system tables..."

This is actually true, currently Druid's system tables are not processed at all by the Druid native query engine, which produces some differing behavior in SQL queries depending on the tables involved. This is something we would like to change someday for a lot of reasons, this being one of the biggest ones, but we haven't got to it yet and it has a few blockers, such as the ability to order native Druid scan queries by columns other than time.

This is documented, but it isn't perhaps as prominent as it could be: https://druid.apache.org/docs/latest/querying/sql.html#unsupported-features, nor it is exhaustive about the complete set of differences between the 2 implementations.

>Druid claims to support SQL, and SQL is a standard. Supporting SQL means supporting the standard with, of course, the subtle adjustments and variations needed for each system. The standard was created as an aggregation of many use cases: the standard reviewed and supported those use cases so that each vendor doesn't have to repeat that process. And, as a user, if Druid claims to support SQL, then I should be able to use my knowledge of SQL with Druid without having to justify each SQL feature I might want to use.

I think we strive to support SQL in a standard manner, but it is a bit of an ever-going work in progress (which to be fair to some extent could maybe be said of every database which claims to support SQL, since there is quite a lot of variety in behavior between different implementations in my experience 😅 ). I think we welcome any reports on where we differ from the SQL standard so that we can try to fix the issue, or document it in cases where it might not be possible without some non-trivial effort.

I this specific case i wonder if it _is_ related to this being done against the system tables. Do you see the same behavior if you use a similar query on a native Druid table?

**Comment by FrankChen021** [comment]
I checked these two functions on user data source, they didn't work too. The exception shows 'Cannot create aggregator factory for type[STRING]', and the stack trace shows as follows.

```
2021-09-06T01:10:26,329 WARN [sql[fb0c9409-8643-46c7-ac1f-ea1ef07b96e7]] org.apache.druid.sql.http.SqlResource - Failed to handle query: SqlQuery{query='SELECT
  
  min("user")
FROM wikipedia
', resultFormat=array, header=true, context={sqlOuterLimit=101}, parameters=[]}
java.lang.RuntimeException: Error while applying rule DruidQueryRule(AGGREGATE), args [rel#2586:LogicalAggregate.NONE.[](input=RelSubset#2577,group={},EXPR$0=MIN($19)), rel#2587:DruidQueryRel.NONE.[](query={"queryType":"scan","dataSource":{"type":"table","name":"wikipedia"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"order":"none","filter":null,"columns":["__time","added","channel","cityName","comment","countryIsoCode","countryName","deleted","delta","isAnonymous","isMinor","isNew","isRobot","isUnpatrolled","metroCode","namespace","page","regionIsoCode","regionName","user"],"legacy":false,"context":{"sqlOuterLimit":101,"sqlQueryId":"fb0c9409-8643-46c7-ac1f-ea1ef07b96e7"},"descending":false,"granularity":{"type":"all"}},signature={__time:LONG, added:LONG, channel:STRING, cityName:STRING, comment:STRING, countryIsoCode:STRING, countryName:STRING, deleted:LONG, delta:LONG, isAnonymous:STRING, isMinor:STRING, isNew:STRING, isRobot:STRING, isUnpatrolled:STRING, metroCode:STRING, namespace:STRING, page:STRING, regionIsoCode:STRING, regionName:STRING, user:STRING})]
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:235) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:631) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.tools.Programs$RuleSetProgram.run(Programs.java:327) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.tools.Programs$SequenceProgram.run(Programs.java:346) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.prepare.PlannerImpl.transform(PlannerImpl.java:357) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.druid.sql.calcite.planner.DruidPlanner.planWithDruidConvention(DruidPlanner.java:243) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.planner.DruidPlanner.plan(DruidPlanner.java:186) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.SqlLifecycle.plan(SqlLifecycle.java:313) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.http.SqlResource.doPost(SqlResource.java:101) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292-internal]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) ~[jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) ~[jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) ~[jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) ~[jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) ~[jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) ~[jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) ~[jersey-servlet-1.19.3.jar:1.19.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) ~[guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) ~[guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) ~[guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) ~[guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) ~[guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) ~[guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) ~[guice-servlet-4.1.0.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.apache.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:82) ~[druid-server-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.apache.druid.server.security.AllowHttpMethodsResourceFilter.doFilter(AllowHttpMethodsResourceFilter.java:78) ~[druid-server-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.apache.druid.server.security.AllowOptionsResourceFilter.doFilter(AllowOptionsResourceFilter.java:75) ~[druid-server-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.apache.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:84) ~[druid-server-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:59) ~[druid-server-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.apache.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:77) ~[druid-server-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292-internal]
Caused by: org.apache.druid.java.util.common.ISE: Cannot create aggregator factory for type[STRING]
	at org.apache.druid.sql.calcite.aggregation.builtin.MinSqlAggregator.createMinAggregatorFactory(MinSqlAggregator.java:72) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.aggregation.builtin.MinSqlAggregator.getAggregation(MinSqlAggregator.java:53) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.aggregation.builtin.SimpleSqlAggregator.toDruidAggregation(SimpleSqlAggregator.java:91) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.rule.GroupByRules.translateAggregateCall(GroupByRules.java:130) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.rel.DruidQuery.computeAggregations(DruidQuery.java:498) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.rel.DruidQuery.computeGrouping(DruidQuery.java:326) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.rel.DruidQuery.fromPartialQuery(DruidQuery.java:194) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.rel.PartialDruidQuery.build(PartialDruidQuery.java:307) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.rel.DruidQueryRel.toDruidQuery(DruidQueryRel.java:105) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.rel.DruidQueryRel.toDruidQueryForExplaining(DruidQueryRel.java:117) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.rel.DruidRel.isValidDruidQuery(DruidRel.java:55) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.druid.sql.calcite.rule.DruidRules$DruidQueryRule.onMatch(DruidRules.java:137) ~[druid-sql-0.22.0-SNAPSHOT.jar:0.22.0-SNAPSHOT]
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:208) ~[calcite-core-1.21.0.jar:1.21.0]
```

**Comment by FrankChen021** [comment]
Another reported problem #11660 is related to sys table only, that function works on user tables.

**Comment by paul-rogers** [comment]
@clintropolis, thanks for the explanation. Again, this is philosophical. Druid started as a super-fast storage engine with its own query semantics. The "native" queries showed what Druid could (and could not) do. It was the job of the application developer to use those building blocks to perform some given task.

Once SQL enters in the picture, us users kind of hope that the SQL engine will work out how to "make it so" to make a given query work. That's what Drill, Presto and Impala do: no matter how ugly the SQL (and I've seen statements thousands of lines long), the engine "does the right thing", even if that "thing" makes you cringe.

The key thing to realize is that a data analyst has to do whatever is required of them; not just what the storage engine makes easy. If Druid does not support operation *x*, because *x* would be slow, then us poor app developers just have to find some way to code it in the app, probably with multiple queries, which makes the result even slower. Ain't no free lunch...

For example, for this case the workaround is to use two `ORDER BY` queries. If Druid did the `MIN()` and `MAX()` operation, the query could use a single unordered pass over the data. With the workaround, the data must be sorted twice. The overall result to the user is much slower.

I wonder if there is some way to use Drill or Presto to do the queries? Drill has a Druid connector, don't know about Presto. Then, Druid gets to say "pure", and I could delegate the ugly real-world queries to a tool that can handle them. Beyond the scope of this issue, just thinking out loud...

**Comment by rfetishkevi** [comment]
Good afternoon,

I'm working on integrating [GrowthBook](https://github.com/growthbook/growthbook) with Druid to enable running A/B tests on analytics data stored in Druid.

GrowthBook supports integrations with various data warehouses through SQL. Unfortunately, it relies heavily on aggregating over string columns. (`MIN()` and `MAX()` in particular)

Is it possible to implement such functionality in Druid? I am willing to attempt this myself with some guidance, if there are no objections. How much effort would this require, and where should I start?

Thank you.

**Comment by abhishekagarwal87** [comment]
@rfetishkevi Go ahead. You can look at existing min/max aggregators to aide you in figuring out the implementation.
