### ISSUE TITLE
Coordinator cannot load mysql and postgres extensions for sql ingest

### ISSUE THREAD

**Issue by kevin-fibich** [apache/druid#11733]
### Affected Version

0.21.1
but everything up to master seems affected

### Description

mysql and postgres sql ingest require the corresponding metadata extensions to be loaded, which results in an error because both modules are extenting SQLMetadataStorageDruidModule and calling its configure function which includes:

JsonConfigProvider.bind(binder, "druid.audit.manager", SQLAuditManagerConfig.class);

Since this bind can only be called once, the second metadata extension loaded encounters an exception at this point and fails to load, which in turn makes the sql ingestion / firehose module of that extension not load.

### Steps to reproduce

put

druid.extensions.loadList=["postgres-metadata-storage","mysql-metadata-storage"]

in your config and start coordinator.

### Stacktrace

Exception in thread "main" java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:
coordinator |
coordinator | 1) A binding to com.google.common.base.Supplier<org.apache.druid.server.audit.SQLAuditManagerConfig> was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule).
coordinator | at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule)
coordinator |
coordinator | 2) A binding to org.apache.druid.server.audit.SQLAuditManagerConfig was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule).
coordinator | at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule)

**Comment by ludun624** [comment]
I can reproduce this issue in 0.23.0, 0.20.2
It does seems to be a valid case to me when a user need to ingest from mysql and postgres in different datasources.
If no one else working on this issue I can give a try @a2l007

**Comment by FrankChen021** [comment]
The metadata storage is designed to store meta data such as segments/datasources in Druid, and it's supposed to have 1 storage at any time.

So I think the SQL ingestion should be indepdent from the metadata storage module.

I look through the code, current `PostgresqlFirehoseDatabaseConnector` and `MySQLFirehoseDatabaseConnector` does not use any APIs of PostgreSQL or MySQL driver, so one way is to move these classes to 'server' module. Once PostgreSQL or MySQL driver is placed under the `lib` directory, the sql ingestion should work.
