### ISSUE TITLE
Druid startup failed with "Zookeeper is disabled, Can't create CuratorFramework." error without zookeeper

### ISSUE THREAD

**Issue by kaojunsong** [apache/druid#12083]
I want to deploy druid cluster without zookeeper, and I update the configs following https://druid.apache.org/docs/latest/development/extensions-core/kubernetes.html,
But the following error occurs when I try to start the cluster:
`{"instant":{"epochSecond":1639994199,"nanoOfSecond":747000000},"thread":"main","level":"ERROR","loggerName":"org.apache.druid.cli.CliOverlord","message":"Error when starting up.  Failing.","thrown":{"commonElementCount":0,"localizedMessage":"Unable to provision, see the following errors:\n\n1) Error in custom provider, org.apache.druid.java.util.common.RE: server initialization exception\n  at org.apache.druid.server.initialization.jetty.JettyServerModule.getServer(JettyServerModule.java:167) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.initialization.jetty.JettyServerModule)\n  at org.apache.druid.server.initialization.jetty.JettyServerModule.getServer(JettyServerModule.java:167) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.initialization.jetty.JettyServerModule)\n  while locating org.eclipse.jetty.server.Server\n\n1 error","message":"Unable to provision, see the following errors:\n\n1) Error in custom provider, org.apache.druid.java.util.common.RE: server initialization exception\n  at org.apache.druid.server.initialization.jetty.JettyServerModule.getServer(JettyServerModule.java:167) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.initialization.jetty.JettyServerModule)\n  at org.apache.druid.server.initialization.jetty.JettyServerModule.getServer(JettyServerModule.java:167) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.initialization.jetty.JettyServerModule)\n  while locating org.eclipse.jetty.server.Server\n\n1 error","name":"com.google.inject.ProvisionException","cause":{"commonElementCount":5,"localizedMessage":"server initialization exception","message":"server initialization exception","name":"org.apache.druid.java.util.common.RE","cause":{"commonElementCount":5,"localizedMessage":"Unable to provision, see the following errors:\n\n1) Error in custom provider, java.lang.RuntimeException: Zookeeper is disabled, Can't create CuratorFramework.\n  at org.apache.druid.curator.CuratorModule.makeCurator(CuratorModule.java:76) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.curator.CuratorModule)\n  at org.apache.druid.curator.CuratorModule.makeCurator(CuratorModule.java:76) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.curator.CuratorModule)\n  while locating org.apache.curator.framework.CuratorFramework\n    for the 1st parameter of org.apache.druid.indexing.overlord.RemoteTaskRunnerFactory.<init>(RemoteTaskRunnerFactory.java:61)\n  at org.apache.druid.cli.CliOverlord$1.configureRunners(CliOverlord.java:310) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.indexing.overlord.RemoteTaskRunnerFactory\n  at org.apache.druid.cli.CliOverlord$1.configureRunners(CliOverlord.java:307) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.indexing.overlord.TaskRunnerFactory annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=85, type=MAPBINDER, keyType=java.lang.String)\n  at org.apache.druid.guice.PolyBind.createChoice(PolyBind.java:71) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.indexing.overlord.TaskRunnerFactory\n    for the 8th parameter of org.apache.druid.indexing.overlord.TaskMaster.<init>(TaskMaster.java:96)\n  at org.apache.druid.cli.CliOverlord$1.configure(CliOverlord.java:183) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.indexing.overlord.TaskMaster\n    for the 1st parameter of org.apache.druid.indexing.overlord.http.OverlordRedirectInfo.<init>(OverlordRedirectInfo.java:44)\n  while locating org.apache.druid.indexing.overlord.http.OverlordRedirectInfo\n  at org.apache.druid.cli.CliOverlord$1.configure(CliOverlord.java:239) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.server.http.RedirectInfo\n    for the 1st parameter of org.apache.druid.server.http.RedirectFilter.<init>(RedirectFilter.java:48)\n  at org.apache.druid.cli.CliOverlord$1.configure(CliOverlord.java:238) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.server.http.RedirectFilter\n\n1 error","message":"Unable to provision, see the following errors:\n\n1) Error in custom provider, java.lang.RuntimeException: Zookeeper is disabled, Can't create CuratorFramework.\n  at org.apache.druid.curator.CuratorModule.makeCurator(CuratorModule.java:76) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.curator.CuratorModule)\n  at org.apache.druid.curator.CuratorModule.makeCurator(CuratorModule.java:76) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.curator.CuratorModule)\n  while locating org.apache.curator.framework.CuratorFramework\n    for the 1st parameter of org.apache.druid.indexing.overlord.RemoteTaskRunnerFactory.<init>(RemoteTaskRunnerFactory.java:61)\n  at org.apache.druid.cli.CliOverlord$1.configureRunners(CliOverlord.java:310) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.indexing.overlord.RemoteTaskRunnerFactory\n  at org.apache.druid.cli.CliOverlord$1.configureRunners(CliOverlord.java:307) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.indexing.overlord.TaskRunnerFactory annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=85, type=MAPBINDER, keyType=java.lang.String)\n  at org.apache.druid.guice.PolyBind.createChoice(PolyBind.java:71) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.indexing.overlord.TaskRunnerFactory\n    for the 8th parameter of org.apache.druid.indexing.overlord.TaskMaster.<init>(TaskMaster.java:96)\n  at org.apache.druid.cli.CliOverlord$1.configure(CliOverlord.java:183) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.indexing.overlord.TaskMaster\n    for the 1st parameter of org.apache.druid.indexing.overlord.http.OverlordRedirectInfo.<init>(OverlordRedirectInfo.java:44)\n  while locating org.apache.druid.indexing.overlord.http.OverlordRedirectInfo\n  at org.apache.druid.cli.CliOverlord$1.configure(CliOverlord.java:239) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.server.http.RedirectInfo\n    for the 1st parameter of org.apache.druid.server.http.RedirectFilter.<init>(RedirectFilter.java:48)\n  at org.apache.druid.cli.CliOverlord$1.configure(CliOverlord.java:238) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)\n  while locating org.apache.druid.server.http.RedirectFilter\n\n1 error","name":"com.google.inject.ProvisionException","cause":{"commonElementCount":5,"localizedMessage":"Zookeeper is disabled, Can't create CuratorFramework.","message":"Zookeeper is disabled, Can't create CuratorFramework.","name":"java.lang.RuntimeException","extendedStackTrace":[{"class":"org.apache.druid.curator.CuratorModule","method":"makeCurator","file":"CuratorModule.java","line":77,"exact":false,"location":"druid-server-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.curator.CuratorModule$$FastClassByGuice$$fa814fe8","method":"invoke","file":"<generated>","line":-1,"exact":false,"location":"druid-server-0.22.1.jar","version":"0.22.1"},{"class":"com.google.inject.internal.ProviderMethod$FastClassProviderMethod","method":"doProvision","file":"ProviderMethod.java","line":264,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderMethod$Factory","method":"provision","file":"ProviderMethod.java","line":401,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderMethod$Factory","method":"get","file":"ProviderMethod.java","line":376,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter$1","method":"call","file":"ProviderToInternalFactoryAdapter.java","line":46,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1092,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter","method":"get","file":"ProviderToInternalFactoryAdapter.java","line":40,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingletonScope$1","method":"get","file":"SingletonScope.java","line":194,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InternalFactoryToProviderAdapter","method":"get","file":"InternalFactoryToProviderAdapter.java","line":41,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingleParameterInjector","method":"inject","file":"SingleParameterInjector.java","line":38,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingleParameterInjector","method":"getAll","file":"SingleParameterInjector.java","line":62,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorInjector","method":"provision","file":"ConstructorInjector.java","line":110,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorInjector","method":"construct","file":"ConstructorInjector.java","line":90,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorBindingImpl$Factory","method":"get","file":"ConstructorBindingImpl.java","line":268,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter$1","method":"call","file":"ProviderToInternalFactoryAdapter.java","line":46,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1092,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter","method":"get","file":"ProviderToInternalFactoryAdapter.java","line":40,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingletonScope$1","method":"get","file":"SingletonScope.java","line":194,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InternalFactoryToProviderAdapter","method":"get","file":"InternalFactoryToProviderAdapter.java","line":41,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.FactoryProxy","method":"get","file":"FactoryProxy.java","line":56,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter$1","method":"call","file":"ProviderToInternalFactoryAdapter.java","line":46,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1092,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter","method":"get","file":"ProviderToInternalFactoryAdapter.java","line":40,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingletonScope$1","method":"get","file":"SingletonScope.java","line":194,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InternalFactoryToProviderAdapter","method":"get","file":"InternalFactoryToProviderAdapter.java","line":41,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl$2$1","method":"call","file":"InjectorImpl.java","line":1019,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1092,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl$2","method":"get","file":"InjectorImpl.java","line":1015,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.spi.ProviderLookup$1","method":"get","file":"ProviderLookup.java","line":104,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.spi.ProviderLookup$1","method":"get","file":"ProviderLookup.java","line":104,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.spi.ProviderLookup$1","method":"get","file":"ProviderLookup.java","line":104,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.multibindings.MapBinder$RealMapBinder$ValueProvider","method":"get","file":"MapBinder.java","line":821,"exact":false,"location":"guice-multibindings-4.1.0.jar","version":"?"},{"class":"org.apache.druid.guice.PolyBind$ConfiggedProvider","method":"get","file":"PolyBind.java","line":202,"exact":false,"location":"druid-core-0.22.1.jar","version":"0.22.1"},{"class":"com.google.inject.internal.ProviderInternalFactory","method":"provision","file":"ProviderInternalFactory.java","line":81,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InternalFactoryToInitializableAdapter","method":"provision","file":"InternalFactoryToInitializableAdapter.java","line":53,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderInternalFactory","method":"circularGet","file":"ProviderInternalFactory.java","line":61,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InternalFactoryToInitializableAdapter","method":"get","file":"InternalFactoryToInitializableAdapter.java","line":45,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingleParameterInjector","method":"inject","file":"SingleParameterInjector.java","line":38,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingleParameterInjector","method":"getAll","file":"SingleParameterInjector.java","line":62,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorInjector","method":"provision","file":"ConstructorInjector.java","line":110,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorInjector","method":"construct","file":"ConstructorInjector.java","line":90,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorBindingImpl$Factory","method":"get","file":"ConstructorBindingImpl.java","line":268,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter$1","method":"call","file":"ProviderToInternalFactoryAdapter.java","line":46,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1092,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter","method":"get","file":"ProviderToInternalFactoryAdapter.java","line":40,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"org.apache.druid.guice.LifecycleScope$1","method":"get","file":"LifecycleScope.java","line":68,"exact":false,"location":"druid-core-0.22.1.jar","version":"0.22.1"},{"class":"com.google.inject.internal.InternalFactoryToProviderAdapter","method":"get","file":"InternalFactoryToProviderAdapter.java","line":41,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingleParameterInjector","method":"inject","file":"SingleParameterInjector.java","line":38,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingleParameterInjector","method":"getAll","file":"SingleParameterInjector.java","line":62,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorInjector","method":"provision","file":"ConstructorInjector.java","line":110,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorInjector","method":"construct","file":"ConstructorInjector.java","line":90,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorBindingImpl$Factory","method":"get","file":"ConstructorBindingImpl.java","line":268,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.FactoryProxy","method":"get","file":"FactoryProxy.java","line":56,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter$1","method":"call","file":"ProviderToInternalFactoryAdapter.java","line":46,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1092,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter","method":"get","file":"ProviderToInternalFactoryAdapter.java","line":40,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingletonScope$1","method":"get","file":"SingletonScope.java","line":194,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InternalFactoryToProviderAdapter","method":"get","file":"InternalFactoryToProviderAdapter.java","line":41,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingleParameterInjector","method":"inject","file":"SingleParameterInjector.java","line":38,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingleParameterInjector","method":"getAll","file":"SingleParameterInjector.java","line":62,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorInjector","method":"provision","file":"ConstructorInjector.java","line":110,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorInjector","method":"construct","file":"ConstructorInjector.java","line":90,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ConstructorBindingImpl$Factory","method":"get","file":"ConstructorBindingImpl.java","line":268,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter$1","method":"call","file":"ProviderToInternalFactoryAdapter.java","line":46,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1092,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter","method":"get","file":"ProviderToInternalFactoryAdapter.java","line":40,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingletonScope$1","method":"get","file":"SingletonScope.java","line":194,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InternalFactoryToProviderAdapter","method":"get","file":"InternalFactoryToProviderAdapter.java","line":41,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl$2$1","method":"call","file":"InjectorImpl.java","line":1019,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1092,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl$2","method":"get","file":"InjectorImpl.java","line":1015,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"getInstance","file":"InjectorImpl.java","line":1054,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"org.apache.druid.cli.CliOverlord$OverlordJettyServerInitializer","method":"initialize","file":"CliOverlord.java","line":418,"exact":false,"location":"druid-services-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.server.initialization.jetty.JettyServerModule","method":"makeAndInitializeServer","file":"JettyServerModule.java","line":406,"exact":false,"location":"druid-server-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.server.initialization.jetty.JettyServerModule","method":"getServer","file":"JettyServerModule.java","line":167,"exact":false,"location":"druid-server-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.server.initialization.jetty.JettyServerModule$$FastClassByGuice$$ff9924d8","method":"invoke","file":"<generated>","line":-1,"exact":false,"location":"druid-server-0.22.1.jar","version":"0.22.1"},{"class":"com.google.inject.internal.ProviderMethod$FastClassProviderMethod","method":"doProvision","file":"ProviderMethod.java","line":264,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderMethod$Factory","method":"provision","file":"ProviderMethod.java","line":401,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderMethod$Factory","method":"get","file":"ProviderMethod.java","line":376,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter$1","method":"call","file":"ProviderToInternalFactoryAdapter.java","line":46,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1092,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter","method":"get","file":"ProviderToInternalFactoryAdapter.java","line":40,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingletonScope$1","method":"get","file":"SingletonScope.java","line":194,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InternalFactoryToProviderAdapter","method":"get","file":"InternalFactoryToProviderAdapter.java","line":41,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl$2$1","method":"call","file":"InjectorImpl.java","line":1019,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1085,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl$2","method":"get","file":"InjectorImpl.java","line":1015,"exact":false,"location":"guice-4.1.0.jar","version":"?"}]},"extendedStackTrace":[{"class":"com.google.inject.internal.InjectorImpl$2","method":"get","file":"InjectorImpl.java","line":1028,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"getInstance","file":"InjectorImpl.java","line":1054,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"org.apache.druid.cli.CliOverlord$OverlordJettyServerInitializer","method":"initialize","file":"CliOverlord.java","line":418,"exact":false,"location":"druid-services-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.server.initialization.jetty.JettyServerModule","method":"makeAndInitializeServer","file":"JettyServerModule.java","line":406,"exact":false,"location":"druid-server-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.server.initialization.jetty.JettyServerModule","method":"getServer","file":"JettyServerModule.java","line":167,"exact":false,"location":"druid-server-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.server.initialization.jetty.JettyServerModule$$FastClassByGuice$$ff9924d8","method":"invoke","file":"<generated>","line":-1,"exact":false,"location":"druid-server-0.22.1.jar","version":"0.22.1"},{"class":"com.google.inject.internal.ProviderMethod$FastClassProviderMethod","method":"doProvision","file":"ProviderMethod.java","line":264,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderMethod$Factory","method":"provision","file":"ProviderMethod.java","line":401,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderMethod$Factory","method":"get","file":"ProviderMethod.java","line":376,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter$1","method":"call","file":"ProviderToInternalFactoryAdapter.java","line":46,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1092,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter","method":"get","file":"ProviderToInternalFactoryAdapter.java","line":40,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingletonScope$1","method":"get","file":"SingletonScope.java","line":194,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InternalFactoryToProviderAdapter","method":"get","file":"InternalFactoryToProviderAdapter.java","line":41,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl$2$1","method":"call","file":"InjectorImpl.java","line":1019,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1085,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl$2","method":"get","file":"InjectorImpl.java","line":1015,"exact":false,"location":"guice-4.1.0.jar","version":"?"}]},"extendedStackTrace":[{"class":"org.apache.druid.server.initialization.jetty.JettyServerModule","method":"makeAndInitializeServer","file":"JettyServerModule.java","line":409,"exact":false,"location":"druid-server-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.server.initialization.jetty.JettyServerModule","method":"getServer","file":"JettyServerModule.java","line":167,"exact":false,"location":"druid-server-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.server.initialization.jetty.JettyServerModule$$FastClassByGuice$$ff9924d8","method":"invoke","file":"<generated>","line":-1,"exact":false,"location":"druid-server-0.22.1.jar","version":"0.22.1"},{"class":"com.google.inject.internal.ProviderMethod$FastClassProviderMethod","method":"doProvision","file":"ProviderMethod.java","line":264,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderMethod$Factory","method":"provision","file":"ProviderMethod.java","line":401,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderMethod$Factory","method":"get","file":"ProviderMethod.java","line":376,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter$1","method":"call","file":"ProviderToInternalFactoryAdapter.java","line":46,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1092,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.ProviderToInternalFactoryAdapter","method":"get","file":"ProviderToInternalFactoryAdapter.java","line":40,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.SingletonScope$1","method":"get","file":"SingletonScope.java","line":194,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InternalFactoryToProviderAdapter","method":"get","file":"InternalFactoryToProviderAdapter.java","line":41,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl$2$1","method":"call","file":"InjectorImpl.java","line":1019,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"callInContext","file":"InjectorImpl.java","line":1085,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl$2","method":"get","file":"InjectorImpl.java","line":1015,"exact":false,"location":"guice-4.1.0.jar","version":"?"}]},"extendedStackTrace":[{"class":"com.google.inject.internal.InjectorImpl$2","method":"get","file":"InjectorImpl.java","line":1028,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"com.google.inject.internal.InjectorImpl","method":"getInstance","file":"InjectorImpl.java","line":1050,"exact":false,"location":"guice-4.1.0.jar","version":"?"},{"class":"org.apache.druid.guice.LifecycleModule$2","method":"start","file":"LifecycleModule.java","line":141,"exact":false,"location":"druid-core-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.cli.GuiceRunnable","method":"initLifecycle","file":"GuiceRunnable.java","line":115,"exact":true,"location":"druid-services-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.cli.ServerRunnable","method":"run","file":"ServerRunnable.java","line":63,"exact":true,"location":"druid-services-0.22.1.jar","version":"0.22.1"},{"class":"org.apache.druid.cli.Main","method":"main","file":"Main.java","line":113,"exact":true,"location":"druid-services-0.22.1.jar","version":"0.22.1"}]},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":1,"threadPriority":5}`

### Affected Version

0.22.1

### Description

Please include as much detailed information about the problem as possible.
- Cluster size
- Configurations in use
`
druid.zk.service.enabled=false 
druid.serverview.type=http 
druid.coordinator.loadqueuepeon.type=http 
druid.indexer.runner.type=httpRemote 
druid.discovery.type=k8s

druid.discovery.k8s.clusterIdentifier=druid
druid.discovery.k8s.podNameEnvKey=K8S_POD_NAME
druid.discovery.k8s.podNamespaceEnvKey=POD_NAMESPACE
`
- Steps to reproduce the problem: https://druid.apache.org/docs/latest/development/extensions-core/kubernetes.html
- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
- Any debugging that you have already done

**Comment by kaojunsong** [comment]
I have solved this issue, it is caused by the space after "druid.zk.service.enabled=false "
