### ISSUE TITLE
Two python script: generate-binary-license.py and generate-binary-notice.py fails with pyyaml 6.0

### ISSUE THREAD

**Issue by kaisun2000** [apache/druid#12272]
Building from source with `mvn clean install -DskipTests -Pdist -Dmaven.javadoc.skip=true` with current pyyaml 6.0, it would fail with following:

```
[INFO] --- exec-maven-plugin:1.6.0:exec (generate-binary-license) @ distribution ---
=== Generating the contents of LICENSE.BINARY file ===

Traceback (most recent call last):
  File "/Users/kai.sun/falcon_druid/druid_source/druid/distribution/bin/generate-binary-license.py", line 181, in <module>
    generate_license(apache_license_v2, license_yaml)
  File "/Users/kai.sun/falcon_druid/druid_source/druid/distribution/bin/generate-binary-license.py", line 140, in generate_license
    licenses_list = list(yaml.load_all(registry_file))
TypeError: load_all() missing 1 required positional argument: 'Loader'
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
```

This is a pyymal version back compatible problem. 
The following would fix them:

```
diff --git a/distribution/bin/generate-binary-license.py b/distribution/bin/generate-binary-license.py
index e69bc7025e..e08fe04710 100755
--- a/distribution/bin/generate-binary-license.py
+++ b/distribution/bin/generate-binary-license.py
@@ -137,7 +137,7 @@ def generate_license(apache_license_v2, license_yaml):
     # Print Apache license first.
     print_outfile(apache_license_v2)
     with open(license_yaml, encoding='utf-8') as registry_file:
-        licenses_list = list(yaml.load_all(registry_file))
+        licenses_list = list(yaml.load_all(registry_file, Loader=yaml.FullLoader))
 
     # Group licenses by license_name, license_category, and then module.
     licenses_map = {}
diff --git a/distribution/bin/generate-binary-notice.py b/distribution/bin/generate-binary-notice.py
index a7778812b9..5ab1d7cf85 100755
--- a/distribution/bin/generate-binary-notice.py
+++ b/distribution/bin/generate-binary-notice.py
@@ -57,7 +57,7 @@ def generate_notice(source_notice, dependences_yaml):
     # Print Apache license first.
     print_outfile(source_notice)
     with open(dependences_yaml, encoding='utf-8') as registry_file:
-        dependencies = list(yaml.load_all(registry_file))
+        dependencies = list(yaml.load_all(registry_file, Loader=yaml.FullLoader))
 
     # Group dependencies by module
     modules_map = defaultdict(list)

```

**Comment by kaisun2000** [comment]
Closing this one. Filed and use https://github.com/apache/druid/issues/12274 with issue templates.
