### ISSUE TITLE
java needs to be available in PATH for Druid to run properly.

### ISSUE THREAD

**Issue by AlanyTan** [apache/druid#12374]
tasks fails 
### Affected Version

0.22.1

### Description

**- Cluster size:** 4 core 16GB RAM
**- Configurations in use:** micro
**- Steps to reproduce the problem:**
after using the "Load data" function, going through all steps, and submitting the data loader task, the task will fail immediately

**- Please include as much detailed information about the problem as possible.**

The task will fail immediately with an error status: "Failed to run task with an exception. See midldeManager or indexer logs for more details." when I click on the question mark next to "FAILDED"

**- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful:**
click on the magnifier button, some error messages are shown: 
{
  "id": "index_parallel_wikiticker-2015-09-12-sampled_cmadcpic_2022-03-28T05:54:51.570Z",
  "groupId": "index_parallel_wikiticker-2015-09-12-sampled_cmadcpic_2022-03-28T05:54:51.570Z",
  "type": "index_parallel",
  "createdTime": "2022-03-28T05:54:51.575Z",
  "queueInsertionTime": "1970-01-01T00:00:00.000Z",
  "statusCode": "FAILED",
  "status": "FAILED",
  "runnerStatusCode": "WAITING",
  "duration": 161,
  "location": {
    "host": null,
    "port": -1,
    "tlsPort": -1
  },
  "dataSource": "wikiticker-2015-09-12-sampled",
  "errorMsg": "Failed to run task with an exception. See middleManager or indexer logs for more details."
}

in the var/sv/middleManager.log, 
...
2022-03-28T20:50:30,389 INFO [WorkerTaskManager-NoticeHandler] org.apache.druid.indexing.worker.WorkerTaskManager - Task[index_parallel_wikipedia_jfekoimc_2022-03-28T20:50:29.837Z] started.
2022-03-28T20:50:30,392 INFO [forking-task-runner-0] org.apache.druid.indexing.overlord.ForkingTaskRunner - Running command: java -cp /usr/local/bin/druid/apache-druid-0.22.1/conf/druid/single-server/mic
ro-quickstart/middleManager:/usr/local/bin/druid/apache-druid-0.22.1/conf/druid/single-server/micro-quickstart/_common:/usr/local/bin/druid/apache-druid-0.22.1/conf/druid/single-server/micro-quickstart/_
common/hadoop-xml:/usr/local/bin/druid/apache-druid-0.22.1/conf/druid/single-server/micro-quickstart/../_common:/usr/local/bin/druid/apache-druid-0.22.1/conf/druid/single-server/micro-quickstart/../_comm
on/hadoop-xml:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/log4j-core-2.15.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/derbynet-10.14.2.0.jar:/usr/local/bin/druid/apache-druid-0.22.1
/bin/../lib/avatica-metrics-1.17.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/druid-indexing-hadoop-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jetty-rewrite-9.4.40.v20210
413.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-annotations-2.10.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/aether-spi-0.9.0.M2.jar:/usr/local/bin/druid/apache-druid-0.
22.1/bin/../lib/jaxb-runtime-2.3.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/javax.servlet-api-3.1.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/netty-handler-proxy-4.1.68.Final
.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/istack-commons-runtime-3.0.7.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/javax.el-api-3.0.0.jar:/usr/local/bin/druid/apache-druid-0.22
.1/bin/../lib/druid-processing-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/guice-assistedinject-4.1.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/json-path-2.3.0.jar:/usr/l
ocal/bin/druid/apache-druid-0.22.1/bin/../lib/stax-ex-1.8.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-jaxrs-smile-provider-2.10.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../l
ib/netty-codec-4.1.68.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/druid-sql-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-logging-1.1.1.jar:/usr/local/bin/druid
/apache-druid-0.22.1/bin/../lib/jetty-proxy-9.4.40.v20210413.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/druid-hll-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/tesla-aether-
0.0.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-lang-2.6.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/netty-transport-native-unix-common-4.1.68.Final.jar:/usr/local/bin/d
ruid/apache-druid-0.22.1/bin/../lib/aether-impl-0.9.0.M2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/vavr-0.10.2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jna-4.5.1.jar:/usr/loc
al/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-module-jaxb-annotations-2.10.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/avatica-server-1.17.0.jar:/usr/local/bin/druid/apache-druid-0.22
.1/bin/../lib/sigar-1.6.5.132.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/guice-multibindings-4.1.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/janino-3.0.11.jar:/usr/local/bin/dr
uid/apache-druid-0.22.1/bin/../lib/ion-java-1.0.2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/google-oauth-client-1.26.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/slf4j-api-1.7.
25.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/okhttp-1.0.2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-jaxrs-base-2.10.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/
../lib/icu4j-55.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/hibernate-validator-5.2.5.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/vavr-match-0.10.2.jar:/usr/local/bin/drui
d/apache-druid-0.22.1/bin/../lib/disruptor-3.3.6.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/spymemcached-2.12.3.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jetty-servlet-9.4.40.v
20210413.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/aopalliance-1.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/rhino-1.7.11.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../l
ib/datasketches-memory-1.3.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/datasketches-java-2.0.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-io-2.11.0.jar:/usr/local/bin/d
ruid/apache-druid-0.22.1/bin/../lib/metrics-core-4.0.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/guice-servlet-4.1.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-collecti
ons-3.2.2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-math3-3.6.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/validation-api-1.1.0.Final.jar:/usr/local/bin/druid/apache-dr
uid-0.22.1/bin/../lib/maven-model-builder-3.1.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jakarta.activation-api-1.2.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/maven-reposito
ry-metadata-3.1.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/netty-transport-native-epoll-4.1.68.Final-linux-x86_64.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/asm-commons-7.1.ja
r:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jcl-over-slf4j-1.7.12.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/guava-16.0.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/ne
tty-resolver-dns-4.1.68.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jsr305-2.0.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-compress-1.21.jar:/usr/local/bin/druid/a
pache-druid-0.22.1/bin/../lib/aggdesigner-algorithm-6.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/log4j-jul-2.15.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/maven-settings-bui
lder-3.1.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/antlr4-runtime-4.5.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/shims-0.9.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bi
n/../lib/maven-artifact-3.6.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jetty-security-9.4.40.v20210413.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/derby-10.14.2.0.jar:/usr/loca
l/bin/druid/apache-druid-0.22.1/bin/../lib/calcite-core-1.21.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/druid-services-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/FastIn
foset-1.2.15.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/error_prone_annotations-2.8.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-compiler-3.0.11.jar:/usr/local/bin/druid
/apache-druid-0.22.1/bin/../lib/javax.activation-api-1.2.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/aether-util-0.9.0.M2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/aether-api-
0.9.0.M2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jdbi-2.63.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-pool2-2.2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../
lib/derbyclient-10.14.2.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jetty-http-9.4.40.v20210413.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-jaxrs-json-provider-2.10.5.ja
r:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/json-smart-2.3.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-dbcp2-2.0.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/ae
ther-connector-file-0.9.0.M2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/druid-console-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/curator-x-discovery-4.3.0.jar:/usr/local/
bin/druid/apache-druid-0.22.1/bin/../lib/aws-java-sdk-kms-1.12.37.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jersey-guice-1.19.3.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/async
-http-client-2.5.3.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/zookeeper-3.5.9.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/zookeeper-jute-3.5.9.jar:/usr/local/bin/druid/apache-dru
id-0.22.1/bin/../lib/resilience4j-bulkhead-1.3.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-datatype-joda-2.10.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/maven-setting
s-3.1.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jetty-server-9.4.40.v20210413.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/asm-7.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/
bin/../lib/jackson-dataformat-cbor-2.10.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jetty-servlets-9.4.40.v20210413.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jsr311-api-1.1.1.
jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/extendedset-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/druid-aws-common-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin
/../lib/compress-lzf-1.0.4.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/zstd-jni-1.3.3-1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/airline-0.7.jar:/usr/local/bin/druid/apache-dru
id-0.22.1/bin/../lib/commons-net-3.6.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jersey-servlet-1.19.3.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/resilience4j-core-1.3.1.jar:/usr
/local/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-dataformat-smile-2.10.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jetty-continuation-9.4.40.v20210413.jar:/usr/local/bin/druid/apache
-druid-0.22.1/bin/../lib/aws-java-sdk-s3-1.12.37.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/txw2-2.3.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/aether-connector-okhttp-0.0.9.j
ar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/plexus-utils-3.0.24.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-codec-1.13.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../l
ib/netty-reactive-streams-2.0.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/netty-3.10.6.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/google-http-client-1.26.0.jar:/usr/local
/bin/druid/apache-druid-0.22.1/bin/../lib/netty-codec-dns-4.1.68.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/classmate-1.1.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/nett
y-transport-4.1.68.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/javax.el-3.0.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-module-guice-2.10.5.jar:/usr/local/bin/drui
d/apache-druid-0.22.1/bin/../lib/audience-annotations-0.5.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jaxb-api-2.3.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/cron-scheduler-0
.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/druid-indexing-service-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/fastutil-core-8.5.4.jar:/usr/local/bin/druid/apache-druid-
0.22.1/bin/../lib/accessors-smart-1.2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/druid-core-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/asm-analysis-7.1.jar:/usr/local/bin
/druid/apache-druid-0.22.1/bin/../lib/google-http-client-jackson2-1.26.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jetty-util-9.4.40.v20210413.jar:/usr/local/bin/druid/apache-druid-0.22.1/b
in/../lib/netty-codec-http-4.1.68.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/google-api-client-1.26.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/RoaringBitmap-0.9.0.jar:/u
sr/local/bin/druid/apache-druid-0.22.1/bin/../lib/log4j-slf4j-impl-2.15.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/netty-common-4.1.68.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bi
n/../lib/config-magic-0.9.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/esri-geometry-api-2.2.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/joni-2.1.27.jar:/usr/local/bin/druid/apac
he-druid-0.22.1/bin/../lib/netty-codec-socks-4.1.68.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/plexus-interpolation-1.19.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/javax.i
nject-1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jvm-attach-api-1.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/xz-1.8.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/n
etty-handler-4.1.68.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/calcite-linq4j-1.21.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jcodings-1.0.43.jar:/usr/local/bin/druid/ap
ache-druid-0.22.1/bin/../lib/caffeine-2.8.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/httpcore-4.4.11.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jmespath-java-1.12.37.jar:/usr/
local/bin/druid/apache-druid-0.22.1/bin/../lib/aws-java-sdk-ec2-1.12.37.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jetty-io-9.4.40.v20210413.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/
../lib/fastutil-8.5.4.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jetty-client-9.4.40.v20210413.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/fastutil-extra-8.5.4.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/asm-tree-7.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-databind-2.10.5.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-jq-0.0.10.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/j2objc-annotations-1.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/reactive-streams-1.0.2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/httpclient-4.5.10.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/aws-java-sdk-core-1.12.37.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/lz4-java-1.7.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/druid-server-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/joda-time-2.10.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/log4j-1.2-api-2.15.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/druid-gcp-common-0.22.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/javax.activation-1.2.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/guice-4.1.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/protobuf-java-3.11.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-lang3-3.8.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jersey-core-1.19.3.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/opencsv-4.6.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/avatica-core-1.17.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/netty-buffer-4.1.68.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-beanutils-1.9.4.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-datatype-guava-2.10.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/wagon-provider-api-2.4.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/curator-recipes-4.3.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/log4j-api-2.15.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jboss-logging-3.2.1.Final.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/maven-model-3.1.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-collections4-4.2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jersey-server-1.19.3.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jetty-util-ajax-9.4.40.v20210413.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/maven-aether-provider-3.1.1.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jackson-core-2.10.5.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/curator-framework-4.3.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/jakarta.xml.bind-api-2.3.2.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/curator-client-4.3.0.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/checker-qual-2.5.7.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/commons-text-1.3.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/async-http-client-netty-utils-2.5.3.jar:/usr/local/bin/druid/apache-druid-0.22.1/bin/../lib/netty-resolver-4.1.68.Final.jar -server -Xms1g -Xmx1g -XX:MaxDirectMemorySize=1g -Duser.timezone=UTC -Dfile.encoding=UTF-8 -XX:+ExitOnOutOfMemoryError -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Ddruid.indexer.task.baseTaskDir=var/druid/task -Ddruid.host=localhost -Ddruid.metadata.storage.connector.host=localhost -Ddruid.indexer.fork.property.druid.processing.numThreads=1 -Ddruid.emitter.logging.logLevel=info -Ddruid.emitter=noop -Ddruid.indexer.fork.property.druid.processing.buffer.sizeBytes=100MiB -Duser.timezone=UTC -Dfile.encoding.pkg=sun.io -Ddruid.storage.storageDirectory=var/druid/segments -Ddruid.selectors.coordinator.serviceName=druid/coordinator -Ddruid.selectors.indexing.serviceName=druid/overlord -Ddruid.indexing.doubleStorage=double -Ddruid.lookup.enableLookupSyncOnStartup=false -Ddruid.server.http.numThreads=12 -Ddruid.worker.capacity=2 -Ddruid.metadata.storage.connector.port=1527 -Ddruid.service=druid/middleManager -Ddruid.metadata.storage.type=derby -Ddruid.metadata.storage.connector.connectURI=jdbc:derby://localhost:1527/var/druid/metadata.db;create=true -Ddruid.plaintextPort=8091 -Djava.io.tmpdir=var/tmp -Ddruid.extensions.loadList=["druid-hdfs-storage", "druid-kafka-indexing-service", "druid-datasketches"] -Ddruid.sql.enable=true -Ddruid.startup.logging.logProperties=true -Ddruid.server.hiddenProperties=["druid.s3.accessKey","druid.s3.secretKey","druid.metadata.storage.connector.password"] -Ddruid.zk.service.host=localhost -Ddruid.monitoring.monitors=["org.apache.druid.java.util.metrics.JvmMonitor"] -Ddruid.indexer.logs.directory=var/druid/indexing-logs -Ddruid.zk.paths.base=/druid -Dfile.encoding=UTF-8 -Ddruid.storage.type=local -Ddruid.indexer.task.hadoopWorkingPath=var/druid/hadoop-tmp -Ddruid.indexer.fork.property.druid.processing.numMergeBuffers=2 -Ddruid.indexer.logs.type=file -Ddruid.processing.numThreads=1 -Ddruid.processing.buffer.sizeBytes=100MiB -Ddruid.processing.numMergeBuffers=2 -Ddruid.metrics.emitter.dimension.dataSource=wikipedia -Ddruid.metrics.emitter.dimension.taskId=index_parallel_wikipedia_jfekoimc_2022-03-28T20:50:29.837Z -Ddruid.metrics.emitter.dimension.taskType=index_parallel -Ddruid.host=localhost -Ddruid.plaintextPort=8100 -Ddruid.tlsPort=-1 -Ddruid.task.executor.service=druid/middleManager -Ddruid.task.executor.host=localhost -Ddruid.task.executor.plaintextPort=8091 -Ddruid.task.executor.enablePlaintextPort=true -Ddruid.task.executor.tlsPort=-1 -Ddruid.task.executor.enableTlsPort=false org.apache.druid.cli.Main internal peon var/druid/task/index_parallel_wikipedia_jfekoimc_2022-03-28T20:50:29.837Z/task.json var/druid/task/index_parallel_wikipedia_jfekoimc_2022-03-28T20:50:29.837Z/4f31d2fa-4cff-45ea-968d-4cc40b47b38d/status.json var/druid/task/index_parallel_wikipedia_jfekoimc_2022-03-28T20:50:29.837Z/4f31d2fa-4cff-45ea-968d-4cc40b47b38d/report.json
2022-03-28T20:50:30,396 INFO [forking-task-runner-0] org.apache.druid.indexing.overlord.ForkingTaskRunner - Exception caught during execution
java.io.IOException: Cannot run program "java": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_202]
        at org.apache.druid.indexing.overlord.ForkingTaskRunner.runTaskProcess(ForkingTaskRunner.java:448) ~[druid-indexing-service-0.22.1.jar:0.22.1]
        at org.apache.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:351) [druid-indexing-service-0.22.1.jar:0.22.1]
        at org.apache.druid.indexing.overlord.ForkingTaskRunner$1.call(ForkingTaskRunner.java:138) [druid-indexing-service-0.22.1.jar:0.22.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_202]
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247) ~[?:1.8.0_202]
        at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_202]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_202]
        ... 7 more
2022-03-28T20:50:30,409 INFO [forking-task-runner-0] org.apache.druid.indexing.overlord.ForkingTaskRunner - Removing task directory: var/druid/task/index_parallel_wikipedia_jfekoimc_2022-03-28T20:50:29.837Z

**- Any debugging that you have already done:**

Turns out, java needs to be in the PATH for DRUID to be able to spun new processes. 
A workaround is adding my JAVA bin directory to my PATH fixed this problem. 
`export PATH=$PATH:/usr/local/bin/jdk1.8.0_202/bin/`

Interestingly this was not mentioned in the quick tutorial guide.  (This was not mentioned in JAVA 8 installation guide either). 

It seems this should not be necessary though, because I specified DRUID_JAVA_HOME, and for any forked processes, it should use my DRUID_JAVA_HOME/bin/java instead of calling "java" directly  (see the line started with [forking-task-runner-0])

**Comment by FrankChen021** [comment]
Druid finds JRE in following order: `DRUID_JAVA_HOME`, `JAVA_HOME`, `PATH`. The tutorial/index.md doc only mentions about the first two.

>  Druid relies on the environment variables `JAVA_HOME` or `DRUID_JAVA_HOME` to find Java on the machine. You can set
`DRUID_JAVA_HOME` if there is more than one instance of Java. To verify Java requirements for your environment, run the 
`bin/verify-java` script.

And from the exception message you gave above, it seems like that Druid does not indicate that the JRE is under  DRUID_JAVA_HOME when forking a task process.

Both the code and doc can be improved.

**Comment by AlanyTan** [comment]
Yeah, I tried both DRUID_JAVA_HOME and JAVA_HOME, either way the `bin/verify-java` returned `0` telling me it passes the verification.  Druid starts, and the webGUI works, I was able to use data loader, etc. 

It only throws error after submitting a task, which needs to be run asynchronously in a separate process, in which case, it seems relying on the PATH.

Not big deal, but seems not consistent given DRUID_JAVA_HOME was given and was able to start the main broker, router, etc.

**Comment by Navid61** [comment]
I did set DRUID_JAVA_HOME in ~. /zshrc (I installed oh-my-zsh) on Debian v11 x64, moreover I did set DRUID_JAVA_HOME in ~/.profile also but I got error message it can't find Java. ai can see DRUID_JAVA_HOME path by ``` echo $DRUID_JAVA_HOME ``` correctly but still I've Java path issue. how can I fix that issue?
