### ISSUE TITLE
Calcite throw java.util.NoSuchElementException when using identical lists in SELECT and WHERE

### ISSUE THREAD

**Issue by renatocron** [apache/druid#12620]
When executing the following query (using the wikipedia sample data):

```SQL
SELECT 
    MAX("added") as last_added, 
    case when cityName IN ('Abbotsford','Aglayan' ) then '-1' else 0 end as MyFavCitiesFirst 
FROM wikipedia 
WHERE 
    __time >= CURRENT_TIMESTAMP - INTERVAL '7' YEAR 
    AND 
    ( 
       cityName IN ('Abbotsford', 'Aglayan') 
    ) 
GROUP BY 
    cityName
ORDER BY MyFavCitiesFirst, last_added DESC 
LIMIT 1 
```
Calcites try to otimize somethings and fails:
```
WARN [query-id] org.apache.druid.sql.http.SqlResource - Failed to handle query: SqlQuery{query='SELECT...
', resultFormat=array, header=true, context={timeout=13033, sqlOuterLimit=101}, parameters=[]}
java.util.NoSuchElementException: null 
at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_275] 
at org.apache.calcite.sql2rel.RelStructuredTypeFlattener.getNewInputFieldByNewOrdinal(RelStructuredTypeFlattener.java:311) ~[calcite-core-1.21.0.jar:1.21.0] 
at org.apache.calcite.sql2rel.RelStructuredTypeFlattener.getNewFieldForOldInput(RelStructuredTypeFlattener.java:301) ~[calcite-core-1.21.0.jar:1.21.0] 
at org.apache.calcite.sql2rel.RelStructuredTypeFlattener.getNewFieldForOldInput(RelStructuredTypeFlattener.java:322) ~[calcite-core-1.21.0.jar:1.21.0] 
at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRexShuttle.visitInputRef(RelStructuredTypeFlattener.java:809) ~[calcite-core-1.21.0.jar:1.21.0]
at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRexShuttle.visitInputRef(RelStructuredTypeFlattener.java:806) ~[calcite-core-1.21.0.jar:1.21.0]
at org.apache.calcite.rex.RexInputRef.accept(RexInputRef.java:112) ~[calcite-core-1.21.0.jar:1.21.0] 
at org.apache.calcite.rex.RexShuttle.visitList(RexShuttle.java:149) ~[calcite-core-1.21.0.jar:1.21.0] 
```
Full log at https://gist.github.com/renatocron/3ef274ec83627b258c4b376b7f9c1cb6

If you change the query to add some item to the first or the second list, the query runs successfully:
```SQL
SELECT 
    MAX("added") as last_added, 
    case when cityName IN ('Abbotsford','Aglayan', '') then '-1' else 0 end as MyFavCitiesFirst 
FROM wikipedia 
WHERE 
    __time >= CURRENT_TIMESTAMP - INTERVAL '7' YEAR 
    AND 
    ( 
       cityName IN ('Abbotsford', 'Aglayan') 
    ) 

GROUP BY 
    cityName
ORDER BY MyFavCitiesFirst, last_added DESC 
LIMIT 1 
```
Should return:

|last_added|MyFavCitiesFirst|
|----------|----------------|
|10        |-1              |

### Affected Version

Tested over 0.22.1 and 0.23.0-rc1 (apache/druid:0.22.1 image, druid.extensions.loadList=["druid-kafka-indexing-service", "druid-s3-extensions", "postgresql-metadata-storage", "druid-histogram", "druid-datasketches", "druid-avro-extensions", "druid-bloom-filter"])

You may ask, why would I run such query? Well, this is the reduced version for easy testing that trigger the bug, the original query was already an attempt to solve another that I will open after that one!

```SQL
SELECT 
    MAX("added") as last_added, 
    case when cityName IN ('Abbotsford','Aglayan', '') then '-1' else 0 end as MyFavCitiesFirst 
FROM wikipedia 
WHERE 
    __time >= CURRENT_TIMESTAMP - INTERVAL '7' YEAR 
    AND 
    ( 
     (
       1 = 1 OR -- only to feature-check this condition for only some runs 
       cityName IN ('Abbotsford', 'Aglayan', '') 
       AND commentLength > 10 -- for example, views on pages..
       ) OR (
           cityName IN ('OTHER', 'list','of','generic','cities')    
           AND isRobot = '0' -- some other conditions .. 
       )
    ) 
GROUP BY 
    cityName
ORDER BY MyFavCitiesFirst, last_added DESC 
LIMIT 1 
```

**Comment by renatocron** [comment]
I was not able to reproduce the issue with the wikipedia datasource, even when re-importing multiple times to have lot of segments.

the original query I was doing was:
(select X where the conditions matched the MyFavCitiesFirst)
union all 
(select 2 where the conds matched other rules)

but for some uses, the first query must should be disabled, so I did the same work-arround I usually do (use some bind to enable/disable the conditions, usually calcite optimizes this for no-op)

but with this query and datasource I have, I got this exception:
```
 2022-06-09T03:24:33,879 WARN [sql[a50ad38f-265e-4115-96be-b4826c95ca86]] org.apache.druid.sql.http.SqlResource - Failed to handle query: SqlQuery{query='( 
 SELECT  
       CONCAT(dim_xpto,''), 
     MAX("last_seen") as last_seen 
 FROM datasource 
 WHERE  
     __time >= CURRENT_TIMESTAMP - INTERVAL '7' DAY  
     AND  
     (  
           1 = -1  -- dynamically disabling this query
     )  
 GROUP BY  
     1 
 ORDER BY last_seen DESC  
  
 LIMIT 1  
  ) 
 UNION ALL 
 ( 
 SELECT  
     CONCAT(dim_xpto,''), 
      
     MAX("last_seen") as last_seen 
 FROM datasource 
 WHERE  
     __time >= CURRENT_TIMESTAMP - INTERVAL '7' DAY  
   
 GROUP BY  
     1 
 ORDER BY last_seen DESC  
 LIMIT 1  
 )', resultFormat=array, header=true, context={sqlOuterLimit=101}, parameters=[]} 
 org.apache.calcite.plan.RelOptPlanner$CannotPlanException: There are not enough rules to produce a node with desired properties: convention=DRUID, sort=[]. 
 Missing conversion is LogicalSort[convention: NONE -> DRUID] 
 There is 1 empty subset: rel#140371:Subset#11.DRUID.[], the relevant part of the original plan is as follows 
 140369:LogicalSort(fetch=[101]) 
   140367:LogicalUnion(subset=[rel#140368:Subset#10.NONE.[]], all=[true]) 
     140350:LogicalProject(subset=[rel#140382:Subset#1.NONE.[1 DESC]], EXPR$0=[CONCAT($2, '')], last_seen=[$1]) 
       140314:LogicalValues(subset=[rel#140349:Subset#0.NONE.[]], tuples=[[]]) 
     140365:LogicalSort(subset=[rel#140366:Subset#9.NONE.[1 DESC]], sort0=[$1], dir0=[DESC], fetch=[1]) 
       140363:LogicalAggregate(subset=[rel#140364:Subset#8.NONE.[]], group=[{0}], last_seen=[MAX($1)]) 
         140361:LogicalProject(subset=[rel#140362:Subset#7.NONE.[]], EXPR$0=[CONCAT($2, '')], last_seen=[$1]) 
           140359:LogicalFilter(subset=[rel#140360:Subset#6.NONE.[]], condition=[>=($0, 2022-06-02 03:24:33)]) 
             140357:LogicalProject(subset=[rel#140358:Subset#5.NONE.[]], __time=[$0], last_seen=[$6], dim_xpto=[$7]) 
               140283:LogicalTableScan(subset=[rel#140356:Subset#4.NONE.[]], table=[[druid, datasource]]) 
  
 Root: rel#140371:Subset#11.DRUID.[] 
 Original rel: 
```
I'll try to make a dataset to reproduce this, but at the moment I'm too busy to debug this further, it's easier to just use the order-by version above with the list work-arround, or change the query on the code instead of using the bind to disable portions of it

**Comment by renatocron** [comment]
Tested on 0.23-rc1 - error is still present

**Comment by renatocron** [comment]
So, it's not related to https://github.com/apache/druid/issues/12621#event-6895083054
still exists on 0.23.0 (before was only tested again the RC1)

**Comment by renatocron** [comment]
Hi @abhishekagarwal87 
same error as before:
```
[druid-gl-brokers-0] 2022-06-28T17:47:59,926 WARN [sql[48ee08ee-b796-4c67-a1b8-7bdcc31339ce]] org.apache.druid.sql.http.SqlResource - Failed to handle query: SqlQuery{query='SELECT  
[druid-gl-brokers-0]     MAX("added") as last_added,  
[druid-gl-brokers-0]     case when cityName IN ('Abbotsford','Aglayan') then '-1' else 0 end as MyFavCitiesFirst  
[druid-gl-brokers-0] FROM wikipedia  
[druid-gl-brokers-0] WHERE  
[druid-gl-brokers-0]     __time >= CURRENT_TIMESTAMP - INTERVAL '7' YEAR  
[druid-gl-brokers-0]     AND  
[druid-gl-brokers-0]     (  
[druid-gl-brokers-0]        cityName IN ('Abbotsford', 'Aglayan')  
[druid-gl-brokers-0]     )  
[druid-gl-brokers-0] GROUP BY  
[druid-gl-brokers-0]     cityName 
[druid-gl-brokers-0] ORDER BY MyFavCitiesFirst, last_added DESC  
[druid-gl-brokers-0] LIMIT 1  
[druid-gl-brokers-0] ', resultFormat=array, header=true, typesHeader=true, sqlTypesHeader=true, context={useApproximateTopN=false, sqlOuterLimit=101, sqlQueryId=48ee08ee-b796-4c67-a1b8-7bdcc31339ce}, parameters=[]} 
[druid-gl-brokers-0] java.util.NoSuchElementException: null 
[druid-gl-brokers-0] 	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_275] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener.getNewInputFieldByNewOrdinal(RelStructuredTypeFlattener.java:311) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener.getNewFieldForOldInput(RelStructuredTypeFlattener.java:301) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener.getNewFieldForOldInput(RelStructuredTypeFlattener.java:322) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRexShuttle.visitInputRef(RelStructuredTypeFlattener.java:809) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRexShuttle.visitInputRef(RelStructuredTypeFlattener.java:806) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rex.RexInputRef.accept(RexInputRef.java:112) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rex.RexShuttle.visitList(RexShuttle.java:149) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rex.RexShuttle.visitCall(RexShuttle.java:101) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRexShuttle.visitCall(RelStructuredTypeFlattener.java:910) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRexShuttle.visitCall(RelStructuredTypeFlattener.java:806) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rex.RexCall.accept(RexCall.java:191) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rex.RexShuttle.visitList(RexShuttle.java:149) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rex.RexShuttle.visitCall(RexShuttle.java:101) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRexShuttle.visitCall(RelStructuredTypeFlattener.java:903) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRexShuttle.visitCall(RelStructuredTypeFlattener.java:806) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rex.RexCall.accept(RexCall.java:191) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rex.RexShuttle.visitList(RexShuttle.java:149) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rex.RexShuttle.visitCall(RexShuttle.java:101) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRexShuttle.visitCall(RelStructuredTypeFlattener.java:903) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRexShuttle.visitCall(RelStructuredTypeFlattener.java:806) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rex.RexCall.accept(RexCall.java:191) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener.flattenProjection(RelStructuredTypeFlattener.java:667) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener.flattenProjections(RelStructuredTypeFlattener.java:565) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener.rewriteRel(RelStructuredTypeFlattener.java:486) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source) ~[?:?] 
[druid-gl-brokers-0] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275] 
[druid-gl-brokers-0] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275] 
[druid-gl-brokers-0] 	at org.apache.calcite.util.ReflectUtil.invokeVisitorInternal(ReflectUtil.java:257) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.util.ReflectUtil.invokeVisitor(ReflectUtil.java:214) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.util.ReflectUtil$1.invokeVisitor(ReflectUtil.java:464) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRelVisitor.visit(RelStructuredTypeFlattener.java:787) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rel.SingleRel.childrenAccept(SingleRel.java:72) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.rel.RelVisitor.visit(RelVisitor.java:44) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener$RewriteRelVisitor.visit(RelStructuredTypeFlattener.java:782) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.RelStructuredTypeFlattener.rewrite(RelStructuredTypeFlattener.java:197) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.sql2rel.SqlToRelConverter.flattenTypes(SqlToRelConverter.java:468) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.calcite.prepare.PlannerImpl.rel(PlannerImpl.java:255) ~[calcite-core-1.21.0.jar:1.21.0] 
[druid-gl-brokers-0] 	at org.apache.druid.sql.calcite.planner.DruidPlanner.plan(DruidPlanner.java:225) ~[druid-sql-0.23.0.jar:0.23.0] 
[druid-gl-brokers-0] 	at org.apache.druid.sql.SqlLifecycle.plan(SqlLifecycle.java:301) ~[druid-sql-0.23.0.jar:0.23.0] 
[druid-gl-brokers-0] 	at org.apache.druid.sql.http.SqlResource.doPost(SqlResource.java:123) ~[druid-sql-0.23.0.jar:0.23.0] 
[druid-gl-brokers-0] 	at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source) ~[?:?] 
[druid-gl-brokers-0] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275] 
[druid-gl-brokers-0] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275] 
[druid-gl-brokers-0] 	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[jersey-server-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) ~[jersey-server-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) ~[jersey-server-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) ~[jersey-server-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) ~[jersey-server-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) ~[jersey-servlet-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) ~[jersey-servlet-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) ~[jersey-servlet-1.19.4.jar:1.19.4] 
[druid-gl-brokers-0] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0] 
[druid-gl-brokers-0] 	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) ~[guice-servlet-4.1.0.jar:?] 
[druid-gl-brokers-0] 	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) ~[guice-servlet-4.1.0.jar:?] 
[druid-gl-brokers-0] 	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) ~[guice-servlet-4.1.0.jar:?] 
[druid-gl-brokers-0] 	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) ~[guice-servlet-4.1.0.jar:?] 
[druid-gl-brokers-0] 	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) ~[guice-servlet-4.1.0.jar:?] 
[druid-gl-brokers-0] 	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) ~[guice-servlet-4.1.0.jar:?] 
[druid-gl-brokers-0] 	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) ~[guice-servlet-4.1.0.jar:?] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.apache.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:82) ~[druid-server-0.23.0.jar:0.23.0] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.apache.druid.server.initialization.jetty.StandardResponseHeaderFilterHolder$StandardResponseHeaderFilter.doFilter(StandardResponseHeaderFilterHolder.java:161) ~[druid-server-0.23.0.jar:0.23.0] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.apache.druid.server.security.AllowHttpMethodsResourceFilter.doFilter(AllowHttpMethodsResourceFilter.java:78) ~[druid-server-0.23.0.jar:0.23.0] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.apache.druid.server.security.AllowOptionsResourceFilter.doFilter(AllowOptionsResourceFilter.java:75) ~[druid-server-0.23.0.jar:0.23.0] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.apache.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:84) ~[druid-server-0.23.0.jar:0.23.0] 
[druid-gl-brokers-0] 	at org.apache.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:59) ~[druid-server-0.23.0.jar:0.23.0] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.apache.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:77) ~[druid-server-0.23.0.jar:0.23.0] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413] 
[druid-gl-brokers-0] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413] 
```

**Comment by renatocron** [comment]
The crazy part is, if you change the order in the list, or add any element, the errors disappear, so is some issue on calcite when it detects 2 identicals lists in the query on Group BY queries

```SQL 
SELECT 
    added
     ,     case when cityName IN ('Abbotsford','Aglayan') then '-1' else 0 end as MyFavCitiesFirst 
FROM wikipedia 
WHERE 
    __time >= CURRENT_TIMESTAMP - INTERVAL '7' YEAR 
    AND 
      
       cityName IN ('Abbotsford', 'Aglayan') 
      ```
Is running, so maybe the issue is not present when the detect "scan" queries,

I tried to make a 'topN' query but I dunno how to force it,
I get the same error (java.util.NoSuchElementException) with this other query:
```
SELECT 
    added
     ,     case when cityName IN ('Abbotsford','Aglayan') then '-1' else 0 end as MyFavCitiesFirst 
FROM wikipedia 
WHERE 
    __time >= CURRENT_TIMESTAMP - INTERVAL '7' YEAR 
    AND 
      
       cityName IN ('Abbotsford', 'Aglayan')
       group by added, cityName, __time
       ORDER BY __time
      limit 2
```
that runs group-by on all fields, but has no max() functions
