### ISSUE TITLE
Flaky test: PrefetchableTextFilesFirehoseFactoryTest

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#12638]
Test [failed on Travis](https://app.travis-ci.com/github/apache/druid/jobs/573231078), works on a Mac. Test passed on previous runs. No code in the PR changed anything in the code covered by this test.

```text
[ERROR] Tests run: 13, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 73.209 s <<< FAILURE! - in org.apache.druid.data.input.impl.prefetch.PrefetchableTextFilesFirehoseFactoryTest
[ERROR] org.apache.druid.data.input.impl.prefetch.PrefetchableTextFilesFirehoseFactoryTest.testWithSmallCacheAndLargeFetch  Time elapsed: 60.066 s  <<< ERROR!
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at org.apache.druid.data.input.impl.prefetch.Fetcher.openObjectFromLocal(Fetcher.java:226)
	at org.apache.druid.data.input.impl.prefetch.Fetcher.next(Fetcher.java:177)
	at org.apache.druid.data.input.impl.prefetch.PrefetchableTextFilesFirehoseFactory$2.next(PrefetchableTextFilesFirehoseFactory.java:239)
	at org.apache.druid.data.input.impl.prefetch.PrefetchableTextFilesFirehoseFactory$2.next(PrefetchableTextFilesFirehoseFactory.java:225)
	at org.apache.druid.data.input.impl.FileIteratingFirehose.getNextLineIterator(FileIteratingFirehose.java:105)
	at org.apache.druid.data.input.impl.FileIteratingFirehose.hasMore(FileIteratingFirehose.java:66)
	at org.apache.druid.data.input.impl.prefetch.PrefetchableTextFilesFirehoseFactoryTest.testWithSmallCacheAndLargeFetch(PrefetchableTextFilesFirehoseFactoryTest.java:278)
```

I have observed other failures in "firehose" tests (can't recall if it is this same test), did some poking around, and noticed that the code, while using concurrency constructs, used them independently with no locking between the various objects. I suspect this leads to race conditions and occasional failures.

**Comment by paul-rogers** [comment]
Failed again [in this run](https://app.travis-ci.com/github/apache/druid/jobs/573231078). The test passes when run on the same code branch from an IDE.

**Comment by paul-rogers** [comment]
Failed again [in this run](https://app.travis-ci.com/github/apache/druid/jobs/573248953). The test passes when run on the same code branch from an IDE.

**Comment by paul-rogers** [comment]
Failed again in [this run](https://app.travis-ci.com/github/apache/druid/jobs/573968991).

**Comment by paul-rogers** [comment]
Failed again in [this run](https://app.travis-ci.com/github/apache/druid/jobs/573975166):

```text

[INFO] Running org.apache.druid.data.input.impl.prefetch.PrefetchableTextFilesFirehoseFactoryTest
[ERROR] Tests run: 13, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 21.109 s <<< FAILURE! - in org.apache.druid.data.input.impl.prefetch.PrefetchableTextFilesFirehoseFactoryTest
[ERROR] org.apache.druid.data.input.impl.prefetch.PrefetchableTextFilesFirehoseFactoryTest.testReconnectWithCacheAndPrefetch  Time elapsed: 8.165 s  <<< ERROR!
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at org.apache.druid.data.input.impl.prefetch.Fetcher.openObjectFromLocal(Fetcher.java:226)
	at org.apache.druid.data.input.impl.prefetch.Fetcher.next(Fetcher.java:177)
	at org.apache.druid.data.input.impl.prefetch.PrefetchableTextFilesFirehoseFactory$2.next(PrefetchableTextFilesFirehoseFactory.java:239)
	at org.apache.druid.data.input.impl.prefetch.PrefetchableTextFilesFirehoseFactory$2.next(PrefetchableTextFilesFirehoseFactory.java:225)
	at org.apache.druid.data.input.impl.FileIteratingFirehose.getNextLineIterator(FileIteratingFirehose.java:105)
	at org.apache.druid.data.input.impl.FileIteratingFirehose.hasMore(FileIteratingFirehose.java:66)
	at org.apache.druid.data.input.impl.prefetch.PrefetchableTextFilesFirehoseFactoryTest.testReconnectWithCacheAndPrefetch(PrefetchableTextFilesFirehoseFactoryTest.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	...
Caused by: java.util.concurrent.TimeoutException
	... 39 more
```

**Comment by paul-rogers** [comment]
Failed again in [this build](https://app.travis-ci.com/github/apache/druid/jobs/576754236).

**Comment by paul-rogers** [comment]
`PrefetchableTextFilesFirehoseFactoryTest.testWithCacheAndFetch` failed again in [this build](https://app.travis-ci.com/github/apache/druid/jobs/578428499).

**Comment by paul-rogers** [comment]
`PrefetchableTextFilesFirehoseFactoryTest.testReconnectWithCacheAndPrefetch` failed again in [this build](https://app.travis-ci.com/github/apache/druid/jobs/578851688). These failures are a real drag on productivity: I have to rerun the expensive Travis tests again and again so I can get to Phase 2 ITs.

**Comment by abhishekagarwal87** [comment]
These flaky test will be gone once https://github.com/apache/druid/pull/12852 is merged.

**Comment by paul-rogers** [comment]
`PrefetchableTextFilesFirehoseFactoryTest.testReconnectWithCacheAndPrefetch` again in [this build](https://app.travis-ci.com/github/apache/druid/jobs/580243194). Looking forward to seeing #12852 be merged!
