### ISSUE TITLE
Flaky Test: RemoteTaskRunnerTest

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#12643]
`RemoteTaskRunnerTest` failed in [this run](https://app.travis-ci.com/github/apache/druid/jobs/573231075):

```text
[ERROR] org.apache.druid.indexing.overlord.RemoteTaskRunnerTest.testRunPendingTaskFailToAssignTask  Time elapsed: 0.247 s  <<< ERROR!
java.util.concurrent.TimeoutException: Timeout waiting for task.
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:269)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at org.apache.druid.indexing.overlord.RemoteTaskRunnerTest.testRunPendingTaskFailToAssignTask(RemoteTaskRunnerTest.java:576)
```

The PR where this failed did not make any changes in Overlord. The same test passes when run on this same code in an IDE.

**Comment by gianm** [comment]
The test case was added in #11419, which was about improving error message. The case is a little strange: it uses a mocked work item whose ID changes across calls to `getTaskId`. No real work item does that. There's a comment `// modify taskId to make task assignment failed` that suggests this is being done to force the RemoteTaskRunner down an assignment-failed path, so we can verify that the error message comes out as expected. We may want to rethink how the test case works, so it can be more realistic.

**Comment by paul-rogers** [comment]
The test [strikes again](https://app.travis-ci.com/github/apache/druid/jobs/573833686):

```text
[INFO] Running org.apache.druid.indexing.overlord.RemoteTaskRunnerTest
[ERROR] Tests run: 30, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 72.755 s <<< FAILURE! - in org.apache.druid.indexing.overlord.RemoteTaskRunnerTest
[ERROR] org.apache.druid.indexing.overlord.RemoteTaskRunnerTest.testRunPendingTaskFailToAssignTask  Time elapsed: 0.243 s  <<< ERROR!
java.util.concurrent.TimeoutException: Timeout waiting for task.
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:269)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at org.apache.druid.indexing.overlord.RemoteTaskRunnerTest.testRunPendingTaskFailToAssignTask(RemoteTaskRunnerTest.java:579)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.apache.druid.testing.DeadlockDetectingFailOnTimeout$CallableStatement.call(DeadlockDetectingFailOnTimeout.java:287)
	at org.apache.druid.testing.DeadlockDetectingFailOnTimeout$CallableStatement.call(DeadlockDetectingFailOnTimeout.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by paul-rogers** [comment]
Failed again in [this build](https://app.travis-ci.com/github/apache/druid/jobs/587271323) (JDK 17):

```text

[INFO] Running org.apache.druid.indexing.overlord.RemoteTaskRunnerTest
[ERROR] Tests run: 30, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 73.777 s <<< FAILURE! - in org.apache.druid.indexing.overlord.RemoteTaskRunnerTest
[ERROR] org.apache.druid.indexing.overlord.RemoteTaskRunnerTest.testRunPendingTaskFailToAssignTask  Time elapsed: 0.227 s  <<< ERROR!
java.util.concurrent.TimeoutException: Timeout waiting for task.
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:269)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at org.apache.druid.indexing.overlord.RemoteTaskRunnerTest.testRunPendingTaskFailToAssignTask(RemoteTaskRunnerTest.java:576)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.apache.druid.testing.DeadlockDetectingFailOnTimeout$CallableStatement.call(DeadlockDetectingFailOnTimeout.java:287)
	at org.apache.druid.testing.DeadlockDetectingFailOnTimeout$CallableStatement.call(DeadlockDetectingFailOnTimeout.java:278)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Usual caveats about the PR in question changing nothing in the are covered by this test.

**Comment by paul-rogers** [comment]
An attempt to rerun also failed, but in a [different way](https://app.travis-ci.com/github/apache/druid/jobs/587271323). There were dozens of failures, starting with:

```text
[ERROR] Tests run: 30, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 74.007 s <<< FAILURE! - in org.apache.druid.indexing.overlord.RemoteTaskRunnerTest
[ERROR] org.apache.druid.indexing.overlord.RemoteTaskRunnerTest.testRunPendingTaskFailToAssignTask  Time elapsed: 0.239 s  <<< ERROR!
java.util.concurrent.TimeoutException: Timeout waiting for task.
```

And compounding with dozens of failures until we get to:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

Again, on this PR, no changes where made to this area of the code. Nothing changed between this failure and the one in the previous note: I simply reran the tests. Something seems very flaky in this test.

**Comment by abhishekagarwal87** [comment]
Fixed by https://github.com/apache/druid/pull/13344
