### ISSUE TITLE
Flaky Test: ITAutoCompactionTest

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#12645]
The Integration test `ITAutoCompactionTest` failed in [this run](https://app.travis-ci.com/github/apache/druid/jobs/573250451) on a branch that (probably) changed nothing in the auto-compaction area. (The only caveat is that this PR omits null or empty fields from JSON serialization of native queries. If this test verifies serialization against a text version of the query, it can fail. Yet, inspection of the code suggests that this is not the problem.)

```text
[ERROR] Failures: 
[ERROR]   ITAutoCompactionTest.testAutoCompactionDutyCanUpdateTaskSlots:592->getAndAssertCompactionStatus:1788 expected [14906] but found [14762]
[ERROR]   ITAutoCompactionTest.testAutoCompactionDutySubmitAndVerifyCompaction:457->getAndAssertCompactionStatus:1789 expected [14906] but found [14762]
```

Specific error:

```text
2022-06-12T05:25:51,745 INFO [main] org.apache.druid.testing.utils.ITRetryUtil - Attempt[0/240] did not pass: Task Waiting for all tasks of [wikipedia_index_test_073384f1-d44c-4cc6-a564-a834fb3e3ec5 %Россия 한국 中国!?] to complete still not complete. Next retry in 5000 ms
2022-06-12T05:25:56,745 INFO [main] org.apache.druid.testing.utils.ITRetryUtil - Trying attempt[1/240]...
2022-06-12T05:25:56,882 ERROR [main] org.apache.druid.testing.utils.LoggerListener - Failed [org.apache.druid.tests.coordinator.duty.ITAutoCompactionTest.testAutoCompactionDutyCanUpdateTaskSlots]
java.lang.AssertionError: expected [14906] but found [14762]
	at org.apache.druid.tests.coordinator.duty.ITAutoCompactionTest.getAndAssertCompactionStatus(ITAutoCompactionTest.java:1788) ~[test-classes/:?]
	at org.apache.druid.tests.coordinator.duty.ITAutoCompactionTest.testAutoCompactionDutyCanUpdateTaskSlots(ITAutoCompactionTest.java:592) ~[test-classes/:?]
```

Unfortunately, it is very difficult to retry this test on a local branch.

**Comment by maytasm** [comment]
These auto compaction tests verify the segments size pre and post compaction. The expected values are hardcoded and changes in the underlying segment file structure can cause the test to fail (for example if adding or removing anything in the segment file).

**Comment by paul-rogers** [comment]
@maytasm, thanks for the explanation. The particular PR where the failures occurred did not change compaction or the segment file format. Any suggestions for how to debug these tests to determine if the bug is "real" or transient?
