### ISSUE TITLE
Flaky IT: ITQueryRetryTestOnMissingSegments

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#12652]
The integration test `ITQueryRetryTestOnMissingSegments` in build step "(Compile=openjdk8, Run=openjdk11) query retry integration test for missing segments" failed in [this build](https://github.com/apache/druid/pull/12222/checks?check_run_id=6884591519). This test had passed previously on the same PR with only trivial differences. The PR in question did not change anything having to do with missing segments.

```text
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 155.186 s <<< FAILURE! - in TestSuite
[ERROR] testWithRetriesDisabledPartialResultAllowed(org.apache.druid.tests.query.ITQueryRetryTestOnMissingSegments)  Time elapsed: 11.274 s  <<< FAILURE!
java.lang.AssertionError: At least one query is expected to return correct results. expected [true] but found [false]
	at org.apache.druid.tests.query.ITQueryRetryTestOnMissingSegments.testQueries(ITQueryRetryTestOnMissingSegments.java:216)
	at org.apache.druid.tests.query.ITQueryRetryTestOnMissingSegments.testQueries(ITQueryRetryTestOnMissingSegments.java:141)
	at org.apache.druid.tests.query.ITQueryRetryTestOnMissingSegments.testWithRetriesDisabledPartialResultAllowed(ITQueryRetryTestOnMissingSegments.java:122)
```

**Comment by abhishekagarwal87** [comment]
Fixed by https://github.com/apache/druid/pull/12818
