### ISSUE TITLE
Flaky test: EmitterTest.testTimeBasedEmission

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#12655]
The unit test `EmitterTest.testTimeBasedEmission` failed in [this build](https://app.travis-ci.com/github/apache/druid/jobs/573410046), but works on the same code when run locally on a Mac. Failure:

```text
[ERROR] org.apache.druid.java.util.emitter.core.EmitterTest.testTimeBasedEmission  Time elapsed: 10.313 s  <<< ERROR!
java.io.IOException: Timed out after [10000] millis during flushing
	at org.apache.druid.java.util.emitter.core.HttpPostEmitter.flush(HttpPostEmitter.java:429)
	at org.apache.druid.java.util.emitter.core.HttpPostEmitter.close(HttpPostEmitter.java:447)
	at org.apache.druid.java.util.emitter.core.EmitterTest.closeNoFlush(EmitterTest.java:616)
	at org.apache.druid.java.util.emitter.core.EmitterTest.testTimeBasedEmission(EmitterTest.java:383)
	at ...
Caused by: java.util.concurrent.TimeoutException
	at org.apache.druid.concurrent.ConcurrentAwaitableCounter.awaitCount(ConcurrentAwaitableCounter.java:126)
	at org.apache.druid.java.util.emitter.core.HttpPostEmitter.flush(HttpPostEmitter.java:425)
	... 33 more
...
[WARNING] Flakes: 
[WARNING] org.apache.druid.java.util.emitter.core.EmitterTest.testTimeBasedEmission
[ERROR]   Run 1: EmitterTest.testTimeBasedEmission:383->closeNoFlush:616 » IO Timed out after [10000] millis during flushing
[INFO]   Run 2: PASS
```

Needless to day, the PR in question did not alter anything having to do with an emitter and its time based emission. The PR instead removed nulls from the serialized JSON query format.

An observation is that time-based tests are generally a poor idea: there is sufficient variability in build systems that one cannot anticipate the time it will take to perform any operation. Time spent waiting also simply shows the entire test run.

It appears that we expect the test to be flaky, and so we retry? The error thus reported is a red-herring? Even so, it took time to track down the fact that the error is not the error that caused the test to fail: having "false" errors is unproductive.

**Comment by paul-rogers** [comment]
Failed again in [this build](https://app.travis-ci.com/github/apache/druid/jobs/573847615).

**Comment by paul-rogers** [comment]
Failed again in [this build](https://app.travis-ci.com/github/apache/druid/jobs/576754236).
