### ISSUE TITLE
Flaky IT: kafka index, transactional kafka index integration test with Indexer

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#12691]
IT test [(Compile=openjdk8, Run=openjdk8) kafka index, transactional kafka index integration test with Indexer](https://app.travis-ci.com/github/apache/druid/jobs/573989714) failed. The PR in question added new "catalog" code, but modified no existing code. The catalog code is, at present, unreachable from the rest of Druid. So, the IT is likely flaky.

Failures:

```text

2022-06-18T22:24:13,276 ERROR [TestNG-test=AllParallelizedTests-1] org.apache.druid.testing.utils.LoggerListener - Failed [org.apache.druid.tests.parallelized.ITKafkaIndexingServiceNonTransactionalParallelizedTest.testKafkaIndexDataWithWithAutoscaler]
org.apache.druid.java.util.common.ISE: Max number of retries[50] exceeded for Task[waiting for autoScaling task numbers from 1 to 2]. Failing.
	at org.apache.druid.testing.utils.ITRetryUtil.retryUntil(ITRetryUtil.java:94) ~[druid-integration-tests-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at org.apache.druid.tests.indexer.AbstractStreamIndexingTest.doTestIndexDataWithAutoscaler(AbstractStreamIndexingTest.java:360) ~[test-classes/:?]
	at org.apache.druid.tests.parallelized.ITKafkaIndexingServiceNonTransactionalParallelizedTest.testKafkaIndexDataWithWithAutoscaler(ITKafkaIndexingServiceNonTransactionalParallelizedTest.java:62) ~[test-classes/:?]

... 
[ERROR] testKafkaIndexDataWithKafkaReshardSplit(org.apache.druid.tests.parallelized.ITKafkaIndexingServiceNonTransactionalParallelizedTest)  Time elapsed: 115.074 s
[ERROR] testKafkaIndexDataWithStartStopSupervisor(org.apache.druid.tests.parallelized.ITKafkaIndexingServiceNonTransactionalParallelizedTest)  Time elapsed: 48.863 s
[ERROR] testKafkaTerminatedSupervisorAutoCleanup(org.apache.druid.tests.parallelized.ITKafkaIndexingServiceNonTransactionalParallelizedTest)  Time elapsed: 91.684 s
[ERROR] testKafkaIndexDataWithKafkaReshardSplit(org.apache.druid.tests.parallelized.ITKafkaIndexingServiceTransactionalParallelizedTest)  Time elapsed: 71.839 s
[ERROR] testKafkaIndexDataWithStartStopSupervisor(org.apache.druid.tests.parallelized.ITKafkaIndexingServiceTransactionalParallelizedTest)  Time elapsed: 71.484 s
[ERROR] testKafkaIndexDataWithWithAutoscaler(org.apache.druid.tests.parallelized.ITKafkaIndexingServiceNonTransactionalParallelizedTest)  Time elapsed: 305.625 s  <<< FAILURE!
org.apache.druid.java.util.common.ISE: Max number of retries[50] exceeded for Task[waiting for autoScaling task numbers from 1 to 2]. Failing.
	at org.apache.druid.tests.parallelized.ITKafkaIndexingServiceNonTransactionalParallelizedTest.testKafkaIndexDataWithWithAutoscaler(ITKafkaIndexingServiceNonTransactionalParallelizedTest.java:62)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ITKafkaIndexingServiceNonTransactionalParallelizedTest.testKafkaIndexDataWithWithAutoscaler:62->AbstractStreamIndexingTest.doTestIndexDataWithAutoscaler:360 » ISE
```

**Comment by abhishekagarwal87** [comment]
Closing as these tests are no longer flaky after moving to GHA.
