### ISSUE TITLE
Flaky IT: ITBroadcastJoinQueryTest. testBroadcastJoin

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#12732]
The IT `ITBroadcastJoinQueryTest.testBroadcastJoin` failed in [(Compile=openjdk8, Run=openjdk11) query integration test (mariaDB)](https://app.travis-ci.com/github/apache/druid/jobs/575271343) with this error:

```text
[ERROR] testBroadcastJoin(org.apache.druid.tests.query.ITBroadcastJoinQueryTest)  Time elapsed: 1,284.467 s  <<< FAILURE!
org.apache.druid.java.util.common.ISE: Max number of retries[240] exceeded for Task[waiting for SQL metadata refresh]. Failing.
	at org.apache.druid.tests.query.ITBroadcastJoinQueryTest.testBroadcastJoin(ITBroadcastJoinQueryTest.java:134)
```

Details:

```text

2022-06-30T21:38:36,853 ERROR [main] org.apache.druid.testing.utils.TestQueryHelper - Failed while executing query {query=SELECT TABLE_NAME, IS_JOINABLE, IS_BROADCAST FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'broadcast_join_wikipedia_test' AND IS_JOINABLE = 'YES' AND IS_BROADCAST = 'YES' AND TABLE_SCHEMA = 'druid'} 
 expectedResults: [{"TABLE_NAME":"broadcast_join_wikipedia_test","IS_JOINABLE":"YES","IS_BROADCAST":"YES"}] 
 actualResults : []
2022-06-30T21:38:36,853 INFO [main] org.apache.druid.testing.utils.TestQueryHelper - Running Query {query=SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'broadcast_join_wikipedia_test'}
2022-06-30T21:38:36,947 INFO [main] org.apache.druid.testing.utils.TestQueryHelper - Results Verified for Query {query=SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'broadcast_join_wikipedia_test'}
2022-06-30T21:38:36,947 ERROR [main] org.apache.druid.tests.query.ITBroadcastJoinQueryTest - SQL metadata not yet in expected state
org.apache.druid.java.util.common.ISE: one or more queries failed
	at org.apache.druid.testing.utils.AbstractTestQueryHelper.testQueries(AbstractTestQueryHelper.java:165) ~[druid-integration-tests-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at org.apache.druid.testing.utils.AbstractTestQueryHelper.testQueriesFromString(AbstractTestQueryHelper.java:138) ~[druid-integration-tests-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at org.apache.druid.tests.query.ITBroadcastJoinQueryTest.lambda$testBroadcastJoin$1(ITBroadcastJoinQueryTest.java:107) ~[test-classes/:?]
	at org.apache.druid.testing.utils.ITRetryUtil.retryUntil(ITRetryUtil.java:61) ~[druid-integration-tests-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at org.apache.druid.testing.utils.ITRetryUtil.retryUntilTrue(ITRetryUtil.java:39) ~[druid-integration-tests-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at org.apache.druid.tests.query.ITBroadcastJoinQueryTest.testBroadcastJoin(ITBroadcastJoinQueryTest.java:104) ~[test-classes/:?]
        ...
```

The PR in question did not change the query execution path, only the JDBC driver. The test had passed on two previous runs. The only change between the runs was correcting the expected error message text in the JDBC IT. Thus, the failure seems spurious.

**Comment by abhishekagarwal87** [comment]
This should have been fixed by https://github.com/apache/druid/pull/12727
