### ISSUE TITLE
org.apache.druid.indexing.common.task.batch.parallel.PartialCompactionTest is flaky

### ISSUE THREAD

**Issue by abhishekagarwal87** [apache/druid#12748]
org.apache.druid.indexing.common.task.batch.parallel.PartialCompactionTest seems to be stalling the build - see this run here for example https://app.travis-ci.com/github/apache/druid/jobs/575725134

**Comment by kfaraz** [comment]
+1, I have noticed this one too several times. It can also be seen in the logs of #12747

**Comment by paul-rogers** [comment]
Failed in [this build](https://app.travis-ci.com/github/apache/druid/jobs/587935826), which is an ARM build:

```text

[ERROR] Tests run: 5, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 201.022 s <<< FAILURE! - in org.apache.druid.indexing.common.task.batch.parallel.PartialCompactionTest
[ERROR] org.apache.druid.indexing.common.task.batch.parallel.PartialCompactionTest.testPartialCompactHashAndDynamicPartitionedSegments  Time elapsed: 89.626 s  <<< FAILURE!
java.lang.AssertionError: Actual task status: TaskStatus{id=compact_dataSource_fjadibcc_2022-11-09T05:26:19.500Z, status=FAILED, duration=-1, errorMsg=Ran [11] specs, [8] succeeded, [3] failed} expected:<SUCCESS> but was:<FAILED>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.apache.druid.indexing.common.task.batch.parallel.AbstractMultiPhaseParallelIndexingTest.runTaskAndVerifyStatus(AbstractMultiPhaseParallelIndexingTest.java:179)
	at org.apache.druid.indexing.common.task.batch.parallel.AbstractMultiPhaseParallelIndexingTest.runTask(AbstractMultiPhaseParallelIndexingTest.java:184)
	at org.apache.druid.indexing.common.task.batch.parallel.PartialCompactionTest.testPartialCompactHashAndDynamicPartitionedSegments(PartialCompactionTest.java:141)
```
