### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1432668

### ISSUE THREAD

**Issue by qoega** [apache/druid#12761]
### Affected Version

The Druid version where the problem was encountered.

0.23.0

### Description
While running query `SELECT SearchEngineID, SearchPhrase, COUNT(*) AS c FROM hits WHERE SearchPhrase <> '' GROUP BY SearchEngineID, SearchPhrase ORDER BY c DESC LIMIT 10`

```
2022-07-08T17:53:55,989 ERROR [processing-1] org.apache.druid.query.groupby.epinephelinae.GroupByMergingQueryRunnerV2 - Exception with one of the sequences!
java.lang.ArrayIndexOutOfBoundsException: 1432668
        at org.apache.druid.query.groupby.epinephelinae.RowBasedGrouperHelper$RowBasedKeySerde$AbstractStringRowBasedKeySerdeHelper.lambda$new$0(RowBasedGrouperHelper.java:1628) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.query.groupby.epinephelinae.GrouperBufferComparatorUtils$3.compare(GrouperBufferComparatorUtils.java:104) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.query.groupby.epinephelinae.BufferHashGrouper.lambda$iterator$0(BufferHashGrouper.java:212) ~[druid-processing-0.23.0.jar:0.23.0]
        at java.util.TimSort.gallopRight(TimSort.java:632) ~[?:1.8.0_312]
        at java.util.TimSort.mergeAt(TimSort.java:496) ~[?:1.8.0_312]
        at java.util.TimSort.mergeForceCollapse(TimSort.java:457) ~[?:1.8.0_312]
        at java.util.TimSort.sort(TimSort.java:254) ~[?:1.8.0_312]
        at java.util.Arrays.sort(Arrays.java:1438) ~[?:1.8.0_312]
        at java.util.List.sort(List.java:478) ~[?:1.8.0_312]
        at java.util.Collections.sort(Collections.java:177) ~[?:1.8.0_312]
        at org.apache.druid.query.groupby.epinephelinae.BufferHashGrouper.iterator(BufferHashGrouper.java:208) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.query.groupby.epinephelinae.SpillingGrouper.spill(SpillingGrouper.java:297) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.query.groupby.epinephelinae.SpillingGrouper.aggregate(SpillingGrouper.java:182) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.query.groupby.epinephelinae.ConcurrentGrouper.aggregate(ConcurrentGrouper.java:286) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.query.groupby.epinephelinae.Grouper.aggregate(Grouper.java:85) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.query.groupby.epinephelinae.RowBasedGrouperHelper.lambda$createGrouperAccumulatorPair$2(RowBasedGrouperHelper.java:335) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.BaseSequence.accumulate(BaseSequence.java:44) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.LazySequence.accumulate(LazySequence.java:40) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.LazySequence.accumulate(LazySequence.java:40) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.query.spec.SpecificSegmentQueryRunner$1.accumulate(SpecificSegmentQueryRunner.java:86) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.query.spec.SpecificSegmentQueryRunner.doNamed(SpecificSegmentQueryRunner.java:169) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.query.spec.SpecificSegmentQueryRunner.access$100(SpecificSegmentQueryRunner.java:43) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.query.spec.SpecificSegmentQueryRunner$2.wrap(SpecificSegmentQueryRunner.java:152) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:77) ~[druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[druid-core-0.23.0.jar:0.23.0]
        at org.apache.druid.query.groupby.epinephelinae.GroupByMergingQueryRunnerV2$1$1$1.call(GroupByMergingQueryRunnerV2.java:246) [druid-processing-0.23.0.jar:0.23.0]
        at org.apache.druid.query.groupby.epinephelinae.GroupByMergingQueryRunnerV2$1$1$1.call(GroupByMergingQueryRunnerV2.java:233) [druid-processing-0.23.0.jar:0.23.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at org.apache.druid.query.PrioritizedListenableFutureTask.run(PrioritizedExecutorService.java:251) [druid-processing-0.23.0.jar:0.23.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

This query failed with default config and suggested to 
```
Not enough dictionary space to execute this query. Try increasing druid.query.groupBy.maxMergingDictionarySize or enable disk spilling by setting druid.query.groupBy.maxOnDiskStorage to a positive number.
```
I tried to add `druid.query.groupBy.maxOnDiskStorage=10000` to `conf/druid/single-server/medium/historical/runtime.properties`

**Comment by gianm** [comment]
Do you have a dataset you can share that will reproduce this?

I'm wondering if it's related to #12513. This patch has not been included in a release yet. It fixed a concurrency bug that could happen when the grouping engine starts spilling to disk. So I'd like to see if this still happens when that patch is applied.

**Comment by qoega** [comment]
I posted information about dataset when I tried to insert it and if failed:
https://apachedruidworkspace.slack.com/archives/C0309C9L90D/p1656418379371149

**Comment by gianm** [comment]
I was able to reproduce this on my machine: thanks @qoega for the detailed guidance. The problem was a race that can occur while a query is canceling itself due to lack of disk scratch space. (10000 is quite small value for maxOnDiskStorage: it is in bytes.)

This patch fixes it: https://github.com/apache/druid/pull/12764. The proper behavior here, after applying that patch, would be to report this error:

> Not enough disk space to execute this query. Try raising druid.query.groupBy.maxOnDiskStorage.

With higher `druid.query.groupBy.maxOnDiskStorage` the query succeeds.
