### ISSUE TITLE
Kinesis Supervisor fails to start when skipIgnorableShards is set to true.

### ISSUE THREAD

**Issue by jimjoamz** [apache/druid#12787]
### Affected Version

0.23.0

### Description

Kinesis supervisors with the setting `skipIgnorableShards` set to `true` are unable to start a supervisor task, going to UNHEALTHY_SUPERVISOR status.  To get a root cause stack trace, you need to turn `DEBUG` logging up on `SeekableStreamSupervisor`.

```
2022-07-14T14:59:05.896-07:00	java.lang.UnsupportedOperationException: null	application/DruidCoordinatorContainer/a784c353ac4044a088524d0097f78caf
	2022-07-14T14:59:05.896-07:00	at com.google.common.collect.ImmutableCollection.removeAll(ImmutableCollection.java:132) ~[guava-16.0.1.jar:?]	application/DruidCoordinatorContainer/a784c353ac4044a088524d0097f78caf
	2022-07-14T14:59:05.896-07:00	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.updatePartitionDataFromStream(SeekableStreamSupervisor.java:2333) ~[druid-indexing-service-0.23.0.jar:0.23.0]	application/DruidCoordinatorContainer/a784c353ac4044a088524d0097f78caf
	2022-07-14T14:59:05.896-07:00	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.runInternal(SeekableStreamSupervisor.java:1442) ~[druid-indexing-service-0.23.0.jar:0.23.0]	application/DruidCoordinatorContainer/a784c353ac4044a088524d0097f78caf
	2022-07-14T14:59:05.896-07:00	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor$RunNotice.handle(SeekableStreamSupervisor.java:398) ~[druid-indexing-service-0.23.0.jar:0.23.0]	application/DruidCoordinatorContainer/a784c353ac4044a088524d0097f78caf
	2022-07-14T14:59:05.896-07:00	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.lambda$tryInit$3(SeekableStreamSupervisor.java:1030) ~[druid-indexing-service-0.23.0.jar:0.23.0]
```

If I submit an otherwise identicial Kinesis supervisor task with this setting as `false` the supervisor starts as expected.

**Comment by AmatyaAvadhanula** [comment]
Hi @jimjoamz
https://github.com/apache/druid/pull/12791 has been raised to fix it
