### ISSUE TITLE
Flaky UT: SeekableStreamSupervisorStateTest.testEmitNoticesTime

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#12865]
The UR `SeekableStreamSupervisorStateTest.testEmitNoticesTime` failed in [this build](https://app.travis-ci.com/github/apache/druid/jobs/578832602):

```text
[ERROR] Tests run: 14, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 9.244 s <<< FAILURE! - in org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisorStateTest
[ERROR] org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisorStateTest.testEmitNoticesTime  Time elapsed: 1.013 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisorStateTest.testEmitNoticesTime(SeekableStreamSupervisorStateTest.java:795)
```

The same test runs fine, on the same branch, when run on a Mac in the IDE. The test passed on this branch in previous Travis runs. The PR in question changes only SQL classes, and changes nothing in the Supervisor. Conclusion: flaky test.

**Comment by abhishekagarwal87** [comment]
Already fixed by #12875
