### ISSUE TITLE
FLAKY UT : .SegmentMetadataCacheTest.testLocalSegmentCacheSetsDataSourceAsBroadcastButNotJoinable

### ISSUE THREAD

**Issue by cryptoe** [apache/druid#12954]
```
org.apache.druid.sql.calcite.schema.SegmentMetadataCacheTest.testLocalSegmentCacheSetsDataSourceAsBroadcastButNotJoinable  Time elapsed: 1.155 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.apache.druid.sql.calcite.schema.SegmentMetadataCacheTest.testLocalSegmentCacheSetsDataSourceAsBroadcastButNotJoinable(SegmentMetadataCacheTest.java:1013)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

```
	
	Found in job : https://app.travis-ci.com/github/apache/druid/jobs/580691762

**Comment by paul-rogers** [comment]
This _should_ be fixed in one of the recent PRs in this area. I ran into this also and made some code changes which, at least in my builds, have fixed the issue. Closing for now, please reopen if anyone sees this again.
