### ISSUE TITLE
Flaky IT: ITKafkaIndexingServiceNonTransactionalParallelizedTest

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#13203]
The IT `ITKafkaIndexingServiceNonTransactionalParallelizedTest` failed in [this build](https://app.travis-ci.com/github/apache/druid/jobs/584928091):

```text
2022-10-06T17:51:12,585 ERROR [TestNG-test=AllParallelizedTests-2] org.apache.druid.testing.utils.LoggerListener - Failed [org.apache.druid.tests.parallelized.ITKafkaIndexingServiceNonTransactionalParallelizedTest.testKafkaIndexDataWithWithAutoscaler]
org.apache.druid.java.util.common.ISE: Max number of retries[50] exceeded for Task[waiting for autoScaling task numbers from 1 to 2]. Failing.
	at org.apache.druid.testing.utils.ITRetryUtil.retryUntil(ITRetryUtil.java:94) ~[druid-integration-tests-25.0.0-SNAPSHOT.jar:25.0.0-SNAPSHOT]
	at org.apache.druid.tests.indexer.AbstractStreamIndexingTest.doTestIndexDataWithAutoscaler(AbstractStreamIndexingTest.java:360) ~[test-classes/:?]
	at org.apache.druid.tests.parallelized.ITKafkaIndexingServiceNonTransactionalParallelizedTest.testKafkaIndexDataWithWithAutoscaler(ITKafkaIndexingServiceNonTransactionalParallelizedTest.java:62) ~[test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132) ~[testng-7.3.0.jar:?]
```

The PR in question added entirely new code (the Catalog PR) and did not in any way touch the Kafka or indexing code. Conclusion: flaky IT.

**Comment by tejaswini-imply** [comment]
Thanks, @paul-rogers, for raising this issue, It's fixed in this PR - https://github.com/apache/druid/pull/13144.

**Comment by paul-rogers** [comment]
Closing since the fix has been merged. Thanks @tejaswini-imply for the fix!
