### ISSUE TITLE
Getting 'java.lang.ArithmeticException: / by zero' in overlord log

### ISSUE THREAD

**Issue by sachidananda007** [apache/druid#13613]
The Druid version where the problem was encountered.
0.22.1
In over lord log i can see this error log
> Uncaught exception.
java.lang.ArithmeticException: / by zero
	at org.apache.druid.java.util.metrics.SysMonitor$CpuStats.emit(SysMonitor.java:459) ~[druid-core-0.22.1.jar:0.22.1]
	at org.apache.druid.java.util.metrics.SysMonitor.doMonitor(SysMonitor.java:107) ~[druid-core-0.22.1.jar:0.22.1]
	at org.apache.druid.java.util.metrics.AbstractMonitor.monitor(AbstractMonitor.java:48) ~[druid-core-0.22.1.jar:0.22.1]
	at org.apache.druid.java.util.metrics.BasicMonitorScheduler.lambda$startMonitor$0(BasicMonitorScheduler.java:56) ~[druid-core-0.22.1.jar:0.22.1]
	at org.apache.druid.java.util.common.concurrent.ScheduledExecutors$4.run(ScheduledExecutors.java:163) [druid-core-0.22.1.jar:0.22.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_342]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_342]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_342]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_342]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]

**Comment by LakshSingla** [comment]
Here's what I think might have happened - For a utilization metric of JVM (nice time, idle time, wait time, etc), the SysMonitor reports the stat as a percentage of the difference between the current utilization time and the last reported utilization time over the difference between total JVM time between the two occurrences. In case the delta between the total time (for any CPU) is 0, this might throw an arithmetic exception. The fix for this should be simple, i.e. to not emit the metrics when the delta total is 0. 
To understand if the above is correct, are you seeing these error messages often in the logs? My guess is that it should be a rare occurrence. And if you are seeing this continuously, does Druid run as a main process on the server, or are there other processes that can preempt the execution?
