### ISSUE TITLE
MSQ Query fails with "Cannot have empty worker set" when running against a time interval with no segments

### ISSUE THREAD

**Issue by adamb-sternumiot** [apache/druid#14102]
### Affected Version

25.0

### Description

Here's an example query that fails
```sql
SELECT *
FROM "table"
WHERE "table"."__time" >= '2020-08-06T00:00:00' 
  AND "table"."__time" < '2020-08-07T00:00:00'
```

the exact error message is 
```
org.apache.druid.java.util.common.IAE: Cannot have empty worker set
	at org.apache.druid.msq.input.stage.ReadablePartition.<init>(ReadablePartition.java:45)
	at org.apache.druid.msq.input.stage.ReadablePartition.striped(ReadablePartition.java:59)
	at org.apache.druid.msq.input.stage.StripedReadablePartitions.lambda$iterator$0(StripedReadablePartitions.java:66)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators.size(Iterators.java:187)
	at org.apache.druid.msq.exec.ControllerImpl$RunQueryUntilDone.lambda$updateLiveReportMaps$4(ControllerImpl.java:2208)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.apache.druid.msq.exec.ControllerImpl$RunQueryUntilDone.updateLiveReportMaps(ControllerImpl.java:2206)
	at org.apache.druid.msq.exec.ControllerImpl$RunQueryUntilDone.run(ControllerImpl.java:2029)
	at org.apache.druid.msq.exec.ControllerImpl$RunQueryUntilDone.access$000(ControllerImpl.java:1983)
	at org.apache.druid.msq.exec.ControllerImpl.runTask(ControllerImpl.java:361)
	at org.apache.druid.msq.exec.ControllerImpl.run(ControllerImpl.java:305)
	at org.apache.druid.msq.indexing.MSQControllerTask.runTask(MSQControllerTask.java:192)
	at org.apache.druid.indexing.common.task.AbstractTask.run(AbstractTask.java:169)
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:477)
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:449)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

If it makes any difference, the `table` datasource is ingested from kafka. There are no segments for this day (06.08.2020) and the query works as expected if it overlaps with any of existing segments.

I'm not sure if it's the same issue, but also when we try to run the `REPLACE INTO ... OVERWRITE` query for the same time interval, the `query_controller` task seems to be running forever doing nothing. But again, works fine if the time interval actually overlaps with any of the segments.

### Cluster size & Configurations in use

We use default settings of the helm chart.

### Steps to reproduce

Have the MSQ plugin enabled, create a new data source, ingest some data, try querying for it using the MSQ engine and with a filter that doesn't hit any segment.

**Comment by cryptoe** [comment]
It should be fixed with : https://github.com/apache/druid/pull/13955. Either you can apply this patch or wait for the druid 26.0.
For druid 26.0 code freeze is done. So we should have a release soon.
