### ISSUE TITLE
Druid Historicals pod is not starting in on-premises

### ISSUE THREAD

**Issue by pokkireddy** [apache/druid#14274]
Getting below error in the historical logs.
The below has been created and permission has been provided
druid.segmentCache.infoDir=/data/druid/segments/infoDir

Attached the logs, cluster details, yaml file. Please assist on this. 
[druid_Cluster_details.txt](https://github.com/apache/druid/files/11466696/druid_Cluster_details.txt)
[druid-sm-druid-cluster-historicals-0_1.log](https://github.com/apache/druid/files/11466697/druid-sm-druid-cluster-historicals-0_1.log)
[1-sm-druid-cluster_error.zip](https://github.com/apache/druid/files/11466705/1-sm-druid-cluster_error.zip)

2023-05-12T17:30:47,848 INFO [main] org.apache.druid.server.coordination.SegmentLoadDropHandler - Starting...
2023-05-12T17:30:47,850 INFO [main-SendThread(zookeeper:2181)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper/10.102.82.192:2181. Will not attempt to authenticate using SASL (unknown error)
2023-05-12T17:30:47,856 ERROR [main] org.apache.druid.cli.CliHistorical - Error when starting up.  Failing.
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:446) ~[druid-core-25.0.0.jar:25.0.0]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:341) ~[druid-core-25.0.0.jar:25.0.0]
	at org.apache.druid.guice.LifecycleModule$2.start(LifecycleModule.java:152) ~[druid-core-25.0.0.jar:25.0.0]
	at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:136) ~[druid-services-25.0.0.jar:25.0.0]
	at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:94) ~[druid-services-25.0.0.jar:25.0.0]
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:63) ~[druid-services-25.0.0.jar:25.0.0]
	at org.apache.druid.cli.Main.main(Main.java:112) ~[druid-services-25.0.0.jar:25.0.0]
Caused by: org.apache.druid.java.util.common.IOE: Cannot create directory [/data/druid/segments/infoDir]
	at org.apache.druid.java.util.common.FileUtils.mkdirp(FileUtils.java:456) ~[druid-core-25.0.0.jar:25.0.0]
	at org.apache.druid.server.coordination.SegmentLoadDropHandler.loadLocalCache(SegmentLoadDropHandler.java:219) ~[druid-server-25.0.0.jar:25.0.0]
	at org.apache.druid.server.coordination.SegmentLoadDropHandler.start(SegmentLoadDropHandler.java:170) ~[druid-server-25.0.0.jar:25.0.0]

**Comment by pokkireddy** [comment]
Could someone assist on this issue
