### ISSUE TITLE
Problem with expression in joins with cte - Possibly a Bug

### ISSUE THREAD

**Issue by pjain1** [apache/druid#14360]
## Description
Running this full outer join query on the standard wikipedia datasource throws exception 

Query -
```
with raw1 as (
  select
  "page",
  "channel",
  "flags",
  added
  from "wikipedia"
  limit 10
),
 raw2 as (
  select 
  "page",
  "comment",
  deleted *added as ad -- problematic expression
  from "wikipedia"
  limit 10
),
output as (
select
  r1.added,
  r2.ad
from raw1 r1
full outer join raw2 r2
on r1.page = r2.page

)
select * from output
```

Exception in broker logs - 
```
java.lang.AssertionError: Type mismatch:
rowtype of new rel:
RecordType(VARCHAR page, BIGINT added, VARCHAR page0, BIGINT NOT NULL $f3) NOT NULL
rowtype of set:
RecordType(VARCHAR page, BIGINT added, VARCHAR page0, BIGINT ad) NOT NULL
	at org.apache.calcite.util.Litmus$1.fail(Litmus.java:31) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.RelOptUtil.equal(RelOptUtil.java:2026) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.volcano.RelSubset.add(RelSubset.java:284) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.volcano.RelSet.add(RelSet.java:148) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.addRelToSet(VolcanoPlanner.java:1818) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.registerImpl(VolcanoPlanner.java:1764) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.register(VolcanoPlanner.java:846) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.ensureRegistered(VolcanoPlanner.java:868) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.ensureRegistered(VolcanoPlanner.java:1939) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.transformTo(VolcanoRuleCall.java:129) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.RelOptRuleCall.transformTo(RelOptRuleCall.java:236) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.druid.sql.calcite.rule.DruidJoinRule.onMatch(DruidJoinRule.java:204) ~[classes/:?]
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:208) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:631) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.tools.Programs$RuleSetProgram.run(Programs.java:327) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.calcite.tools.Programs$SequenceProgram.run(Programs.java:346) ~[calcite-core-1.21.0.jar:1.21.0]
	at org.apache.druid.sql.calcite.planner.CalcitePlanner.transform(CalcitePlanner.java:399) ~[classes/:?]
	at org.apache.druid.sql.calcite.planner.QueryHandler.planWithDruidConvention(QueryHandler.java:486) ~[classes/:?]
	at org.apache.druid.sql.calcite.planner.QueryHandler$SelectHandler.planForDruid(QueryHandler.java:640) ~[classes/:?]
	at org.apache.druid.sql.calcite.planner.QueryHandler.plan(QueryHandler.java:211) ~[classes/:?]
	at org.apache.druid.sql.calcite.planner.DruidPlanner.plan(DruidPlanner.java:230) ~[classes/:?]
	at org.apache.druid.sql.DirectStatement.createPlan(DirectStatement.java:241) ~[classes/:?]
	at org.apache.druid.sql.DirectStatement.plan(DirectStatement.java:219) ~[classes/:?]
	at org.apache.druid.sql.http.SqlResource.doPost(SqlResource.java:131) ~[classes/:?
```
### Affected Version

Getting on Druid 25 but should be affecting all versions

**Comment by happy5035** [comment]
This problem occurs when the version is switched to 24.0.0. The problem does not occur in earlier versions.

**Comment by somu-imply** [comment]
@pjain1 please try on open source master. I tried a similar query and was able to execute it. My query is
```
with raw1 as (
  select
  "page",
  "channel",
  'flags'
  "added"
  from "wikipedia"
  limit 10
),
 raw2 as (
  select 
  "page",
  "comment",
  "deleted"*"added" as ad 
  from "wikipedia"
  limit 10
),
output as (
select
  r1.added,
  r2.ad
from raw1 r1
full outer join raw2 r2
on r1.page = r2.page

)
select * from output
```

**Comment by pjain1** [comment]
@somu-imply can confirm it works on master and 26.0.0 relase, thanks for looking into it.

**Comment by egor-ryashin** [comment]
Hmm, I have almost the same query failing with that exception:
```sql
with base as (
  SELECT 
    "pub", 
    min(total)/ max(price) as "rate" 
  FROM 
    "test_data" 
  GROUP BY 
    "pub"
), 
comparison AS (
  SELECT 
    "pub", 
    min(total)/ max(price) as "rate" 
  FROM 
    "test_data" 
  GROUP BY 
    "pub"
), 
output AS (
  SELECT 
    base."pub", 
    comparison."rate"
  FROM 
    base 
    left outer join comparison on base."pub" = comparison."pub"
) 
select 
  * 
from
  output
```

**Comment by egor-ryashin** [comment]
Though, now I'm not sure, it can be Druid bug as well: 
```
org.apache.druid.error.DruidException: Calcite assertion violated: [Type mismatch:
rowtype of new rel:
RecordType(VARCHAR publisher, VARCHAR publisher0, DOUBLE NOT NULL $f2) NOT NULL
rowtype of set:
RecordType(VARCHAR publisher, VARCHAR publisher0, DOUBLE rate) NOT NULL]
	at org.apache.druid.error.DruidException$DruidExceptionBuilder.build(DruidException.java:454)
	at org.apache.druid.error.InvalidInput.makeException(InvalidInput.java:60)
	at org.apache.druid.error.InvalidSqlInput.makeException(InvalidSqlInput.java:46)
	at org.apache.druid.error.DruidException.fromFailure(DruidException.java:154)
	at org.apache.druid.error.InvalidSqlInput.exception(InvalidSqlInput.java:31)
	at org.apache.druid.sql.DirectStatement.plan(DirectStatement.java:244)
	at org.apache.druid.sql.http.SqlResource$SqlResourceQueryResultPusher$1.start(SqlResource.java:248)
	at org.apache.druid.server.QueryResultPusher.push(QueryResultPusher.java:121)
	at org.apache.druid.sql.http.SqlResource.doPost(SqlResource.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.apache.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:84)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.apache.druid.server.initialization.jetty.StandardResponseHeaderFilterHolder$StandardResponseHeaderFilter.doFilter(StandardResponseHeaderFilterHolder.java:164)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.apache.druid.server.security.AllowHttpMethodsResourceFilter.doFilter(AllowHttpMethodsResourceFilter.java:78)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.apache.druid.server.security.AllowOptionsResourceFilter.doFilter(AllowOptionsResourceFilter.java:74)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.apache.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:84)
	at org.apache.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:59)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.apache.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:77)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.AssertionError: Type mismatch:
rowtype of new rel:
RecordType(VARCHAR publisher, VARCHAR publisher0, DOUBLE NOT NULL $f2) NOT NULL
rowtype of set:
RecordType(VARCHAR publisher, VARCHAR publisher0, DOUBLE rate) NOT NULL
	at org.apache.calcite.util.Litmus$1.fail(Litmus.java:31)
	at org.apache.calcite.plan.RelOptUtil.equal(RelOptUtil.java:2026)
	at org.apache.calcite.plan.volcano.RelSubset.add(RelSubset.java:284)
	at org.apache.calcite.plan.volcano.RelSet.add(RelSet.java:148)
	at org.apache.calcite.plan.volcano.VolcanoPlanner.addRelToSet(VolcanoPlanner.java:1818)
	at org.apache.calcite.plan.volcano.VolcanoPlanner.registerImpl(VolcanoPlanner.java:1764)
	at org.apache.calcite.plan.volcano.VolcanoPlanner.register(VolcanoPlanner.java:846)
	at org.apache.calcite.plan.volcano.VolcanoPlanner.ensureRegistered(VolcanoPlanner.java:868)
	at org.apache.calcite.plan.volcano.VolcanoPlanner.ensureRegistered(VolcanoPlanner.java:1939)
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.transformTo(VolcanoRuleCall.java:129)
	at org.apache.calcite.plan.RelOptRuleCall.transformTo(RelOptRuleCall.java:236)
	at org.apache.druid.sql.calcite.rule.DruidJoinRule.onMatch(DruidJoinRule.java:208)
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:208)
	at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:631)
	at org.apache.calcite.tools.Programs$RuleSetProgram.run(Programs.java:327)
	at org.apache.calcite.tools.Programs$SequenceProgram.run(Programs.java:346)
	at org.apache.druid.sql.calcite.planner.CalcitePlanner.transform(CalcitePlanner.java:399)
	at org.apache.druid.sql.calcite.planner.QueryHandler.planWithDruidConvention(QueryHandler.java:590)
	at org.apache.druid.sql.calcite.planner.QueryHandler$SelectHandler.planForDruid(QueryHandler.java:738)
	at org.apache.druid.sql.calcite.planner.QueryHandler.plan(QueryHandler.java:220)
	at org.apache.druid.sql.calcite.planner.DruidPlanner.plan(DruidPlanner.java:244)
	at org.apache.druid.sql.DirectStatement.createPlan(DirectStatement.java:255)
	at org.apache.druid.sql.DirectStatement.plan(DirectStatement.java:223)
	... 76 more
```

**Comment by pjain1** [comment]
```
with raw1 as (
  select
  "page",
  count(*)/2 as c
  from "wikipedia"
  GROUP BY 1
),
 raw2 as (
  select 
  "page",
  count(*)/2 as c
  from "wikipedia"
  GROUP BY 1
)
select
  r1.c-r2.c
from raw1 r1
left join raw2 r2
on r1.page = r2.page
```

This still fails in 28

**Comment by somu-imply** [comment]
Thanks for reopening this @pjain1 and thanks to @egor-ryashin for the details. I'm taking a look at this one to check if we can manage the datatype mismatch at Druid level

**Comment by soumyava** [comment]
@pjain1 , @egor-ryashin this issue has been merged into the master today
