### ISSUE TITLE
Some Druid overlord API returns 503 when switched from remote to httpRemote for druid.indexer.runner.type

### ISSUE THREAD

**Issue by harinirajendran** [apache/druid#14375]
### Affected Version

24.0.2

### Description
When we switch `druid.indexer.runner.type` from `remote` to `httpRemote` and redeploy overlords, the overlord leader returns 503 for most of the APIs. I tried rolling 1 overlord at a time and also tried scaling down all overlords and scaling them back up. Neither worked.

<img width="1741" alt="Screen Shot 2023-06-06 at 9 07 53 AM" src="https://github.com/apache/druid/assets/9054348/20aad0d2-29a4-45ea-af3a-0fe9210ee740">

<img width="1782" alt="Screen Shot 2023-06-06 at 9 05 37 AM" src="https://github.com/apache/druid/assets/9054348/f1681053-10eb-49c0-8d2b-53bf879b553a">

@gianm Any thoughts on why this could happen?

**Comment by abhishekagarwal87** [comment]
Can you take thread dumps on Overlord when this happens? Is this state
transient or persistent where leader nodes returns 503?
Btw in 26, the leader client automatically retries when it runs into a 503.

**Comment by harinirajendran** [comment]
> Can you take thread dumps on Overlord when this happens? Is this state transient or persistent where leader nodes returns 503? Btw in 26, the leader client automatically retries when it runs into a 503.

It is persistent @abhishekagarwal87. I can do a thread dump of overlord. How would it help debug the issue?

**Comment by abhishekagarwal87** [comment]
I am suspecting that HTTP threads are saturated on Overlord.

**Comment by harinirajendran** [comment]
> I am suspecting that HTTP threads are saturated on Overlord.

I don't think the threads are saturated because both the overlords are responding to some API calls. Rather, I think its a bug. When both the overlords are running with `druid.indexer.runner.type=httpRemote`, when I port-forward to either of them and make the `isLeader` API call, both of them return False. But when I make the `leader` API call, one of them is getting returned as the leader.

**Comment by nathanschnarr** [comment]
I ran into this issue as well when attempting to upgrade from v24 to v26, changing from remote to httpRemote and saw the same symptoms. 

Additionally, I also tried leaving the value as remote and changing the other flags outlined [here](https://github.com/apache/druid/releases/tag/druid-25.0.0#25-upgrade-segment-discovery) back to their default values. This also manifested as a bunch of 503 errors now in the segments as well as the overlord. I didn't see a path forward onto v26 due to this.

**Comment by harinirajendran** [comment]
In our case one of the Middle Managers was in a weird state and the overlord wasn't able to become the leader because of that
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.apache.druid.indexing.overlord.TaskMaster$1.becomeLeader(TaskMaster.java:161)
	at org.apache.druid.curator.discovery.CuratorDruidLeaderSelector$1.isLeader(CuratorDruidLeaderSelector.java:98)
	at org.apache.curator.framework.recipes.leader.LeaderLatch$9.apply(LeaderLatch.java:702)
	at org.apache.curator.framework.recipes.leader.LeaderLatch$9.apply(LeaderLatch.java:698)
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:100)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:446)
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:341)
	at org.apache.druid.indexing.overlord.TaskMaster$1.becomeLeader(TaskMaster.java:158)
	... 7 more
Caused by: java.lang.RuntimeException: org.apache.druid.java.util.common.RE: Failed to sync with worker[druid-op-batch-middlemanagers-0.druid-op-batch-middlemanagers.druid-events-prod.svc.cluster.local:8091].
	at org.apache.druid.indexing.overlord.hrtr.HttpRemoteTaskRunner.start(HttpRemoteTaskRunner.java:285)
	... 14 more
Caused by: org.apache.druid.java.util.common.RE: Failed to sync with worker[druid-op-batch-middlemanagers-0.druid-op-batch-middlemanagers.druid-events-prod.svc.cluster.local:8091].
	at org.apache.druid.indexing.overlord.hrtr.WorkerHolder.waitForInitialization(WorkerHolder.java:344)
	at org.apache.druid.indexing.overlord.hrtr.HttpRemoteTaskRunner.startWorkersHandling(HttpRemoteTaskRunner.java:560)
	at org.apache.druid.indexing.overlord.hrtr.HttpRemoteTaskRunner.start(HttpRemoteTaskRunner.java:265)
	... 14 more
```
Restarting that middle manager node helped resolve the issue.

**Comment by abhishekagarwal87** [comment]
Thank you @harinirajendran. I see that @xvrl has already filed an issue. Are you or @xvrl planning to do a fix as well?

**Comment by harinirajendran** [comment]
> Thank you @harinirajendran. I see that @xvrl has already filed an issue. Are you or @xvrl planning to do a fix as well?

We don't have any plans of working on a fix for this right away. Shall discuss it with the druid team here internally and update this thread.
