### ISSUE TITLE
The class PostJoinCursor causes the CPU to spike to 100% and cannot be terminated.

### ISSUE THREAD

**Issue by 599166320** [apache/druid#14514]
I executed a query similar to the one below in Grafana, which caused the CPU to spike to 100%:
```
WITH ta as(
select distinct uri from t_a where xx='xx'
)
select time_floor(__time, 'PT1H'),count(*) from t_b  left join ta on ta.uri = t_b.uri group by 1
```

When I executed this SQL, I already added timeout=120000 in the context, but it had no effect. It has been running on the historical server for more than 10 hours and still hasn't terminated.

Here is the call stack:

```
 "timeseries_JoinDataSource{left=t_a, right=InlineDataSource{signature={d0:STRING, a0:LONG, a1:LONG}}, rightPrefix='j0.', condition=("uri" == "j0.d0"), joinType=LEFT, leftFilter=null}_[2023-06-29T14:00:00.000Z/2023-06-29T15:00:00.000Z]" #199 daemon prio=5 os_prio=0 cpu=3626786.80ms elapsed=2666537.92s tid=0x0000fff45c007800 nid=0x4208 runnable  [0x0000fff34c9b7000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.String.<init>(java.base@11.0.16.1/String.java:467)
        at java.lang.String.<init>(java.base@11.0.16.1/String.java:537)
        at org.apache.druid.java.util.common.StringUtils.fromUtf8(StringUtils.java:83)
        at org.apache.druid.java.util.common.StringUtils.fromUtf8(StringUtils.java:99)
        at org.apache.druid.segment.data.GenericIndexed$2.fromByteBuffer(GenericIndexed.java:153)
        at org.apache.druid.segment.data.GenericIndexed$2.fromByteBuffer(GenericIndexed.java:143)
        at org.apache.druid.segment.data.GenericIndexed$BufferIndexed.get(GenericIndexed.java:483)
        at org.apache.druid.segment.data.CachingIndexed.get(CachingIndexed.java:81)
        at org.apache.druid.segment.column.StringDictionaryEncodedColumn.lookupName(StringDictionaryEncodedColumn.java:105)
        at org.apache.druid.segment.column.StringDictionaryEncodedColumn$1QueryableDimensionSelector.lookupName(StringDictionaryEncodedColumn.java:166)
        at org.apache.druid.segment.virtual.ExpressionSelectors.lambda$supplierFromDimensionSelector$1(ExpressionSelectors.java:457)
        at org.apache.druid.segment.virtual.ExpressionSelectors$$Lambda$789/0x0000000800b6c440.get(Unknown Source)
        at org.apache.druid.math.expr.InputBindings$6.get(InputBindings.java:145)
        at org.apache.druid.math.expr.IdentifierExpr.eval(IdentifierExpr.java:130)
        at org.apache.druid.math.expr.BinaryBooleanOpExprBase.eval(BinaryOperatorExpr.java:180)
        at org.apache.druid.segment.virtual.ExpressionColumnValueSelector.eval(ExpressionColumnValueSelector.java:54)
        at org.apache.druid.segment.virtual.BaseExpressionColumnValueSelector.computeCurrentEval(BaseExpressionColumnValueSelector.java:108)
        at org.apache.druid.segment.virtual.BaseExpressionColumnValueSelector.getObject(BaseExpressionColumnValueSelector.java:77)
        at org.apache.druid.segment.virtual.BaseExpressionColumnValueSelector.getObject(BaseExpressionColumnValueSelector.java:32)
        at org.apache.druid.segment.filter.ExpressionFilter$1.matches(ExpressionFilter.java:139)
        at org.apache.druid.segment.join.PostJoinCursor.advanceToMatch(PostJoinCursor.java:71)
        at org.apache.druid.segment.join.PostJoinCursor.advanceUninterruptibly(PostJoinCursor.java:100)
        at org.apache.druid.segment.join.PostJoinCursor.advance(PostJoinCursor.java:92)
        at org.apache.druid.query.timeseries.TimeseriesQueryEngine.lambda$processNonVectorized$3(TimeseriesQueryEngine.java:291)
        at org.apache.druid.query.timeseries.TimeseriesQueryEngine$$Lambda$704/0x0000000800b29c40.apply(Unknown Source)
```

I feel that adding the following code at an appropriate location in the classes HashJoinEngine and PostJoinCursor could fix this issue, but I'm unsure about potential problems. There might be a better way to handle this.

```
if (hasTimeout && System.currentTimeMillis() >= timeoutAt) {
  throw new QueryTimeoutException(StringUtils.nonStrictFormat("Query [%s] timed out", query.getId()));
}
```

### Affected Version

24.0.1

**Comment by abhishekagarwal87** [comment]
what is the cardinality of uri in the t_a table after the filter is applied? can you also share the native plan for this query?

**Comment by 599166320** [comment]
@abhishekagarwal87 The cardinality of URI is over one million. It's been a while, and I'm not able to provide the specific query plan at the moment. However, I am aware that this query is quite slow, and what I'd really like to see is this type of query completing within a reasonable timeframe, rather than consuming CPU resources for an extended period.

**Comment by LakshSingla** [comment]
There have been instances in the past where the query timeout is not respected properly.

> I already added timeout=120000 in the context, but it had no effect. It has been running on the historical server for more than 10 hours and still hasn't terminated

This shouldn't be happening. Even if the query is non-performant (fixing it is a different task), it should always respect the timeout. I suppose it should be a bug in the `TimeseriesQueryEngine` rather than the PostJoinCursor. Will see if its reproducible locally for small values of timeout.

**Comment by abhishekagarwal87** [comment]
yeah. I think that the historical thread is running a CPU-intensive operation and hence is not getting interrupted. So having a check of nature `Thread.currentThread().isInterrupted()` will help. This is something that `PostJoinCursor#advance` already does. So that means, `advanceUninterruptibly` is running for more than 10 hours.

**Comment by abhishekagarwal87** [comment]
We should probably add methods below and use `advanceToMatch` in the `advance` method and use `advanceToMatchUninterruptibly` in `advanceUninterruptibly`
```
private void advanceToMatch()
  {
    if (valueMatcher != null) {
      while (!isDone() && !valueMatcher.matches()) {
        baseCursor.advance();
      }
    }
  }

 private void advanceToMatchUninterruptibly()
  {
    if (valueMatcher != null) {
      while (!isDone() && !valueMatcher.matches()) {
        baseCursor.advanceUninterruptibly();
      }
    }
  }
```

**Comment by abhishekagarwal87** [comment]
@gianm - If you have some thoughts?
