### ISSUE TITLE
Exception Eating duck in query failures flow

### ISSUE THREAD

**Issue by pranavbhole** [apache/druid#15055]
### Description
Found an exception eating duck in query failure slow ( esp segmentMetadata queries)

```
org.apache.druid.query.QueryInterruptedException: null
Caused by: java.lang.NullPointerException

org.apache.druid.error.DruidException: null
	at org.apache.druid.error.DruidException$DruidExceptionBuilder.build(DruidException.java:460) ~[druid-processing-2023.09.0-iap.jar:2023.09.0-iap]
	at org.apache.druid.error.QueryExceptionCompat.makeException(QueryExceptionCompat.java:50) ~[druid-processing-2023.09.0-iap.jar:2023.09.0-iap]
	at org.apache.druid.error.DruidException.fromFailure(DruidException.java:154) ~[druid-processing-2023.09.0-iap.jar:2023.09.0-iap]
	at org.apache.druid.server.QueryResultPusher.handleQueryException(QueryResultPusher.java:211) ~[druid-server-2023.09.0-iap.jar:2023.09.0-iap]
	at org.apache.druid.server.QueryResultPusher.push(QueryResultPusher.java:177) ~[druid-server-2023.09.0-iap.jar:2023.09.0-iap]
	at org.apache.druid.server.QueryResource.doPost(QueryResource.java:218) ~[druid-server-2023.09.0-iap.jar:2023.09.0-iap]
	at jdk.internal.reflect.GeneratedMethodAccessor252.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.19.4.jar:1.19.4]

**Comment by pranavbhole** [comment]
I am working on it to fix it.
