### ISSUE TITLE
org.apache.druid.java.util.common.ISE: Could not allocate segment for row with timestamp

### ISSUE THREAD

**Issue by Sixty-one** [apache/druid#15297]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version
0.22.1
The Druid version where the problem was encountered.
0.22.1
### Description
The steps are as follows：
1.Durid is running normally，Write data through kafka
2.Execute command to modify operating system time，date -s "2023-10-04 15:30:00"
3.restart druid service

Please include as much detailed information about the problem as possible.
- Cluster size
- Configurations in use
- Steps to reproduce the problem
- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
- Any debugging that you have already done

errros infos:
2023-11-01T02:25:56,503 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner - Encountered exception while running task.
org.apache.druid.java.util.common.ISE: Could not allocate segment for row with timestamp[2023-11-04T07:30:09.000Z]
        at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.runInternal(SeekableStreamIndexTaskRunner.java:665) ~[druid-indexing-service-0.22.1.jar:0.22.1]
        at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.run(SeekableStreamIndexTaskRunner.java:263) [druid-indexing-service-0.22.1.jar:0.22.1]
        at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTask.run(SeekableStreamIndexTask.java:146) [druid-indexing-service-0.22.1.jar:0.22.1]
        at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:471) [druid-indexing-service-0.22.1.jar:0.22.1]
        at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:443) [druid-indexing-service-0.22.1.jar:0.22.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
2023-11-01T02:25:56,530 INFO [task-runner-0-priority-0] org.apache.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_kafka_cache_flow_section_23e8131b930cc09_mnhgkclm",
  "status" : "FAILED",
  "duration" : 5036,
  "errorMsg" : "org.apache.druid.java.util.common.ISE: Could not allocate segment for row with timestamp[2023-11-04T...",
  "location" : {
    "host" : null,
    "port" : -1,
    "tlsPort" : -1
  }
}

so how to solve the problem？

**Comment by acherla** [comment]
@abhagraw Bumping this one up as we still see this error even in 27.0.0
