### ISSUE TITLE
Overlord does not start in mm-less k8sAndWorker mode in a zookeeper-less environment.

### ISSUE THREAD

**Issue by hnakamor** [apache/druid#15431]
### Affected Version

Druid 28.0.0

### Description

I have druid-kubernetes-extensions loaded and running in a zookeeper-less environment.
I really like the zookeeper-less feature as it works well in my environment and simplifies the components.

I was also very excited about the mm-less k8sAndWorker mode introduced in Druid 28.0.0, as it matched the use case mentioned in #15196.
Unfortunately, I wanted to configure mm-less k8sAndWorker mode for this zookeeper-less environment, but when I configured k8sAndWorker mode, overlord would not start with an error.

The configuration and error for this environment is as follows

- common.runtime.properties
```
# Extensions
druid.extensions.loadList=["druid-datasketches","mysql-metadata-storage","druid-s3-extensions","druid-kafka-indexing-service","druid-bloom-filter","druid-multi-stage-query","prometheus-emitter","druid-kubernetes-extensions"]

# Zookeeper less
druid.zk.service.enabled=false
druid.serverview.type=http
druid.coordinator.loadqueuepeon.type=http
druid.indexer.runner.type=httpRemote
druid.discovery.type=k8s
druid.discovery.k8s.clusterIdentifier=${env:POD_NAMESPACE}

# Service discovery
druid.selectors.indexing.serviceName=druid/overlord
druid.selectors.coordinator.serviceName=druid/coordinator
```

- Overlord(coordinator)'s runtime.properties
```
# Extensions
druid.extensions.loadList=["druid-datasketches","mysql-metadata-storage","druid-s3-extensions","druid-kafka-indexing-service","druid-bloom-filter","druid-multi-stage-query","prometheus-emitter","druid-kubernetes-extensions","druid-kubernetes-overlord-extensions"]

# MM less
druid.indexer.runner.type=k8sAndWorker
druid.indexer.runner.namespace=mynamespace
druid.indexer.task.encapsulatedTask=true
druid.indexer.runner.k8sAndWorker.runnerStrategy.type=taskType
druid.indexer.runner.k8sAndWorker.runnerStrategy.taskType.default=k8s
druid.indexer.runner.k8sAndWorker.runnerStrategy.taskType.overrides={"index_kafka": "worker"}

# Configure this coordinator to also run as Overlord
druid.coordinator.asOverlord.enabled=true
druid.coordinator.asOverlord.overlordService=druid/overlord
```

- [k8sAndWorker_error.log](https://github.com/apache/druid/files/13463097/k8sAndWorker_error.log)

As additional information, I have confirmed that the k8s mode of mm-less will start overlord even in the zookeeper-less environment.

**Comment by YongGang** [comment]
Hi @hnakamor, thanks for trying this feature. I put up a fix for the issue you reported https://github.com/apache/druid/pull/15445
But I don't have druid-kubernetes-extensions loaded and running in a zookeeper-less environment for test.
Could you help verify if the fix works for you? Thanks.

**Comment by hnakamor** [comment]
Hi @YongGang, Thank you for fixing this issue. I would love to help verify your fix.
In order to verify it, I need to create an environment to build DockerImage with this fix, but I can't get around to it right away.
Please give me some days. Best regards.

**Comment by hnakamor** [comment]
Hi @YongGang, thank you for your patience. I created a Docker image using the code in your branch, but unfortunately Overlord(coordinator) could not start with an error.
The error is described below.
```
Exception in thread "main" java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Unknown provider [k8s] of Key[type=org.apache.druid.discovery.DruidNodeAnnouncer, annotation=[none]], known options [[curator]]
  at org.apache.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:110) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.curator.discovery.DiscoveryModule)
  while locating org.apache.druid.discovery.DruidNodeAnnouncer
    for field at org.apache.druid.cli.ServerRunnable$DiscoverySideEffectsProvider.announcer(ServerRunnable.java:105)
  at org.apache.druid.cli.ServerRunnable.bindAnnouncer(ServerRunnable.java:93) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliCoordinator$1)

1 error
	at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:88)
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:62)
	at org.apache.druid.cli.Main.main(Main.java:112)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Unknown provider [k8s] of Key[type=org.apache.druid.discovery.DruidNodeAnnouncer, annotation=[none]], known options [[curator]]
  at org.apache.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:110) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.curator.discovery.DiscoveryModule)
  while locating org.apache.druid.discovery.DruidNodeAnnouncer
    for field at org.apache.druid.cli.ServerRunnable$DiscoverySideEffectsProvider.announcer(ServerRunnable.java:105)
  at org.apache.druid.cli.ServerRunnable.bindAnnouncer(ServerRunnable.java:93) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliCoordinator$1)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.apache.druid.initialization.ExtensionInjectorBuilder.build(ExtensionInjectorBuilder.java:49)
	at org.apache.druid.initialization.ServerInjectorBuilder.build(ServerInjectorBuilder.java:118)
	at org.apache.druid.initialization.ServerInjectorBuilder.makeServerInjector(ServerInjectorBuilder.java:73)
	at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:85)
	... 2 more
```

**Comment by YongGang** [comment]
Hi @hnakamor, sorry for my late reply.

Thanks for trying the change, but seems the error you saw not related to the change I made to `druid-kubernetes-overlord-extensions`
The error is from `DruidNodeAnnouncer` initialization, it couldn't find `k8s` config provider which looking for `K8sDruidNodeAnnouncer` class from druid-kubernetes-extensions I believe.

Could you help check if druid-kubernetes-extensions is in the druid.extensions.loadList config for Overlord/Coordinator?

**Comment by hnakamor** [comment]
Hi @YongGang
I am so sorry. I had made a mistake in the settings.
I have corrected the settings and tried again and confirmed that the overload (coordinator) is working correctly.

Thank you for initiating this issue. I look forward to seeing your PR merged.

**Comment by suneet-s** [comment]
Fixed in #15445

**Comment by twij2332** [comment]
Hi @hnakamor ,

Can u pls tell me the configurations that u have used cuz I am also facing the same issue

Thanks

**Comment by hnakamor** [comment]
Hi @twij2332 ,
First, you need to use Druid 29.0.0 or higher. 
My configuration was as follows.
- common.runtime.properties
```
# Extensions
druid.extensions.loadList=["druid-datasketches","mysql-metadata-storage","druid-s3-extensions","druid-kafka-indexing-service","druid-bloom-filter","druid-multi-stage-query","prometheus-emitter","druid-kubernetes-extensions"]

# Zookeeper less
druid.zk.service.enabled=false
druid.serverview.type=http
druid.coordinator.loadqueuepeon.type=http
druid.indexer.runner.type=httpRemote
druid.discovery.type=k8s
druid.discovery.k8s.clusterIdentifier=${env:POD_NAMESPACE}
```

- Overlord(Coordinator)'s runtime.properties
```
# Extensions
druid.extensions.loadList=["druid-datasketches","mysql-metadata-storage","druid-s3-extensions","druid-kafka-indexing-service","druid-bloom-filter","druid-multi-stage-query","prometheus-emitter","druid-kubernetes-extensions","druid-kubernetes-overlord-extensions"]

# MM less
druid.indexer.runner.type=k8sAndWorker
druid.indexer.runner.namespace=${env:POD_NAMESPACE}
druid.indexer.task.encapsulatedTask=true
druid.indexer.runner.k8sAndWorker.runnerStrategy.type=taskType
druid.indexer.runner.k8sAndWorker.runnerStrategy.taskType.default=k8s
druid.indexer.runner.k8sAndWorker.runnerStrategy.taskType.overrides={"index_kafka": "worker"}
```
