### ISSUE TITLE
Exception java.lang.UnsatisfiedLinkError: 'void org.hyperic.sigar.SigarLog.setLevel(org.hyperic.sigar.Sigar, int)'

### ISSUE THREAD

**Issue by chn217** [apache/druid#15560]
The issue arises when **org.apache.druid.java.util.metrics.SysMonitor** is enabled via druid.monitoring.monitors on AWS r6g (processor: ARM) instances with the latest Amazon Linux 2 AMI.
 
When historical starts, the following exceptions is seen in the output:
```
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.UnsatisfiedLinkError: 'void org.hyperic.sigar.SigarLog.setLevel(org.hyperic.sigar.Sigar, int)'
```
The historical process keeps restarting due to this error.

### Affected Version
v27

### Description

Please include as much detailed information about the problem as possible.
- Cluster size
- Configurations in use
```
druid.monitoring.monitors=["org.apache.druid.java.util.metrics.JvmMonitor", 
"org.apache.druid.java.util.metrics.SysMonitor", "org.apache.druid.server.metrics.HistoricalMetricsMonitor", "org.apache.druid.server.metrics.QueryCountStatsMonitor"]
```
- Steps to reproduce the problem
Load the configuration on AWS r6g instances.

- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
```
  at org.apache.druid.server.metrics.MetricsModule.getSysMonitor(MetricsModule.java:187) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.metrics.MetricsModule)
  at org.apache.druid.server.metrics.MetricsModule.getSysMonitor(MetricsModule.java:187) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.metrics.MetricsModule)
  while locating org.apache.druid.java.util.metrics.SysMonitor
  at org.apache.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:112) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.metrics.MetricsModule)
  at org.apache.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:112) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.metrics.MetricsModule)
  while locating org.apache.druid.java.util.metrics.MonitorScheduler
  at org.apache.druid.server.metrics.MetricsModule.configure(MetricsModule.java:97) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.metrics.MetricsModule)
  while locating org.apache.druid.java.util.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at org.apache.druid.initialization.ExtensionInjectorBuilder.build(ExtensionInjectorBuilder.java:49)
        at org.apache.druid.initialization.ServerInjectorBuilder.build(ServerInjectorBuilder.java:118)
        at org.apache.druid.initialization.ServerInjectorBuilder.makeServerInjector(ServerInjectorBuilder.java:73)
        at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:85)
        ... 2 more
Caused by:d 'void org.hyperic.sigar.SigarLog.setLevel(org.hyperic.sigar.Sigar, int)'
        at org.hyperic.sigar.SigarLog.setLevel(Native Method)
        at org.hyperic.sigar.SigarLog.enable(SigarLog.java:87)
        at org.hyperic.sigar.Sigar.enableLogging(Sigar.java:965)
        at org.apache.druid.java.util.metrics.SysMonitor.<init>(SysMonitor.java:86)
        at org.apache.druid.java.util.metrics.SysMonitor.<init>(SysMonitor.java:77)
        at org.apache.druid.server.metrics.MetricsModule.getSysMonitor(MetricsModule.java:194)
        at org.apache.druid.server.metrics.MetricsModule$$FastClassByGuice$$99ddce1b.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
        at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.apache.druid.guice.LifecycleScope$1.get(LifecycleScope.java:68)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
        at org.apache.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:115)
        at org.apache.druid.server.metrics.MetricsModule$$FastClassByGuice$$99ddce1b.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
        at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at org.apache.druid.guice.LifecycleScope$1.get(LifecycleScope.java:68)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        ... 10 more
```
- Any debugging that you have already done

**Comment by abhishekagarwal87** [comment]
We recommend using `OshiSysMonitor` instead, which is known to work on ARM-based machines.
