### ISSUE TITLE
All replica Tasks fail for the task group due to previous task timed out before completion

### ISSUE THREAD

**Issue by pagrawal10** [apache/druid#15944]
Druid Version:
25.0.0

Description:
We are running a Druid cluster with ingestion from Kafka along with task replication enabled.
Suppose two replica tasks A1 and A2 start together. They ingest data from Kafka as expected. After some time, A1 completes the ingestion and publishing. This sends a trigger to kill all the tasks in the taskGroup to be killed:
Stopping all tasks in taskGroup[1] because: [Task [A1] completed successfully, stopping tasks [A1, A2]]
As task A2 is in the publishing state and has received a stop signal, it is added to a Pending completion task group:
Creating new pending completion task group [1] for discovered task [A2]
Now, new tasks B1, B2 have also started consuming data for the same partition. They start consuming from Kafka as expected and are running without any lag.
However, A2 is unable to complete publishing and thus stop.
This causes A2 to fail after the completion timeout elapses:
No task in [[A2]] for taskGroup [1] succeeded before the completion timeout elapsed [PT1800S]!: {class=org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor}
Then, from this code: [https://github.com/confluentinc/druid/blob/master/indexing-service/src/main/java/o[…]ndexing/seekablestream/supervisor/SeekableStreamSupervisor.java](https://github.com/confluentinc/druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java#L2275-L2305)
it also kills the actively reading task groups for the same partition. This kills B1 and B2 causing ingestion lag.

While I agree, that without replication, it makes sense to kill the currently reading tasks as they would eventually fail if the previous task has failed. This scenario is not valid when task replication is enabled.

**Comment by abhishekagarwal87** [comment]
> However, A2 is unable to complete publishing and thus stop.
Do you know why this happens? A2 should have exited even before the completion timeout elapsed.

**Comment by pagrawal10** [comment]
@abhishekagarwal87 
The task report file is < 400 bytes. The problematic task A2 never pushed any task report but when the main task runner thread was interrupted with exception Encountered exception while waiting for task [A2] shutdown , it was stuck at pushing the task reports to S3. I am still debugging further into this issue, but the bug exists irrespective of this reason.

**Comment by pagrawal10** [comment]
Hey Amatya,
I debugged the logs further and this is the flow of events:
Handoff started for A2 task at 15:23. The task was waiting for handoff to be complete.
At 15:26:19 , A1 completed and gave the stop signal to A2. When A2 received the stop signal, it started shutting down immediately and dropped the segment which it was handling. The segment was dropped successfully. The task could not have been waiting for a segment to pick up the segment as the segment was already loaded to historicals by the replica task which had completed.
At 15:26:23 , discoverTasks() function ran and put A2 in a new Pending Completion task group.
The task never completed shutting down and was stuck somewhere till the timeout elapsed. I see no logs for the task coming between 15:27 and 15:56 except stating its current offset.
At 15:56, we see this exception:
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.druid.java.util.common.RE: Current thread is interrupted after [0] tries
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.apache.druid.indexing.overlord.ThreadingTaskRunner$2.call(ThreadingTaskRunner.java:323)
	at org.apache.druid.indexing.overlord.ThreadingTaskRunner$2.call(ThreadingTaskRunner.java:315)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.druid.java.util.common.RE: Current thread is interrupted after [0] tries
	at org.apache.druid.indexing.overlord.ThreadingTaskRunner$1.call(ThreadingTaskRunner.java:232)
	at org.apache.druid.indexing.overlord.ThreadingTaskRunner$1.call(ThreadingTaskRunner.java:152)
	... 4 more
Caused by: java.lang.RuntimeException: org.apache.druid.java.util.common.RE: Current thread is interrupted after [0] tries
	at org.apache.druid.storage.s3.S3TaskLogs.pushTaskFile(S3TaskLogs.java:156)
	at org.apache.druid.storage.s3.S3TaskLogs.pushTaskReports(S3TaskLogs.java:141)
	at org.apache.druid.indexing.overlord.ThreadingTaskRunner$1.call(ThreadingTaskRunner.java:223)
	... 5 more
Caused by: org.apache.druid.java.util.common.RE: Current thread is interrupted after [0] tries
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:148)
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:81)
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:163)
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:153)
	at org.apache.druid.storage.s3.S3Utils.retryS3Operation(S3Utils.java:101)
	at org.apache.druid.storage.s3.S3TaskLogs.pushTaskFile(S3TaskLogs.java:147)
	... 7 more
I have gone through the code but could not pinpoint where the task thread was stuck or the exception was swallowed. Can you please take a look?

It seems like the discoveryTasks() interfered with the graceful shutdown process.

**Comment by pagrawal10** [comment]
However, irrespective of the reason for A2's failure, this issue tracks that any such task failure should not kill activelyReading tasks. Can you please explain why we kill the activelyReadingTaskGroups in case a previous task for the same partition has timed out?
