### ISSUE TITLE
WorkerTaskCountStatsMonitor doesn't work in Druid 30.0.0

### ISSUE THREAD

**Issue by jakubmatyszewski** [apache/druid#16855]
### Affected Version

30.0.0

### Description

I'm using a Middlemanager+Peons and I used to have following monitors enabled in MM config:
```
druid.monitoring.monitors=["org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.server.metrics.EventReceiverFirehoseMonitor", "org.apache.druid.server.metrics.WorkerTaskCountStatsMonitor"]
```

This was alright in earlier versions (my production cluster is running 29.0.1 right now with said config).
With version 30.0.0 ingestion tasks are failing with following errors in Peons:
```
1 error
	at org.apache.druid.cli.CliPeon.run(CliPeon.java:397)
	at org.apache.druid.cli.Main.main(Main.java:112)
Caused by: java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.apache.druid.server.metrics.IndexerTaskCountStatsProvider was bound.
  while locating org.apache.druid.server.metrics.IndexerTaskCountStatsProvider
  at org.apache.druid.server.metrics.WorkerTaskCountStatsMonitor.<init>(WorkerTaskCountStatsMonitor.java:47)
  while locating org.apache.druid.server.metrics.WorkerTaskCountStatsMonitor
  at org.apache.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:113) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.metrics.MetricsModule)
  at org.apache.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:113) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.metrics.MetricsModule)
  while locating org.apache.druid.java.util.metrics.MonitorScheduler
  at org.apache.druid.server.metrics.MetricsModule.configure(MetricsModule.java:98) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.metrics.MetricsModule)
  while locating org.apache.druid.java.util.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)
```

I've confirmed that if I run Indexer instead of MM+Peons, the tasks are running successfully.
I think that this [PR](https://github.com/apache/druid/pull/15991) introduced regression, so that this monitor doesn't work with Middlemanager/Peon setup.

@rbankar7
@kfaraz

**Comment by kfaraz** [comment]
This is odd, why should `IndexerTaskCountStatsProvider` need to be bound on peons. The `IndexerTaskCountStatsProvider` is needed only by `WorkerTaskCountStatsMonitor` which itself should be bound only on MMs.

I guess the problem is all that the MM properties get propagated to the peons. Maybe there should be a check to not propagate unsupported monitor properties to peons.
