### ISSUE TITLE
Peon OOM causes task to never terminate

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#1709]
OOMs in the form of

```
11996.553: [GC concurrent-mark-abort]
Exception in thread "plumber_merge_0" java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3236)
    at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191)
    at io.druid.segment.data.GenericIndexed.fromIterable(GenericIndexed.java:110)
    at io.druid.segment.data.CompressedVSizeIntsIndexedSupplier.fromList(CompressedVSizeIntsIndexedSupplier.java:197)
    at io.druid.segment.CompressedVSizeIndexedSupplier.fromIterable(CompressedVSizeIndexedSupplier.java:118)
    at io.druid.segment.IndexIO$DefaultIndexIOHandler.convertV8toV9(IndexIO.java:726)
    at io.druid.segment.IndexMerger.makeIndexFiles(IndexMerger.java:933)
    at io.druid.segment.IndexMerger.merge(IndexMerger.java:336)
    at io.druid.segment.IndexMerger.mergeQueryableIndex(IndexMerger.java:218)
    at io.druid.segment.IndexMerger.mergeQueryableIndex(IndexMerger.java:207)
    at io.druid.segment.realtime.plumber.RealtimePlumber$4.doRun(RealtimePlumber.java:444)
    at io.druid.common.guava.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:40)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

can cause the indexing service's realtime plumber to fail and never recover, leaving the task in a state where it never persists and never exits.

**Comment by drcrallen** [comment]
One potential solution is http://stackoverflow.com/a/12096648 and setting `-XX:OnOutOfMemoryError="kill -9 %p"`

**Comment by drcrallen** [comment]
The prior solution does not work well because javaOpts cannot accept arguments with spaces.

**Comment by himanshug** [comment]
we do use -XX:OnOutOfMemoryError="kill -9 %p" on our servers.

**Comment by drcrallen** [comment]
@himanshug Do you specify that with javaOpts for the peons?

**Comment by drcrallen** [comment]
I suppose you could make it part of javaCommand

**Comment by himanshug** [comment]
ah sorry, I spoke too soon, we actually do it only for the druid processes right now and not for peons
(peons never complained so far, it was mostly an issue at the brokers  time to time)

**Comment by licl2014** [comment]
> The prior solution does not work well because javaOpts cannot accept arguments with spaces.
what's your jdk version? it is invaild for jdk8.   BTW, if peon is killed , the data in memory also dropped?
