### ISSUE TITLE
Columns with slashes in the name cannot be written out

### ISSUE THREAD

**Issue by gianm** [apache/druid#2370]
Probably need some kind of encoding for filenames. Maybe url encoding? (so "count/us" becomes "count%2Fus" and "😄" becomes "%F0%9F%98%84".

The exception you get for a metric named "count/us" is:

```
java.io.IOException: Unable to create temporary file, /var/folders/b_/6stj7v_j6txbpbt9xt2_j00r0000gn/T/filePeon4092801455999907717count/us.long_column.header

    at java.io.File$TempDirectory.generateFile(File.java:1921)
    at java.io.File.createTempFile(File.java:2010)
    at java.io.File.createTempFile(File.java:2070)
    at io.druid.segment.data.TmpFileIOPeon.makeOutputStream(TmpFileIOPeon.java:55)
    at io.druid.segment.data.GenericIndexedWriter.open(GenericIndexedWriter.java:68)
    at io.druid.segment.data.CompressedLongsSupplierSerializer.open(CompressedLongsSupplierSerializer.java:88)
    at io.druid.segment.LongColumnSerializer.open(LongColumnSerializer.java:69)
    at io.druid.segment.IndexMergerV9.setupMetricsWriters(IndexMergerV9.java:746)
    at io.druid.segment.IndexMergerV9.makeIndexFiles(IndexMergerV9.java:195)
    at io.druid.segment.IndexMerger.merge(IndexMerger.java:421)
    at io.druid.segment.IndexMerger.persist(IndexMerger.java:193)
    at io.druid.segment.IndexMerger.persist(IndexMerger.java:159)
    at io.druid.segment.IndexMerger.persist(IndexMerger.java:137)
```

**Comment by xvrl** [comment]
@gianm is this an 0.9 regression with v9 indexing?

**Comment by gianm** [comment]
@xvrl this is a pre-existing bug, it was reported on the forums: https://groups.google.com/d/topic/druid-user/Q1IxjMtAtEw/discussion

**Comment by himanshug** [comment]
having '/' in metric name is interesting, I believe we should put restriction on the set of characters allowed in the metric/dimension names.
