### ISSUE TITLE
Middle Manager with low memory fails if druid-namespace-lookup is in the extension list with offHeap configured.

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#2725]
The OffHeap setting for druid-namespace-lookup has a hard-coded heap cache layer of ~10MB at https://github.com/druid-io/druid/blob/druid-0.9.0-rc3/extensions-core/namespace-lookup/src/main/java/io/druid/server/namespace/cache/OffHeapNamespaceExtractionCacheManager.java#L84

For Middle Managers with very low memory settings, this can cause out of memory errors as per

```
ERROR [main] io.druid.cli.CliMiddleManager - Error when starting up.  Failing.
com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.OutOfMemoryError: Java heap space
  at io.druid.server.namespace.cache.OffHeapNamespaceExtractionCacheManager.<init>(OffHeapNamespaceExtractionCacheManager.java:67)
  while locating io.druid.server.namespace.cache.OffHeapNamespaceExtractionCacheManager
  at io.druid.server.namespace.NamespacedExtractionModule.configure(NamespacedExtractionModule.java:145)
  while locating io.druid.server.namespace.cache.NamespaceExtractionCacheManager annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=79, type=MAPBINDER)
  at io.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:86)
  at io.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:86)
  while locating io.druid.server.namespace.cache.NamespaceExtractionCacheManager
    for parameter 1 at io.druid.server.namespace.NamespacedExtractionModule$NamespaceStaticConfiguration.<init>(NamespacedExtractionModule.java:113)
  at io.druid.server.namespace.NamespacedExtractionModule$NamespaceStaticConfiguration.class(NamespacedExtractionModule.java:113)
  while locating io.druid.server.namespace.NamespacedExtractionModule$NamespaceStaticConfiguration

1 error
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:1014) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1036) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:153) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:91) [druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at io.druid.cli.ServerRunnable.run(ServerRunnable.java:40) [druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at io.druid.cli.Main.main(Main.java:105) [druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.mapdb.Caches$HashTable.<init>(Caches.java:209) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at org.mapdb.DBMaker.extendCacheHashTable(DBMaker.java:926) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at org.mapdb.DBMaker.makeEngine(DBMaker.java:774) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at org.mapdb.DBMaker.make(DBMaker.java:701) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at io.druid.server.namespace.cache.OffHeapNamespaceExtractionCacheManager.<init>(OffHeapNamespaceExtractionCacheManager.java:75) ~[?:?]
        at io.druid.server.namespace.cache.OffHeapNamespaceExtractionCacheManager$$FastClassByGuice$$973c3b28.newInstance(<generated>) ~[?:?]
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:108) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1058) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.Scopes$1$1.get(Scopes.java:65) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:1005) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1058) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:1001) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:90) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:90) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at io.druid.guice.PolyBind$ConfiggedProvider.get(PolyBind.java:181) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1058) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.Scopes$1$1.get(Scopes.java:65) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[druid-selfcontained-0.9.0-rc2-mmx5.jar:0.9.0-rc2-mmx5]
```

A simple fix is to allow this value to be configurable. A more complex fix would be to allow the extension to be loaded on the Peons but not the Middle Managers.

**Comment by drcrallen** [comment]
This is NOT a regression in 0.9.0

**Comment by AbhinavPhutela** [comment]
Can someone help me resolve this issue:

ERROR [main] io.druid.cli.CliPeon - Error when starting up.  Failing.
java.lang.OutOfMemoryError: unable to create new native thread

**Comment by abhijain1351** [comment]
Has anyone worked on the Heap space issue because of namespaces

**Comment by gianm** [comment]
Not that I am aware of.

**Comment by abhijain1351** [comment]
I did a workaround. Thanks anyway.
