### ISSUE TITLE
Multiple injectors can cause racy or locking behavior in GuiceFilter

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#2791]
If a task tries to create the startup injector at the same time while the main creator is being instantiated, AND both are in the same classloader, then there is some racy handling in GuiceFilter that can cause deadlocks in the initialization process. Here are the thread dumps of some locked threads as an example:

```
"task-runner-0-priority-0" #164 daemon prio=5 os_prio=0 tid=0x00007fd889650000 nid=0x26cb waiting for monitor entry [0x00007fd6253bc000]
   java.lang.Thread.State: BLOCKED (on object monitor)
    at com.google.inject.Scopes$1$1.get(Scopes.java:63)
    - waiting to lock <0x000000070011fb18> (a java.lang.Class for com.google.inject.internal.InternalInjectorCreator)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:84)
    at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
    at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
    at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1051)
    at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
    at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:174)
    at com.google.inject.internal.Initializer.injectAll(Initializer.java:108)
    at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:174)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
    at com.google.inject.Guice.createInjector(Guice.java:96)
    at com.google.inject.Guice.createInjector(Guice.java:73)
    at com.google.inject.Guice.createInjector(Guice.java:62)
    at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:324)
    at io.druid.indexer.spark.SerializedJsonStatic$.liftedTree1$1(SparkDruidIndexer.scala:423)
    at io.druid.indexer.spark.SerializedJsonStatic$.injector$lzycompute(SparkDruidIndexer.scala:422)
    - locked <0x000000070080a740> (a io.druid.indexer.spark.SerializedJsonStatic$)
    at io.druid.indexer.spark.SerializedJsonStatic$.injector(SparkDruidIndexer.scala:421)
    at io.druid.indexer.spark.SerializedJsonStatic$.liftedTree2$1(SparkDruidIndexer.scala:450)
    at io.druid.indexer.spark.SerializedJsonStatic$.mapper$lzycompute(SparkDruidIndexer.scala:449)
    - locked <0x000000070080a740> (a io.druid.indexer.spark.SerializedJsonStatic$)
    at io.druid.indexer.spark.SerializedJsonStatic$.mapper(SparkDruidIndexer.scala:448)
    at io.druid.indexer.spark.SparkBatchIndexTask.run(SparkBatchIndexTask.scala:152)
    at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:338)
    at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:318)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

```
"main" #1 prio=5 os_prio=0 tid=0x00007fd888014000 nid=0x1edb waiting on condition [0x00007fd88fad8000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x0000000700814de8> (a java.util.concurrent.CountDownLatch$Sync)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
    at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:155)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1058)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
    at com.google.inject.Scopes$1$1.get(Scopes.java:65)
    - locked <0x000000070011fb18> (a java.lang.Class for com.google.inject.internal.InternalInjectorCreator)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
    at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:1005)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1051)
    at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:1001)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1036)
    at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:110)
    at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:84)
    at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:104)
    - locked <0x0000000700815158> (a com.google.inject.servlet.ManagedFilterPipeline)
    at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:224)
    at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:138)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:852)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    - locked <0x00000007008153e8> (a java.lang.Object)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    - locked <0x0000000700815478> (a java.lang.Object)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:387)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:354)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    - locked <0x00000007008155a8> (a java.lang.Object)
    at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:170)
    at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259)
    - locked <0x0000000701512a50> (a java.util.HashMap)
    at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155)
    at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:91)
    at io.druid.cli.CliPeon.run(CliPeon.java:237)
    at io.druid.cli.Main.main(Main.java:105)
```

The work around is to not create multiple injectors in the same classloader.

**Comment by xvrl** [comment]
@drcrallen any reason this issue is closed? We should leave it open until GuiceFilter is fixed or until there is a way to isolate injector from GuiceFilter more explicitly.

**Comment by drcrallen** [comment]
Sure, I can leave it open for now. Since this is an issue two libraries outside of Druid proper encountered, I didn't want it to seem like a blocker in druid release for everyone.

**Comment by xvrl** [comment]
well, it's a known bug that's been around for a long time. I don't think it should be a blocker since it not something new.
