### ISSUE TITLE
NPE on loading segment when druid.announcer.skipLoadSpec=true

### ISSUE THREAD

**Issue by drcrallen** [apache/druid#2957]
```
2016-05-12T03:11:35,076 ERROR [ZkCoordinator-6] io.druid.server.coordination.ZkCoordinator - Failed to load segment for dataSource: {class=io.druid.server.coordination.ZkCoordinator, ex
ceptionType=class io.druid.segment.loading.SegmentLoadingException, exceptionMessage=Exception loading segment[REDACTED_2014-08-06T19:00:00.000Z_2014-08-06T20:00:00.000Z_2015-04-23T08
:19:08.204Z], segment=DataSegment{size=2620696, shardSpec=NoneShardSpec, metrics=[], dimensions=[], version='2015-04-23T08:19:08.204Z', loadSpec=null, interval=2014-08-06T19:00:00.000Z/
2014-08-06T20:00:00.000Z, dataSource='REDACTED', binaryVersion='9'}}
io.druid.segment.loading.SegmentLoadingException: Exception loading segment[REDACTED_2014-08-06T19:00:00.000Z_2014-08-06T20:00:00.000Z_2015-04-23T08:19:08.204Z]
        at io.druid.server.coordination.ZkCoordinator.loadSegment(ZkCoordinator.java:309) ~[druid-selfcontained-3ef66bb.jar:3ef66bb]
        at io.druid.server.coordination.ZkCoordinator.addSegment(ZkCoordinator.java:350) [druid-selfcontained-3ef66bb.jar:3ef66bb]
        at io.druid.server.coordination.SegmentChangeRequestLoad.go(SegmentChangeRequestLoad.java:44) [druid-selfcontained-3ef66bb.jar:3ef66bb]
        at io.druid.server.coordination.ZkCoordinator$1.childEvent(ZkCoordinator.java:152) [druid-selfcontained-3ef66bb.jar:3ef66bb]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:522) [druid-selfcontained-3ef66bb.jar:3ef66bb]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:516) [druid-selfcontained-3ef66bb.jar:3ef66bb]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [druid-selfcontained-3ef66bb.jar:3ef66bb]
        at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [druid-selfcontained-3ef66bb.jar:3ef66bb]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [druid-selfcontained-3ef66bb.jar:3ef66bb]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.callListeners(PathChildrenCache.java:514) [druid-selfcontained-3ef66bb.jar:3ef66bb]
        at org.apache.curator.framework.recipes.cache.EventOperation.invoke(EventOperation.java:35) [druid-selfcontained-3ef66bb.jar:3ef66bb]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:772) [druid-selfcontained-3ef66bb.jar:3ef66bb]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at io.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegmentFiles(SegmentLoaderLocalCacheManager.java:143) ~[druid-selfcontained-3ef66bb.jar:3ef66bb]
        at io.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegment(SegmentLoaderLocalCacheManager.java:95) ~[druid-selfcontained-3ef66bb.jar:3ef66bb]
        at io.druid.server.coordination.ServerManager.loadSegment(ServerManager.java:152) ~[druid-selfcontained-3ef66bb.jar:3ef66bb]
        at io.druid.server.coordination.ZkCoordinator.loadSegment(ZkCoordinator.java:305) ~[druid-selfcontained-3ef66bb.jar:3ef66bb]
        ... 18 more
```

Occurs on occasion in our logs on historicals running against master. I have not looked to see if this appears regularly in 0.9.0.

Seems benign, but NPE should be handled appropriately beforehand

**Comment by drcrallen** [comment]
Looking to why loadSpec is null

**Comment by nishantmonu51** [comment]
its due to skipLoadSpec being set to true in our config. 
the NPE seems to be caused while moving the segment from one server to another.

**Comment by drcrallen** [comment]
Since this is specifically present with a particular (non-default) flag set, I'm removing this as a blocker for 0.9.1 unless someone feels it should block.

**Comment by vogievetsky** [comment]
Is this still an issue in the upcoming 0.15.0?
