### ISSUE TITLE
Deadlock in io.druid.indexing.overlord.TaskMaster

### ISSUE THREAD

**Issue by leventov** [apache/druid#3579]
```
Java stack information for the threads listed above:
===================================================
"Thread-302":
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000071069e3d8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
        at io.druid.indexing.overlord.TaskMaster.stop(TaskMaster.java:202)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.stop(Lifecycle.java:362)
        at com.metamx.common.lifecycle.Lifecycle.stop(Lifecycle.java:280)
        - locked <0x00000007107f00f8> (a java.util.HashMap)
        at com.metamx.common.lifecycle.Lifecycle$1.run(Lifecycle.java:306)
        at java.lang.Thread.run(Thread.java:745)
"Curator-LeaderSelector-0":
        at com.metamx.common.lifecycle.Lifecycle.addMaybeStartHandler(Lifecycle.java:241)
        - waiting to lock <0x00000007107f00f8> (a java.util.HashMap)
        at com.metamx.common.lifecycle.Lifecycle.addMaybeStartHandler(Lifecycle.java:227)
        at com.metamx.common.concurrent.ExecutorServices.manageLifecycle(ExecutorServices.java:42)
        at com.metamx.common.concurrent.ScheduledExecutors$5.create(ScheduledExecutors.java:196)
        at io.druid.indexing.overlord.RemoteTaskRunnerFactory.build(RemoteTaskRunnerFactory.java:84)
        at io.druid.indexing.overlord.RemoteTaskRunnerFactory.build(RemoteTaskRunnerFactory.java:44)
        at io.druid.indexing.overlord.TaskMaster$1.takeLeadership(TaskMaster.java:103)
        at org.apache.curator.framework.recipes.leader.LeaderSelector$WrappedListener.takeLeadership(LeaderSelector.java:534)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:399)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:441)
        at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:64)
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:245)
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:239)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.
```

**Comment by leventov** [comment]
Apparently it happens because new taskRunner constructed here: https://github.com/druid-io/druid/blob/d981a2aa02aedfdf18e0bed5848e704bd9597563/indexing-service/src/main/java/io/druid/indexing/overlord/TaskMaster.java#L103 uses the older lifecycle object to start threads and register shutdown hooks, because the new one is instantiated only several lines below in the code. However it's difficult to trace actual execution path because of `@Inject`, `@LazySingleton`, etc. I don't understand from where `Lifecycle` instance is taken here: https://github.com/druid-io/druid/blob/d981a2aa02aedfdf18e0bed5848e704bd9597563/server/src/main/java/io/druid/guice/ServerModule.java#L55
