### ISSUE TITLE
global cached lookups /  java.sql.SQLException: No suitable driver found for jdbc

### ISSUE THREAD

**Issue by grocon** [apache/druid#3770]
Hello,
as described on https://groups.google.com/forum/#!topic/druid-user/c0iQVkDFToE , I had a problem with druid (0.9.2) not loading lookups from a mysql database.

```
org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/xxxxxxx
        at org.skife.jdbi.v2.DBI.open(DBI.java:230) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:279) ~[jdbi-2.63.1.jar:2.63.1]
        at io.druid.server.lookup.namespace.JDBCExtractionNamespaceCacheFactory$2.call(JDBCExtractionNamespaceCacheFactory.java:84) ~[druid-lookups-cached-global-0.9.2.jar:0.9.2]
        at io.druid.server.lookup.namespace.JDBCExtractionNamespaceCacheFactory$2.call(JDBCExtractionNamespaceCacheFactory.java:73) ~[druid-lookups-cached-global-0.9.2.jar:0.9.2]
        at io.druid.server.lookup.namespace.cache.NamespaceExtractionCacheManager$3.run(NamespaceExtractionCacheManager.java:362) [druid-lookups-cached-global-0.9.2.jar:0.9.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_111]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [?:1.7.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [?:1.7.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/xxxxxxx
        at java.sql.DriverManager.getConnection(DriverManager.java:596) ~[?:1.7.0_111]
        at java.sql.DriverManager.getConnection(DriverManager.java:215) ~[?:1.7.0_111]
        at org.skife.jdbi.v2.DBI$3.openConnection(DBI.java:140) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.DBI.open(DBI.java:212) ~[jdbi-2.63.1.jar:2.63.1]
        ... 13 more
```

as a temporary fix, I copied mysql-connector-java-5.1.38.jar from the mysql-metadata-storage extension to lib directory.

**Comment by drcrallen** [comment]
Related to https://github.com/druid-io/druid/issues/2345

If adding the SQL driver jars to the application classpath fixes things, then the documentation should be updated to reflect this until a "proper" fix is in place.

**Comment by Igosuki** [comment]
I personnally fixed the issue with postgres here.
https://github.com/Igosuki/druid/commit/7435372ad2afce855a44a950060bf1a30ed5570f

I haven't tested it, but I bet I could remove the manual driver registration and simply implement the connection factory in the main thread.

**Comment by chirpy2291** [comment]
Please update the documentation for lookups:regarding jdbc lookups!It would help others :)
