### ISSUE TITLE
java.lang.ClassNotFoundException: Class org.apache.hadoop.hive.ql.io.orc.OrcNewSplit not found

### ISSUE THREAD

**Issue by bettybao1209** [apache/druid#4133]
Hi, recently I wanna ingest batch data in hdfs, which is in ORC format. And I have already include druid-orc-extension-0.9.2.jar into extensions directory, and add this extension into commom_runtime.propreties as well. However, I still meet class not found exception , just as following:
Error: java.lang.RuntimeException: readObject can't find class
	at org.apache.hadoop.mapreduce.lib.input.TaggedInputSplit.readClass(TaggedInputSplit.java:136)
	at org.apache.hadoop.mapreduce.lib.input.TaggedInputSplit.readFields(TaggedInputSplit.java:120)
	at org.apache.hadoop.io.serializer.WritableSerialization$WritableDeserializer.deserialize(WritableSerialization.java:71)
	at org.apache.hadoop.io.serializer.WritableSerialization$WritableDeserializer.deserialize(WritableSerialization.java:42)
	at org.apache.hadoop.mapred.MapTask.getSplitDetails(MapTask.java:372)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:754)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.hive.ql.io.orc.OrcNewSplit not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101)
	at org.apache.hadoop.mapreduce.lib.input.TaggedInputSplit.readClass(TaggedInputSplit.java:134)

BTW, I set mapreduce.job.classloader=true. And use druid with 0.9.2 version and hadoop 2.5.0-cdh5.3.2

Thanks.

**Comment by knoguchi** [comment]
I've never used that extension, so this is just a suggestion only.   The OrcNewSplit class is provided by `hive-exec` version 2.0.0 jar.  The first thing I'd do is [pull-deps](http://druid.io/docs/latest/operations/pull-deps.html) and make sure necessary jars for the plugin is downloaded.  

`java -classpath "./lib/*" io.druid.cli.Main tools pull-deps --clean -c io.druid.extensions.contrib:druid-orc-extensions:0.9.2 -h org.apache.hadoop:hadoop-client:2.3.0`

If the hadoop v2.3.0 client does not work for some reasons, please see [my post at Stackoverflow](http://stackoverflow.com/questions/40146584/an-error-loading-batch-data-in-druid-with-hadoop-2-6-0-cdh5-7-1-map-reduce).

**Comment by Hailei** [comment]
I resolved this problem，set mapreduce.job.classloader=true,Hadoop's classloder and application's classloader is isolated,Hadoop's classloader only load hadoop jar,don't include hive's jar,so cause classnotfound exception,So you can't enable this option.
If disable this option will cause jackson json conflict with CDH. Refer to [http://druid.io/docs/0.10.0/operations/other-hadoop.html](url),recompile and using shade plugin to mask a fat jar, you can choose one of them.I choose shade plugin,it is a relatively simple way.

**Comment by chenhaiyan** [comment]
when I run `java -classpath "./lib/*" -Ddruid.extensions.directory="./extensions" -Ddruid.extensions.hadoopDependenciesDir="./hadoop-dependencies" io.druid.cli.Main tools pull-deps --clean -c io.druid.extensions.contrib:druid-orc-extensions:0.12.0`  I don't know what wrong is it?

**Comment by chenhaiyan** [comment]
it always return Error: Could not find or load main class io.druid.cli.Main

**Comment by chenhaiyan** [comment]
@stale

> This issue has been marked as stale due to 280 days of inactivity. It will be closed in 4 weeks if no further activity occurs. If this issue is still relevant, please simply write any comment. Even if closed, you can still revive the issue at any time or discuss it on the [dev@druid.apache.org](mailto:dev@druid.apache.org) list. Thank you for your contributions.

Sorry about this,I didn't see my mail for a long time . As for the question,it is ok to close.
