### ISSUE TITLE
If you use druid.lookup.snapshotWorkingDir on middle managers they may die with fatal error

### ISSUE THREAD

**Issue by mgastel** [apache/druid#4334]
If you are using the lookup druid.lookup.snapshotWorkingDir on middle managers you may get a fatal error that looks like this:

2017-05-24T18:01:16,096 INFO [main] io.druid.server.lookup.namespace.cache.OffHeapNamespaceExtractionCacheManager - Using file [/data/tmp/druidMapDB4041895013520786151io.druid.server.lookup.namespace.cache.OffHeapNamespaceExtractionCacheManager] for mapDB off heap namespace cache
2017-05-24T18:01:16,383 ERROR [main] io.druid.cli.CliPeon - Error when starting up.  Failing.
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:350) ~[java-util-0.27.10.jar:?]
at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) ~[java-util-0.27.10.jar:?]
at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) ~[druid-api-0.9.2.jar:0.9.2]
at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:101) [druid-services-0.9.2.jar:0.9.2]
at io.druid.cli.CliPeon.run(CliPeon.java:274) [druid-services-0.9.2.jar:0.9.2]
at io.druid.cli.Main.main(Main.java:106) [druid-services-0.9.2.jar:0.9.2]
Caused by: com.metamx.common.ISE: Exception during reading lookups from [/data/snapshot/lookupSnapshot.json]
at io.druid.query.lookup.LookupSnapshotTaker.pullExistingSnapshot(LookupSnapshotTaker.java:79) ~[druid-processing-0.9.2.jar:0.9.2]
at io.druid.query.lookup.LookupReferencesManager.start(LookupReferencesManager.java:84) ~[druid-processing-0.9.2.jar:0.9.2]
... 10 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input in VALUE_STRING
at [Source: /data/snapshot/lookupSnapshot.json; line: 1, column: 16001] (through reference chain: java.util.ArrayList[16]->io.druid.query.lookup.LookupBean["factory"])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210) ~[jackson-databind-2.4.6.jar:2.4.6]
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177) ~[jackson-databind-2.4.6.jar:2.4.6]
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1428) ~[jackson-databind-2.4.6.jar:2.4.6]
....

I'm guessing that multiple peons starting on the middle manager may result in concurrent modification / reading of the snapshotWorkingDir potentially resulting in garbage.   The error goes way if you do not set the snapshot directory.   Perhaps the snapshot feature should be disabled on middle managers or the documentation updated to reflect this problem.

**Comment by leventov** [comment]
@mgastel note that you shouldn't use offHeap cache, it is broken: #3663
