### ISSUE TITLE
Hourly Aggregation Job Failing

### ISSUE THREAD

**Issue by arpankhagram** [apache/druid#5008]
We are getting below exception while submitting hourly aggregation task 

```
2017-10-26T05:38:04,555 INFO [rtr-pending-tasks-runner-0] io.druid.indexing.overlord.RemoteTaskRunner - Coordinator asking Worker[172.25
.182.158:8091] to add task[index_EPC_SGSN_Hourly_2017-10-26T05:38:04.533Z]
2017-10-26T05:38:04,560 ERROR [rtr-pending-tasks-runner-0] io.druid.indexing.overlord.RemoteTaskRunner - Exception while trying to assig
n task: {class=io.druid.indexing.overlord.RemoteTaskRunner, exceptionType=class io.druid.java.util.common.IAE, exceptionMessage=Length o
f raw bytes for znode[/druid/indexer/tasks/172.25.182.158:8091/index_EPC_SGSN_Hourly_2017-10-26T05:38:04.533Z] too large[603,385 > 524,2
88], taskId=index_EPC_SGSN_Hourly_2017-10-26T05:38:04.533Z}
io.druid.java.util.common.IAE: Length of raw bytes for znode[/druid/indexer/tasks/172.25.182.158:8091/index_EPC_SGSN_Hourly_2017-10-26T0
5:38:04.533Z] too large[603,385 > 524,288]
        at io.druid.curator.CuratorUtils.verifySize(CuratorUtils.java:127) ~[druid-server-0.10.0.jar:0.10.0]
        at io.druid.curator.CuratorUtils.createIfNotExists(CuratorUtils.java:56) ~[druid-server-0.10.0.jar:0.10.0]
```

**Comment by arpankhagram** [comment]
Understood what the problem is but is there anything I can do other than removing some of the metrics from json spec

**Comment by drcrallen** [comment]
When we encounter this error it is usually from specifying a bunch of files in a list in the index spec. The solution in such a case is change the job to have fewer files.

**Comment by drcrallen** [comment]
you should also be able to specify `maxZnodeBytes` in your remote task runner config if you have good control and understanding of what your underlying ZK cluster is set to handle.

**Comment by l15k4** [comment]
I'm getting this to while `druid.coordinator.merge.on` : 
```
2017-11-06T00:47:43,276 ERROR [rtr-pending-tasks-runner-0] io.druid.indexing.overlord.RemoteTaskRunner - Exception while trying to assign task: {class=io.druid.indexing.overlord.RemoteTaskRunner, exceptionType=class io.druid.java.util.common.IAE, exceptionMessage=Length of raw bytes for znode[/druid/indexer/tasks/host/merge_gwiq-p_3e5765361213014fa09f684b60769226c337b011_2017-11-06T00:47:42.761Z] too large[534,073 > 524,288], taskId=merge_gwiq-p_3e5765361213014fa09f684b60769226c337b011_2017-11-06T00:47:42.761Z}
io.druid.java.util.common.IAE: Length of raw bytes for znode[/druid/indexer/tasks/host:8091/merge_gwiq-p_3e5765361213014fa09f684b60769226c337b011_2017-11-06T00:47:42.761Z] too large[534,073 > 524,288]
	at io.druid.curator.CuratorUtils.verifySize(CuratorUtils.java:127) ~[druid-server-0.10.1-iap3.jar:0.10.1-iap3]
	at io.druid.curator.CuratorUtils.createIfNotExists(CuratorUtils.java:56) ~[druid-server-0.10.1-iap3.jar:0.10.1-iap3]
	at io.druid.indexing.overlord.RemoteTaskRunner.announceTask(RemoteTaskRunner.java:837) ~[druid-indexing-service-0.10.1-iap3.jar:0.10.1-iap3]
	at io.druid.indexing.overlord.RemoteTaskRunner.tryAssignTask(RemoteTaskRunner.java:790) ~[druid-indexing-service-0.10.1-iap3.jar:0.10.1-iap3]
	at io.druid.indexing.overlord.RemoteTaskRunner.access$1400(RemoteTaskRunner.java:126) ~[druid-indexing-service-0.10.1-iap3.jar:0.10.1-iap3]
	at io.druid.indexing.overlord.RemoteTaskRunner$3.call(RemoteTaskRunner.java:651) [druid-indexing-service-0.10.1-iap3.jar:0.10.1-iap3]
	at io.druid.indexing.overlord.RemoteTaskRunner$3.call(RemoteTaskRunner.java:633) [druid-indexing-service-0.10.1-iap3.jar:0.10.1-iap3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by l15k4** [comment]
Strange thing is, that if I increase `mergeBytesLimit` a bit to be bigger than those required `534,073`, then I get the same error with `[1,097,157 > 524,288]` :-/

**Comment by l15k4** [comment]
I think that the coordination dynamic configuration should have <min,max> for `mergeBytesLimit` and `mergeSegmentsLimit`, so far it seems to me that they represent something like both `min & max`. Ie. I had to slowly decrease `mergeSegmentsLimit` to be ably to merge all historical segments as they were growing in time. And I also had sometimes increase `mergeBytesLimit` due to the error above ^

**Comment by mihai-cazacu-adswizz** [comment]
We are also having this issue:

```
Length of raw bytes for znode[/.../indexer/tasks/server:8091/ds_2019-04-30T12:48:57.577Z] too large[655,019 > 524,288]
```

And this is due some intervals which have many segments (~400). Because of this, the generated JSON has ~2.5 MB and the Zookeeper's limit appears to be 1MB.

Is there a way to solve this or the only choice we have is to modify the value of [druid.indexer.runner.maxZnodeBytes](https://github.com/metabase/druid/blob/master/docs/content/configuration/indexing-service.md)?
