### ISSUE TITLE
Port confliction in peon

### ISSUE THREAD

**Issue by litao91** [apache/druid#5230]
Occasionally, my index realtime job failed with the following error message:

```
Error when starting up.  Failing.
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_131]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_131]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_131]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_131]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_131]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:317) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
	at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:206) ~[druid-server-0.10.1.jar:0.10.1]
	at io.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:263) ~[java-util-0.10.1.jar:0.10.1]
	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:156) ~[druid-api-0.10.1.jar:0.10.1]
	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:103) [druid-services-0.10.1.jar:0.10.1]
	at io.druid.cli.CliPeon.run(CliPeon.java:282) [druid-services-0.10.1.jar:0.10.1]
	at io.druid.cli.Main.main(Main.java:108) [druid-services-0.10.1.jar:0.10.1]
```

There is exactly one MM running on the machine and there is no other service other than some server maintenance service provided by infrastructure team running on it. 

I guess here is what happened:

1. MiddleManager found a unused port PORT
2. Unfortunately a mysterious TCP local connection used that PORT right before the starting of the Peon service. 
3. Peon service starts and finds that the port is used, so it panic.

**Comment by himanshug** [comment]
scenario, you described, is indeed possible. but if you're hitting it too often then something else is likely going on. I have had two instances of above problem with following causes (just-in-case if you're having one of those)

- `druid.port` at MM being same as `druid.indexer.runner.startPort`
- another software deployed which dynamically used port in same port range. (you've probably already checked for this one though)

**Comment by litao91** [comment]
@himanshug I don't think the `druid.port` at MM matters. The port finding logic in MM will find a available port before starting Peon. The `druid.port` won't be available at that time thus that port will be skipped. 

I have no control on the heartbeat/health checking services provided by system admin. 

It occurs in a fairly low probability actually, but as our cluster becoming busier (more than 500 tasks at any moment), it's getting more serious, especially when working with tranquility, in which case tranquility will throw away a full segment of data. 

I think it's not the problem of other services but a design flaw of Druid. In my opinion A better strategy may be Peon find a port and start the service itself and report to MM after that.

**Comment by himanshug** [comment]
> @himanshug I don't think the druid.port at MM matters. The port finding logic in MM will find a available port before starting Peon. The druid.port won't be available at that time thus that port will be skipped.

I remember this being an issue at least once for a customer. When MM starts , it would select ports for the tasks to be restored and spawn peon process ( which would go on to start server sockets) asynchronously... and at this point MM would also starts its own jetty server ... a port conflict could happen in this situation if MM `druid.port` and startPort were same. I never confirmed it because problem was solved by just incrementing startPort by 1, but most likely above theory would hold.


> It occurs in a fairly low probability actually, but as our cluster becoming busier (more than 500 tasks at any moment), it's getting more serious, especially when working with tranquility, in which case tranquility will throw away a full segment of data.

if you have multiple replicants and at least one of them runs successfully then such data loss shouldn't happen. that said, starting Druid-0.12.0 , using KafkaIndexingService for realtime ingestion would be a better choice for many other reasons as well.

> I think it's not the problem of other services but a design flaw of Druid. In my opinion A better strategy may be Peon find a port and start the service itself and report to MM after that.

I see your point, it could be improved.

All said, We run many clusters with many many middle managers and don't hit this problem. what is your startPort ? Also, you can run following command to see what is your host's ephemeral ports range. Is your startPort very close to system ephemeral port range ?
```
$ sysctl net.ipv4.ip_local_port_range
net.ipv4.ip_local_port_range = 32768	60999
```
and, I'm assuming you have checked there aren't other services that would try and use same port range.

**Comment by YingHun** [comment]
Hi, I meet the same issue, peon inserts druid task into mysql, but can't create segment under directory "var/druid/task". and exception: 
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_65]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_65]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_65]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_65]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_65]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:317) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
	at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:315) ~[druid-server-0.12.1.jar:0.12.1]
	at io.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:311) ~[java-util-0.12.1.jar:0.12.1]
	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:134) ~[druid-api-0.12.1.jar:0.12.1]
	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:101) [druid-services-0.12.1.jar:0.12.1]
	at io.druid.cli.CliPeon.run(CliPeon.java:301) [druid-services-0.12.1.jar:0.12.1]
	at io.druid.cli.Main.main(Main.java:116) [druid-services-0.12.1.jar:0.12.1]

**Comment by YingHun** [comment]
Hi, I meet the same issue, peon inserts druid task into mysql, but can't create segment under directory "var/druid/task". and exception:

java.net.BindException: Address already in use
at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_65]
at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_65]
at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_65]
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_65]
at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_65]
at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:317) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:315) ~[druid-server-0.12.1.jar:0.12.1]
at io.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:311) ~[java-util-0.12.1.jar:0.12.1]
at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:134) ~[druid-api-0.12.1.jar:0.12.1]
at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:101) [druid-services-0.12.1.jar:0.12.1]
at io.druid.cli.CliPeon.run(CliPeon.java:301) [druid-services-0.12.1.jar:0.12.1]
at io.druid.cli.Main.main(Main.java:116) [druid-services-0.12.1.jar:0.12.1]

**Comment by jihoonson** [comment]
I would say it's better for peon to find a usable port by its own and let the middleManager know it.
