### ISSUE TITLE
Netty error: "exception was thrown by a user handler while handling an exception"

### ISSUE THREAD

**Issue by gianm** [apache/druid#5326]
I think I haven't seen this before. Noticed it with the current master. I'm not sure what is going on, but it looks related to the read-timeout handler we add in NettyHttpClient.

```
2018-02-02T08:13:37,626 WARN [HttpClient-Netty-Worker-0] org.jboss.netty.channel.DefaultChannelPipeline - An exception was thrown by a user handler while handling an exception event ([id: 0xdf1578fe, /1
72.31.12.65:39006 :> ip-172-31-3-17.ec2.internal/172.31.3.17:8304] EXCEPTION: org.jboss.netty.handler.timeout.ReadTimeoutException)
java.util.NoSuchElementException: read-timeout
        at org.jboss.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:684) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:153) [netty-3.10.6.Final.jar:?]
        at io.druid.java.util.http.client.NettyHttpClient$1.removeHandlers(NettyHttpClient.java:329) ~[java-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at io.druid.java.util.http.client.NettyHttpClient$1.exceptionCaught(NettyHttpClient.java:293) ~[java-util-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:536) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.timeout.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:236) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.timeout.ReadTimeoutHandler$ReadTimeoutTask$1.run(ReadTimeoutHandler.java:276) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.ChannelRunnableWrapper.run(ChannelRunnableWrapper.java:40) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.6.Final.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by VijayakumarBalakrishnan** [comment]
2019-07-22 15:58:00.589  WARN 5822 --- [:0:0:0:0:1903])] o.j.n.channel.DefaultChannelPipeline     : An exception was thrown by a user handler while handling an exception event ([id: 0x08ca0e26, /127.0.0.1:45258 :> 0.0.0.0/0.0.0.0:1903] EXCEPTION: java.lang.NullPointerException)

java.lang.NullPointerException: null
	at com.ai.proxyserver.tcptunnel.TcpTunnelInboundHandler.exceptionCaught(TcpTunnelInboundHandler.java:186) ~[classes/:na]
	at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:432) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:52) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:176) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioAcceptedSocketChannel.<init>(NioAcceptedSocketChannel.java:49) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.registerAcceptedChannel(NioServerSocketPipelineSink.java:280) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:247) ~[netty-3.2.2.Final.jar:na]
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) [netty-3.2.2.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

**Comment by VijayakumarBalakrishnan** [comment]
I don't know where the null pointer comes

**Comment by buffaloDeveloper** [comment]
I am seeing the same issue.  Did anyone find a way to resolve this?
```
2024-01-11T14:30:46,784 DEBUG [HttpClient-Netty-Worker-2] org.apache.druid.java.util.http.client.NettyHttpClient - [POST http://192.168.156.244:8088/druid/indexer/v1/action] Caught exception
org.jboss.netty.handler.timeout.ReadTimeoutException: null
	at org.jboss.netty.handler.timeout.ReadTimeoutHandler.<clinit>(ReadTimeoutHandler.java:84) ~[netty-3.10.6.Final.jar:?]
	at org.apache.druid.java.util.http.client.NettyHttpClient.go(NettyHttpClient.java:180) ~[druid-core-25.0.0.jar:25.0.0]
	at org.apache.druid.rpc.ServiceClientImpl.lambda$tryRequest$2(ServiceClientImpl.java:162) ~[druid-server-25.0.0.jar:25.0.0]
	at org.apache.druid.rpc.ServiceClientImpl$2.onSuccess(ServiceClientImpl.java:391) ~[druid-server-25.0.0.jar:25.0.0]
	at org.apache.druid.rpc.ServiceClientImpl$2.onSuccess(ServiceClientImpl.java:381) ~[druid-server-25.0.0.jar:25.0.0]
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1181) ~[guava-16.0.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```
