### ISSUE TITLE
ec2 autoscaler doesn't seem to work in regions other than us-east-1

### ISSUE THREAD

**Issue by raravena80** [apache/druid#5383]
it launches instances if I'm running in us-east-1 but not if if I use us-west-1 (us-west-1a) for example: 

```
2018-02-12T21:43:50,184 ERROR [SimpleResourceManagement-manager--0] io.druid.indexing.overlord.autoscaling.ec2.EC2AutoScaler - Unable to provision any EC2 instances.
com.amazonaws.services.ec2.model.AmazonEC2Exception: Invalid availability zone: [us-west-1a] (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: e48c26d7-3abf-441d-a52b-0065b314a746)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:16092) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:16068) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.services.ec2.AmazonEC2Client.executeRunInstances(AmazonEC2Client.java:15446) ~[aws-java-sdk-1.11.275.jar:?]
        at com.amazonaws.services.ec2.AmazonEC2Client.runInstances(AmazonEC2Client.java:15422) ~[aws-java-sdk-1.11.275.jar:?]
        at io.druid.indexing.overlord.autoscaling.ec2.EC2AutoScaler.provision(EC2AutoScaler.java:148) [druid-indexing-service-0.11.0.jar:0.11.0]
        at io.druid.indexing.overlord.autoscaling.SimpleWorkerProvisioningStrategy$SimpleProvisioner.doProvision(SimpleWorkerProvisioningStrategy.java:151) [druid-indexing-service-0.11.0.jar:0.11.0]
        at io.druid.indexing.overlord.autoscaling.AbstractWorkerProvisioningStrategy$WorkerProvisioningService$1.run(AbstractWorkerProvisioningStrategy.java:75) [druid-indexing-service-0.11.0.jar:0.11.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_144]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_144]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

Using druid 0.11.0

Tried with aws-sdk `1.11.275` and `1.10.77`

Looks like we may need another parameter in the request, perhaps vpc-id? When I launched in in us-east-1 with no value for avzone or subnet it launched in the default VPC.

This also worked fine for me using the aws cli

```
aws ec2 run-instances --image-id ami-xxxxxxxx --count 1 --instance-type m4.2xlarge --key-name mykey --security-group-ids sg-xxxxxxxx sg-xxxxxxxx sg-xxxxxxxx --subnet-id subnet-xxxxxxxx --iam-instance-profile Arn=arn:aws:iam::xxxxxxxxxxxx:instance-profile/myprofile --associate-public-ip-address --placement AvailabilityZone=us-west-1a
```

**Comment by raravena80** [comment]
Confirmed that we need this somewhere:

```
amazonEC2Client.setRegion("region-id");
// For example
amazonEC2Client.setRegion("us-west-1");
```

Perhaps in this file, in the constructor:

https://github.com/druid-io/druid/blob/master/indexing-service/src/main/java/io/druid/indexing/overlord/autoscaling/ec2/EC2AutoScaler.java#L68

**Comment by drcrallen** [comment]
Can you just set `aws.region` as per https://github.com/aws/aws-sdk-java/blob/1.11.277/aws-java-sdk-core/src/main/java/com/amazonaws/SDKGlobalConfiguration.java#L62 ?

**Comment by sunakshi-saxena** [comment]
I am stiil facing the same issue, even after adding aws.region in jvm.config for all services
