### ISSUE TITLE
io.druid.java.util.common.ISE: Request did not have an authorization check performed

### ISSUE THREAD

**Issue by ghost** [apache/druid#5573]
Got the latest code base from master, build docker container  FROM ubuntu:14.04.
Getting this exception:

2018-04-04T15:06:35,864 ERROR [qtp1825811850-78] **io.druid.server.security.PreResponseAuthorizationCheckFilter - Request did not have an authorization check performed.: {class=io.druid.server.security.PreResponseAuthorizationCheckFilter, uri=/console.html, method=GET, remoteAddr=xxx.xx.x.x, remoteHost=xxx.xx.x.x}**
docker-druid       | 2018-04-04T15:06:35,941 WARN [qtp1825811850-78] org.eclipse.jetty.server.HttpChannel - //localhost:8081/console.html
docker-druid       | io.druid.java.util.common.ISE: Request did not have an authorization check performed.
docker-druid       | 	at io.druid.server.security.PreResponseAuthorizationCheckFilter.handleAuthorizationCheckError(PreResponseAuthorizationCheckFilter.java:158) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:91) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:85) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:60) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:86) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:493) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.Server.handle(Server.java:534) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
docker-druid       | 2018-04-04T15:06:53,224 ERROR [qtp1825811850-97] io.druid.server.security.PreResponseAuthorizationCheckFilter - Request did not have an authorization check performed.: {class=io.druid.server.security.PreResponseAuthorizationCheckFilter, uri=/, method=GET, remoteAddr=172.18.0.1, remoteHost=172.18.0.1}
docker-druid       | 2018-04-04T15:06:53,680 WARN [qtp1825811850-97] org.eclipse.jetty.server.HttpChannel - //localhost:8081/
docker-druid       | io.druid.java.util.common.ISE: Request did not have an authorization check performed.
docker-druid       | 	at io.druid.server.security.PreResponseAuthorizationCheckFilter.handleAuthorizationCheckError(PreResponseAuthorizationCheckFilter.java:158) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:91) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:85) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:60) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:86) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:493) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.Server.handle(Server.java:534) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
docker-druid       | 2018-04-04T15:07:20,715 INFO [LookupCoordinatorManager--2] io.druid.server.lookup.cache.LookupCoordinatorManager - Not updating lookups because no data exists
docker-druid       | 2018-04-04T15:07:27,872 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Starting coordination. Getting available segments.
docker-druid       | 2018-04-04T15:07:28,520 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Found [0] available segments.
docker-druid       | 2018-04-04T15:07:28,942 INFO [Coordinator-Exec--0] io.druid.server.coordinator.ReplicationThrottler - [_default_tier]: Replicant create queue is empty.
docker-druid       | 2018-04-04T15:07:29,124 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorCleanupUnneeded - Found 0 availableSegments, skipping the cleanup of segments from historicals. This is done to prevent a race condition in which the coordinator would drop all segments if it started running cleanup before it finished polling the metadata storage for available segments for the first time.
docker-druid       | 2018-04-04T15:07:31,718 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorBalancer - [_default_tier]: One or fewer servers found.  Cannot balance.
docker-druid       | 2018-04-04T15:07:31,718 INFO [DatabaseRuleManager-Exec--0] io.druid.metadata.SQLMetadataRuleManager - Polled and found rules for 1 datasource(s)
docker-druid       | 2018-04-04T15:07:44,064 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorLogger - Load Queues:
docker-druid       | 2018-04-04T15:07:47,607 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorLogger - Server[172.18.0.4:8083, historical, _default_tier] has 0 left to load, 0 left to drop, 0 bytes queued, 0 bytes served.
docker-druid       | 2018-04-04T15:08:14,977 WARN [DatabaseSegmentManager-Exec--0] io.druid.metadata.SQLMetadataSegmentManager - No segments found in the database!
docker-druid       | 2018-04-04T15:08:15,921 INFO [TaskQueue-StorageSync] io.druid.indexing.overlord.TaskQueue - Synced 1 tasks from storage (0 tasks added, 0 tasks removed).
docker-druid       | 2018-04-04T15:08:53,973 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Starting coordination. Getting available segments.
docker-druid       | 2018-04-04T15:08:54,501 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Found [0] available segments.
docker-druid       | 2018-04-04T15:08:55,092 INFO [Coordinator-Exec--0] io.druid.server.coordinator.ReplicationThrottler - [_default_tier]: Replicant create queue is empty.
docker-druid       | 2018-04-04T15:08:55,635 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorCleanupUnneeded - Found 0 availableSegments, skipping the cleanup of segments from historicals. This is done to prevent a race condition in which the coordinator would drop all segments if it started running cleanup before it finished polling the metadata storage for available segments for the first time.
docker-druid       | 2018-04-04T15:08:56,109 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorBalancer - [_default_tier]: One or fewer servers found.  Cannot balance.
docker-druid       | 2018-04-04T15:08:56,762 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorLogger - Load Queues:
docker-druid       | 2018-04-04T15:08:57,644 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorLogger - Server[172.18.0.4:8083, historical, _default_tier] has 0 left to load, 0 left to drop, 0 bytes queued, 0 bytes served.
docker-druid       | 2018-04-04T15:08:57,900 INFO [DatabaseRuleManager-Exec--0] io.druid.metadata.SQLMetadataRuleManager - Polled and found rules for 1 datasource(s)
docker-druid       | 2018-04-04T15:09:01,542 INFO [TaskQueue-StorageSync] io.druid.indexing.overlord.TaskQueue - Synced 1 tasks from storage (0 tasks added, 0 tasks removed).
docker-druid       | 2018-04-04T15:09:20,775 INFO [LookupCoordinatorManager--2] io.druid.server.lookup.cache.LookupCoordinatorManager - Not updating lookups because no data exists
docker-druid       | 2018-04-04T15:09:29,296 WARN [DatabaseSegmentManager-Exec--0] io.druid.metadata.SQLMetadataSegmentManager - No segments found in the database!
docker-druid       | 2018-04-04T15:09:30,944 INFO [TaskQueue-StorageSync] io.druid.indexing.overlord.TaskQueue - Synced 1 tasks from storage (0 tasks added, 0 tasks removed).

**Comment by jon-wei** [comment]
Do you have `druid.coordinator.asOverlord.enabled=true` in your config? If so, https://github.com/druid-io/druid/pull/5579 fixes this.

**Comment by srggrs** [comment]
Hi guys I get the same issue with Druid 0.13.0:

> 2019-01-31T02:28:34,357 ERROR [qtp1844372336-99] org.apache.druid.server.security.PreResponseAuthorizationCheckFilter - Request did not have an authorization check performed.: {class=org.apache.druid.serv
er.security.PreResponseAuthorizationCheckFilter, uri=/, method=GET, remoteAddr=127.0.0.1, remoteHost=127.0.0.1}
2019-01-31T02:28:34,363 WARN [qtp1844372336-99] org.eclipse.jetty.server.HttpChannel - /
org.apache.druid.java.util.common.ISE: Request did not have an authorization check performed.
        at org.apache.druid.server.security.PreResponseAuthorizationCheckFilter.handleAuthorizationCheckError(PreResponseAuthorizationCheckFilter.java:158) ~[druid-server-0.13.0-incubating.jar:0.13.0-incu
bating]
        at org.apache.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:91) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) ~[jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.apache.druid.server.security.AllowOptionsResourceFilter.doFilter(AllowOptionsResourceFilter.java:76) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) ~[jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.apache.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:85) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:60) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) ~[jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.apache.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:88) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) ~[jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) ~[jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) ~[jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.Server.handle(Server.java:531) ~[jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

and my coordinator GUI won't update after the compaction tasks (spawned by automatic compaction on the coordinator) have been completed.

![image](https://user-images.githubusercontent.com/34258464/52026749-1241d000-255d-11e9-82cb-fdc56178d560.png)

**Comment by srggrs** [comment]
restarting the cluster fix that
