### ISSUE TITLE
Error enabling http emitter module by set metrics of "io.druid.server.metrics.HistoricalMetricsMonitor" and "io.druid.server.metrics.QueryCountStatsMonitor"

### ISSUE THREAD

**Issue by regardfs** [apache/druid#5855]
Hi, first I want to post the `common.runtime.properties` config which run successfully:

```
#
# Monitoring
#
druid.monitoring.monitors=["io.druid.java.util.metrics.JvmMonitor","io.druid.client.cache.CacheMonitor"]
druid.emitter.composing.emitters=["logging","http"]
druid.emitter.logging.logLevel=warn
druid.emitter.http.recipientBaseUrl=http://10.12.0.130:8091  ## https://github.com/wikimedia/operations-software-druid_exporter
```
Then, i change to below config and start failed with error:
Error config:
```
#
# Monitoring
#
druid.monitoring.monitors=["io.druid.server.metrics.HistoricalMetricsMonitor"]
druid.emitter.composing.emitters=["logging","http"]
druid.emitter.logging.logLevel=warn
druid.emitter.http.recipientBaseUrl=http://10.12.0.130:8091
```
Error log:
```
]
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) null returned by binding at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:134) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.StorageNodeModule)
 but the 2nd parameter of io.druid.segment.loading.SegmentLoaderLocalCacheManager.<init>(SegmentLoaderLocalCacheManager.java:68) is not @Nullable
  while locating io.druid.segment.loading.SegmentLoaderConfig
    for the 2nd parameter of io.druid.segment.loading.SegmentLoaderLocalCacheManager.<init>(SegmentLoaderLocalCacheManager.java:68)
  while locating io.druid.segment.loading.SegmentLoaderLocalCacheManager
  at io.druid.guice.LocalDataStorageDruidModule.configure(LocalDataStorageDruidModule.java:54) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.LocalDataStorageDruidModule)
  while locating io.druid.segment.loading.SegmentLoader
    for the 1st parameter of io.druid.server.SegmentManager.<init>(SegmentManager.java:100)
  while locating io.druid.server.SegmentManager
    for the 5th parameter of io.druid.server.coordination.SegmentLoadDropHandler.<init>(SegmentLoadDropHandler.java:107)
  at io.druid.server.coordination.SegmentLoadDropHandler.class(SegmentLoadDropHandler.java:72)
  while locating io.druid.server.coordination.SegmentLoadDropHandler
    for the 3rd parameter of io.druid.server.metrics.HistoricalMetricsMonitor.<init>(HistoricalMetricsMonitor.java:48)
  while locating io.druid.server.metrics.HistoricalMetricsMonitor
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  while locating io.druid.java.util.metrics.MonitorScheduler
  at io.druid.server.metrics.MetricsModule.configure(MetricsModule.java:75) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  while locating io.druid.java.util.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

2) null returned by binding at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:134) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.StorageNodeModule)
 but the 2nd parameter of io.druid.server.coordination.SegmentLoadDropHandler.<init>(SegmentLoadDropHandler.java:107) is not @Nullable
  while locating io.druid.segment.loading.SegmentLoaderConfig
    for the 2nd parameter of io.druid.server.coordination.SegmentLoadDropHandler.<init>(SegmentLoadDropHandler.java:107)
  at io.druid.server.coordination.SegmentLoadDropHandler.class(SegmentLoadDropHandler.java:72)
  while locating io.druid.server.coordination.SegmentLoadDropHandler
    for the 3rd parameter of io.druid.server.metrics.HistoricalMetricsMonitor.<init>(HistoricalMetricsMonitor.java:48)
  while locating io.druid.server.metrics.HistoricalMetricsMonitor
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  while locating io.druid.java.util.metrics.MonitorScheduler
  at io.druid.server.metrics.MetricsModule.configure(MetricsModule.java:75) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  while locating io.druid.java.util.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

3) druid.segmentCache.locations - 不能为空
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:133) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.StorageNodeModule)
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:133) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.StorageNodeModule)
  while locating com.google.common.base.Supplier<io.druid.segment.loading.SegmentLoaderConfig>
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:134) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.StorageNodeModule)
  while locating io.druid.segment.loading.SegmentLoaderConfig
    for the 2nd parameter of io.druid.segment.loading.SegmentLoaderLocalCacheManager.<init>(SegmentLoaderLocalCacheManager.java:68)
  while locating io.druid.segment.loading.SegmentLoaderLocalCacheManager
  at io.druid.guice.LocalDataStorageDruidModule.configure(LocalDataStorageDruidModule.java:54) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.LocalDataStorageDruidModule)
  while locating io.druid.segment.loading.SegmentLoader
    for the 1st parameter of io.druid.server.SegmentManager.<init>(SegmentManager.java:100)
  while locating io.druid.server.SegmentManager
    for the 2nd parameter of io.druid.server.metrics.HistoricalMetricsMonitor.<init>(HistoricalMetricsMonitor.java:48)
  while locating io.druid.server.metrics.HistoricalMetricsMonitor
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  while locating io.druid.java.util.metrics.MonitorScheduler
  at io.druid.server.metrics.MetricsModule.configure(MetricsModule.java:75) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  while locating io.druid.java.util.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

4) Must override the binding for NodeTypeConfig if you want a DruidServerMetadata.
  at io.druid.guice.StorageNodeModule.getMetadata(StorageNodeModule.java:56) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.StorageNodeModule)
  at io.druid.guice.StorageNodeModule.getMetadata(StorageNodeModule.java:56) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.StorageNodeModule)
  while locating io.druid.server.coordination.DruidServerMetadata
    for the 1st parameter of io.druid.server.coordination.BatchDataSegmentAnnouncer.<init>(BatchDataSegmentAnnouncer.java:84)
  at io.druid.guice.AnnouncerModule.configure(AnnouncerModule.java:45) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.AnnouncerModule)
  while locating io.druid.server.coordination.BatchDataSegmentAnnouncer
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:133) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.AnnouncerModule)
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:133) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.AnnouncerModule)
  while locating com.google.common.base.Supplier<io.druid.server.coordination.DataSegmentAnnouncerProvider>
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:134) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.AnnouncerModule)
  while locating io.druid.server.coordination.DataSegmentAnnouncerProvider
  while locating io.druid.server.coordination.DataSegmentAnnouncer
    for the 3rd parameter of io.druid.server.coordination.SegmentLoadDropHandler.<init>(SegmentLoadDropHandler.java:107)
  at io.druid.server.coordination.SegmentLoadDropHandler.class(SegmentLoadDropHandler.java:72)
  while locating io.druid.server.coordination.SegmentLoadDropHandler
    for the 3rd parameter of io.druid.server.metrics.HistoricalMetricsMonitor.<init>(HistoricalMetricsMonitor.java:48)
  while locating io.druid.server.metrics.HistoricalMetricsMonitor
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  while locating io.druid.java.util.metrics.MonitorScheduler
  at io.druid.server.metrics.MetricsModule.configure(MetricsModule.java:75) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  while locating io.druid.java.util.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

5) Must override the binding for NodeTypeConfig if you want a DruidServerMetadata.
  at io.druid.guice.StorageNodeModule.getMetadata(StorageNodeModule.java:56) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.StorageNodeModule)
  at io.druid.guice.StorageNodeModule.getMetadata(StorageNodeModule.java:56) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.StorageNodeModule)
  while locating io.druid.server.coordination.DruidServerMetadata
    for the 1st parameter of io.druid.server.coordination.CuratorDataSegmentServerAnnouncer.<init>(CuratorDataSegmentServerAnnouncer.java:55)
  while locating io.druid.server.coordination.CuratorDataSegmentServerAnnouncer
  at io.druid.guice.AnnouncerModule.configure(AnnouncerModule.java:46) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.AnnouncerModule)
  while locating io.druid.server.coordination.DataSegmentServerAnnouncer
    for the 4th parameter of io.druid.server.coordination.SegmentLoadDropHandler.<init>(SegmentLoadDropHandler.java:107)
  at io.druid.server.coordination.SegmentLoadDropHandler.class(SegmentLoadDropHandler.java:72)
  while locating io.druid.server.coordination.SegmentLoadDropHandler
    for the 3rd parameter of io.druid.server.metrics.HistoricalMetricsMonitor.<init>(HistoricalMetricsMonitor.java:48)
  while locating io.druid.server.metrics.HistoricalMetricsMonitor
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  while locating io.druid.java.util.metrics.MonitorScheduler
  at io.druid.server.metrics.MetricsModule.configure(MetricsModule.java:75) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.metrics.MetricsModule)
  while locating io.druid.java.util.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

5 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:421)
	at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:62)
	at io.druid.cli.ServerRunnable.run(ServerRunnable.java:49)
	at io.druid.cli.Main.main(Main.java:116)
2018-06-07T09:43:33,032 INFO [main] io.druid.guice.PropertiesModule - Loading properties from common.runtime.properties
2018-06-07T09:43:33,039 INFO [main] io.druid.guice.PropertiesModule - Loading properties from runtime.properties
2018-06-07T09:43:33,158 INFO [main] org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
```

But I surly have configs like below in `conf-quickstart/druid/historical/runtime.properties `
```
# Segment storage
druid.segmentCache.locations=[{"path":"var/druid/segment-cache","maxSize":300000000000}]
druid.server.maxSize=300000000000
```
I could not figure out why this error happen, could you guys help me with this?

**Comment by shivtools** [comment]
@regardfs did you figure out a fix for this issue?

**Comment by abhijain1351** [comment]
For which service is this happening?
Coordinator or historical?

**Comment by ankitatreja-z** [comment]
@abhijain1351 same happening for me on coordinator and overlord. Probably HistoricalMetricsMonitor only works on historical node only. In that case is it possible to specify common monitors in common properties and HistoricalMetricMonitor in historical's runtime.properties and all monitors from these 2 files will be loaded

**Comment by abhijain1351** [comment]
You can specify the necessary metric monitors in the runtime.properties for historical and broker service seperately
