### ISSUE TITLE
Faulty channel in resource pool

### ISSUE THREAD

**Issue by QubitPi** [apache/druid#6043]
We keep getting inconsistent query error of "org.jboss.netty.channel.ChannelException: Faulty channel in resource pool".

Looks like this comes from `NettyHttpClient`. Is it because netty has capacity limit on the number of async requests? Or what could be other causes?

**Comment by huanzhang** [comment]
I also got this when I ran sql from hive.

**Comment by achelimed** [comment]
Hello,

I have the same problem with Hive 2.3.x from AWS EMR 5.13

Have you an idea please?

**Comment by QubitPi** [comment]
We concluded that the cause is we had extremely high memory usage on heap, causing GC-pauses to over-kill Druid process resources. We decided to optimize by reducing memory footprint and it seemed to help in our application.

**Comment by achelimed** [comment]
Problem resolved into druid runtime config by setting `druid.host` property value to ip address instead of `localhost` or dns not reached from hive (like in case of HDP with sandbox-hdp.hortonworks.com hostname).

**Comment by mlubavin-vg** [comment]
Happening to us as well, couple times a day, connecting from broker to middle manager.  Our exception though is "connection refused":

```Failure getting results for query[8015958b-de01-4242-9ef4-6c39eff9407e] url[http://ip-10-0-5-135.ec2.internal:20003/druid/v2/] because of [org.jboss.netty.channel.ChannelException: Faulty channel in resource pool]
Caused by: java.net.ConnectException: Connection refused: ip-10-0-5-135.ec2.internal/10.0.5.135:20003
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_191]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_191]
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.6.Final.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
        ... 1 more```

**Comment by rafitadiaz** [comment]
A quick comment to see if this can be useful for someone having this problem. 

We got the same issue today in our druid cluster. After some research we discover that one of the data nodes was announcing itself with a wrong ip.

We use puppet to populate the conf file when the node is created. We think now that the instance was rebooted and the ip changed but the conf file was not updated.

So the instance now had the `10.132.0.3` but was announcing itself using the old ip `10.132.0.51` and all the queries failed with this:

```java
Caused by: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: /10.132.0.51:8083
...
2020-03-25T11:11:58,709 WARN [DruidSchema-Cache-0] org.apache.druid.sql.calcite.schema.DruidSchema - Metadata refresh failed, trying again soon.
org.apache.druid.query.QueryInterruptedException: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
```

**Comment by yachShekhar** [comment]
> Problem resolved into druid runtime config by setting `druid.host` property value to ip address instead of `localhost` or dns not reached from hive (like in case of HDP with sandbox-hdp.hortonworks.com hostname).

@achelimed 
I am using Druid-21 and and zookeeper 3.6 and facing the above issue
```
Caused by: org.apache.hive.druid.org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
	at org.apache.hive.druid.com.metamx.http.client.NettyHttpClient.go(NettyHttpClient.java:137)
	at org.apache.hive.druid.com.metamx.http.client.AbstractHttpClient.go(AbstractHttpClient.java:14)
	at org.apache.hadoop.hive.druid.DruidStorageHandlerUtils.submitRequest(DruidStorageHandlerUtils.java:194)
	... 30 more
Caused by: java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:101)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
```
I have to use SSL connection so changing to IP is throwing certificate issue. Whereas using DNS throws above problem.
But same configuration is working with Druid 0.19.0 and zookeeper 3.4

Any help is appreciated
