### ISSUE TITLE
With latest version of druid is it possible to use OpenStack Swift custom implementation (not Amazon S3)?

### ISSUE THREAD

**Issue by anantmf** [apache/druid#6980]
With latest version of druid is it possible to use OpenStack Swift custom implementation (not Amazon S3) as a deep storage?
I am having some issue in setting up this, so wanted to check if this is supported or not before asking further questions.

Just FYI, following properties I am setting

druid.s3.endpoint.url=custom url
druid.storage.type=s3
druid.storage.bucket=bucket
druid.storage.baseKey=druid/segments
druid.s3.accessKey=actual key
druid.s3.secretKey=key

**Comment by jihoonson** [comment]
Hi @anantmf, it should work if you use S3 compatible API for Swift.

**Comment by jihoonson** [comment]
If you want to use `http`, you may need https://github.com/apache/incubator-druid/pull/6954.

**Comment by anantmf** [comment]
Hi @jihoonson , Thanks for the reply. I found couple of configuration issues after which I was able to make it work. So now segments are correctly stored in Swift, however when Historical is trying to get it back from Deep storage it fails.

I think the issue is
https://github.com/apache/incubator-druid/pull/5382#discussion_r175933001

When it is doing ListObjectsV2Request, i tried to debug the code and the response actually has object summary but KeyCount is Zero. Which is causing it to fail.
I tried to debug the code of unmarshalling of List object result, and it seems the Unmarshaller expects the response to have a element called as KeyCount then only it sets it in the result object, otherwise it stays zero.

This is the actual log I get:
2019-02-02T15:04:19,789 ERROR [ZkCoordinator] org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager - Failed to load segment in current location /data/projects/imply-2.8.9/var/druid/segment-cache, try next location if any: {class=org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager, exceptionType=class org.apache.druid.segment.loading.SegmentLoadingException, exceptionMessage=Cannot find object for bucket[test4] and key[druid/segments/Consumer_Complaints/2016-01-01T00:00:00.000Z_2017-01-01T00:00:00.000Z/2019-02-02T15:03:18.693Z/0/index.zip], location=/data/projects/imply-2.8.9/var/druid/segment-cache}
org.apache.druid.segment.loading.SegmentLoadingException: Cannot find object for bucket[test4] and key[druid/segments/Consumer_Complaints/2016-01-01T00:00:00.000Z_2017-01-01T00:00:00.000Z/2019-02-02T15:03:18.693Z/0/index.zip]
	at org.apache.druid.storage.s3.S3DataSegmentPuller.getSegmentFiles(S3DataSegmentPuller.java:139) ~[?:?]
	at org.apache.druid.storage.s3.S3LoadSpec.loadSegment(S3LoadSpec.java:60) ~[?:?]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadInLocation(SegmentLoaderLocalCacheManager.java:200) ~[druid-server-0.13.0-incubating-iap6-SNAPSHOT.jar:0.13.0-incubating-iap6-SNAPSHOT]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadInLocationWithStartMarker(SegmentLoaderLocalCacheManager.java:188) ~[druid-server-0.13.0-incubating-iap6-SNAPSHOT.jar:0.13.0-incubating-iap6-SNAPSHOT]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadSegmentWithRetry(SegmentLoaderLocalCacheManager.java:151) [

**Comment by jihoonson** [comment]
Thank you for the investigation! I haven’t expected that such case would happen. Would you please raise a PR to fix it? I think we can check the size of objectSummaries instead of keyCount.

**Comment by anantmf** [comment]
@jihoonson Raised a PR https://github.com/apache/incubator-druid/pull/7000
This is my first OpenSource PR, so let me know if anything I have missed.

**Comment by MrMoronIV** [comment]
May I ask what you've used for connecting Druid to Swift? I can't find anything about it in the documentation.

Is it supposed to work using the S3 compatible API?
