### ISSUE TITLE
druid in Ambari coordinator and overlord port not listen

### ISSUE THREAD

**Issue by hueiyuanSu** [apache/druid#7432]
Hello! Everyone.
I install druid with Ambari. Then,My metadata storage is mysql.
When I installed druid , everything seems like ok!
But I found coordinator and overlord port not listen.
In addition, I have check my firewall setting is ok.

following is my error:
-------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/common-services/DRUID/0.10.1/package/scripts/service_check.py", line 44, in <module>
    ServiceCheck().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 375, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/common-services/DRUID/0.10.1/package/scripts/service_check.py", line 30, in service_check
    self.checkComponent(params, "druid_coordinator", "druid-coordinator")
  File "/var/lib/ambari-agent/cache/common-services/DRUID/0.10.1/package/scripts/service_check.py", line 40, in checkComponent
    logoutput=True)
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 262, in action_run
    tries=self.resource.tries, try_sleep=self.resource.try_sleep)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 303, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of 'curl -s -o /dev/null -w'%{http_code}' --negotiate -u: -k ip-172-31-0-167.ap-northeast-1.compute.internal:8081/status | grep 200' returned 1.
-------------------------------------------------

Then, when I change metadata storage to derby that it can work!
Does anyone know this problem.
I don't know how to solve it !
Please someone can help me.

**Comment by vogievetsky** [comment]
If changing the metadata storage to derby fixes the issue it is likely not a network issue but rather an issue with you metadata store. How was it installed?
