### ISSUE TITLE
[materialized view] IOException: user supplied segments list did not match with segments list obtained from db

### ISSUE THREAD

**Issue by mihai-cazacu-adswizz** [apache/druid#7510]
### Affected Version

`0.13.0-incubating`

### Description

I'm trying to create a materialized view and, for a few days, everything went well with this process (a good part of the segments has been created). In the last hours, the indexing job that creates the view has started to throw this error:

```
2019-04-19T06:23:13,538 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.common.task.HadoopIndexTask - Encountered exception in run():
java.io.IOException: user supplied segments list did not match with segments list obtained from db
	at org.apache.druid.indexer.HadoopIngestionSpec.updateSegmentListIfDatasourcePathSpecIsUsed(HadoopIngestionSpec.java:194) ~[druid-indexing-hadoop-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.common.task.HadoopIndexTask.runInternal(HadoopIndexTask.java:265) ~[druid-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.common.task.HadoopIndexTask.run(HadoopIndexTask.java:232) [druid-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:421) [druid-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:393) [druid-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```
(The error is related to the last segment - the oldest one - from the base data source; the other ones have been ingested.)

How can we fix this?
Thank you!

**Comment by mihai-cazacu-adswizz** [comment]
@zhangxinyu1: Can you take a look at this, please?

**Comment by zhangxinyu1** [comment]
We should find out the difference between segments list in db and the segments list of the hadoop-indexing-task. Could you please add some logs in the method `updateSegmentListIfDatasourcePathSpecIsUsed()` of `HadoopIngestionSpec.java`?

**Comment by mihai-cazacu-adswizz** [comment]
I've added some logs:

```
if (segmentsList.size() == userSuppliedSegmentsList.size()) {
  Set<DataSegment> segmentsSet = new HashSet<>(segmentsList);

  for (DataSegment userSegment : userSuppliedSegmentsList) {
    if (!segmentsSet.contains(userSegment)) {
      log.error("Segment %s is not present in %s",
              userSegment,
              segmentsSet.stream()
                      .map(DataSegment::toString)
                      .collect(Collectors.joining(","))
      );
      throw new IOException("user supplied segments list did not match with segments list obtained from db");
    }
  }
} else {
  log.error("Different segment size: %d != %d", segmentsList.size(), userSuppliedSegmentsList.size());
  throw new IOException("user supplied segments list did not match with segments list obtained from db");
}
```

and this is the error message:

```
2019-04-22T13:15:22,551 ERROR [task-runner-0-priority-0] org.apache.druid.indexer.HadoopIngestionSpec - Different segment size: 37 != 7
2019-04-22T13:15:22,551 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.common.task.HadoopIndexTask - Encountered exception in run():
java.io.IOException: user supplied segments list did not match with segments list obtained from db
	at org.apache.druid.indexer.HadoopIngestionSpec.updateSegmentListIfDatasourcePathSpecIsUsed(HadoopIngestionSpec.java:204) ~[druid-indexing-hadoop-0.13.1-incubating-SNAPSHOT.jar:0.13.1-incubating-SNAPSHOT]
	at org.apache.druid.indexing.common.task.HadoopIndexTask.runInternal(HadoopIndexTask.java:265) ~[druid-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.common.task.HadoopIndexTask.run(HadoopIndexTask.java:232) [druid-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:421) [druid-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:393) [druid-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

In Aurora I've found `7` rows by running:

```
SELECT *
FROM druid_segments
WHERE
    dataSource = "the-data-source"
    AND start  = "2018-01-29T00:00:00.000Z"
    AND end    = "2018-02-05T00:00:00.000Z";
```

which is the number specified by the aforementioned exception.

The S3 is also containing `7` files:
```
aws s3 ls --profile meru-prod s3://.../segments/the-data-source/2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z/2018-05-24T09:30:16.545Z/
                           PRE 0/
                           PRE 1/
                           PRE 2/
                           PRE 3/
                           PRE 4/
                           PRE 5/
                           PRE 6/
```

I don't know yet why `segmentsList` has `37` elements.

**Comment by mihai-cazacu-adswizz** [comment]
The Overlord is also showing `7` segments for the base data surce:

`7 segments (3.62 GB) for 2018-01-29T00 to 2018-02-05T00`

**Comment by mihai-cazacu-adswizz** [comment]
The spec (which contains 7 segments):

```
{
  "payload": {
    "classpathPrefix": null,
    "context": {
      "maxTaskCount": 1,
      "minDataLagMs": 172800000
    },
    "dataSource": "...",
    "groupId": "...",
    "hadoopDependencyCoordinates": [
      "org.apache.hadoop:hadoop-client:2.7.3"
    ],
    "id": "the-id",
    "resource": {
      "availabilityGroup": "...",
      "requiredCapacity": 1
    },
    "spec": {
      "dataSchema": {
        "dataSource": "...",
        "granularitySpec": {
          "intervals": [
            "2018-01-29T00:00:00.000Z/2018-02-05T00:00:00.000Z"
          ],
          "queryGranularity": {
            "type": "none"
          },
          "rollup": true,
          "type": "arbitrary"
        },
        "metricsSpec": [
			...
        ],
        "parser": {
          "parseSpec": {
            "dimensionsSpec": {
              "dimensionExclusions": [],
              "dimensions": [
                ...
              ]
            },
            "format": "timeAndDims"
          },
          "type": "map"
        },
        "transformSpec": {
          "filter": null,
          "transforms": []
        }
      },
      "ioConfig": {
        "inputSpec": {
          "ingestionSpec": {
            "dataSource": "...",
            "dimensions": null,
            "filter": null,
            "ignoreWhenNoSegments": false,
            "intervals": [
              "2018-01-29T00:00:00.000Z/2018-02-05T00:00:00.000Z"
            ],
            "metrics": null,
            "segments": [
              {
                "binaryVersion": 9,
                "dataSource": "...,
                "dimensions": "...",
                "identifier": "...2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z",
                "interval": "2018-01-29T00:00:00.000Z/2018-02-05T00:00:00.000Z",
                "loadSpec": {
                  "S3Schema": "s3n",
                  "bucket": "...",
                  "key": ".../2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z/2018-05-24T09:30:16.545Z/0/index.zip",
                  "type": "s3_zip"
                },
                "metrics": "...",
                "shardSpec": {
                  "partitionNum": 0,
                  "partitions": 7,
                  "type": "numbered"
                },
                "size": 497736710,
                "version": "2018-05-24T09:30:16.545Z"
              },
              {
                "binaryVersion": 9,
                "dataSource": "...,
                "dimensions": "...",
                "identifier": "...2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_1",
                "interval": "2018-01-29T00:00:00.000Z/2018-02-05T00:00:00.000Z",
                "loadSpec": {
                  "S3Schema": "s3n",
                  "bucket": "...",
                  "key": ".../2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z/2018-05-24T09:30:16.545Z/1/index.zip",
                  "type": "s3_zip"
                },
                "metrics": "...",
                "shardSpec": {
                  "partitionNum": 1,
                  "partitions": 7,
                  "type": "numbered"
                },
                "size": 533520591,
                "version": "2018-05-24T09:30:16.545Z"
              },
              {
                "binaryVersion": 9,
                "dataSource": "...,
                "dimensions": "...",
                "identifier": "...2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_2",
                "interval": "2018-01-29T00:00:00.000Z/2018-02-05T00:00:00.000Z",
                "loadSpec": {
                  "S3Schema": "s3n",
                  "bucket": "...",
                  "key": ".../2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z/2018-05-24T09:30:16.545Z/2/index.zip",
                  "type": "s3_zip"
                },
                "metrics": "...",
                "shardSpec": {
                  "partitionNum": 2,
                  "partitions": 7,
                  "type": "numbered"
                },
                "size": 509401366,
                "version": "2018-05-24T09:30:16.545Z"
              },
              {
                "binaryVersion": 9,
                "dataSource": "...,
                "dimensions": "...",
                "identifier": "...2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_3",
                "interval": "2018-01-29T00:00:00.000Z/2018-02-05T00:00:00.000Z",
                "loadSpec": {
                  "S3Schema": "s3n",
                  "bucket": "...",
                  "key": ".../2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z/2018-05-24T09:30:16.545Z/3/index.zip",
                  "type": "s3_zip"
                },
                "metrics": "...",
                "shardSpec": {
                  "partitionNum": 3,
                  "partitions": 7,
                  "type": "numbered"
                },
                "size": 499634299,
                "version": "2018-05-24T09:30:16.545Z"
              },
              {
                "binaryVersion": 9,
                "dataSource": "...,
                "dimensions": "...",
                "identifier": "...2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_4",
                "interval": "2018-01-29T00:00:00.000Z/2018-02-05T00:00:00.000Z",
                "loadSpec": {
                  "S3Schema": "s3n",
                  "bucket": "...",
                  "key": ".../2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z/2018-05-24T09:30:16.545Z/4/index.zip",
                  "type": "s3_zip"
                },
                "metrics": "...",
                "shardSpec": {
                  "partitionNum": 4,
                  "partitions": 7,
                  "type": "numbered"
                },
                "size": 536469931,
                "version": "2018-05-24T09:30:16.545Z"
              },
              {
                "binaryVersion": 9,
                "dataSource": "...,
                "dimensions": "...",
                "identifier": "...2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_5",
                "interval": "2018-01-29T00:00:00.000Z/2018-02-05T00:00:00.000Z",
                "loadSpec": {
                  "S3Schema": "s3n",
                  "bucket": "...",
                  "key": ".../2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z/2018-05-24T09:30:16.545Z/5/index.zip",
                  "type": "s3_zip"
                },
                "metrics": "...",
                "shardSpec": {
                  "partitionNum": 5,
                  "partitions": 7,
                  "type": "numbered"
                },
                "size": 531237597,
                "version": "2018-05-24T09:30:16.545Z"
              },
              {
                "binaryVersion": 9,
                "dataSource": "...,
                "dimensions": "...",
                "identifier": "...2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_6",
                "interval": "2018-01-29T00:00:00.000Z/2018-02-05T00:00:00.000Z",
                "loadSpec": {
                  "S3Schema": "s3n",
                  "bucket": "...",
                  "key": ".../2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z/2018-05-24T09:30:16.545Z/6/index.zip",
                  "type": "s3_zip"
                },
                "metrics": "...",
                "shardSpec": {
                  "partitionNum": 6,
                  "partitions": 7,
                  "type": "numbered"
                },
                "size": 516432248,
                "version": "2018-05-24T09:30:16.545Z"
              }
            ],
            "transformSpec": {
              "filter": null,
              "transforms": []
            }
          },
          "type": "dataSource"
        },
        "metadataUpdateSpec": null,
        "segmentOutputPath": null,
        "type": "hadoop"
      },
      "tuningConfig": {
        "allowedHadoopPrefix": [],
        "buildV9Directly": true,
        "cleanupOnFailure": true,
        "combineText": false,
        "forceExtendableShardSpecs": false,
        "ignoreInvalidRows": false,
        "indexSpec": {
          "bitmap": {
            "type": "concise"
          },
          "dimensionCompression": "lz4",
          "longEncoding": "longs",
          "metricCompression": "lz4"
        },
        "jobProperties": {
          "fs.s3.impl": "org.apache.hadoop.fs.s3native.NativeS3FileSystem",
          "fs.s3n.impl": "org.apache.hadoop.fs.s3native.NativeS3FileSystem",
          "io.compression.codecs": "org.apache.hadoop.io.compress.GzipCodec,org.apache.hadoop.io.compress.DefaultCodec,org.apache.hadoop.io.compress.BZip2Codec,org.apache.hadoop.io.compress.SnappyCodec",
          "mapreduce.job.classloader": "true"
        },
        "leaveIntermediate": false,
        "logParseExceptions": false,
        "maxBytesInMemory": 0,
        "maxParseExceptions": 0,
        "maxRowsInMemory": 1000000,
        "numBackgroundPersistThreads": 0,
        "overwriteFiles": false,
        "partitionsSpec": {
          "assumeGrouped": false,
          "maxPartitionSize": -1,
          "numShards": -1,
          "partitionDimensions": [],
          "targetPartitionSize": -1,
          "type": "hashed"
        },
        "shardSpecs": {},
        "type": "hadoop",
        "useCombiner": false,
        "useExplicitVersion": true,
        "version": "2018-05-24T10:24:35.928Z",
        "workingPath": null
      },
      "uniqueId": "17123d0ad0da4a56b43beb56670a3af1"
    },
    "type": "index_hadoop"
  },
  "task": "..."
}
```

**Comment by zhangxinyu1** [comment]
The value of `segmentsList.size()` is 37. Could you please print these segment ids?

**Comment by mihai-cazacu-adswizz** [comment]
For an unknown reason, the last month (`2018-01-29`) contains segments both from January and February:

```
...
2018-02-01T00 | 30 | 21.7 GB
2018-01-29T00 |  7 | 3.62 GB
...
```

```
30 segments (21.7 GB) for 2018-02-01T00 to 2018-03-01T00

the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_1
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_10
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_11
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_12
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_13
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_14
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_15
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_16
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_17
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_18
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_19
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_2
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_20
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_21
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_22
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_23
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_24
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_25
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_26
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_27
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_28
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_29
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_3
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_4
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_5
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_6
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_7
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_8
the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_9
```

```
7 segments (3.62 GB) for 2018-01-29T00 to 2018-02-05T00

the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z
the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_1
the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_2
the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_3
the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_4
the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_5
the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_6
```
and, because of this, we are receiving that `segmentsList.size()` is `37` (`30` + `7`).

It remains to reingest that month and I'll come with the results. Thank you, @zhangxinyu1!

**Comment by NoahSheep** [comment]
> 出于未知原因，最后一个月（`2018-01`）包含来自一月和二月的细分：
> 
> ```
> ...
> 2018-02-01T00 | 30 | 21.7 GB
> 2018-01-29T00 |  7 | 3.62 GB
> ...
> ```
> 
> ```
> 30 segments (21.7 GB) for 2018-02-01T00 to 2018-03-01T00
> 
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_1
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_10
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_11
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_12
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_13
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_14
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_15
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_16
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_17
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_18
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_19
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_2
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_20
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_21
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_22
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_23
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_24
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_25
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_26
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_27
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_28
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_29
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_3
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_4
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_5
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_6
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_7
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_8
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_9
> ```
> 
> ```
> 7 segments (3.62 GB) for 2018-01-29T00 to 2018-02-05T00
> 
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_1
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_2
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_3
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_4
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_5
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_6
> ```
> 
> 因此，我们收到的`segmentsList.size()`是`37`（`30`+ `7`）。
> 
> 那个月还有待解决，我会给出结果。谢谢@ zhangxinyu1！

Hi,

> For an unknown reason, the last month (`2018-01`) contains segments from both January and February:
> 
> ```
> ...
> 2018-02-01T00 | 30 | 21.7 GB
> 2018-01-29T00 |  7 | 3.62 GB
> ...
> ```
> 
> ```
> 30 segments (21.7 GB) for 2018-02-01T00 to 2018-03-01T00
> 
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_1
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_10
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_11
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_12
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_13
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_14
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_15
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_16
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_17
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_18
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_19
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_2
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_20
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_21
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_22
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_23
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_24
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_25
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_26
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_27
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_28
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_29
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_3
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_4
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_5
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_6
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_7
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_8
> the-datasource-druid_2018-02-01T00:00:00.000Z_2018-03-01T00:00:00.000Z_2018-09-05T13:21:49.297Z_9
> ```
> 
> ```
> 7 segments (3.62 GB) for 2018-01-29T00 to 2018-02-05T00
> 
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_1
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_2
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_3
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_4
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_5
> the-datasource-druid_2018-01-29T00:00:00.000Z_2018-02-05T00:00:00.000Z_2018-05-24T09:30:16.545Z_6
> ```
> 
> and, because of this, we are receiving that `segmentsList.size()` is `37` (`30` + `7`).
> 
> It remains to reingest that month and I'll come with the results. Thank you, @zhangxinyu1!

Has Druid solved this problem yet?
