### ISSUE TITLE
0.14-incubation: Coordinator failed to start because of the CDI BeanManager is not available. JAX-RS CDI support is disabled 

### ISSUE THREAD

**Issue by havannavar** [apache/druid#7519]
I downloaded the new version of **0.14-incubation** and started setting up similar to the 0.13-incubation, on a single cluster machine, but fails with error CDI Bean manager not available . 

### Affected Version
0.14.0-incubating

### Description
This is my configuration

```

#
# Extensions
#

druid.extensions.loadList=[ "druid-kafka-indexing-service", "druid-s3-extensions", "postgresql-metadata-storage"]

#
# Logging
#

# Log all runtime properties on startup. Disable to avoid logging properties on startup:
druid.startup.logging.logProperties=true

#
# Hostname
#
druid.host=<ip>

#
# Zookeeper
#

druid.zk.service.host=<zk-host>
druid.zk.paths.base=/druid

#
# Metadata storage
#

# For PostgreSQL (make sure to additionally include the Postgres extension):
druid.metadata.storage.type=postgresql
druid.metadata.storage.connector.connectURI=jdbc:postgresql://my.domain.com:5432/druid
druid.metadata.storage.connector.user=abc
druid.metadata.storage.connector.password=abc

#
# Deep storage
#

# For S3:
druid.storage.type=s3
druid.storage.bucket=events
druid.storage.baseKey=druid/segments
druid.s3.accessKey=asd
druid.s3.secretKey=acbdge

#
# Indexing service logs
#

# For S3:
druid.indexer.logs.type=s3
druid.indexer.logs.s3Bucket=events
druid.indexer.logs.s3Prefix=druid/indexing-logs

#
# Service discovery
#

druid.selectors.indexing.serviceName=druid/overlord
druid.selectors.coordinator.serviceName=druid/coordinator

#
# Monitoring
#

druid.monitoring.monitors=["org.apache.druid.java.util.metrics.JvmMonitor"]
druid.emitter=logging
druid.emitter.logging.logLevel=debug

# Storage type of double columns
# ommiting this will lead to index double as float at the storage layer

druid.indexing.doubleStorage=double

#
# SQL
#
druid.sql.enable=true
```
and the docker file is

```
FROM openjdk:8-jre

MAINTAINER Sateesh H

RUN mkdir -p /opt/

RUN apt-get update && apt-get install -y libtest-www-mechanize-perl

# add (the rest of) our code
COPY . /opt/

RUN mkdir log && \
	mkdir -p opt/tmp && \
	mkdir -p opt/druid/indexing-logs && \
	mkdir -p opt/druid/segments && \
	mkdir -p opt/druid/segment-cache && \
	mkdir -p opt/druid/task && \
	mkdir -p opt/druid/hadoop-tmp && \
	mkdir -p opt/druid/pids && \
	mkdir -p _config/common && \
	mkdir -p _config/specific


EXPOSE 8081
EXPOSE 8082
EXPOSE 8083
EXPOSE 8090
EXPOSE 3306
EXPOSE 2181
EXPOSE 8888

CMD /opt/druid/bin/supervise -c /opt/druid/conf/druid-cluster.conf
```
The above configuration creates 10tables in the postgres database.

Though I can see console 
![druid_console](https://user-images.githubusercontent.com/1104650/56453348-f03b3b00-635e-11e9-8046-02b938d4854e.png)

But, able to see following error in coordinator, overlord services.

```
2019-04-21T13:59:26,683 INFO [LeaderSelector[/druid/coordinator/_COORDINATOR]] org.apache.druid.common.config.ConfigManager - Creating watch for key[coordinator.config]
2019-04-21T13:59:26,694 INFO [LeaderSelector[/druid/coordinator/_COORDINATOR]] org.apache.druid.server.coordinator.DruidCoordinator - Done making indexing service helpers [[org.apache.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader, org.apache.druid.server.coordinator.helper.DruidCoordinatorSegmentCompactor]]
2019-04-21T13:59:26,694 DEBUG [LeaderSelector[/druid/coordinator/_COORDINATOR]] org.apache.druid.java.util.common.concurrent.ScheduledExecutors - Scheduling repeatedly: org.apache.druid.server.coordinator.DruidCoordinator$2@58bc0ca9 with delay PT30S
2019-04-21T13:59:26,705 DEBUG [LeaderSelector[/druid/coordinator/_COORDINATOR]] org.apache.druid.java.util.common.concurrent.ScheduledExecutors - Scheduling repeatedly: org.apache.druid.server.coordinator.DruidCoordinator$2@54166a72 with delay PT1800S
2019-04-21T13:59:26,703 CONFIG [main] com.sun.jersey.server.impl.ejb.EJBComponentProviderFactoryInitilizer - The EJB interceptor binding API is not available. JAX-RS EJB support is disabled.
javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:662) ~[?:1.8.0_191]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[?:1.8.0_191]
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:350) ~[?:1.8.0_191]
	at javax.naming.InitialContext.lookup(InitialContext.java:417) ~[?:1.8.0_191]
	at com.sun.jersey.server.impl.ejb.EJBComponentProviderFactoryInitilizer.initialize(EJBComponentProviderFactoryInitilizer.java:64) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.WebComponent.configure(WebComponent.java:570) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.configure(ServletContainer.java:332) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:604) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577) [jersey-servlet-1.19.3.jar:1.19.3]
	at javax.servlet.GenericServlet.init(GenericServlet.java:244) [javax.servlet-api-3.1.0.jar:3.1.0]
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:120) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:103) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:226) [guice-servlet-4.1.0.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:139) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:741) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:403) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.Server.start(Server.java:419) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.Server.doStart(Server.java:386) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.apache.druid.server.initialization.jetty.JettyServerModule$2.start(JettyServerModule.java:397) [druid-server-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:323) [druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.guice.LifecycleModule$2.start(LifecycleModule.java:138) [druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:107) [druid-services-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:58) [druid-services-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.cli.Main.main(Main.java:118) [druid-services-0.14.0-incubating.jar:0.14.0-incubating]
2019-04-21T13:59:26,708 CONFIG [main] com.sun.jersey.server.impl.cdi.CDIComponentProviderFactoryInitializer - The CDI BeanManager is not available at java:comp/BeanManager
javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:662) ~[?:1.8.0_191]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[?:1.8.0_191]
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:350) ~[?:1.8.0_191]
	at javax.naming.InitialContext.lookup(InitialContext.java:417) ~[?:1.8.0_191]
	at com.sun.jersey.server.impl.cdi.CDIComponentProviderFactoryInitializer.lookupInJndi(CDIComponentProviderFactoryInitializer.java:110) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.cdi.CDIComponentProviderFactoryInitializer.lookup(CDIComponentProviderFactoryInitializer.java:83) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.cdi.CDIComponentProviderFactoryInitializer.initialize(CDIComponentProviderFactoryInitializer.java:70) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.WebComponent.configure(WebComponent.java:572) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.configure(ServletContainer.java:332) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:604) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577) [jersey-servlet-1.19.3.jar:1.19.3]
	at javax.servlet.GenericServlet.init(GenericServlet.java:244) [javax.servlet-api-3.1.0.jar:3.1.0]
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:120) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:103) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:226) [guice-servlet-4.1.0.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:139) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:741) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:403) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.Server.start(Server.java:419) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.Server.doStart(Server.java:386) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.apache.druid.server.initialization.jetty.JettyServerModule$2.start(JettyServerModule.java:397) [druid-server-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:323) [druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.guice.LifecycleModule$2.start(LifecycleModule.java:138) [druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:107) [druid-services-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:58) [druid-services-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.cli.Main.main(Main.java:118) [druid-services-0.14.0-incubating.jar:0.14.0-incubating]
2019-04-21T13:59:26,711 CONFIG [main] com.sun.jersey.server.impl.cdi.CDIComponentProviderFactoryInitializer - The CDI BeanManager is not available at javax.enterprise.inject.spi.BeanManager
2019-04-21T13:59:26,711 CONFIG [main] com.sun.jersey.server.impl.cdi.CDIComponentProviderFactoryInitializer - The CDI BeanManager is not available at org.jboss.weld.environment.servlet.javax.enterprise.inject.spi.BeanManager
2019-04-21T13:59:26,711 CONFIG [main] com.sun.jersey.server.impl.cdi.CDIComponentProviderFactoryInitializer - The CDI BeanManager is not available. JAX-RS CDI support is disabled.
2019-04-21T13:59:26,712 CONFIG [main] com.sun.jersey.server.impl.managedbeans.ManagedBeanComponentProviderFactoryInitilizer - The managed beans injection manager API is not available. JAX-RS managed beans support is disabled.
javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:662) ~[?:1.8.0_191]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[?:1.8.0_191]
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:350) ~[?:1.8.0_191]
	at javax.naming.InitialContext.lookup(InitialContext.java:417) ~[?:1.8.0_191]
	at com.sun.jersey.server.impl.managedbeans.ManagedBeanComponentProviderFactoryInitilizer.initialize(ManagedBeanComponentProviderFactoryInitilizer.java:65) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.WebComponent.configure(WebComponent.java:576) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.configure(ServletContainer.java:332) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:604) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577) [jersey-servlet-1.19.3.jar:1.19.3]
	at javax.servlet.GenericServlet.init(GenericServlet.java:244) [javax.servlet-api-3.1.0.jar:3.1.0]
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:120) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:103) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:226) [guice-servlet-4.1.0.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:139) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:741) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:403) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.Server.start(Server.java:419) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.server.Server.doStart(Server.java:386) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
	at org.apache.druid.server.initialization.jetty.JettyServerModule$2.start(JettyServerModule.java:397) [druid-server-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:323) [druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.guice.LifecycleModule$2.start(LifecycleModule.java:138) [druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:107) [druid-services-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:58) [druid-services-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.cli.Main.main(Main.java:118) [druid-services-0.14.0-incubating.jar:0.14.0-incubating]
2019-04-21T13:59:26,720 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory - Registering com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider as a provider class
2019-04-21T13:59:26,720 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory - Registering com.fasterxml.jackson.jaxrs.smile.JacksonSmileProvider as a provider class
2019-04-21T13:59:26,721 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory - Registering org.apache.druid.server.initialization.jetty.CustomExceptionMapper as a provider class
2019-04-21T13:59:26,721 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory - Registering org.apache.druid.server.initialization.jetty.ForbiddenExceptionMapper as a provider class

```

Also, while creating datasource, it returns the response of 
`{"id":"event_datasource"}` but no records found in druid_datasource table and doesn't reflect in the console too. Also, index-logs getting created in S3 for every 10mins(I gave that interval in supervisor spec)

@vogievetsky @jon-wei @gianm @egor-ryashin @fjy ; guys can you help me.

Thanks in advance.

**Comment by havannavar** [comment]
I tried debugging, but didn't find the exact reason
either its jar mismatch or I might have missed adding a configuration.

I tried adding `druid.host=<ip>` 
in both common.runtime.properties and also coordinator/runtime.properties, but no luck

**Comment by jon-wei** [comment]
This error doesn't look like it's fatal and your services seem to be up:

```
2019-04-21T13:59:26,712 CONFIG [main] com.sun.jersey.server.impl.managedbeans.ManagedBeanComponentProviderFactoryInitilizer - The managed beans injection manager API is not available. JAX-RS managed beans support is disabled.
```

> {"id":"event_datasource"} but no records found in druid_datasource table

It sounds like the real issue here is some kind of ingestion issue, you could check the task logs and reports (http://druid.io/docs/latest/ingestion/reports.html) for those tasks to see if any events were actually ingested.

**Comment by havannavar** [comment]
Thanks @jon-wei for your response

Below is my datasource spec

```
{
  "type": "kafka",
  "dataSchema": {
    "dataSource": "event_datasource",
    "parser": {
      "type": "string",
      "parseSpec": {
        "format": "json",
        "timestampSpec": {
          "column": "time",
          "format": "auto"
        },
        "dimensionsSpec": {
          "dimensions": [],
          "dimensionExclusions": [
            "timestamp",
            "value"
          ]
        }
      }
    },
    "metricsSpec" : [
      {
        "name": "count",
        "type": "count"
      },
      {
        "name": "value_sum",
        "fieldName": "value",
        "type": "doubleSum"
      },
      {
        "name": "value_min",
        "fieldName": "value",
        "type": "doubleMin"
      },
      {
        "name": "value_max",
        "fieldName": "value",
        "type": "doubleMax"
      }
    ],
    "granularitySpec": {
      "type": "uniform",
      "segmentGranularity": "HOUR",
      "queryGranularity": "NONE",
      "rollup": false
    }
  },
  "tuningConfig": {
    "type": "kafka",
    "reportParseExceptions": false
  },
  "ioConfig": {
    "topic": "event_traffic",
    "replicas": 1,
    "taskDuration": "PT10M",
    "completionTimeout": "PT20M",
    "consumerProperties": {
      "bootstrap.servers": "<ip1>:<port1>,<ip2>:<port2>,<ip3>:<port3>"
    }
  }
}

```

This is the task report after creating datasource and after ingesting message/data via Kafka-ingestion
```
{
	"ingestionStatsAndErrors": {
		"taskId": "index_kafka_event_datasource_25c11ef7d533a4b_ofconddn",
		"payload": {
			"ingestionState": "COMPLETED",
			"unparseableEvents": {},
			"rowStats": {
				"buildSegments": {
					"processed": 0,
					"processedWithError": 0,
					"thrownAway": 0,
					"unparseable": 5
				}
			},
			"errorMsg": null
		},
		"type": "ingestionStatsAndErrors"
	}
}
```

A complete log file of the same.
[index-logfile.log](https://github.com/apache/incubator-druid/files/3105534/index-logfile.log)

**Comment by jon-wei** [comment]
```
	"buildSegments": {
					"processed": 0,
					"processedWithError": 0,
					"thrownAway": 0,
					"unparseable": 5
				}
```

None of the rows are being parsed, so your spec or input probably has issues, try setting `logParseExceptions` and related properties to troubleshoot: http://druid.io/docs/latest/development/extensions-core/kafka-ingestion.html

**Comment by jon-wei** [comment]
The sample you posted is invalid JSON (has an extra comma after the last field), I would double check that:

```
    "userGender" : null,
    "userDOB" : null,
}
```

**Comment by vogievetsky** [comment]
@havannavar did @jon-wei 's suggestion of having your events be on a single line ( http://ndjson.org/ ) work for you?
