### ISSUE TITLE
does druid-0.14 support PreparedStatement?

### ISSUE THREAD

**Issue by shizhengchao** [apache/druid#7916]
Does druid-0.14 support PreparedStatement with 'org.apache.calcite.avatica.remote.Driver' ?
### Affected Version
0.14
### Description
```java
String sql = "SELECT page, COUNT(*) AS Edits FROM wikipedia WHERE __time BETWEEN TIMESTAMP ? AND TIMESTAMP ? GROUP BY page ORDER BY Edits DESC LIMIT 10";
        String url = "jdbc:avatica:remote:url=http://10.204.57.143:8082/druid/v2/sql/avatica/";
        Properties connectionProperties = new Properties();
        try {
            try {
                Class.forName("org.apache.calcite.avatica.remote.Driver");
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }
            Connection connection = DriverManager.getConnection(url, connectionProperties);
            PreparedStatement ps = connection.prepareStatement(sql);
            ps.setString(1, "2015-09-12 00:00:00");
            ps.setString(2, "2015-09-13 00:00:00");
            final ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                System.out.println(rs.getMetaData().getColumnName(1) + ":" + rs.getString(1));
                System.out.println(rs.getMetaData().getColumnName(2) + ":" + rs.getInt(2));

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
```

Running the code gets the following error：
```
org.apache.calcite.avatica.AvaticaSqlException: Error -1 (00000) : while preparing SQL: SELECT page, COUNT(*) AS Edits FROM wikipedia WHERE __time BETWEEN TIMESTAMP ? AND TIMESTAMP ? GROUP BY page ORDER BY Edits DESC LIMIT 10
	at org.apache.calcite.avatica.Helper.createException(Helper.java:54)
	at org.apache.calcite.avatica.Helper.createException(Helper.java:41)
	at org.apache.calcite.avatica.AvaticaConnection.prepareStatement(AvaticaConnection.java:358)
	at org.apache.calcite.avatica.AvaticaConnection.prepareStatement(AvaticaConnection.java:175)
	at com.fcbox.turbo.druid.avatica.SelectDemo.main(SelectDemo.java:25)
java.lang.RuntimeException: org.apache.calcite.sql.parser.SqlParseException: Encountered "TIMESTAMP ?" at line 1, column 68.
Was expecting one of:
    "SYMMETRIC" ...
    "ASYMMETRIC" ...
    "+" ...
```

**Comment by clintropolis** [comment]
Hi @shizhengchao , this functionality is not yet in Druid, but will be added in the future by #6974 which is just waiting on review which I think it should work with your use case.

**Comment by clintropolis** [comment]
#6974 was merged and will be released in upcoming version 0.18, closing this issue

**Comment by archichen** [comment]
same error. I have upgraded to Imply 3.4.3(Druid 0.19.0-iap5), the problem not resolve.

```
org.apache.calcite.avatica.AvaticaSqlException: Error -1 (00000) : while preparing SQL: SELECT * FROM ?
	at org.apache.calcite.avatica.Helper.createException(Helper.java:54)
	at org.apache.calcite.avatica.Helper.createException(Helper.java:41)
	at org.apache.calcite.avatica.AvaticaConnection.prepareStatement(AvaticaConnection.java:358)
	at org.apache.calcite.avatica.AvaticaConnection.prepareStatement(AvaticaConnection.java:175)
	at com.michi.datapublisher.DataPublisherApplicationTest.test(DataPublisherApplicationTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
java.lang.RuntimeException: org.apache.calcite.sql.parser.SqlParseException: Encountered "?" at line 1, column 15.
Was expecting one of:
    "LATERAL" ...
    "TABLE" ...
    "UNNEST" ...
    <IDENTIFIER> ...
    <QUOTED_IDENTIFIER> ...
    <BACK_QUOTED_IDENTIFIER> ...
    <BRACKET_QUOTED_IDENTIFIER> ...
    <UNICODE_QUOTED_IDENTIFIER> ...
    "(" ...```

**Comment by archichen** [comment]
Find out that PreparedStatement can't fill the table name.
