### ISSUE TITLE
SeekableStreamSupervisor failed to handle notice

### ISSUE THREAD

**Issue by RestfulBlue** [apache/druid#8186]
### Affected Version
Druid 0.14.2

### Description
From time to time some of supervisors is being stuck. When we look into logs, there is this error:
```
2019-07-29T09:38:26,766 ERROR [KafkaSupervisor-some_log] org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor - SeekableStreamSupervisor[some_log] failed to handle notice: {class=org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor, exceptionType=class org.apache.druid.java.util.common.IAE, exceptionMessage=Expected instance of org.apache.druid.indexing.seekablestream.SeekableStreamEndSequenceNumbers, got org.apache.druid.indexing.seekablestream.SeekableStreamStartSequenceNumbers, noticeClass=RunNotice}
org.apache.druid.java.util.common.IAE: Expected instance of org.apache.druid.indexing.seekablestream.SeekableStreamEndSequenceNumbers, got org.apache.druid.indexing.seekablestream.SeekableStreamStartSequenceNumbers
	at org.apache.druid.indexing.seekablestream.SeekableStreamEndSequenceNumbers.minus(SeekableStreamEndSequenceNumbers.java:159) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamDataSourceMetadata.minus(SeekableStreamDataSourceMetadata.java:95) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.resetInternal(SeekableStreamSupervisor.java:1173) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.getOffsetFromStorageForPartition(SeekableStreamSupervisor.java:2468) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.generateStartingSequencesForPartitionGroup(SeekableStreamSupervisor.java:2445) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.createNewTasks(SeekableStreamSupervisor.java:2343) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.runInternal(SeekableStreamSupervisor.java:1039) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor$RunNotice.handle(SeekableStreamSupervisor.java:291) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.lambda$tryInit$3(SeekableStreamSupervisor.java:750) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```
After reset of supervisor everything works fine, but after some time it appears again(Usually after cluster restart)  :( 
Is there a way to avoid that?

**Comment by nicopadu** [comment]
seems duplicate of https://github.com/apache/incubator-druid/issues/7926

**Comment by jihoonson** [comment]
@nicopadu thanks for pointing the potentially related issue. 

@RestfulBlue it seems the same issue with #7926 to me. Did you turn on `resetOffsetAutomatically` for your supervisor? If so, https://github.com/apache/incubator-druid/pull/8305 probably will fix this.

**Comment by RestfulBlue** [comment]
@jihoonson Hi, sorry for late response. Yes, we use auto reset. But also we have a problem with #8215 . In some places where we have a lot of data, sometimes we have huge overload(that's okey in that case, we can loss some data here), and as a result we need to reset offsets, but they are not resetting automatically and task is just being stuck :( 
Will #8305 fix it?
