### ISSUE TITLE
druid0.15 with cdh6.2 hadoop3.0

### ISSUE THREAD

**Issue by anonymous-shy** [apache/druid#8278]
guys:
    When I use druid0.15 with cdh6.2 hadoop3.0.0 run a hadoop index, it's failed:
java.lang.NoSuchMethodError: org.apache.hadoop.hdfs.DistributedFileSystem.setErasureCodingPolicy(Lorg/apache/hadoop/fs/Path;Ljava/lang/String;)V
	at org.apache.hadoop.mapreduce.JobResourceUploader.disableErasureCodingForPath(JobResourceUploader.java:882) ~[?:?]
	at org.apache.hadoop.mapreduce.JobResourceUploader.uploadResourcesInternal(JobResourceUploader.java:174) ~[?:?]
	at org.apache.hadoop.mapreduce.JobResourceUploader.uploadResources(JobResourceUploader.java:131) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.copyAndConfigureFiles(JobSubmitter.java:102) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:197) ~[?:?]
	at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1570) ~[?:?]
	at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1567) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_60]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836) ~[?:?]
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1567) ~[?:?]
	at org.apache.druid.indexer.DetermineHashedPartitionsJob.run(DetermineHashedPartitionsJob.java:124) ~[druid-indexing-hadoop-0.15.0-incubating.jar:0.15.0-incubating]
	at org.apache.druid.indexer.JobHelper.runSingleJob(JobHelper.java:384) ~[druid-indexing-hadoop-0.15.0-incubating.jar:0.15.0-incubating]
	at org.apache.druid.indexer.HadoopDruidDetermineConfigurationJob.run(HadoopDruidDetermineConfigurationJob.java:58) ~[druid-indexing-hadoop-0.15.0-incubating.jar:0.15.0-incubating]
	at org.apache.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessingRunner.runTask(HadoopIndexTask.java:617) ~[druid-indexing-service-0.15.0-incubating.jar:0.15.0-incubating]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.apache.druid.indexing.common.task.HadoopIndexTask.runInternal(HadoopIndexTask.java:309) ~[druid-indexing-service-0.15.0-incubating.jar:0.15.0-incubating]
	at org.apache.druid.indexing.common.task.HadoopIndexTask.run(HadoopIndexTask.java:244) [druid-indexing-service-0.15.0-incubating.jar:0.15.0-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:419) [druid-indexing-service-0.15.0-incubating.jar:0.15.0-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:391) [druid-indexing-service-0.15.0-incubating.jar:0.15.0-incubating]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

How should I do?
tks

**Comment by drnushooz** [comment]
What's the classpath for your druid indexer? Checking the `3.0` bracnh of hadoop the class has correct method with signature https://github.com/apache/hadoop/blob/branch-3.0/hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DistributedFileSystem.java#L2626.

**Comment by stelios313** [comment]
Run into same error. Running with 0.15.1 and CDH 6.3
