### ISSUE TITLE
i use druid version0.15.1  add Materialized View ，but in query node:router have exception

### ISSUE THREAD

**Issue by shaoxinye** [apache/druid#8549]
router node has exception :

  2019-09-17T16:30:27,996 WARN [main] org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.apache.druid.client.TimelineServerView was bound.
  while locating org.apache.druid.client.TimelineServerView
    for the 1st parameter of org.apache.druid.query.materializedview.DataSourceOptimizer.<init>(DataSourceOptimizer.java:60)
  at org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule.configure(MaterializedViewSelectionDruidModule.java:55) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule)

1 error
	at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:71)
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:56)
	at org.apache.druid.cli.Main.main(Main.java:118)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.apache.druid.client.TimelineServerView was bound.
  while locating org.apache.druid.client.TimelineServerView
    for the 1st parameter of org.apache.druid.query.materializedview.DataSourceOptimizer.<init>(DataSourceOptimizer.java:60)
  at org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule.configure(MaterializedViewSelectionDruidModule.java:55) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.apache.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:419)
	at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:68)
	... 2 more

**Comment by shaoxinye** [comment]
who can help me?

**Comment by surekhasaharan** [comment]
Hey @shaoxinye it seems you might be missing some hadoop jars. What is there in your `druid.extensions.loadList` ?

**Comment by nutant-h** [comment]
This is happening with me too, just out of the box running the `./bin/start-micro-quickstart` tutorial and getting this error.

**Comment by liguifa** [comment]
I had the same problem.
druid.extensions.loadList=["druid-hdfs-storage", "mysql-metadata-storage", "druid-lookups-cached-global", "druid-kafka-indexing-service", "druid-datasketches", "druid-histogram", "druid-uniq", "materialized-view-maintenance", "materialized-view-selection"]

**Comment by surekhasaharan** [comment]
do you have `"materialized-view-maintenance", "materialized-view-selection"` on all the nodes or in `common.runtime.properties`. [This](https://druid.apache.org/docs/latest/development/extensions-contrib/materialized-view.html) suggests "make sure to only load materialized-view-selection on Broker and load materialized-view-maintenance on Overlord." Also these extensions are not required on router, so you can remove them from your router config.
