### ISSUE TITLE
SQL error: Column '__time' not found in any table

### ISSUE THREAD

**Issue by jinyangli34** [apache/druid#8650]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version
0.13

### Description
https://groups.google.com/forum/#!searchin/druid-user/not$20found$20in$20any$20table%7Csort:date/druid-user/yKZ4XzOTZMY/XjqdmauYBwAJ

Hit the following error with SQL query.
The problem disappeared after restarting broker service.
The same issue happened again after a few days.
Any help is appreciated.

```
2019-09-25T00:33:27,531 ERROR [qtp2061424899-229] org.apache.calcite.runtime.CalciteException - org.apache.calcite.sql.validate.SqlValidatorException: Column '__time' not found in any table
2019-09-25T00:33:27,531 ERROR [qtp2061424899-229] org.apache.calcite.runtime.CalciteException - org.apache.calcite.runtime.CalciteContextException: From line 1, column 225 to line 1, column 232: Column '__time' not found in any table
2019-09-25T00:33:27,531 WARN [qtp2061424899-229] org.apache.druid.sql.http.SqlResource - Failed to handle query: SqlQuery{query='SELECT FLOOR("__time" TO DAY) AS "__timestamp", SUM(google_click_cohorted_positions_total) / SUM(google_click_cohorted_impressions) AS "google_click_cohorted_avg_position" FROM "minerva__google_click_cohorted_metrics" WHERE "__time" >= TIMESTAMP '2019-02-14 00:00:00' AND "__time" <= TIMESTAMP '2019-09-22 00:00:00' GROUP BY FLOOR("__time" TO DAY) ORDER BY SUM(google_click_cohorted_positions_total) / SUM(google_click_cohorted_impressions) DESC LIMIT 10000', resultFormat=OBJECT, header=true, context={}}
org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 1, column 225 to line 1, column 232: Column '__time' not found in any table
 at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:190) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.druid.sql.calcite.planner.DruidPlanner.plan(DruidPlanner.java:124) ~[druid-sql-0.13.0.3.jar:0.13.0.3]
 at org.apache.druid.sql.calcite.planner.DruidPlanner.plan(DruidPlanner.java:97) ~[druid-sql-0.13.0.3.jar:0.13.0.3]
 at org.apache.druid.sql.http.SqlResource.doPost(SqlResource.java:88) [druid-sql-0.13.0.3.jar:0.13.0.3]
 at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
 at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
 at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.19.3.jar:1.19.3]
 at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.19.3.jar:1.19.3]
 at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.19.3.jar:1.19.3]
 at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.19.3.jar:1.19.3]
 at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.19.3.jar:1.19.3]
 at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.19.3.jar:1.19.3]
 at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.19.3.jar:1.19.3]
 at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [jersey-server-1.19.3.jar:1.19.3]
 at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [jersey-server-1.19.3.jar:1.19.3]
 at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.19.3.jar:1.19.3]
 at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.19.3.jar:1.19.3]
 at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [jersey-servlet-1.19.3.jar:1.19.3]
 at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) [jersey-servlet-1.19.3.jar:1.19.3]
 at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) [jersey-servlet-1.19.3.jar:1.19.3]
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
 at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:?]
 at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:?]
 at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:?]
 at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:?]
 at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:?]
 at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:?]
 at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:?]
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.apache.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:84) [druid-server-0.13.0.3.jar:0.13.0.3]
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.apache.druid.server.security.AllowOptionsResourceFilter.doFilter(AllowOptionsResourceFilter.java:76) [druid-server-0.13.0.3.jar:0.13.0.3]
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.apache.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:58) [druid-server-0.13.0.3.jar:0.13.0.3]
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.apache.druid.security.ranger.auth.RangerFilter.doFilter(RangerFilter.java:63) [ranger-extensions-0.13.0.3.jar:0.13.0.3]
 at org.apache.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:60) [druid-server-0.13.0.3.jar:0.13.0.3]
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.apache.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:88) [druid-server-0.13.0.3.jar:0.13.0.3]
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.Server.handle(Server.java:531) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
 at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 225 to line 1, column 232: Column '__time' not found in any table
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
 at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:783) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:768) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4759) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.DelegatingScope.fullyQualify(DelegatingScope.java:259) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5619) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5601) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlIdentifier.accept(SqlIdentifier.java:334) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:134) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:101) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:859) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visitScoped(SqlValidatorImpl.java:5654) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:50) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:33) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:138) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:134) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:101) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:859) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visitScoped(SqlValidatorImpl.java:5654) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:50) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:33) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:138) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.expand(SqlValidatorImpl.java:5208) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validateWhereClause(SqlValidatorImpl.java:3948) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3276) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:967) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:943) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:225) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:918) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:628) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:188) ~[calcite-core-1.17.0.jar:1.17.0]
 ... 69 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Column '__time' not found in any table
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
 at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:572) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:783) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:768) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4759) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.DelegatingScope.fullyQualify(DelegatingScope.java:259) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5619) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5601) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlIdentifier.accept(SqlIdentifier.java:334) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:134) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:101) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:859) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visitScoped(SqlValidatorImpl.java:5654) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:50) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:33) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:138) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:134) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:101) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:859) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visitScoped(SqlValidatorImpl.java:5654) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:50) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:33) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:138) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.expand(SqlValidatorImpl.java:5208) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validateWhereClause(SqlValidatorImpl.java:3948) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3276) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:967) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:943) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:225) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:918) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:628) ~[calcite-core-1.17.0.jar:1.17.0]
 at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:188) ~[calcite-core-1.17.0.jar:1.17.0]
 ... 69 more
```

**Comment by vogievetsky** [comment]
I remember in early DruidSQL versions the SQL metadata could get de-synced. I think this was fixed in 0.14 (cant find the PR). SQL has been declared non-experimantal in 0.15.0 so it would be really helpful of you could upgrade and see if there is still an issue in 0.16.0.

**Comment by ridox** [comment]
We've got the same problem. The solution has been the same too - restarted the broker.

**Comment by gianm** [comment]
@ridox What version are you running on?

**Comment by sneerin** [comment]
having the same issue, pretty much breaking down entire consumption, for us restarting service doesn't help

**Comment by sneerin** [comment]
basically, it's loss of metadata issue and loss of functionality, since the query stopped working after this feature, only restoring ingestion metadata help, no restarts, version latest, 0.21.1

**Comment by uditsharma** [comment]
Facing the same issue. Does any one knows the reason behind this and possible solution ?
