### ISSUE TITLE
ERROR [main] org.apache.druid.cli.CliMiddleManager - Error when starting up.  Failing.

### ISSUE THREAD

**Issue by hui001** [apache/druid#8773]
I followed the guide http://druid.apache.org/docs/latest/tutorials/index.html to run a start-micro-quickstart, but after it started for several seconds, the following error incured. So what I should do?thx

2019-10-29T06:38:12,783 ERROR [main] org.apache.druid.cli.CliMiddleManager - Error when starting up.  Failing.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) null returned by binding at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliMiddleManager$1)
 but the 2nd parameter of org.apache.druid.cli.CliMiddleManager$1.getWorker(CliMiddleManager.java:152) is not @Nullable
  while locating org.apache.druid.indexing.worker.config.WorkerConfig
    for the 2nd parameter of org.apache.druid.cli.CliMiddleManager$1.getWorker(CliMiddleManager.java:152)
  at org.apache.druid.cli.CliMiddleManager$1.getWorker(CliMiddleManager.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliMiddleManager$1)
  while locating org.apache.druid.indexing.worker.Worker
    for the 5th parameter of org.apache.druid.indexing.worker.WorkerCuratorCoordinator.<init>(WorkerCuratorCoordinator.java:74)
  at org.apache.druid.cli.CliMiddleManager.bindWorkerManagementClasses(CliMiddleManager.java:181) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliMiddleManager$1)
  while locating org.apache.druid.indexing.worker.WorkerCuratorCoordinator
    for the 5th parameter of org.apache.druid.indexing.worker.WorkerTaskMonitor.<init>(WorkerTaskMonitor.java:72)
  at org.apache.druid.cli.CliMiddleManager.bindWorkerManagementClasses(CliMiddleManager.java:180) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliMiddleManager$1)
  while locating org.apache.druid.indexing.worker.WorkerTaskMonitor

2) Problem parsing object at prefix[druid.worker]: Instantiation of [simple type, class org.apache.druid.indexing.worker.config.WorkerConfig] value failed: test: Name or service not known.
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliMiddleManager$1)
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliMiddleManager$1)
  while locating com.google.common.base.Supplier<org.apache.druid.indexing.worker.config.WorkerConfig>
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliMiddleManager$1)
  while locating org.apache.druid.indexing.worker.config.WorkerConfig
    for the 3rd parameter of org.apache.druid.indexing.overlord.ForkingTaskRunner.<init>(ForkingTaskRunner.java:112)
  at org.apache.druid.cli.CliMiddleManager$1.configure(CliMiddleManager.java:106) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliMiddleManager$1)
  while locating org.apache.druid.indexing.overlord.ForkingTaskRunner
  while locating org.apache.druid.indexing.overlord.TaskRunner
    for the 2nd parameter of org.apache.druid.indexing.worker.WorkerTaskMonitor.<init>(WorkerTaskMonitor.java:72)
  at org.apache.druid.cli.CliMiddleManager.bindWorkerManagementClasses(CliMiddleManager.java:180) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliMiddleManager$1)
  while locating org.apache.druid.indexing.worker.WorkerTaskMonitor

2 errors
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028) ~[guice-4.1.0.jar:?]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050) ~[guice-4.1.0.jar:?]
        at org.apache.druid.guice.LifecycleModule$2.start(LifecycleModule.java:138) ~[druid-core-0.16.0-incubating.jar:0.16.0-incubating]
        at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:115) [druid-services-0.16.0-incubating.jar:0.16.0-incubating]
        at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:57) [druid-services-0.16.0-incubating.jar:0.16.0-incubating]
        at org.apache.druid.cli.Main.main(Main.java:113) [druid-services-0.16.0-incubating.jar:0.16.0-incubating]
Caused by: java.lang.IllegalArgumentException: Instantiation of [simple type, class org.apache.druid.indexing.worker.config.WorkerConfig] value failed: test: Name or service not known
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3459) ~[jackson-databind-2.6.7.jar:2.6.7]
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3378) ~[jackson-databind-2.6.7.jar:2.6.7]
        at org.apache.druid.guice.JsonConfigurator.configurate(JsonConfigurator.java:117) ~[druid-core-0.16.0-incubating.jar:0.16.0-incubating]
        at org.apache.druid.guice.JsonConfigProvider.get(JsonConfigProvider.java:243) ~[druid-core-0.16.0-incubating.jar:0.16.0-incubating]

**Comment by luhhujbb** [comment]
I've the same issue on 0.21.0 version. A workaround is to populate missing name into /etc/hosts.
