### ISSUE TITLE
io.druid.java.util.common.IAE: Asked to add buffers

### ISSUE THREAD

**Issue by dutao1** [apache/druid#8959]
io.druid.java.util.common.IAE: Asked to add buffers

### Affected Version

 0.12.3

### Description

```
 ERROR [commerce_adx_stream_flow02-2019-11-27T14:00:00.000Z-persist-n-merge] io.druid.segment.realtime.plumber.RealtimePlumber - Failed to persist merged index[commerce_adx_stream_flow02]: {class=io.druid.segment.realtime.plumber.RealtimePlumber, exceptionType=class io.druid.java.util.common.IAE, exceptionMessage=Asked to add buffers[2,410,316,460] larger than configured max[2,147,483,647], interval=2019-11-27T14:00:00.000Z/2019-11-27T15:00:00.000Z}
io.druid.java.util.common.IAE: Asked to add buffers[2,410,316,460] larger than configured max[2,147,483,647]
	at io.druid.java.util.common.io.smoosh.FileSmoosher.addWithSmooshedWriter(FileSmoosher.java:170) ~[java-util-0.12.3.jar:0.12.3]
	at io.druid.segment.IndexMergerV9.makeColumn(IndexMergerV9.java:425) ~[druid-processing-0.12.3.jar:0.12.3]
	at io.druid.segment.IndexMergerV9.makeIndexFiles(IndexMergerV9.java:224) ~[druid-processing-0.12.3.jar:0.12.3]
	at io.druid.segment.IndexMergerV9.merge(IndexMergerV9.java:837) ~[druid-processing-0.12.3.jar:0.12.3]
	at io.druid.segment.IndexMergerV9.mergeQueryableIndex(IndexMergerV9.java:710) ~[druid-processing-0.12.3.jar:0.12.3]
	at io.druid.segment.IndexMergerV9.mergeQueryableIndex(IndexMergerV9.java:688) ~[druid-processing-0.12.3.jar:0.12.3]
```
	

is one segment so big？

**Comment by dutao1** [comment]
public SmooshedWriter addWithSmooshedWriter(final String name, final long size) throws IOException
  {

    if (size > maxChunkSize) {

how can i make size Smaller？

**Comment by jon-wei** [comment]
You'll want to reduce the amount of data handled by one task, some possibilities are:
- Run parallel tasks
- Shorten the task duration
