### ISSUE TITLE
FileRequestLogger fails when used with FilteredRequestLogger

### ISSUE THREAD

**Issue by DockerLive** [apache/druid#9090]
There was a previous issue for this issue and it was fixed in 0.14.0 (#6580,#6637), but I reproduced it in 0.15.0
### Affected Version

version :   0.15.0

### Description
config:
druid.request.logging.type=filtered
druid.request.logging.queryTimeThresholdMs=200
druid.request.logging.sqlQueryTimeThresholdMs=200
druid.request.logging.mutedQueryTypes=["segmentMetadata","datasourceMetadata"]
druid.request.logging.delegate={"type":"file","dir":"log/"}

error log:

2019-12-23T16:08:52,909 ERROR [qtp1477856922-142] org.apache.druid.sql.SqlLifecycle - Unable to log sql [select
            business_type as businessType,
            space_status as cellStatus,
            reserve_status as reservationStatus,
            has_exception as hasException,
            sum(cell_count) as dataCnt
        from cell_statistics_v2
        where __time >= '2019-12-23 16:04' and __time < '2019-12-23 16:05'
         
        and status_continue_time>=0
         
        group by reserve_status,space_status, has_exception,business_type]!
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[guava-16.0.1.jar:?]
        at com.google.common.base.Joiner.toString(Joiner.java:433) ~[guava-16.0.1.jar:?]
        at com.google.common.base.Joiner.appendTo(Joiner.java:111) ~[guava-16.0.1.jar:?]
        at com.google.common.base.Joiner.appendTo(Joiner.java:152) ~[guava-16.0.1.jar:?]
        at com.google.common.base.Joiner.join(Joiner.java:193) ~[guava-16.0.1.jar:?]
        at com.google.common.base.Joiner.join(Joiner.java:183) ~[guava-16.0.1.jar:?]
        at org.apache.druid.server.RequestLogLine.getSqlQueryLine(RequestLogLine.java:94) ~[druid-server-0.15.0-incubating-iap6.jar:0.15.0-incubating-iap6]
        at org.apache.druid.server.log.FileRequestLogger.logSqlQuery(FileRequestLogger.java:140) ~[druid-server-0.15.0-incubating-iap6.jar:0.15.0-incubating-iap6]
        at org.apache.druid.server.log.FilteredRequestLoggerProvider$FilteredRequestLogger.logSqlQuery(FilteredRequestLoggerProvider.java:112) ~[druid-server-0.15.0-incubating-iap6.jar:0.15.0-incubating-iap6]
        at org.apache.druid.sql.SqlLifecycle.emitLogsAndMetrics(SqlLifecycle.java:326) [druid-sql-0.15.0-incubating-iap6.jar:0.15.0-incubating-iap6]
        at org.apache.druid.sql.avatica.DruidStatement.close(DruidStatement.java:343) [druid-sql-0.15.0-incubating-iap6.jar:0.15.0-incubating-iap6]
        at org.apache.druid.sql.avatica.DruidStatement.nextFrame(DruidStatement.java:281) [druid-sql-0.15.0-incubating-iap6.jar:0.15.0-incubating-iap6]
        at org.apache.druid.sql.avatica.DruidMeta.execute(DruidMeta.java:264) [druid-sql-0.15.0-incubating-iap6.jar:0.15.0-incubating-iap6]
        at org.apache.calcite.avatica.remote.LocalService.apply(LocalService.java:254) [avatica-core-1.12.0.jar:1.12.0]
        at org.apache.calcite.avatica.remote.Service$ExecuteRequest.accept(Service.java:1031) [avatica-core-1.12.0.jar:1.12.0]
        at org.apache.calcite.avatica.remote.Service$ExecuteRequest.accept(Service.java:1001) [avatica-core-1.12.0.jar:1.12.0]
        at org.apache.calcite.avatica.remote.AbstractHandler.apply(AbstractHandler.java:94) [avatica-core-1.12.0.jar:1.12.0]
        at org.apache.calcite.avatica.remote.JsonHandler.apply(JsonHandler.java:52) [avatica-core-1.12.0.jar:1.12.0]
        at org.apache.calcite.avatica.server.AvaticaJsonHandler.handle(AvaticaJsonHandler.java:130) [avatica-server-1.12.0.jar:1.12.0]
        at org.apache.druid.sql.avatica.DruidAvaticaHandler.handle(DruidAvaticaHandler.java:59) [druid-sql-0.15.0-incubating-iap6.jar:0.15.0-incubating-iap6]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.Server.handle(Server.java:531) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

**Comment by laserscout** [comment]
I have the same issue with Druid 0.16 and the kafka emitter enabled
