### ISSUE TITLE
Load streaming data from Apache Kafka Problem

### ISSUE THREAD

**Issue by qinyz** [apache/druid#9207]
Deployment environment
Operating system: CentOS Linux release 7.4.1708 (core)
Druid version: apache-druid-0.16.1-incoming-bin
Java version: 1.8.0_112

druid-data.log:
--------------------------------------------------------------------
2020-01-17 16:30:53:519] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Submitting persist runnable for dataSource[ACTION_LOG_DRUID]
[2020-01-17 16:30:53:507] [ERROR] - org.apache.druid.java.util.common.logger.Logger.error(Logger.java:123) - Encountered exception in run() before persisting.
org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeThrowInterruptException(ConsumerNetworkClient.java:493) ~[?:?]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:281) ~[?:?]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236) ~[?:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1243) ~[?:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1188) ~[?:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1164) ~[?:?]
	at org.apache.druid.indexing.kafka.KafkaRecordSupplier.poll(KafkaRecordSupplier.java:119) ~[?:?]
	at org.apache.druid.indexing.kafka.IncrementalPublishingKafkaIndexTaskRunner.getRecords(IncrementalPublishingKafkaIndexTaskRunner.java:111) ~[?:?]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.runInternal(SeekableStreamIndexTaskRunner.java:575) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.run(SeekableStreamIndexTaskRunner.java:259) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTask.run(SeekableStreamIndexTask.java:177) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:419) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:391) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.InterruptedException
	... 17 more
[2020-01-17 16:30:53:519] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Persisting all pending data
--------------------------------------------------------------------
[2020-01-17 16:30:53:562] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Invoking stop method[public void org.apache.druid.java.util.emitter.service.ServiceEmitter.close() throws java.io.IOException] on object[ServiceEmitter{serviceDimensions={service=druid/middleManager, host=address:8100, version=0.16.1-incubating}, emitter=org.apache.druid.java.util.emitter.core.NoopEmitter@34414ffc}].
[2020-01-17 16:30:53:558] [ERROR] - org.apache.druid.java.util.common.logger.Logger.error(Logger.java:123) - Encountered exception while running task.
org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeThrowInterruptException(ConsumerNetworkClient.java:493) ~[?:?]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:281) ~[?:?]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236) ~[?:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1243) ~[?:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1188) ~[?:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1164) ~[?:?]
	at org.apache.druid.indexing.kafka.KafkaRecordSupplier.poll(KafkaRecordSupplier.java:119) ~[?:?]
	at org.apache.druid.indexing.kafka.IncrementalPublishingKafkaIndexTaskRunner.getRecords(IncrementalPublishingKafkaIndexTaskRunner.java:111) ~[?:?]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.runInternal(SeekableStreamIndexTaskRunner.java:575) ~[druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.run(SeekableStreamIndexTaskRunner.java:259) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTask.run(SeekableStreamIndexTask.java:177) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:419) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:391) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
	Suppressed: java.lang.InterruptedException
		at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404) ~[?:1.8.0_112]
		at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:1.8.0_112]
		at org.apache.druid.segment.realtime.appenderator.StreamAppenderatorDriver.persist(StreamAppenderatorDriver.java:232) ~[druid-server-0.16.1-incubating.jar:0.16.1-incubating]
		at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.runInternal(SeekableStreamIndexTaskRunner.java:752) ~[druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
		at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.run(SeekableStreamIndexTaskRunner.java:259) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
		at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTask.run(SeekableStreamIndexTask.java:177) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
		at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:419) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
		at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:391) [druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
		at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.InterruptedException
	... 17 more
[2020-01-17 16:30:53:562] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Stopping Curator
--------------------------------------------------------------------
[2020-01-17 16:30:53:687] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - [_default_tier] : Assigned 0 segments among 1 servers
[2020-01-17 16:30:53:687] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Load Queues:
[2020-01-17 16:30:53:688] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Server[address:8083, historical, _default_tier] has 0 left to load, 0 left to drop, 0 bytes queued, 4,666,524 bytes served.
[2020-01-17 16:30:53:716] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Wrote task log to: hdfs://address:8020/druid/indexing-logs/index_kafka_ACTION_LOG_ALL_8c356a49b740725_cfcibngo
[2020-01-17 16:30:53:717] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Wrote task log to: hdfs://address:8020/druid/indexing-logs/index_kafka_ACTION_LOG_DRUID_0f297596027627a_cfcibngo
[2020-01-17 16:30:53:717] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Writing task reports to: hdfs://address:8020/druid/indexing-logs/index_kafka_ACTION_LOG_ALL_8c356a49b740725_cfcibngo.reports.json
[2020-01-17 16:30:53:717] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Task [index_kafka_ACTION_LOG_DRUID_0f297596027627a_cfcibngo] status changed to [FAILED].
[2020-01-17 16:30:53:719] [ERROR] - com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:161) - RuntimeException while executing runnable com.google.common.util.concurrent.Futures$4@bcdf660 with executor com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService@2ec064b5
java.util.concurrent.RejectedExecutionException: Task org.apache.druid.indexing.worker.WorkerTaskManager$$Lambda$48/807560198@7cea38ec rejected from java.util.concurrent.ThreadPoolExecutor@5a2fe5d8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 19]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_112]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668) ~[?:1.8.0_112]
	at org.apache.druid.indexing.worker.WorkerTaskManager.submitNoticeToExec(WorkerTaskManager.java:182) ~[druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.worker.WorkerTaskManager.access$000(WorkerTaskManager.java:77) ~[druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.worker.WorkerTaskManager$2.onSuccess(WorkerTaskManager.java:246) ~[druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.worker.WorkerTaskManager$2.onSuccess(WorkerTaskManager.java:242) ~[druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1181) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) [guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) [guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:91) [guava-16.0.1.jar:?]
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.set(FutureTask.java:233) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:274) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
[2020-01-17 16:30:53:742] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Wrote task reports to: hdfs://address:8020/druid/indexing-logs/index_kafka_ACTION_LOG_ALL_8c356a49b740725_cfcibngo.reports.json
[2020-01-17 16:30:53:743] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Task [index_kafka_ACTION_LOG_ALL_8c356a49b740725_cfcibngo] status changed to [FAILED].
[2020-01-17 16:30:53:743] [ERROR] - com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:161) - RuntimeException while executing runnable com.google.common.util.concurrent.Futures$4@3929c1be with executor com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService@2f31adda
java.util.concurrent.RejectedExecutionException: Task org.apache.druid.indexing.worker.WorkerTaskManager$$Lambda$48/807560198@180eeee3 rejected from java.util.concurrent.ThreadPoolExecutor@5a2fe5d8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 19]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_112]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668) ~[?:1.8.0_112]
	at org.apache.druid.indexing.worker.WorkerTaskManager.submitNoticeToExec(WorkerTaskManager.java:182) ~[druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.worker.WorkerTaskManager.access$000(WorkerTaskManager.java:77) ~[druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.worker.WorkerTaskManager$2.onSuccess(WorkerTaskManager.java:246) ~[druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at org.apache.druid.indexing.worker.WorkerTaskManager$2.onSuccess(WorkerTaskManager.java:242) ~[druid-indexing-service-0.16.1-incubating.jar:0.16.1-incubating]
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1181) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) [guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) [guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:91) [guava-16.0.1.jar:?]
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.set(FutureTask.java:233) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:274) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
[2020-01-17 16:30:53:745] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Finished stopping in 307ms.
[2020-01-17 16:30:53:745] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Stopped WorkerTaskManager.
[2020-01-17 16:30:53:745] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Stopped WorkerTaskMonitor.
[2020-01-17 16:30:53:746] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Invoking stop method[public void org.apache.druid.discovery.DruidLeaderClient.stop()] on object[org.apache.druid.discovery.DruidLeaderClient@7ab802f4].
[2020-01-17 16:30:53:746] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Stopped.
[2020-01-17 16:30:53:746] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Invoking stop method[public void org.apache.druid.curator.discovery.ServerDiscoverySelector.stop() throws java.io.IOException] on object[org.apache.druid.curator.discovery.ServerDiscoverySelector@553d2579].
[2020-01-17 16:30:53:750] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Invoking stop method[public void org.apache.druid.curator.discovery.CuratorDruidNodeDiscoveryProvider.stop()] on object[org.apache.druid.curator.discovery.CuratorDruidNodeDiscoveryProvider@b5b9333].
[2020-01-17 16:30:53:751] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - stopping
[2020-01-17 16:30:53:751] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - stopped
[2020-01-17 16:30:53:751] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Invoking stop method[public void org.apache.druid.java.util.http.client.NettyHttpClient.stop()] on object[org.apache.druid.java.util.http.client.NettyHttpClient@6371cf2f].
[2020-01-17 16:30:53:785] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Invoking stop method[public void org.apache.druid.indexing.worker.WorkerCuratorCoordinator.stop()] on object[org.apache.druid.indexing.worker.WorkerCuratorCoordinator@236fdf].
[2020-01-17 16:30:53:787] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Stopping WorkerCuratorCoordinator for worker[address:8091]
[2020-01-17 16:30:53:787] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Stopping announcer
[2020-01-17 16:30:53:788] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - unannouncing [/druid/indexer/announcements/address:8091]
[2020-01-17 16:30:53:791] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Invoking stop method[public void org.apache.druid.storage.hdfs.HdfsStorageAuthentication.stop()] on object[org.apache.druid.storage.hdfs.HdfsStorageAuthentication@54af3cb9].
[2020-01-17 16:30:53:792] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Invoking stop method[public void org.apache.druid.java.util.metrics.MonitorScheduler.stop()] on object[org.apache.druid.java.util.metrics.MonitorScheduler@52831a73].
[2020-01-17 16:30:53:792] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Kaboom! Worker[address:8091] removed!
[2020-01-17 16:30:53:792] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Invoking stop method[public void org.apache.druid.java.util.emitter.service.ServiceEmitter.close() throws java.io.IOException] on object[ServiceEmitter{serviceDimensions={service=druid/middleManager, host=address:8091, version=0.16.1-incubating}, emitter=org.apache.druid.java.util.emitter.core.NoopEmitter@60e06f7d}].
[2020-01-17 16:30:53:793] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - [address:8091]: Found [index_kafka_ACTION_LOG_ALL_8c356a49b740725_cfcibngo] running
[2020-01-17 16:30:53:794] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - [address:8091]: Found [index_kafka_ACTION_LOG_DRUID_0f297596027627a_cfcibngo] running
[2020-01-17 16:30:53:794] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - [address:8091]: Found 2 tasks assigned
[2020-01-17 16:30:53:795] [INFO] - org.apache.druid.java.util.common.logger.Logger.info(Logger.java:71) - Stopping Curator

**Comment by vogievetsky** [comment]
What does your Tasks view in the console look like?

**Comment by qinyz** [comment]
After an error is reported, the Druid will stop the service. After the Druid is restarted,

In the task window, the supervisors will display running, and new tasks will be generated under the task, which is also running
![image](https://user-images.githubusercontent.com/12380584/72673775-da070a80-3aa9-11ea-8d15-613fa760ed88.png)

**Comment by abhi751993** [comment]
Hey @qinyz, were you able to find a solution to this problem? I'm facing the same problem too.

**Comment by vikramarsid** [comment]
@vogievetsky @qinyz @abhi751993 Any solution on this issues? I am facing the same issue on v0.16.1. Let me know if you need more details to fill in.

**Comment by klDen** [comment]
I faced the same issue running in docker containers.
The issue was the docker service was running as another user. What resolved it temporarily was to make the local volume **storage** directory writable to all (e.g. chmod 777).
