### ISSUE TITLE
Enabling basic security with an external metadata database causes usermap error

### ISSUE THREAD

**Issue by ceastman-ibm** [apache/druid#9453]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

0.17.0

### Description

Using postgresql as an external metadata database.
configuration added to common.runtime.properties:
druid.auth.authenticatorChain=["MyBasicPostgreSQLAuthenticator"]
druid.auth.authenticator.MyBasicPostgreSQLAuthenticator.type=basic
druid.auth.authenticator.MyBasicPostgreSQLAuthenticator.credentialsValidator.type=metadata
druid.auth.authenticator.MyBasicPostgreSQLAuthenticator.skipOnFailure=false
druid.auth.authenticator.MyBasicPostgreSQLAuthenticator.authorizerName=MyBasicPostgreSQLAuthorizer
druid.escalator.type=basic
druid.escalator.authorizerName=MyBasicPostgreSQLAuthorizer
druid.auth.authorizers=["MyBasicPostgreSQLAuthorizer"]
druid.auth.authorizer.MyBasicPostgreSQLAuthorizer.type=basic
druid.metadata.postgres.ssl.sslMode=require
druid.escalator.internalClientUsername=<<redacted>>
druid.escalator.internalClientPassword=<<redacted>>
druid.auth.authenticator.MyBasicPostgreSQLAuthenticator.initialAdminPassword=<<redacted>>
druid.auth.authenticator.MyBasicPostgreSQLAuthenticator.initialInternalClientPassword=<<redacted>>
 
druid.metadata.storage.connector.user=redacted
druid.metadata.storage.connector.password=redacted
druid.metadata.storage.type=postgresql
druid.metadata.storage.connector.connectURI=jdbc:postgresql://redacted.databases.appdomain.cloud:31039/druid?sslmode=verify-full
druid.metadata.storage.connector.user=redacted
druid.metadata.storage.connector.password=redacted
druid.metadata.postgres.ssl.sslMode=require
Please include as much detailed information about the problem as possible.
- Cluster size
- Configurations in use
- Steps to reproduce the problem
- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
- Any debugging that you have already done

logs from the historical/middle manager kubernetes pod:
2020-03-03T18:25:07,145 WARN [main] org.apache.druid.java.util.common.RetryUtils - Retrying (6 of 9) in 43,455ms.
com.fasterxml.jackson.core.JsonParseException: Input does not start with Smile format header (first byte = 0x3c) and parser has REQUIRE_HEADER enabled: can not parse
 at [Source: (byte[])"<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 401 Unauthorized</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /druid-ext/basic-security/authentication/db/MyBasicPostgreSQLAuthenticator/cachedSerializedUserMap. Reason:
<pre>    Unauthorized</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.12.v20180830</a><hr/>

</body>
</html>
"; line: -1, column: 0]
	at com.fasterxml.jackson.dataformat.smile.SmileParserBootstrapper.constructParser(SmileParserBootstrapper.java:133) ~[jackson-dataformat-smile-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.dataformat.smile.SmileFactory._createParser(SmileFactory.java:460) ~[jackson-dataformat-smile-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.dataformat.smile.SmileFactory.createParser(SmileFactory.java:366) ~[jackson-dataformat-smile-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.dataformat.smile.SmileFactory.createParser(SmileFactory.java:353) ~[jackson-dataformat-smile-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.dataformat.smile.SmileFactory.createParser(SmileFactory.java:29) ~[jackson-dataformat-smile-2.10.1.jar:2.10.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3283) ~[jackson-databind-2.10.1.jar:2.10.1]
	at org.apache.druid.security.basic.authentication.db.cache.CoordinatorPollingBasicAuthenticatorCacheManager.tryFetchUserMapFromCoordinator(CoordinatorPollingBasicAuthenticatorCacheManager.java:262) ~[?:?]
	at org.apache.druid.security.basic.authentication.db.cache.CoordinatorPollingBasicAuthenticatorCacheManager.lambda$fetchUserMapFromCoordinator$1(CoordinatorPollingBasicAuthenticatorCacheManager.java:192) ~[?:?]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:87) [druid-core-0.17.0.jar:0.17.0]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:115) [druid-core-0.17.0.jar:0.17.0]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:105) [druid-core-0.17.0.jar:0.17.0]
	at org.apache.druid.security.basic.authentication.db.cache.CoordinatorPollingBasicAuthenticatorCacheManager.fetchUserMapFromCoordinator(CoordinatorPollingBasicAuthenticatorCacheManager.java:190) [druid-basic-security-0.17.0.jar:0.17.0]
	at org.apache.druid.security.basic.authentication.db.cache.CoordinatorPollingBasicAuthenticatorCacheManager.initUserMaps(CoordinatorPollingBasicAuthenticatorCacheManager.java:289) [druid-basic-security-0.17.0.jar:0.17.0]
	at org.apache.druid.security.basic.authentication.db.cache.CoordinatorPollingBasicAuthenticatorCacheManager.start(CoordinatorPollingBasicAuthenticatorCacheManager.java:108) [druid-basic-security-0.17.0.jar:0.17.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:446) [druid-core-0.17.0.jar:0.17.0]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:341) [druid-core-0.17.0.jar:0.17.0]
	at org.apache.druid.guice.LifecycleModule$2.start(LifecycleModule.java:143) [druid-core-0.17.0.jar:0.17.0]
	at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:115) [druid-services-0.17.0.jar:0.17.0]
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:59) [druid-services-0.17.0.jar:0.17.0]
	at org.apache.druid.cli.Main.main(Main.java:113) [druid-services-0.17.0.jar:0.17.0]

**Comment by ceastman-ibm** [comment]
<img width="1680" alt="Screen Shot 2020-03-03 at 12 29 11 PM" src="https://user-images.githubusercontent.com/25593207/75807222-9d862a00-5d4a-11ea-9dc1-f77ef7ac74c6.png">

**Comment by ceastman-ibm** [comment]
this was due to a bad configuration on my part.

**Comment by PeterCahn** [comment]
> 
> 
> this was due to a bad configuration on my part.

Which configuration was the problem?

**Comment by luisarojas** [comment]
@ceastman-ibm Hey Carl, I know this issue is kinda old, but do you remember what the configuration issue was? I'm trying to add a similar authentication configuration and I'm getting the same errors.

**Comment by CesarManriqueH** [comment]
I was using Apache Druid v21.1 and got this error after configuring Basic Authentication following the steps described here https://support.imply.io/hc/en-us/articles/360051794093-How-to-Enable-Basic-Auth-in-Druid

So I tried with v20.2 and it worked properly.
