### ISSUE TITLE
Unable to debug tests from the IDE

### ISSUE THREAD

**Issue by abhishekrb19** [apache/druid#9511]
Hi, 

I am trying to debug the `CompactionTest`, but unfortunately I am unable to step through the code with breakpoints setup from my IDE (Intellij). Note: I am fairly new to the codebase.

**Using maven:**

Ran the test in isolation with debug on.

```bash
mvn -Dtest=CompactionTaskTest -Dmaven.surefire.debug test
...
INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ druid-indexing-service ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Listening for transport dt_socket at address: 5005
```
And when I create a remote application and connect to port 5005, I get the following stacktrace and the test terminates:

```bash
error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: Can't attach symbolicator to the process
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: Can't attach symbolicator to the process
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$BsdDebuggerLocalWorkerThread.execute(BsdDebuggerLocal.java:169)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach(BsdDebuggerLocal.java:287)
	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerDarwin(HotSpotAgent.java:659)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:341)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
```

The above looks like a known JDK 1.8 bug - https://bugs.openjdk.java.net/browse/JDK-8160376. The recommendation is to bump up the JDK to 1.9 -- which is not supported in Druid AFAIK.

**Using IDE:**
I tried running the tests directly from the IDE with the `JUnit`, but wasn't successful either.

<img width="1372" alt="Screen Shot 2020-03-12 at 4 59 27 PM" src="https://user-images.githubusercontent.com/8687261/76577553-0411f300-6483-11ea-8cfd-23bf2c8452ca.png">

**Environment:**
1. Java version:
```bash
❯ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```
2. Maven version
```bash
❯ mvn -version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T08:06:16-07:00)
Maven home: /Users/abradhak/apache-maven-3.6.2
Java version: 1.8.0_162, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

3. Intellij IDEA: 2019.3.1

3. Druid: 0.17.0

If there's a way to debug the tests directly from the IDE or otherwise, please let me know. Appreciate any tips. Thanks!

CC: @gianm @himanshug @ccaominh @clintropolis

**Comment by himanshug** [comment]
Just tried from Intellij, worked for me.

```
~/work/druid[(HEAD detached at apache/master)]$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
~/work/druid[(HEAD detached at apache/master)]$ mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T11:49:05-08:00)
Maven home: /Users/hgupta/installations/apache-maven-3.5.3
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
```

I would suggest doing a `mvn clean` ,  then "Maven Reimport" in Intelliji and then try.

**Comment by abhishekrb19** [comment]
hey, thanks @himanshug, that worked! Closing this.
