### ISSUE TITLE
middleManager container is unable to connect a zookeeper container under bridge mode network

### ISSUE THREAD

**Issue by Fullstop000** [apache/druid#9522]
### Affected Version

0.17.0

### Description

I set up a single-server druid cluster by `docker-compose` with my own `docker-compose.yml`. All the members in cluster were fine except the middleMnanger container. Here is the error message:
```
2020-03-16T13:02:56,388 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=var/tmp
2020-03-16T13:02:56,388 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
2020-03-16T13:02:56,388 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux
2020-03-16T13:02:56,388 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
2020-03-16T13:02:56,388 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:os.version=4.19.84-microsoft-standard
2020-03-16T13:02:56,388 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:user.name=root
2020-03-16T13:02:56,388 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:user.home=/root
2020-03-16T13:02:56,388 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/opt/apache-druid-0.17.0
2020-03-16T13:02:56,389 INFO [main] org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=druid.zookeeper sessionTimeout=30000 watcher=org.apache.curator.ConnectionState@7a687d8d
2020-03-16T13:02:56,392 DEBUG [main] org.apache.zookeeper.ClientCnxn - zookeeper.disableAutoWatchReset is false
2020-03-16T13:02:56,417 INFO [main] org.apache.curator.framework.imps.CuratorFrameworkImpl - Default schema
2020-03-16T13:02:56,419 DEBUG [main] org.apache.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking start method[public void org.apache.druid.java.util.emitter.service.ServiceEmitter.start()] on object[ServiceEmitter{serviceDimensions={service=druid/middleManager, host=192.168.65.3:8091, version=0.17.0}, emitter=NoopEmitter{}}].
2020-03-16T13:02:56,419 DEBUG [main] org.apache.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking start method[public void org.apache.druid.java.util.metrics.MonitorScheduler.start()] on object[org.apache.druid.java.util.metrics.MonitorScheduler@d7bbf12].
2020-03-16T13:02:56,422 DEBUG [main] org.apache.druid.java.util.common.concurrent.ScheduledExecutors - Scheduling periodically: org.apache.druid.java.util.metrics.MonitorScheduler$1@47acd13b with period PT15S
2020-03-16T13:02:56,424 DEBUG [main] org.apache.druid.java.util.common.concurrent.ScheduledExecutors - Scheduling periodically: org.apache.druid.java.util.metrics.MonitorScheduler$1@3f6f3cc with period PT15S
2020-03-16T13:02:56,424 DEBUG [main] org.apache.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking start method[public void org.apache.druid.storage.hdfs.HdfsStorageAuthentication.authenticate()] on object[org.apache.druid.storage.hdfs.HdfsStorageAuthentication@180b3819].
2020-03-16T13:02:56,425 DEBUG [main] org.apache.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking start method[public void org.apache.druid.indexing.worker.WorkerCuratorCoordinator.start() throws java.lang.Exception] on object[org.apache.druid.indexing.worker.WorkerCuratorCoordinator@733c464f].
2020-03-16T13:02:56,425 INFO [main] org.apache.druid.indexing.worker.WorkerCuratorCoordinator - WorkerCuratorCoordinator good to go sir. Server[192.168.65.3:8091]
2020-03-16T13:02:56,614 WARN [main-SendThread(druid.zookeeper:2181)] org.apache.zookeeper.ClientCnxn - Session 0x0 for server druid.zookeeper:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address druid.zookeeper:2181 because it's not resolvable
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) [zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
2020-03-16T13:02:57,719 WARN [main-SendThread(druid.zookeeper:2181)] org.apache.zookeeper.ClientCnxn - Session 0x0 for server druid.zookeeper:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address druid.zookeeper:2181 because it's not resolvable
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) [zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
```

It seems the middleManager is unable to resolve `druid.zookeeper` in bridge mode docker network.
However, the connection between the overelord and zookeeper works fine. Here are some relative logs: 
```
2020-03-16T13:04:45,961 DEBUG [main] org.apache.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking start method[public void org.apache.druid.java.util.emitter.service.ServiceEmitter.start()] on object[ServiceEmitter{serviceDimensions={service=druid/overlord, host=172.28.0.4:8090, version=0.17.0}, emitter=NoopEmitter{}}].
2020-03-16T13:04:45,962 DEBUG [main] org.postgresql.Driver - Loading driver configuration via classloader java.net.URLClassLoader@6d1310f6
2020-03-16T13:04:45,963 DEBUG [main] org.postgresql.Driver - Connecting with URL: jdbc:postgresql://druid.postgres/druid
2020-03-16T13:04:45,964 DEBUG [main] org.postgresql.jdbc.PgConnection - PostgreSQL JDBC Driver 42.2.8
2020-03-16T13:04:45,965 DEBUG [main] org.postgresql.jdbc.PgConnection -   setDefaultFetchSize = 0
2020-03-16T13:04:45,965 DEBUG [main] org.postgresql.jdbc.PgConnection -   setPrepareThreshold = 5
2020-03-16T13:04:45,965 DEBUG [main] org.postgresql.core.v3.ConnectionFactoryImpl - Trying to establish a protocol version 3 connection to druid.postgres:5432
2020-03-16T13:04:45,967 DEBUG [main] org.postgresql.core.v3.ConnectionFactoryImpl - Receive Buffer Size is 186,240
2020-03-16T13:04:45,967 DEBUG [main] org.postgresql.core.v3.ConnectionFactoryImpl - Send Buffer Size is 43,520
2020-03-16T13:04:45,971 DEBUG [main] org.postgresql.Driver - Connecting with URL: jdbc:postgresql://druid.postgres/druid
2020-03-16T13:04:45,971 DEBUG [main] org.postgresql.jdbc.PgConnection - PostgreSQL JDBC Driver 42.2.8
2020-03-16T13:04:45,971 DEBUG [main] org.postgresql.jdbc.PgConnection -   setDefaultFetchSize = 0
2020-03-16T13:04:45,972 DEBUG [main] org.postgresql.jdbc.PgConnection -   setPrepareThreshold = 5
2020-03-16T13:04:45,972 DEBUG [main] org.postgresql.core.v3.ConnectionFactoryImpl - Trying to establish a protocol version 3 connection to druid.postgres:5432
2020-03-16T13:04:45,973 DEBUG [main] org.postgresql.core.v3.ConnectionFactoryImpl - Receive Buffer Size is 186,240
2020-03-16T13:04:45,973 DEBUG [main] org.postgresql.core.v3.ConnectionFactoryImpl - Send Buffer Size is 43,520
2020-03-16T13:04:45,978 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Table[druid_audit] already exists
2020-03-16T13:04:45,978 DEBUG [main] org.apache.druid.curator.CuratorModule - Starting Curator
2020-03-16T13:04:45,978 INFO [main] org.apache.curator.framework.imps.CuratorFrameworkImpl - Starting
2020-03-16T13:04:45,980 DEBUG [main] org.apache.curator.CuratorZookeeperClient - Starting
2020-03-16T13:04:45,980 DEBUG [main] org.apache.curator.ConnectionState - Starting
2020-03-16T13:04:45,980 DEBUG [main] org.apache.curator.ConnectionState - reset
2020-03-16T13:04:45,984 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf, built on 03/06/2019 16:18 GMT
2020-03-16T13:04:45,984 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:host.name=17fd6f30ba81
2020-03-16T13:04:45,984 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:java.version=1.8.0_242
2020-03-16T13:04:45,984 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Oracle Corporation
2020-03-16T13:04:45,984 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre
2020-03-16T13:04:45,984 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=/tmp/conf/druid/cluster/_common:/tmp/conf/druid/cluster/master/overlord:lib/netty-3.10.6.Final.jar:lib/config-magic-0.9.jar:lib/netty-resolver-4.1.42.Final.jar:lib/maven-settings-builder-3.1.1.jar:lib/aopalliance-1.0.jar:lib/FastInfoset-1.2.15.jar:lib/javax.el-api-3.0.0.jar:lib/aether-api-0.9.0.M2.jar:lib/commons-compress-1.19.jar:lib/jmespath-java-1.11.199.jar:lib/jetty-http-9.4.12.v20180830.jar:lib/druid-core-0.17.0.jar:lib/compress-lzf-1.0.4.jar:lib/fastutil-8.2.3.jar:lib/esri-geometry-api-2.2.0.jar:lib/hibernate-validator-5.2.5.Final.jar:lib/opencsv-4.6.jar:lib/javax.servlet-api-3.1.0.jar:lib/netty-codec-4.1.42.Final.jar:lib/jakarta.activation-api-1.2.1.jar:lib/druid-aws-common-0.17.0.jar:lib/google-http-client-1.22.0.jar:lib/druid-console-0.17.0.jar:lib/jackson-dataformat-cbor-2.10.1.jar:lib/jersey-servlet-1.19.3.jar:lib/netty-transport-native-unix-common-4.1.42.Final.jar:lib/jackson-annotations-2.10.1.jar:lib/xz-1.8.jar:lib/commons-text-1.3.jar:lib/asm-commons-7.1.jar:lib/derby-10.14.2.0.jar:lib/jetty-client-9.4.12.v20180830.jar:lib/aws-java-sdk-s3-1.11.199.jar:lib/commons-net-3.6.jar:lib/jersey-server-1.19.3.jar:lib/jackson-module-jaxb-annotations-2.10.1.jar:lib/janino-3.0.11.jar:lib/jackson-datatype-guava-2.10.1.jar:lib/jaxb-runtime-2.3.1.jar:lib/jetty-server-9.4.12.v20180830.jar:lib/jaxb-api-2.3.1.jar:lib/maven-repository-metadata-3.1.1.jar:lib/jetty-servlets-9.4.12.v20180830.jar:lib/json-smart-2.3.jar:lib/javax.activation-1.2.0.jar:lib/netty-handler-proxy-4.1.42.Final.jar:lib/jcl-over-slf4j-1.7.12.jar:lib/checker-qual-2.5.7.jar:lib/accessors-smart-1.2.jar:lib/maven-model-builder-3.1.1.jar:lib/commons-io-2.6.jar:lib/zookeeper-3.4.14.jar:lib/aggdesigner-algorithm-6.0.jar:lib/jetty-io-9.4.12.v20180830.jar:lib/avatica-core-1.15.0.jar:lib/RoaringBitmap-0.8.11.jar:lib/netty-transport-4.1.42.Final.jar:lib/classmate-1.1.0.jar:lib/calcite-linq4j-1.21.0.jar:lib/commons-lang-2.6.jar:lib/extendedset-0.17.0.jar:lib/wagon-provider-api-2.4.jar:lib/aws-java-sdk-kms-1.11.199.jar:lib/rhino-1.7.11.jar:lib/asm-tree-7.1.jar:lib/jetty-continuation-9.4.12.v20180830.jar:lib/slf4j-api-1.7.25.jar:lib/jackson-core-asl-1.9.13.jar:lib/httpclient-4.5.10.jar:lib/jackson-core-2.10.1.jar:lib/netty-common-4.1.42.Final.jar:lib/reactive-streams-1.0.2.jar:lib/plexus-utils-3.0.24.jar:lib/jackson-datatype-joda-2.10.1.jar:lib/commons-compiler-3.0.11.jar:lib/joni-2.1.27.jar:lib/jackson-jaxrs-json-provider-2.10.1.jar:lib/derbyclient-10.14.2.0.jar:lib/plexus-interpolation-1.19.jar:lib/jcodings-1.0.43.jar:lib/commons-codec-1.13.jar:lib/jackson-mapper-asl-1.9.13.jar:lib/druid-processing-0.17.0.jar:lib/caffeine-2.8.0.jar:lib/jakarta.xml.bind-api-2.3.2.jar:lib/jline-0.9.94.jar:lib/calcite-core-1.21.0.jar:lib/jvm-attach-api-1.5.jar:lib/commons-pool2-2.2.jar:lib/guice-servlet-4.1.0.jar:lib/icu4j-55.1.jar:lib/guice-4.1.0.jar:lib/google-http-client-jackson2-1.22.0.jar:lib/validation-api-1.1.0.Final.jar:lib/jackson-jaxrs-base-2.10.1.jar:lib/derbynet-10.14.2.0.jar:lib/antlr4-runtime-4.5.1.jar:lib/error_prone_annotations-2.3.2.jar:lib/log4j-jul-2.8.2.jar:lib/aether-util-0.9.0.M2.jar:lib/airline-0.7.jar:lib/jackson-jaxrs-smile-provider-2.10.1.jar:lib/druid-indexing-service-0.17.0.jar:lib/log4j-slf4j-impl-2.8.2.jar:lib/maven-artifact-3.6.0.jar:lib/jersey-core-1.19.3.jar:lib/druid-gcp-common-0.17.0.jar:lib/javax.el-3.0.0.jar:lib/google-oauth-client-1.22.0.jar:lib/stax-ex-1.8.jar:lib/json-path-2.3.0.jar:lib/aether-spi-0.9.0.M2.jar:lib/txw2-2.3.1.jar:lib/jetty-servlet-9.4.12.v20180830.jar:lib/netty-handler-4.1.42.Final.jar:lib/netty-transport-native-epoll-4.1.42.Final-linux-x86_64.jar:lib/curator-recipes-4.1.0.jar:lib/ion-java-1.0.2.jar:lib/commons-logging-1.1.1.jar:lib/datasketches-java-1.1.0-incubating.jar:lib/netty-codec-http-4.1.42.Final.jar:lib/audience-annotations-0.5.0.jar:lib/zstd-jni-1.3.3-1.jar:lib/avatica-metrics-1.15.0.jar:lib/jsr311-api-1.1.1.jar:lib/jersey-guice-1.19.3.jar:lib/okhttp-1.0.2.jar:lib/maven-model-3.1.1.jar:lib/sigar-1.6.5.132.jar:lib/log4j-1.2-api-2.8.2.jar:lib/netty-codec-dns-4.1.42.Final.jar:lib/joda-time-2.10.5.jar:lib/netty-reactive-streams-2.0.0.jar:lib/shims-0.8.11.jar:lib/protobuf-java-3.11.0.jar:lib/jackson-jq-0.0.10.jar:lib/metrics-core-4.0.0.jar:lib/avatica-server-1.15.0.jar:lib/jackson-databind-2.10.1.jar:lib/netty-buffer-4.1.42.Final.jar:lib/guava-16.0.1.jar:lib/maven-aether-provider-3.1.1.jar:lib/datasketches-memory-1.2.0-incubating.jar:lib/jsr305-2.0.1.jar:lib/curator-framework-4.1.0.jar:lib/log4j-api-2.8.2.jar:lib/spymemcached-2.12.3.jar:lib/jetty-util-9.4.12.v20180830.jar:lib/log4j-core-2.8.2.jar:lib/commons-dbcp2-2.0.1.jar:lib/commons-beanutils-1.9.4.jar:lib/istack-commons-runtime-3.0.7.jar:lib/guice-multibindings-4.1.0.jar:lib/async-http-client-2.5.3.jar:lib/aether-impl-0.9.0.M2.jar:lib/jna-4.5.1.jar:lib/druid-hll-0.17.0.jar:lib/aether-connector-okhttp-0.0.9.jar:lib/jdbi-2.63.1.jar:lib/disruptor-3.3.6.jar:lib/druid-indexing-hadoop-0.17.0.jar:lib/aws-java-sdk-core-1.11.199.jar:lib/aether-connector-file-0.9.0.M2.jar:lib/lz4-java-1.6.0.jar:lib/jetty-rewrite-9.4.12.v20180830.jar:lib/maven-settings-3.1.1.jar:lib/httpcore-4.4.11.jar:lib/commons-lang3-3.8.1.jar:lib/async-http-client-netty-utils-2.5.3.jar:lib/asm-7.1.jar:lib/jboss-logging-3.2.1.Final.jar:lib/asm-analysis-7.1.jar:lib/commons-collections4-4.2.jar:lib/curator-x-discovery-4.1.0.jar:lib/jackson-dataformat-smile-2.10.1.jar:lib/tesla-aether-0.0.5.jar:lib/jackson-module-guice-2.10.1.jar:lib/commons-math3-3.6.1.jar:lib/aws-java-sdk-ec2-1.11.199.jar:lib/jetty-proxy-9.4.12.v20180830.jar:lib/jetty-security-9.4.12.v20180830.jar:lib/curator-client-4.1.0.jar:lib/druid-sql-0.17.0.jar:lib/javax.activation-api-1.2.0.jar:lib/javax.inject-1.jar:lib/netty-codec-socks-4.1.42.Final.jar:lib/druid-services-0.17.0.jar:lib/google-api-client-1.22.0.jar:lib/druid-server-0.17.0.jar:lib/netty-resolver-dns-4.1.42.Final.jar:lib/commons-collections-3.2.2.jar:
2020-03-16T13:04:45,985 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
2020-03-16T13:04:45,985 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=var/tmp
2020-03-16T13:04:45,985 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
2020-03-16T13:04:45,985 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux
2020-03-16T13:04:45,985 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
2020-03-16T13:04:45,985 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:os.version=4.19.84-microsoft-standard
2020-03-16T13:04:45,985 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:user.name=root
2020-03-16T13:04:45,985 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:user.home=/root
2020-03-16T13:04:45,985 INFO [main] org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/opt/apache-druid-0.17.0
2020-03-16T13:04:45,986 INFO [main] org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=druid.zookeeper sessionTimeout=30000 watcher=org.apache.curator.ConnectionState@6a3fbcb1
2020-03-16T13:04:45,988 DEBUG [main] org.apache.zookeeper.ClientCnxn - zookeeper.disableAutoWatchReset is false
2020-03-16T13:04:46,000 INFO [main] org.apache.curator.framework.imps.CuratorFrameworkImpl - Default schema
2020-03-16T13:04:46,001 DEBUG [main-SendThread(druid.zookeeper:2181)] org.apache.zookeeper.SaslServerPrincipal - Canonicalized address to druid.zookeeper.test_docker_compose_default
2020-03-16T13:04:46,001 DEBUG [main] org.apache.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking start method[public void org.apache.druid.java.util.metrics.MonitorScheduler.start()] on object[org.apache.druid.java.util.metrics.MonitorScheduler@773c2214].
2020-03-16T13:04:46,002 DEBUG [main] org.apache.druid.java.util.common.concurrent.ScheduledExecutors - Scheduling periodically: org.apache.druid.java.util.metrics.MonitorScheduler$1@6ee88e21 with period PT15S
2020-03-16T13:04:46,002 DEBUG [main] org.apache.druid.java.util.common.concurrent.ScheduledExecutors - Scheduling periodically: org.apache.druid.java.util.metrics.MonitorScheduler$1@2dd1086 with period PT15S
2020-03-16T13:04:46,002 INFO [main-SendThread(druid.zookeeper:2181)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server druid.zookeeper/172.28.0.3:2181. Will not attempt to authenticate using SASL (unknown error)
2020-03-16T13:04:46,003 DEBUG [main] org.apache.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking start method[public void org.apache.druid.storage.hdfs.HdfsStorageAuthentication.authenticate()] on object[org.apache.druid.storage.hdfs.HdfsStorageAuthentication@79957f11].
2020-03-16T13:04:46,004 DEBUG [main] org.apache.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking start method[public void org.apache.druid.indexing.overlord.MetadataTaskStorage.start()] on object[org.apache.druid.indexing.overlord.MetadataTaskStorage@217235f5].
2020-03-16T13:04:46,006 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Table[druid_tasks] already exists
2020-03-16T13:04:46,007 INFO [main-SendThread(druid.zookeeper:2181)] org.apache.zookeeper.ClientCnxn - Socket connection established to druid.zookeeper/172.28.0.3:2181, initiating session
2020-03-16T13:04:46,008 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Table[druid_tasklogs] already exists
2020-03-16T13:04:46,010 DEBUG [main-SendThread(druid.zookeeper:2181)] org.apache.zookeeper.ClientCnxn - Session establishment request sent on druid.zookeeper/172.28.0.3:2181
2020-03-16T13:04:46,012 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Table[druid_tasklocks] already exists
```

So is there anything wrong in middleManager? ( I'm sure all the configuration file are same in each druid components).

I'm willing to post my `conf` and `docker-compose.yml` if needed

**Comment by akamensky** [comment]
@Fullstop000 how did you solve this issue? I have the same "Unable to canonicalize" error in my logs, while other services connect to ZK just fine.

**Comment by vladComan0** [comment]
@akamensky Any luck finding the answer? I got that same error out of nowhere.
