### ISSUE TITLE
KILL TASK error - failed to delete .../0_descriptor.json

### ISSUE THREAD

**Issue by dataedgehungary** [apache/druid#9540]
### Affected Version

0.12.1 - HDP 3.1.4 install

### Description

Dear All,

I am trying to delete unused segment data from hdfs deep storage. I encounter a weird error and the kill task failes, with:

`2020-03-19T15:39:39,737 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[KillTask{id=kill_PONTMASTERDB.druid_vasarlas_2011068_2017-02-01T00:00:00.000Z_2017-03-01T00:00:00.000Z_2020-03-19T15:39:30.395Z, type=kill, dataSource=PONTMASTERDB.druid_vasarlas_2011068}]
io.druid.segment.loading.SegmentLoadingException: Unable to kill segment, failed to delete [hdfs://namenodeha/druid/segments/PONTMASTERDB.druid_vasarlas_2011068/20170201T000000.000Z_20170301T000000.000Z/2020-03-13T10_14_25.197+01_00/0_descriptor.json]
	at io.druid.storage.hdfs.HdfsDataSegmentKiller.kill(HdfsDataSegmentKiller.java:93) ~[?:?]
	at io.druid.segment.loading.OmniDataSegmentKiller.kill(OmniDataSegmentKiller.java:46) ~[druid-server-0.12.1.3.1.4.0-315.jar:0.12.1.3.1.4.0-315]
	at io.druid.indexing.common.task.KillTask.run(KillTask.java:103) ~[druid-indexing-service-0.12.1.3.1.4.0-315.jar:0.12.1.3.1.4.0-315]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:445) [druid-indexing-service-0.12.1.3.1.4.0-315.jar:0.12.1.3.1.4.0-315]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:417) [druid-indexing-service-0.12.1.3.1.4.0-315.jar:0.12.1.3.1.4.0-315]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) [guava-28.0-jre.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) [guava-28.0-jre.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) [guava-28.0-jre.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]`

My first guess is that it is trying to delete 0_descriptor.json but it does not find the file. On my HDFS tree, inside all the segments, there are 2 file:

0_index.zip
descriptor.json

The kill task successfully deletes the 0_index.zip, but returns error when it tries to delete 0_descriptor.json but that does not exists... 

Where do I go wrong? 

Thanks

**Comment by adamkahr** [comment]
I'm seeing the same issue 0_descriptor.json does not exist anywhere in hdfs... thought this might have been a permissions issue

@dataedgehungary was this problem ever resolved?

Thanks

**Comment by dataedgehungary** [comment]
Hey! I havent seen an official solution yet. We got around it with a small python script removing the data for the unused segments from the metastore and deleting the underlying files via hdfs api.
-------- Original message --------From: Adam Kahr <notifications@github.com> Date: 23/06/2020  21:49  (GMT+01:00) To: apache/druid <druid@noreply.github.com> Cc: dataedgehungary <mlekeny@dataedge.hu>, Mention <mention@noreply.github.com> Subject: Re: [apache/druid] KILL TASK error - failed to delete .../0_descriptor.json (#9540) 
I'm seeing the same issue 0_descriptor.json does not exist anywhere in hdfs... thought this might have been a permissions issue
@dataedgehungary was this problem ever resolved?
Thanks

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/druid/issues/9540#issuecomment-648381860",
"url": "https://github.com/apache/druid/issues/9540#issuecomment-648381860",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by adamkahr** [comment]
Thank you @dataedgehungary, looks like we will be doing the same type of thing... By any chance are you using the hive druid storage handler for ingest? 

Adam

**Comment by dataedgehungary** [comment]
Yes we ingest via Hive. 
null

**Comment by adamkahr** [comment]
interesting this might be a bug with in the Hive Druid Storage Handler...
