### ISSUE TITLE
druid-ranger-security failure when building distribution

### ISSUE THREAD

**Issue by jon-wei** [apache/druid#9629]
@Fokko 

I'm seeing the following when building a distribution tarball with `mvn clean && mvn install -DskipTests=true -Dtar -T 8`: 

```

13:57:40.592 [main] ERROR org.apache.druid.cli.PullDependencies - Unable to resolve artifacts for [org.apache.druid.extensions:druid-ranger-security:jar:0.19.0-SNAPSHOT (runtime) -> [] < [ (https://repo1.maven.org/maven2/, releases+snapshots)]].
org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.apache.druid.extensions:druid-ranger-security:jar:0.19.0-SNAPSHOT in  (https://repo1.maven.org/maven2/)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384) ~[aether-impl-0.9.0.M2.jar:?]
	at io.tesla.aether.internal.DefaultTeslaAether.resolveArtifacts(DefaultTeslaAether.java:289) ~[tesla-aether-0.0.5.jar:0.0.5]
	at org.apache.druid.cli.PullDependencies.downloadExtension(PullDependencies.java:404) [druid-services-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
	at org.apache.druid.cli.PullDependencies.downloadExtension(PullDependencies.java:362) [druid-services-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
	at org.apache.druid.cli.PullDependencies.run(PullDependencies.java:308) [druid-services-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
	at org.apache.druid.cli.Main.main(Main.java:113) [druid-services-0.19.0-SNAPSHOT.jar:0.19.0-SNAPSHOT]
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.apache.druid.extensions:druid-ranger-security:jar:0.19.0-SNAPSHOT in  (https://repo1.maven.org/maven2/)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:459) ~[aether-impl-0.9.0.M2.jar:?]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262) ~[aether-impl-0.9.0.M2.jar:?]
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367) ~[aether-impl-0.9.0.M2.jar:?]
	... 5 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache.druid.extensions:druid-ranger-security:jar:0.19.0-SNAPSHOT in  (https://repo1.maven.org/maven2/)
	at io.tesla.aether.connector.AetherRepositoryConnector$2.wrap(AetherRepositoryConnector.java:828) ~[aether-connector-okhttp-0.0.9.jar:0.0.9]
	at io.tesla.aether.connector.AetherRepositoryConnector$2.wrap(AetherRepositoryConnector.java:824) ~[aether-connector-okhttp-0.0.9.jar:0.0.9]
	at io.tesla.aether.connector.AetherRepositoryConnector$GetTask.flush(AetherRepositoryConnector.java:619) ~[aether-connector-okhttp-0.0.9.jar:0.0.9]
	at io.tesla.aether.connector.AetherRepositoryConnector.get(AetherRepositoryConnector.java:238) ~[aether-connector-okhttp-0.0.9.jar:0.0.9]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:535) ~[aether-impl-0.9.0.M2.jar:?]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:436) ~[aether-impl-0.9.0.M2.jar:?]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262) ~[aether-impl-0.9.0.M2.jar:?]
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367) ~[aether-impl-0.9.0.M2.jar:?]
	... 5 more
```

**Comment by jon-wei** [comment]
@bolkedebruin Can you take a look?

**Comment by bolkedebruin** [comment]
@jon-wei sure will do. But why is it reaching out to internet maven repository while 0.19 obviously hasn't been published yet?

**Comment by jon-wei** [comment]
The build would put the 0.19.0-SNAPSHOT artifacts in the local maven repo, maybe it's not finding druid-ranger-security there and falling back to trying a remote repo

**Comment by ccaominh** [comment]
@jon-wei I was able to reproduce the issue you saw. After running `mvn install -N` from the druid repo root, I'm able to successfully do a distribution build locally.

**Comment by bolkedebruin** [comment]
@jon-wei @ccaominh anything left for me to cover? Or is what @ccaominh suggest the correct fix?
