### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.druid.security.basic.BasicSecuritySSLSocketFactory

### ISSUE THREAD

**Issue by v-vishwa** [apache/druid#9720]
When a druid is configured to authenticate against SSL enabled LDAP server Coordinator service throws `ClassNotFoundException`

**Exception trace from coordinator log:**

```
Caused by: java.lang.ClassNotFoundException: org.apache.druid.security.basic.BasicSecuritySSLSocketFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
	at com.sun.jndi.ldap.VersionHelper12.loadClass(VersionHelper12.java:72) ~[?:1.8.0_242]
	at com.sun.jndi.ldap.Connection.createSocket(Connection.java:291) ~[?:1.8.0_242]
	at com.sun.jndi.ldap.Connection.<init>(Connection.java:213) ~[?:1.8.0_242]
	... 46 more
```

++++
**Steps to reproduce this issue:**
1) Configure druid to use SSL enabled LDAP authentication 
2) Start the master services. You can observe the exception in the coordinator log.

The issue can be quickly reproduced in micor start mode as well.
++++

**Few Interesting facts:**

1) Druid basic-security-extension is loaded and Verified that only one version of the druid-basic-security extension jar present into the druid security extension directory.

2)The coordinator log shows that the druid-basic-security extension jar being loaded.

3)Verified the druid-basic security extension jar and it has the BasicSecuritySSLSocketFactory.class

4) To extra confirm if BasicSecuritySSLSocketFactory class is loaded by coordinator JVM or not, Enabled verbose class loading and this confirms the BasicSecuritySSLSocketFactory class being loaded by the class loader, but still, coordinator throws `ClassNotFoundException`

`[Loaded org.apache.druid.security.basic.BasicSecuritySSLSocketFactory from file:<path to softeare>/druid-basic-security/druid-basic-security-0.17.1.jar:0.17.1]`

**Workaround:** – I placed druid-security-extension jar into the druid lib directory and restarted the server and this resolves the ClassNotFoundException.

It seems some jar dependency issues.

**Comment by anton-antonenko** [comment]
Hi, I'm getting the same issue.
@mohammadjkhan can you assist, please?

**Comment by v-vishwa** [comment]
@anton-antonenko 

Did you try below workaround ?

**COPY** `druid-basic-security-$version.jar`

**FROM** `druid/dist/druid/extensions/druid-basic-security`

**TO** `druid/dist/druid/lib` Directory

**Comment by anton-antonenko** [comment]
@v-vishwa not yet, I hoped that there's a different solution which doesn't include copying jars

**Comment by mohammadjkhan** [comment]
@anton-antonenko I believe that's the just standard way to go about incorporating extensions in Druid
