### ISSUE TITLE
Druid tasks failed: Triggering JVM shutdown.

### ISSUE THREAD

**Issue by HoraceLee** [apache/druid#9774]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version
apache-druid-0.17.0

The Druid version where the problem was encountered.

### Description
I installed my Druid cluster on the ARM machine. the supervisors can run, but the tasks failed because of the jvm error.

My java environment setting are as follows:
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181.b15-5.h3.eulerosv2r8.aarch64/jre
CLASSPATH=$JAVA_HOME/lib/ 
PATH=$PATH:$JAVA_HOME/bin 
export PATH JAVA_HOME CLASSPATH

Here is the task log : 
2020-04-26T01:55:54,261 DEBUG [main-SendThread(10.0.143.37:2181)] org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x100003127200022, packet:: clientPath:/druid/internal-discovery/OVERLORD serverPath:/druid/internal-discovery/OVERLORD finished:false header:: 30,12  replyHeader:: 30,4294967989,0  request:: '/druid/internal-discovery/OVERLORD,T  response:: v{'10.0.141.215:8081,'10.0.137.189:8081},s{4294967308,4294967308,1586425848814,1586425848814,0,6,0,0,0,2,4294967964} 
2020-04-26T01:55:54,263 DEBUG [main-SendThread(10.0.143.37:2181)] org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x100003127200022, packet:: clientPath:null serverPath:null finished:false header:: 31,4  replyHeader:: 31,4294967989,0  request:: '/druid/internal-discovery/COORDINATOR/10.0.141.215:8081,F  response:: #1fffffff8b8000000055ffffff8f41effffffc2201045ffffffef326b4430ffffff9a34ffffff9effffffc0ffffff95ffffffb2ffffffe856819239ffffff8166ffffffa0ffffff8dffffffa6ffffffe9ffffffdd1dffffffd1ffffff9a74fffffff779ffffff9fffffff99ffffffbcffffff99ffffffc1ffffffd1ffffffe8ffffffdd3539ffffff84fffffff3c1969fffffff23dffffffc72fffffffdefffffff729ffffff91fffffff3ffffffd1ffffff964420ffffffe0ffffff9172ffffffe14a2bffffffa9ffffffa43e6a79ffffffd027ffffffa6ffffff9dffffff8fffffffee162fffffffb5ffffffbbffffffdbffffff9051ffffffc010ffffffacffffff8f5ffffff9fffffffc52462ffffffdaffffffa84633ffffffac79ffffffc7ffffffa9ffffff846cfffffffefffffff8cffffffb6b68ffffffb613ffffff85465cffffffab76fffffffd5dffffff972f222ffffffcbffffffb6ffffffafffffffe163ffffffb9fffffff5fffffffbffffffd967ffffffbe6459ffffffde3cffffffb2ffffff93ffffffd6ffffffda000,s{4294967963,4294967963,1587865775087,1587865775087,0,0,0,144115399142998042,160,0,4294967963} 
2020-04-26T01:55:54,265 DEBUG [main-SendThread(10.0.143.37:2181)] org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x100003127200022, packet:: clientPath:/druid/internal-discovery/OVERLORD/10.0.141.215:8081 serverPath:/druid/internal-discovery/OVERLORD/10.0.141.215:8081 finished:false header:: 32,4  replyHeader:: 32,4294967989,0  request:: '/druid/internal-discovery/OVERLORD/10.0.141.215:8081,T  response:: #1fffffff8b8000000055ffffff8f41affffffc2301045ffffffef32ffffffeb58135128ffffff9effffffc0ffffff9566ffffffd1bffffffa4ffffffcdffffff88ffffff81ffffff9029ffffff93ffffffb4544affffffefffffffee58ffffffadffffffe0ffffffeeffffffe7fffffffdffffffccfffffff0666ffffffcf43fffffff057fffffff28ffffffe71932fffffff2183affffff891fffffffbcffffffefffffff88ffffffd8ffffff87ffffffe4a312878502e52195dffffffe9ffffffca1c4d753027ffffffa16d48fffffffeffffff962e6b777731ffffffa3ffffff823effffffbaffffff90a4effffffc512bffffffad756d4ffffffae7927ffffffa9ffffffc46c7ff4cffffffaeffffff8d68ffffffff27afffffffb855ffffffcdfffffff67b5dffffffbe284822ffffffdb3cfffffffbffffffb725ffffff8dffffffc8511445ffffffe3ffffffabffffff9effffffe5ffffff8c657916cffffffa1ffffffe1ffffffcaffffffd7000,s{4294967964,4294967964,1587865775093,1587865775093,0,0,0,144115399142998042,165,0,4294967964} 
2020-04-26T01:55:54,266 DEBUG [main-SendThread(10.0.143.37:2181)] org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x100003127200022, packet:: clientPath:/druid/internal-discovery/OVERLORD/10.0.137.189:8081 serverPath:/druid/internal-discovery/OVERLORD/10.0.137.189:8081 finished:false header:: 33,4  replyHeader:: 33,4294967989,0  request:: '/druid/internal-discovery/OVERLORD/10.0.137.189:8081,T  response:: #1fffffff8b8000000055ffffff8f31effffffc230c45ffffffefffffffe2ffffffb9ffffff9446c44effffffc04197affffff81ffffffb431225214574e5a1555ffffffb93bffffffa65024ffffffb6ffffff9ffffffff763ffffffeb791ffffffc7ffffffa37757728ffffffe7512fffffff2ffffffe47bffffff891fffffffbcffffffefffffff89ffffffd8fffffff968333154fffffff0ffffffa0ffffff94ffffffa5524dffffffddffffffd4ffffffea70ffffffacffffff953e9ffffffed7c74ffffffb77859ffffffbbffffffbbd92b18ffffff82fffffff531ffffffe3ffffff9cdffffffb150ffffffdd682570ffffffcd3b493924fffffff37b60ffffffb45d40fffffff33fffffff9179ffffffc4ffffffad6affffffb7ffffffdfffffffebfffffff2524114ffffffd9fffffff639ffffffbc2d6942effffffa2281a5ffffffff52467ffffff94fffffff22ffffff95dffffffbf3bffffffd7000,s{4294967962,4294967962,1587865774795,1587865774795,0,0,0,72057805147734048,165,0,4294967962} 
2020-04-26T01:55:54,268 DEBUG [main-SendThread(10.0.143.37:2181)] org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x100003127200022, packet:: clientPath:null serverPath:null finished:false header:: 34,4  replyHeader:: 34,4294967989,0  request:: '/druid/internal-discovery/OVERLORD/10.0.141.215:8081,F  response:: #1fffffff8b8000000055ffffff8f41affffffc2301045ffffffef32ffffffeb58135128ffffff9effffffc0ffffff9566ffffffd1bffffffa4ffffffcdffffff88ffffff81ffffff9029ffffff93ffffffb4544affffffefffffffee58ffffffadffffffe0ffffffeeffffffe7fffffffdffffffccfffffff0666ffffffcf43fffffff057fffffff28ffffffe71932fffffff2183affffff891fffffffbcffffffefffffff88ffffffd8ffffff87ffffffe4a312878502e52195dffffffe9ffffffca1c4d753027ffffffa16d48fffffffeffffff962e6b777731ffffffa3ffffff823effffffbaffffff90a4effffffc512bffffffad756d4ffffffae7927ffffffa9ffffffc46c7ff4cffffffaeffffff8d68ffffffff27afffffffb855ffffffcdfffffff67b5dffffffbe284822ffffffdb3cfffffffbffffffb725ffffff8dffffffc8511445ffffffe3ffffffabffffff9effffffe5ffffff8c657916cffffffa1ffffffe1ffffffcaffffffd7000,s{4294967964,4294967964,1587865775093,1587865775093,0,0,0,144115399142998042,165,0,4294967964} 
2020-04-26T01:55:54,281 INFO [NodeRoleWatcher[COORDINATOR]] org.apache.druid.curator.discovery.CuratorDruidNodeDiscoveryProvider$NodeRoleWatcher - Node[http://10.0.141.215:8081] of role[coordinator] detected.
2020-04-26T01:55:54,281 INFO [NodeRoleWatcher[OVERLORD]] org.apache.druid.curator.discovery.CuratorDruidNodeDiscoveryProvider$NodeRoleWatcher - Node[http://10.0.141.215:8081] of role[overlord] detected.
2020-04-26T01:55:54,283 DEBUG [main-SendThread(10.0.143.37:2181)] org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x100003127200022, packet:: clientPath:null serverPath:null finished:false header:: 35,4  replyHeader:: 35,4294967989,0  request:: '/druid/internal-discovery/COORDINATOR/10.0.137.189:8081,F  response:: #1fffffff8b8000000055ffffff8f41effffffc2201045ffffffef326b44ffffff88bffffffd113ffffffb85216ffffffbd02d632421ffffffd006d34d7777446bffffffd2ffffffddffffffe77d66fffffff2661ffffff9b2667ffffffafffffffd122ffffff9c17ffffffc8ffffff98663750fffffffcffffffe2fffffffd1063ffffffb22effffff9812133078ffffffc45cffffffa8ffffff92ffffff82b2ef472effffffd5ffffff8968ffffffefffffff82ffffffbdffffff854bffffffebffffffeeffffffc66764307affffffe342ffffffc167ffffffd13111554249ffffff822dffffffef2815ffffff9ffffffff5ffffffffffffff81ffffffc1fffffff41efffffff576ffffffa2ffffffa49ffffffd7ffffffaa5b7fffffffb7ffffffe5ffffff954120ffffffd9ffffffee357e2cffffffb77e3ffffffffb4cffffff97ffffffd4fffffffa6ffffff8475ffffffe7ffffffe2ffffffda000,s{4294967961,4294967961,1587865774788,1587865774788,0,0,0,72057805147734048,160,0,4294967961} 
2020-04-26T01:55:54,283 INFO [NodeRoleWatcher[COORDINATOR]] org.apache.druid.curator.discovery.CuratorDruidNodeDiscoveryProvider$NodeRoleWatcher - Node[http://10.0.137.189:8081] of role[coordinator] detected.
2020-04-26T01:55:54,283 INFO [NodeRoleWatcher[COORDINATOR]] org.apache.druid.curator.discovery.CuratorDruidNodeDiscoveryProvider$NodeRoleWatcher - Node watcher of role[coordinator] is now initialized.
2020-04-26T01:55:54,285 DEBUG [main-SendThread(10.0.143.37:2181)] org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x100003127200022, packet:: clientPath:null serverPath:null finished:false header:: 36,4  replyHeader:: 36,4294967989,0  request:: '/druid/internal-discovery/OVERLORD/10.0.137.189:8081,F  response:: #1fffffff8b8000000055ffffff8f31effffffc230c45ffffffefffffffe2ffffffb9ffffff9446c44effffffc04197affffff81ffffffb431225214574e5a1555ffffffb93bffffffa65024ffffffb6ffffff9ffffffff763ffffffeb791ffffffc7ffffffa37757728ffffffe7512fffffff2ffffffe47bffffff891fffffffbcffffffefffffff89ffffffd8fffffff968333154fffffff0ffffffa0ffffff94ffffffa5524dffffffddffffffd4ffffffea70ffffffacffffff953e9ffffffed7c74ffffffb77859ffffffbbffffffbbd92b18ffffff82fffffff531ffffffe3ffffff9cdffffffb150ffffffdd682570ffffffcd3b493924fffffff37b60ffffffb45d40fffffff33fffffff9179ffffffc4ffffffad6affffffb7ffffffdfffffffebfffffff2524114ffffffd9fffffff639ffffffbc2d6942effffffa2281a5ffffffff52467ffffff94fffffff22ffffff95dffffffbf3bffffffd7000,s{4294967962,4294967962,1587865774795,1587865774795,0,0,0,72057805147734048,165,0,4294967962} 
2020-04-26T01:55:54,286 INFO [NodeRoleWatcher[OVERLORD]] org.apache.druid.curator.discovery.CuratorDruidNodeDiscoveryProvider$NodeRoleWatcher - Node[http://10.0.137.189:8081] of role[overlord] detected.
2020-04-26T01:55:54,286 INFO [NodeRoleWatcher[OVERLORD]] org.apache.druid.curator.discovery.CuratorDruidNodeDiscoveryProvider$NodeRoleWatcher - Node watcher of role[overlord] is now initialized.
2020-04-26T01:55:54,424 INFO [main] org.apache.druid.indexing.worker.executor.ExecutorLifecycle - Running with task: {
	...
}
2020-04-26T01:55:54,427 INFO [main] org.apache.druid.indexing.worker.executor.ExecutorLifecycle - Attempting to lock file[var/druid/task/index_kafka_CCOPS_WL_1_2_EVENT_FRONT_16a77035ef356fc_imjbpjlh/lock].
2020-04-26T01:55:54,431 INFO [main] org.apache.druid.indexing.worker.executor.ExecutorLifecycle - Acquired lock file[var/druid/task/index_kafka_CCOPS_WL_1_2_EVENT_FRONT_16a77035ef356fc_imjbpjlh/lock] in 4ms.
2020-04-26T01:55:54,433 INFO [parent-monitor-0] org.apache.druid.indexing.worker.executor.ExecutorLifecycle - Triggering JVM shutdown.

I have read the logs of the middle manager, coordinator, broker, and I didn’t see anything abnormal

![druid tasks error](https://user-images.githubusercontent.com/9915526/80295906-6449c380-87a9-11ea-918e-bff5186fcbd4.PNG)

**Comment by HoraceLee** [comment]
Exception Logs on MiddleManager:

2020-04-26T02:43:40,217 DEBUG [qtp512029640-112] org.eclipse.jetty.io.WriteFlusher - ignored: WriteFlusher@1db05c2f{IDLE}->null
java.nio.channels.ClosedChannelException: null
        at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:502) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:353) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.ChannelEndPoint.onClose(ChannelEndPoint.java:216) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:225) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.AbstractEndPoint.shutdownInput(AbstractEndPoint.java:107) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.ChannelEndPoint.fill(ChannelEndPoint.java:241) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:331) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:243) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
