### ISSUE TITLE
Web console e2e test failing locally

### ISSUE THREAD

**Issue by pjain1** [apache/druid#9802]
I am trying to run e2e tests locally on the latest master branch with druid processes running at standard ports without any security enabled. I can access the console at localhost:8888. However, when I run `jest --config jest.e2e.config.js --detectOpenHandles e2e-tests`, I get the following error -

```
node_modules/.bin/jest --config jest.e2e.config.js --detectOpenHandles e2e-tests
 FAIL  e2e-tests/tutorial-batch.spec.ts (32.427s)
  Tutorial: Loading a file
    ✕ Loads data from local disk (31378ms)

  ● Tutorial: Loading a file › Loads data from local disk

    TimeoutError: waiting for selector ".raw-lines" failed: timeout 30000ms exceeded

      66 |   private async validateConnect(validator: (preview: string) => void) {
      67 |     const previewSelector = '.raw-lines';
    > 68 |     await this.page.waitFor(previewSelector);
         |                     ^
      69 |     const preview = await this.page.$eval(previewSelector, el => (el as HTMLTextAreaElement).value);
      70 |     validator(preview!);
      71 |   }

      at new RerunnableTask (node_modules/playwright-core/lib/frames.js:822:34)
      at Frame._scheduleRerunnableTask (node_modules/playwright-core/lib/frames.js:770:32)
      at Frame._waitForSelectorInUtilityContext (node_modules/playwright-core/lib/frames.js:741:35)
      at Frame.waitForSelector (node_modules/playwright-core/lib/frames.js:485:35)
      at Frame.<anonymous> (node_modules/playwright-core/lib/helper.js:55:31)
      at Frame.waitFor (node_modules/playwright-core/lib/frames.js:710:25)
      at Frame.<anonymous> (node_modules/playwright-core/lib/helper.js:55:31)
      at Page.waitFor (node_modules/playwright-core/lib/page.js:383:33)
      at Page.<anonymous> (node_modules/playwright-core/lib/helper.js:55:31)
      at DataLoader.<anonymous> (e2e-tests/component/load-data/data-loader.ts:68:21)
      at step (node_modules/tslib/tslib.js:136:27)
      at Object.next (node_modules/tslib/tslib.js:117:57)
      at node_modules/tslib/tslib.js:110:75
      at Object.__awaiter (node_modules/tslib/tslib.js:106:16)
      at DataLoader.Object.<anonymous>.DataLoader.validateConnect (e2e-tests/component/load-data/data-loader.ts:111:24)
      at DataLoader.<anonymous> (e2e-tests/component/load-data/data-loader.ts:62:16)
      at step (node_modules/tslib/tslib.js:136:27)
      at Object.next (node_modules/tslib/tslib.js:117:57)
      at fulfilled (node_modules/tslib/tslib.js:107:62)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        32.98s, estimated 33s
Ran all test suites matching /e2e-tests/i.

```
What might be the issue ? @ccaominh

**Comment by pjain1** [comment]
ok figured out the issue, I was not running druid from tar ball but directly from IDE so the location to file `wikiticker-2015-09-12-sampled.json.gz` was different and that's why it was failing.

**Comment by ccaominh** [comment]
Sorry for the late response, but I'm adding some comments here in case anyone finds this issue when trying to debug the end-to-end tests.

From the stack trace, the data loader failed during the "connect" step. Specifically, the preview of the raw data did not appear in the web console.

When the e2e test fails, it'll dump a screen shot of the of the web console at the time of test failure, which can be helpful for debugging. For this particular test, the screen shot is named `load-data-from-local-disk-screenshot.png`.

Disabling headless mode while running the tests can also be helpful for debugging. One way of doing this is by modifying `tutorial-batch.spec.ts` to change:

```
import { createBrowserNormal as createBrowser } from './util/playwright';
```

to

```
import { createBrowserDebug as createBrowser } from './util/playwright';
```


Once that's done, running the tests will launch a chromium instance and you can watch all the interactions with the web console.

**Comment by pjain1** [comment]
thanks makes sense, I was able to find the problem after looking at the screenshot but took me a long time to find it. Disabling headless mode sound nice, it would be great to check in these notes probably in web console readme.

**Comment by ccaominh** [comment]
I've opened https://github.com/apache/druid/pull/9864 to add some docs to the web console readme.
