### ISSUE TITLE
preparedStatement report Node could not be implemented

### ISSUE THREAD

**Issue by zhcwang** [apache/druid#9862]
Java preparedStatement works abnormal while Statement is okay. 

# Affected Version

docker images version : 0.16.0-incubating

### Description
**K8S pods list:**

1. space-druid-broker-5995f96448-bfv5m                   
2. space-druid-coordinator-6c5557f446-xkvdp                       
3. space-druid-historical-646dfd566-dj9q8                        
4. space-druid-middlemanager-5bc6d4d477-6dlcz                     
5. space-druid-overlord-7fd5b46745-db6gj                    
6. space-druid-router-7979b7cc56-gq45j 
               
**JDBC code demo:**
```
public static void main(String[] args) throws Exception {
        String url = "jdbc:avatica:remote:url=https://xxxx/druid/v2/sql/avatica/";
        Properties connectionProperties = new Properties();
        String sqlStr = "SELECT * FROM \"test\" WHERE (\"process_id\" = ?) AND (\"signal_id\" = ?)";
        try {
            Connection connection = DriverManager.getConnection(url, connectionProperties);
            PreparedStatement preparedStatement = connection.prepareStatement(sqlStr);
            preparedStatement.setString(1, "10217");
            preparedStatement.setString(2, "3032543");
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                System.out.println(" druid rs is " + resultSet.getObject(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
**Detail log:**

org.apache.calcite.avatica.AvaticaSqlException: Error -1 (00000) : while preparing SQL: SELECT * FROM "test" WHERE ("process_id" = ?) AND ("signal_id" = ?)
	at org.apache.calcite.avatica.Helper.createException(Helper.java:54)
	at org.apache.calcite.avatica.Helper.createException(Helper.java:41)
	at org.apache.calcite.avatica.AvaticaConnection.prepareStatement(AvaticaConnection.java:358)
	at org.apache.calcite.avatica.AvaticaConnection.prepareStatement(AvaticaConnection.java:175)
	at io.zontal.space.prestosql.plugin.druid.Test.main(Test.java:19)
java.lang.RuntimeException: org.apache.calcite.plan.RelOptPlanner$CannotPlanException: Node [rel#3087070:Subset#1.DRUID.[]] could not be implemented; planner state:

Root: rel#3087070:Subset#1.DRUID.[]
Original rel:
LogicalProject(subset=[rel#3087068:Subset#2.DRUID.[]], __time=[$0], cube_iri=[$1], process_id=[$2], signal_class=[$3], signal_id=[$4], x_concept=[$5], x_unit_symbol=[$6], x_value_double=[$7], y_concept=[$8], y_unit_symbol=[$9], y_value_double=[$10], y_value_float=[$11], y_value_int=[$12], y_value_text=[$13]): rowcount = 2.25, cumulative cost = {2.25 rows, 31.5 cpu, 0.0 io}, id = 3087066
  LogicalFilter(subset=[rel#3087065:Subset#1.NONE.[]], condition=[AND(=($2, ?0), =($4, ?1))]): rowcount = 2.25, cumulative cost = {2.25 rows, 100.0 cpu, 0.0 io}, id = 3087064
    LogicalTableScan(subset=[rel#3087063:Subset#0.NONE.[]], table=[[druid, test]]): rowcount = 100.0, cumulative cost = {100.0 rows, 101.0 cpu, 0.0 io}, id = 3087055

Sets:
Set#0, type: RecordType(TIMESTAMP(3) __time, VARCHAR cube_iri, VARCHAR process_id, VARCHAR signal_class, VARCHAR signal_id, VARCHAR x_concept, VARCHAR x_unit_symbol, DOUBLE x_value_double, VARCHAR y_concept, VARCHAR y_unit_symbol, DOUBLE y_value_double, FLOAT y_value_float, BIGINT y_value_int, VARCHAR y_value_text)
	rel#3087063:Subset#0.NONE.[], best=null, importance=0.81
		rel#3087055:LogicalTableScan.NONE.[](table=[druid, test]), rowcount=100.0, cumulative cost={inf}
		rel#3087071:DruidQueryRel.NONE.[](query={"queryType":"scan","dataSource":{"type":"table","name":"test"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775807,"order":"none","filter":null,"columns":["__time","cube_iri","process_id","signal_class","signal_id","x_concept","x_unit_symbol","x_value_double","y_concept","y_unit_symbol","y_value_double","y_value_float","y_value_int","y_value_text"],"legacy":false,"context":{"sqlQueryId":"0dcf7b7b-7fea-410c-be30-3cdb1cce2068"},"descending":false,"granularity":{"type":"all"}},signature={__time:LONG, cube_iri:STRING, process_id:STRING, signal_class:STRING, signal_id:STRING, x_concept:STRING, x_unit_symbol:STRING, x_value_double:DOUBLE, y_concept:STRING, y_unit_symbol:STRING, y_value_double:DOUBLE, y_value_float:FLOAT, y_value_int:LONG, y_value_text:STRING}), rowcount=1.0, cumulative cost={inf}
	rel#3087074:Subset#0.DRUID.[], best=rel#3087073, importance=0.405
		rel#3087073:DruidQueryRel.DRUID.[](query={"queryType":"scan","dataSource":{"type":"table","name":"test"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775807,"order":"none","filter":null,"columns":["__time","cube_iri","process_id","signal_class","signal_id","x_concept","x_unit_symbol","x_value_double","y_concept","y_unit_symbol","y_value_double","y_value_float","y_value_int","y_value_text"],"legacy":false,"context":{"sqlQueryId":"0dcf7b7b-7fea-410c-be30-3cdb1cce2068"},"descending":false,"granularity":{"type":"all"}},signature={__time:LONG, cube_iri:STRING, process_id:STRING, signal_class:STRING, signal_id:STRING, x_concept:STRING, x_unit_symbol:STRING, x_value_double:DOUBLE, y_concept:STRING, y_unit_symbol:STRING, y_value_double:DOUBLE, y_value_float:FLOAT, y_value_int:LONG, y_value_text:STRING}), rowcount=1.0, cumulative cost={1.0 rows, 0.0 cpu, 0.0 io}
Set#1, type: RecordType(TIMESTAMP(3) __time, VARCHAR cube_iri, VARCHAR process_id, VARCHAR signal_class, VARCHAR signal_id, VARCHAR x_concept, VARCHAR x_unit_symbol, DOUBLE x_value_double, VARCHAR y_concept, VARCHAR y_unit_symbol, DOUBLE y_value_double, FLOAT y_value_float, BIGINT y_value_int, VARCHAR y_value_text)
	rel#3087065:Subset#1.NONE.[], best=null, importance=0.9
		rel#3087064:LogicalFilter.NONE.[](input=rel#3087063:Subset#0.NONE.[],condition=AND(=($2, ?0), =($4, ?1))), rowcount=2.25, cumulative cost={inf}
		rel#3087066:LogicalProject.NONE.[](input=rel#3087065:Subset#1.NONE.[],__time=$0,cube_iri=$1,process_id=$2,signal_class=$3,signal_id=$4,x_concept=$5,x_unit_symbol=$6,x_value_double=$7,y_concept=$8,y_unit_symbol=$9,y_value_double=$10,y_value_float=$11,y_value_int=$12,y_value_text=$13), rowcount=2.25, cumulative cost={inf}
	rel#3087070:Subset#1.DRUID.[], best=null, importance=0.45
		rel#3087069:AbstractConverter.DRUID.[](input=rel#3087065:Subset#1.NONE.[],convention=DRUID,sort=[]), rowcount=2.25, cumulative cost={inf}

	at org.apache.druid.sql.avatica.DruidStatement.prepare(DruidStatement.java:175)
	at org.apache.druid.sql.avatica.DruidMeta.prepare(DruidMeta.java:157)
	at org.apache.calcite.avatica.remote.LocalService.apply(LocalService.java:195)
	at org.apache.calcite.avatica.remote.Service$PrepareRequest.accept(Service.java:1215)
	at org.apache.calcite.avatica.remote.Service$PrepareRequest.accept(Service.java:1186)
	at org.apache.calcite.avatica.remote.AbstractHandler.apply(AbstractHandler.java:94)
	at org.apache.calcite.avatica.remote.JsonHandler.apply(JsonHandler.java:52)
	at org.apache.calcite.avatica.server.AvaticaJsonHandler.handle(AvaticaJsonHandler.java:130)
	at org.apache.druid.sql.avatica.DruidAvaticaHandler.handle(DruidAvaticaHandler.java:59)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:291)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:151)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.calcite.plan.RelOptPlanner$CannotPlanException: Node [rel#3087070:Subset#1.DRUID.[]] could not be implemented; planner state:

Root: rel#3087070:Subset#1.DRUID.[]
Original rel:
LogicalProject(subset=[rel#3087068:Subset#2.DRUID.[]], __time=[$0], cube_iri=[$1], process_id=[$2], signal_class=[$3], signal_id=[$4], x_concept=[$5], x_unit_symbol=[$6], x_value_double=[$7], y_concept=[$8], y_unit_symbol=[$9], y_value_double=[$10], y_value_float=[$11], y_value_int=[$12], y_value_text=[$13]): rowcount = 2.25, cumulative cost = {2.25 rows, 31.5 cpu, 0.0 io}, id = 3087066
  LogicalFilter(subset=[rel#3087065:Subset#1.NONE.[]], condition=[AND(=($2, ?0), =($4, ?1))]): rowcount = 2.25, cumulative cost = {2.25 rows, 100.0 cpu, 0.0 io}, id = 3087064
    LogicalTableScan(subset=[rel#3087063:Subset#0.NONE.[]], table=[[druid, test]]): rowcount = 100.0, cumulative cost = {100.0 rows, 101.0 cpu, 0.0 io}, id = 3087055

Sets:
Set#0, type: RecordType(TIMESTAMP(3) __time, VARCHAR cube_iri, VARCHAR process_id, VARCHAR signal_class, VARCHAR signal_id, VARCHAR x_concept, VARCHAR x_unit_symbol, DOUBLE x_value_double, VARCHAR y_concept, VARCHAR y_unit_symbol, DOUBLE y_value_double, FLOAT y_value_float, BIGINT y_value_int, VARCHAR y_value_text)
	rel#3087063:Subset#0.NONE.[], best=null, importance=0.81
		rel#3087055:LogicalTableScan.NONE.[](table=[druid, test]), rowcount=100.0, cumulative cost={inf}
		rel#3087071:DruidQueryRel.NONE.[](query={"queryType":"scan","dataSource":{"type":"table","name":"test"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775807,"order":"none","filter":null,"columns":["__time","cube_iri","process_id","signal_class","signal_id","x_concept","x_unit_symbol","x_value_double","y_concept","y_unit_symbol","y_value_double","y_value_float","y_value_int","y_value_text"],"legacy":false,"context":{"sqlQueryId":"0dcf7b7b-7fea-410c-be30-3cdb1cce2068"},"descending":false,"granularity":{"type":"all"}},signature={__time:LONG, cube_iri:STRING, process_id:STRING, signal_class:STRING, signal_id:STRING, x_concept:STRING, x_unit_symbol:STRING, x_value_double:DOUBLE, y_concept:STRING, y_unit_symbol:STRING, y_value_double:DOUBLE, y_value_float:FLOAT, y_value_int:LONG, y_value_text:STRING}), rowcount=1.0, cumulative cost={inf}
	rel#3087074:Subset#0.DRUID.[], best=rel#3087073, importance=0.405
		rel#3087073:DruidQueryRel.DRUID.[](query={"queryType":"scan","dataSource":{"type":"table","name":"test"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775807,"order":"none","filter":null,"columns":["__time","cube_iri","process_id","signal_class","signal_id","x_concept","x_unit_symbol","x_value_double","y_concept","y_unit_symbol","y_value_double","y_value_float","y_value_int","y_value_text"],"legacy":false,"context":{"sqlQueryId":"0dcf7b7b-7fea-410c-be30-3cdb1cce2068"},"descending":false,"granularity":{"type":"all"}},signature={__time:LONG, cube_iri:STRING, process_id:STRING, signal_class:STRING, signal_id:STRING, x_concept:STRING, x_unit_symbol:STRING, x_value_double:DOUBLE, y_concept:STRING, y_unit_symbol:STRING, y_value_double:DOUBLE, y_value_float:FLOAT, y_value_int:LONG, y_value_text:STRING}), rowcount=1.0, cumulative cost={1.0 rows, 0.0 cpu, 0.0 io}
Set#1, type: RecordType(TIMESTAMP(3) __time, VARCHAR cube_iri, VARCHAR process_id, VARCHAR signal_class, VARCHAR signal_id, VARCHAR x_concept, VARCHAR x_unit_symbol, DOUBLE x_value_double, VARCHAR y_concept, VARCHAR y_unit_symbol, DOUBLE y_value_double, FLOAT y_value_float, BIGINT y_value_int, VARCHAR y_value_text)
	rel#3087065:Subset#1.NONE.[], best=null, importance=0.9
		rel#3087064:LogicalFilter.NONE.[](input=rel#3087063:Subset#0.NONE.[],condition=AND(=($2, ?0), =($4, ?1))), rowcount=2.25, cumulative cost={inf}
		rel#3087066:LogicalProject.NONE.[](input=rel#3087065:Subset#1.NONE.[],__time=$0,cube_iri=$1,process_id=$2,signal_class=$3,signal_id=$4,x_concept=$5,x_unit_symbol=$6,x_value_double=$7,y_concept=$8,y_unit_symbol=$9,y_value_double=$10,y_value_float=$11,y_value_int=$12,y_value_text=$13), rowcount=2.25, cumulative cost={inf}
	rel#3087070:Subset#1.DRUID.[], best=null, importance=0.45
		rel#3087069:AbstractConverter.DRUID.[](input=rel#3087065:Subset#1.NONE.[],convention=DRUID,sort=[]), rowcount=2.25, cumulative cost={inf}

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:437)
	at org.apache.calcite.plan.volcano.RelSubset.buildCheapestPlan(RelSubset.java:296)
	at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:662)
	at org.apache.calcite.tools.Programs$RuleSetProgram.run(Programs.java:339)
	at org.apache.calcite.tools.Programs$SequenceProgram.run(Programs.java:358)
	at org.apache.calcite.prepare.PlannerImpl.transform(PlannerImpl.java:337)
	at org.apache.druid.sql.calcite.planner.DruidPlanner.planWithDruidConvention(DruidPlanner.java:119)
	at org.apache.druid.sql.calcite.planner.DruidPlanner.plan(DruidPlanner.java:89)
	at org.apache.druid.sql.SqlLifecycle.plan(SqlLifecycle.java:141)
	at org.apache.druid.sql.SqlLifecycle.planAndAuthorize(SqlLifecycle.java:207)
	at org.apache.druid.sql.avatica.DruidStatement.prepare(DruidStatement.java:155)
	... 28 more
	Suppressed: org.apache.calcite.plan.RelOptPlanner$CannotPlanException: Node [rel#3087089:Subset#4.BINDABLE.[]] could not be implemented; planner state:

Root: rel#3087089:Subset#4.BINDABLE.[]
Original rel:
LogicalProject(subset=[rel#3087086:Subset#5.BINDABLE.[]], __time=[$0], cube_iri=[$1], process_id=[$2], signal_class=[$3], signal_id=[$4], x_concept=[$5], x_unit_symbol=[$6], x_value_double=[$7], y_concept=[$8], y_unit_symbol=[$9], y_value_double=[$10], y_value_float=[$11], y_value_int=[$12], y_value_text=[$13]): rowcount = 2.25, cumulative cost = {2.25 rows, 31.5 cpu, 0.0 io}, id = 3087084
  LogicalFilter(subset=[rel#3087083:Subset#4.NONE.[]], condition=[AND(=($2, ?0), =($4, ?1))]): rowcount = 2.25, cumulative cost = {2.25 rows, 100.0 cpu, 0.0 io}, id = 3087082
    LogicalTableScan(subset=[rel#3087081:Subset#3.NONE.[]], table=[[druid, test]]): rowcount = 100.0, cumulative cost = {100.0 rows, 101.0 cpu, 0.0 io}, id = 3087055

Sets:
Set#3, type: RecordType(TIMESTAMP(3) __time, VARCHAR cube_iri, VARCHAR process_id, VARCHAR signal_class, VARCHAR signal_id, VARCHAR x_concept, VARCHAR x_unit_symbol, DOUBLE x_value_double, VARCHAR y_concept, VARCHAR y_unit_symbol, DOUBLE y_value_double, FLOAT y_value_float, BIGINT y_value_int, VARCHAR y_value_text)
	rel#3087081:Subset#3.NONE.[], best=null, importance=0.81
		rel#3087055:LogicalTableScan.NONE.[](table=[druid, test]), rowcount=100.0, cumulative cost={inf}
	rel#3087096:Subset#3.BINDABLE.[], best=null, importance=0.9
		rel#3087099:InterpretableConverter.BINDABLE.[](input=rel#3087081:Subset#3.NONE.[]), rowcount=100.0, cumulative cost={inf}
Set#4, type: RecordType(TIMESTAMP(3) __time, VARCHAR cube_iri, VARCHAR process_id, VARCHAR signal_class, VARCHAR signal_id, VARCHAR x_concept, VARCHAR x_unit_symbol, DOUBLE x_value_double, VARCHAR y_concept, VARCHAR y_unit_symbol, DOUBLE y_value_double, FLOAT y_value_float, BIGINT y_value_int, VARCHAR y_value_text)
	rel#3087083:Subset#4.NONE.[], best=null, importance=0.9
		rel#3087082:LogicalFilter.NONE.[](input=rel#3087081:Subset#3.NONE.[],condition=AND(=($2, ?0), =($4, ?1))), rowcount=2.25, cumulative cost={inf}
		rel#3087084:LogicalProject.NONE.[](input=rel#3087083:Subset#4.NONE.[],__time=$0,cube_iri=$1,process_id=$2,signal_class=$3,signal_id=$4,x_concept=$5,x_unit_symbol=$6,x_value_double=$7,y_concept=$8,y_unit_symbol=$9,y_value_double=$10,y_value_float=$11,y_value_int=$12,y_value_text=$13), rowcount=2.25, cumulative cost={inf}
	rel#3087089:Subset#4.BINDABLE.[], best=null, importance=1.0
		rel#3087087:AbstractConverter.BINDABLE.[](input=rel#3087083:Subset#4.NONE.[],convention=BINDABLE,sort=[]), rowcount=2.25, cumulative cost={inf}
		rel#3087088:InterpretableConverter.BINDABLE.[](input=rel#3087083:Subset#4.NONE.[]), rowcount=2.25, cumulative cost={inf}
		rel#3087092:BindableProject.BINDABLE.[](input=rel#3087089:Subset#4.BINDABLE.[],__time=$0,cube_iri=$1,process_id=$2,signal_class=$3,signal_id=$4,x_concept=$5,x_unit_symbol=$6,x_value_double=$7,y_concept=$8,y_unit_symbol=$9,y_value_double=$10,y_value_float=$11,y_value_int=$12,y_value_text=$13), rowcount=2.25, cumulative cost={inf}
		rel#3087097:BindableFilter.BINDABLE.[[]](input=rel#3087096:Subset#3.BINDABLE.[],condition=AND(=($2, ?0), =($4, ?1))), rowcount=2.25, cumulative cost={inf}

		at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:437)
		at org.apache.calcite.plan.volcano.RelSubset.buildCheapestPlan(RelSubset.java:296)
		at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:662)
		at org.apache.calcite.tools.Programs$RuleSetProgram.run(Programs.java:339)
		at org.apache.calcite.tools.Programs$SequenceProgram.run(Programs.java:358)
		at org.apache.calcite.prepare.PlannerImpl.transform(PlannerImpl.java:337)
		at org.apache.druid.sql.calcite.planner.DruidPlanner.planWithBindableConvention(DruidPlanner.java:169)
		at org.apache.druid.sql.calcite.planner.DruidPlanner.plan(DruidPlanner.java:94)
		... 31 more

Process finished with exit code 0

### questions
Is my preparedStatement query right?

**Comment by zhcwang** [comment]
addon, main configuration is :
   druid_with_version: 0.16.0-incubating
    druid_xmx: "1g"
    druid_xms: "1g"
    druid_max_new_size: "205m"
    druid_new_size: "250m"
    druid_max_direct_memory_size: "10240m"
    druid_emitter_logging_log_level: "info"
    druid_default_query_timeout: "30000000"
    druid_connection_idle_timeout: "PT5000M"
    druid_extensions_load_list: \[\"druid-histogram\"\,\"druid-datasketches\"\,\"druid-lookups-cached-global\"\,\"postgresql-metadata-storage\"\,\"simple-client-sslcontext\"\,\"druid-s3-extensions\"\]
    druid_metadata_storage_type: "postgresql"
    druid_coordinator_balancer_strategy: "cachingCost"
    druid_indexer_runner_javaOptsArray: \[\"-server\"\,\"-Xmx1g\"\,\"-Xms1g\"\,\"-XX:MaxDirectMemorySize=3g\"\,\"-Duser.timezone=UTC\"\, \"-Dfile.encoding=UTF-8\"\,\"-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager\"\, \"-Daws.region={{aws_region}}\"\]
    druid_indexer_fork_property_druid_processing_buffer_sizeBytes: "268435456"
    druid_storage_type: "s3"
    druid_storage_bucket: "druid"
    druid_storage_baseKey: "druid/segments"
